### ISSUE TITLE
没有错误却无法正常使用

### ISSUE THREAD

**Issue by zuzuviewer** [jpush/jpush-react-native#101]
可以在安卓debug版本里看到toast了“init push success”，也就是调用initPush方法成功，但是设置别名没有反应，失败或成功的回调函数都没执行，并且用web群发通知，也无法收到，提示“没有满足条件的推送目标“

**Comment by KenChoi1992** [comment]
@zuzuviewer  看看能否拿到 registrationId

**Comment by zuzuviewer** [comment]
@KenChoi1992 ，不可以，getRegistrationID是IOS的方法，不过我也试了下，返回的是空

**Comment by twohouses** [comment]
不说一下是什么原因，就直接关了……
