### ISSUE TITLE
 在js代码重复接受notification

### ISSUE THREAD

**Issue by uyson** [jpush/jpush-react-native#102]

**Comment by huangminlinux** [comment]
iOS 端还是 android 端 ？  事件是 ReceiveNotification  还是 OpenNotification ？

**Comment by uyson** [comment]
android

**Comment by uyson** [comment]
我发现每次reload js的时候init函数重复加载，并执行init函数导致重复添加listener

**Comment by KenChoi1992** [comment]
@uyson 你可以判断一下有没有添加 listener 啊，如果没有再添加。

**Comment by KenChoi1992** [comment]
@uyson 这个问题我先关了，还有疑问你再打开。

**Comment by uyson** [comment]
这个我得改源代码， 而且我也不太熟悉 object+c 如果可以的话 麻烦加一下
