### ISSUE TITLE
无法处理通知事件

### ISSUE THREAD

**Issue by zuzuviewer** [jpush/jpush-react-native#103]
在安卓debug版本中，增加了通知接收和打开监听事件，但是来了通知不会调用事件处理函数，并且点击通知会让前台运行的应用重新启动一次

**Comment by KenChoi1992** [comment]
@zuzuviewer 你有没有注册接收收到通知的事件？

**Comment by KenChoi1992** [comment]
@zuzuviewer  https://community.jiguang.cn/t/topic/11850/49 相信这个问题你应该有答案了，我把 issue 关了。
