### ISSUE TITLE
realse 模式编译失败

### ISSUE THREAD

**Issue by mx1700** [jpush/jpush-react-native#104]
debug 模式可以编译成功并运行
realse 模式编译失败

RN 版本：0.39.2

错误信息：

Undefined symbols for architecture i386:
  "_kJPFNetworkDidSetupNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidRegisterNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidReceiveMessageNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in libRCTJPushModule.a(RCTJPushActionQueue.o)
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidLoginNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidCloseNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPUSHRegisterEntity", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

哪位知道什么原因？谢谢

**Comment by huangminlinux** [comment]
TARGETS -> Build Settings -> Build Active Architecture Only -> release 设为 Yes

**Comment by huangminlinux** [comment]
问题解决没？
@mx1700

**Comment by mx1700** [comment]
@huangminlinux 
换了一种错误：

Undefined symbols for architecture x86_64:
  "___gxx_personality_v0", referenced from:
      _RCTDefaultLogFunction_block_invoke in libReact.a(RCTLog.o)
      _RCTFormatLog in libReact.a(RCTLog.o)
      ___RCTAddLogFunction_block_invoke in libReact.a(RCTLog.o)
      _RCTPerformBlockWithLogFunction in libReact.a(RCTLog.o)
      _RCTPerformBlockWithLogPrefix in libReact.a(RCTLog.o)
      RCTGetLocalLogFunction() in libReact.a(RCTLog.o)
      ___RCTPerformBlockWithLogPrefix_block_invoke in libReact.a(RCTLog.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by huangminlinux** [comment]
是在 主工程 target 设置的吗？

**Comment by mx1700** [comment]
@huangminlinux 是 react native 问题，已经解决。

非常感谢！

**Comment by pamler** [comment]
我也遇到同样的问题，请问是如何解决的？ @mx1700

**Comment by mx1700** [comment]
选择 project，build settings
里边的 Other Linker Flags 增加 -lc++

**Comment by Xing-He** [comment]
![a76e88bc-f514-48bc-bfdb-f55af4f2e4d7](https://cloud.githubusercontent.com/assets/11990205/22765371/cfd52fc2-eeaa-11e6-900b-4fda1cdf5121.png)

贴个图说明下：  

我的也是debug版可以正常运行，release就编译错误，按照楼主的做法然后编译成功了  

**`Project`** ->`Build Setting` -> `Other Linker Flags` -> 添加 `-lc++`  

虽然操作成功了，我还是没明白为什么会出现这个问题，小白😢 ，有知道望解答...

**Comment by xgxchina** [comment]
Undefined symbols for architecture x86_64:
"_kJPFNetworkIsConnectingNotification", referenced from:
-[RCTJPushModule init] in RCTJPushModule.o
"_kJPFNetworkDidRegisterNotification", referenced from:
-[RCTJPushModule init] in RCTJPushModule.o
"_JCOREDisplayVersion", referenced from:
+[JPUSHService commonSetupWithOption:appKey:channel:apsForProduction:advertisingIdentifier:] in libjpush-ios-3.0.7.a(JPUSHService.o)
"_JCOREGetBuildVersion", referenced from:
+[JPUSHService commonSetupWithOption:appKey:channel:apsForProduction:advertisingIdentifier:] in libjpush-ios-3.0.7.a(JPUSHService.o)
"_kJPFNetworkDidSetupNotification", referenced from:
-[RCTJPushModule init] in RCTJPushModule.o
"_kJPFNetworkDidCloseNotification", referenced from:
-[RCTJPushModule init] in RCTJPushModule.o
-[RCTJPushModule reactJSDidload] in RCTJPushModule.o
"_kJPFNetworkDidLoginNotification", referenced from:
-[RCTJPushModule init] in RCTJPushModule.o
-[RCTJPushModule reactJSDidload] in RCTJPushModule.o
"_kJPFNetworkDidReceiveMessageNotification", referenced from:
-[RCTJPushModule init] in RCTJPushModule.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

求各位大神帮忙解决这个问题！！！

**Comment by huangminlinux** [comment]
release 换真机试试，如果想要 模拟器编译 release 要添加额外配置。

**Comment by lixutao** [comment]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ethanzway** [comment]
@huangminlinux 有空能写个文章说明下这个问题，看了issue挺多人遇到的，目前我觉得可能因为静态文件中缺少x86_64的编译部分吧，但是很好奇为什么真机能顺利编译，望请教
