### ISSUE TITLE
推送被多次分发

### ISSUE THREAD

**Issue by godot007** [jpush/jpush-react-native#106]
接收到推送时，每次reload或者热更新时RCTJPushModule里的- (void)receiveRemoteNotification:(NSNotification *)notification方法执行次数加1。请问大神们有遇到这个bug没，或者什么方法解决一下。jpush-react-native版本：1.2.6

**Comment by huangminlinux** [comment]
有执行 取消订阅指定事件吗？

**Comment by godot007** [comment]
谢谢，问题解决了。在RCTJPushModule里init方法在reload或者热更新重启后会再次执行，导致通知被重复订阅。解决方法是在iOS原生init方法添加监听前添加[[NSNotificationCenter defaultCenter] removeObserver:self]或者重写init的单例方法。
