### ISSUE TITLE
Windows configuration Andrews problem / windows配置安卓的问题 

### ISSUE THREAD

**Issue by TrustTheBoy** [jpush/jpush-react-native#107]
EN:'Jpush' can only use the 'Mac' computer configuration? I 'windows' configuration is completed, I did not see 'android Library' into the 'java' directory

CH:请问'jpush‘只能使用’Mac‘电脑进行配置？我在'windows'配置完成之后,我没有看见’ android Library‘导入到’java'目录下

**Comment by TrustTheBoy** [comment]
![image](https://cloud.githubusercontent.com/assets/20201085/21515507/634a4984-cd0b-11e6-8fa0-3b55e8621051.png)
![image](https://cloud.githubusercontent.com/assets/20201085/21515512/6bc1eaea-cd0b-11e6-90b8-d2add09d93dd.png)

EN:In the above problem is not resolved, open the application to push the message in the figure, and the phone (real machine) error: Unknown named module: 'Jpush-react-native'; 
The case code used is the Dome in the document:>>![https://github.com/jpush/jpush-react-native/blob/master/example/react-native-android/push_activity.js]

CH:在以上问题没有解决的时候，打开应用推送上图中的消息，并且手机（真机）报错：Unknown named module: 'Jpush-react-native'; 使用的案例代码是文档中的Dome>>![https://github.com/jpush/jpush-react-native/blob/master/example/react-native-android/push_activity.js]

**Comment by KenChoi1992** [comment]
@TrustTheBoy 你好，本 demo 在 Mac 下 和 Windows 下都可以运行，你要使用 demo 可以先把本项目 clone 下来，然后把一个 node_modules 文件夹拷贝到 example 下（或者把 example 文件夹下的文件拷贝到已经初始化的 React Native 项目中）然后用 Android Studio 打开 example 下的 android 文件夹，
然后在命令行中执行
```
react-native run-android
```
这样你在 Android Studio 中可以看到日志输出，并且如果你增加了改动可以直接点击运行按钮来运行你的 demo。

**Comment by TrustTheBoy** [comment]
@KenChoi1992 我按照文档一步一步配置的，但是android/app/下并没有新导入文件：
请问是什么问题呢？
 文档中的：
![image](https://cloud.githubusercontent.com/assets/20201085/21517518/ce2941a6-cd1a-11e6-9153-8bfefcd19681.png)
我的：
![image](https://cloud.githubusercontent.com/assets/20201085/21517545/fe54d926-cd1a-11e6-827e-e06abf60e5df.png)

**Comment by KenChoi1992** [comment]
@TrustTheBoy  你看看 settings.gradle 有没有这个：
```
include ':app', ':jpush-react-native'
project(':jpush-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/jpush-react-native/android')

```

**Comment by TrustTheBoy** [comment]
@KenChoi1992 有，JPush-react-native README.md文档上面的配置我都配置了，就是不行，reload之后还报错：Unknown named module: 'Jpush-react-native';

**Comment by KenChoi1992** [comment]
@TrustTheBoy 你把名字拼错了吧，不是 Jpush-react-native，而是 jpush-react-native

**Comment by TrustTheBoy** [comment]
@KenChoi1992 ....好吧，报错信息：Unknown named module:  jpush-react-native';
我手敲错了，配置时都是复制的你们的案例demo，我就想问问这个是怎么回事，import 路径都没问题，前后也检查好几遍了

**Comment by TrustTheBoy** [comment]
@KenChoi1992 好吧，非常感谢你的回答，我重新跑一个新的项目再试试，如果不行，再来请教你

**Comment by KenChoi1992** [comment]
@TrustTheBoy  讲道理你 settings.gradle 加了上面那句，sync 一下，在 Android Studio 就可以看到
![image](https://cloud.githubusercontent.com/assets/8196928/21518126/1fa23b74-cd1f-11e6-9c1d-06616c8136a5.png)

除非你的项目中没有包含 node_modules 文件夹，并且其中不包含 jpush-react-native 模块。

**Comment by TrustTheBoy** [comment]
@KenChoi1992 我在windows环境配置，并且没有安装 Android Studio.
我在Sublime Text中进行项目开发，这个必须使用 Android Studio查看吗？
但是如果新增文件的话，不管哪个编辑器都能看到呀

**Comment by KenChoi1992** [comment]
@TrustTheBoy 安装吧，因为 [React Native ](https://facebook.github.io/react-native/docs/getting-started.html#content) 在开始的章节中就说道在 Windows 上开发 Android 必须安装的软件中就有 Android Studio。

**Comment by KenChoi1992** [comment]
@TrustTheBoy 没什么问题就关掉 issue 了。
