### ISSUE TITLE
IOS 下,应用内消息没有反应

### ISSUE THREAD

**Issue by Woodswu** [jpush/jpush-react-native#109]
推送消息正常推送没有问题，现在想实现站内消息，可是添加了回调却没有反应

   NativeAppEventEmitter.addListener(
      'networkDidReceiveMessage',
      (message)=>{
        alert(JSON.stringify(message));
        console.log('站内消息'+JSON.stringify(message));
      }
    );
前台 没有任何反应 是需要修改什么地方的代码实现么

**Comment by huangminlinux** [comment]
这边是没有问题的，   确定发送的是应用内消息吗？ 应用内消息和推送是不一样的

**Comment by Woodswu** [comment]
是站内应用消息，嗯 我知道根推送不一样，在极光的管理后台能看到api的推送记录 是成功的，可是前台手机端就是没反应，不清楚怎么回事

**Comment by huangminlinux** [comment]
提供一下 你的 message id   控制台里面

**Comment by Woodswu** [comment]
Message ID	3329745848
推送平台	ios-product
推送结果	已发送
audience	{"registration_id":["161a3797c80884623dc"]}
notification	{"title":"我是title","ios":{"sound":"sound.caf","badge":"+1"},"alert":"重新测试"}
message	null
options	null

**Comment by huangminlinux** [comment]
你这个是推送通知，，，不是自定义消息。。。

**Comment by llitfkitfk** [comment]
@huangminlinux 自定义消息  如果app在后台运行 如何提示notification?

**Comment by huangminlinux** [comment]
@llitfkitfk  自定义消息在后台是不会触发的，只有进入前台的时候还会接收自定义消息。

如果需要在后台想要收到提醒， 应该用推送通知。 或者让后台同时推送 自定义消息 和 推送通知。

**Comment by llitfkitfk** [comment]
app在前台是 想用自定义消息的效果(不提示notification) app

**Comment by llitfkitfk** [comment]
可以了 改为completionHandler(UNNotificationPresentationOptionNone);
