### ISSUE TITLE
Cannot build in android

### ISSUE THREAD

**Issue by sunkibaek** [jpush/jpush-react-native#111]
I think the line below has syntax error

https://github.com/jpush/jpush-react-native/blob/1c30f89d41eb56550122725eb15dff19790182b9/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java#L278

When I try to build it says
```
/Users/sunkibaek/apps/hsMobile/node_modules/jpush-react-native/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java:278: error: ')' expected
                    Logger.e("Throwable", e.printStackTrace(););
                                                             ^
/Users/sunkibaek/apps/hsMobile/node_modules/jpush-react-native/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java:278: error: illegal start of expression
                    Logger.e("Throwable", e.printStackTrace(););
```

**Comment by chenpengjun** [comment]
将日志打印删了就OK了

**Comment by KenChoi1992** [comment]
@sunkibaek sorry, my fault,  already updated.

**Comment by KenChoi1992** [comment]
@sunkibaek Thank you to point it out, this error should never come up, sorry again. Welcome to point out our mistakes(Certainly, we wish the less mistakes, the better),  Closing issue now.

**Comment by sunkibaek** [comment]
@KenChoi1992 No need to apologize! I understand it can happen -- it happens all the time to my code :-)

Thanks for the great project btw, we are using it in production. Without your help we wouldn't have notification function in our app.

Thanks!
