### ISSUE TITLE
setAliasAndTags设置alias的时间返回6009，权限错误，请问这个是什么问题

### ISSUE THREAD

**Issue by LiuC520** [jpush/jpush-react-native#112]
在设置别名的时间，会返回6009，提示权限错误，这个如何解决？

**Comment by huangminlinux** [comment]
android 还是iOS ？

**Comment by LiuC520** [comment]
android，ios的是正常的没问题

**Comment by KenChoi1992** [comment]
@LiuC520 你有没有 Android 的推送目标？能否拿到 registrationId ？

**Comment by LiuC520** [comment]
拿不到android的推送目标，也拿不到registrationId ，我把你的包换了，换成了官方的3.0.0的包，然后一样的提示6009，然后用as clean，会提示找不到包名，然后把你的包下面的AndroidManifest里面的applicationid都换成了我自己的包名，直接写死了，就好了

**Comment by KenChoi1992** [comment]
@LiuC520 那这个问题可能是你自己在 build.gradle 没有替换 applicationId 引起的
