### ISSUE TITLE
iOS 会触发两次OpenNotification事件

### ISSUE THREAD

**Issue by RayCai** [jpush/jpush-react-native#114]
kJPFOpenNotification事件监听了两次
[RCTJPushModule.m](https://github.com/jpush/jpush-react-native/blob/master/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.m#L70)

**Comment by huangminlinux** [comment]
感谢反馈，已发布修复版本 1.3.4 ：

https://github.com/jpush/jpush-react-native/releases/tag/1.3.4
