### ISSUE TITLE
JPushModule.getRegistrationID() doesn't work in react-native even i got the ID in Xcode?

### ISSUE THREAD

**Issue by yuanliangYL** [jpush/jpush-react-native#115]
In Xcode ,I have got the uid and the registionID that JPUSH feedback to me. But there is a log that "Sending `websocketFailed` with no listeners registered"  I don't understand what is mean. And in react-native ,when i using the method  "JPushModule.getRegistrationID()" dosen't work too.Anyone konws why this happened ? Help me fix it PLZ!

**Comment by huangminlinux** [comment]
make sure npm server was launching
```
npm start
```

or restart you react native server

**Comment by yuanliangYL** [comment]
I had fix it.Thanks.


发自网易邮箱大师
On 01/09/2017 21:15, huangminlinux wrote:

make sure npm server was launching

npm start


or restart you react native server
