### ISSUE TITLE
[IOS] 应用在前台运行时，收到推送还会有通知栏提示

### ISSUE THREAD

**Issue by MiRinZhang** [jpush/jpush-react-native#120]
> 如题，这个问题要怎么解决啊。是需要在哪里配置么？

**Comment by huangminlinux** [comment]
AppDelegate.m
把下面代码 修改一下
```
// iOS 10 Support
- (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger))completionHandler {
  // Required
  NSDictionary * userInfo = notification.request.content.userInfo;
  if([notification.request.trigger isKindOfClass:[UNPushNotificationTrigger class]]) {
    [JPUSHService handleRemoteNotification:userInfo];
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo];
  }
  completionHandler(UNNotificationPresentationOptionAlert); // 需要执行这个方法，选择是否提醒用户，有Badge、Sound、Alert三种类型可以选择设置
}
```

改成```
// iOS 10 Support
- (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger))completionHandler {
  // Required
  NSDictionary * userInfo = notification.request.content.userInfo;
  if([notification.request.trigger isKindOfClass:[UNPushNotificationTrigger class]]) {
    [JPUSHService handleRemoteNotification:userInfo];
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo];
  }
  completionHandler(); // 需要执行这个方法，选择是否提醒用户，有Badge、Sound、Alert三种类型可以选择设置
}
```

**Comment by MiRinZhang** [comment]
@huangminlinux 你好，我不太懂OC代码，所以得再问个不成熟的小问题：
> `completionHandler();`这里面是从`UIUserNotificationTypeAlert | UIUserNotificationTypeSound | UIUserNotificationTypeBadge`这三个里面任选一个么？还是直接置空[直接置空的话会报错]。

**Comment by huangminlinux** [comment]
可以三个都选你可以理解为  | 叠加关系,,

哦，刚刚忘记加类型了 ，你换成这个

```
completionHandler(UIUserNotificationTypeNone);
```

**Comment by MiRinZhang** [comment]
@huangminlinux 谢谢，问题解决啦。
