### ISSUE TITLE
[ios 10]Warning: Sending 'AppDelegate *const__strong' to parameter of incompatible type 'id<JPUSHRegisterDelegate>'

### ISSUE THREAD

**Issue by pampang** [jpush/jpush-react-native#123]
![image](https://cloud.githubusercontent.com/assets/13509115/22005357/6d724a78-dc9d-11e6-8896-35833a2a7d07.png)

加入了代码：
```
    if ([[UIDevice currentDevice].systemVersion floatValue] >= 10.0) {
 #ifdef NSFoundationVersionNumber_iOS_9_x_Max
    JPUSHRegisterEntity * entity = [[JPUSHRegisterEntity alloc] init];
     entity.types = UNAuthorizationOptionAlert|UNAuthorizationOptionBadge|UNAuthorizationOptionSound;
     [JPUSHService registerForRemoteNotificationConfig:entity delegate:self];

#endif
   }
```
之后，出现的warning，会有任何影响吗？

**Comment by AmatsuZero** [comment]
让你的代理遵守一下JPUSHRegisterDelegate这个协议就好了....
iOS具体的，请搜一下iOS Protocol/Delegate的相关知识………

**Comment by pampang** [comment]
@AmatsuZero 感谢感谢，ios小白一名，不太懂，谢谢你的回答！

**Comment by inkCrazy** [comment]
![D9A75843-EC57-4BCC-8E02-64CBC3DC2D48](https://user-images.githubusercontent.com/12253453/200098156-6e9b9396-3768-4291-8f6a-a7aa9d5e10e6.png)
为什么我加了还是报错了
