### ISSUE TITLE
请问一下Android端在下载完应用设置tag的时候,报超时的错误怎么回事啊....

### ISSUE THREAD

**Issue by NextChampion** [jpush/jpush-react-native#125]
![2ef4e9b46a21741d0f80ed0957377c1f](https://cloud.githubusercontent.com/assets/17548233/22010811/71b6306c-dcc6-11e6-804d-ffa9b96ff3ed.jpg)
![2ef4e9b46a21741d0f80ed0957377c1f](https://cloud.githubusercontent.com/assets/17548233/22010820/79221cda-dcc6-11e6-87d9-eb5876d0ad49.jpg)

一开始是设置好的,后来突然就不行了....按照文档检查了相关的配置 也没发现错误.
现在推送,提示推送成功,但是收不到消息.以前都是好的.不知道怎么突然就不行了

**Comment by KenChoi1992** [comment]
@NextChampion 看一下日志

**Comment by KenChoi1992** [comment]
@NextChampion 没有提供后续线索，我就把这个 issue 关闭了。
