### ISSUE TITLE
init成功了，getinfo也获取到了，就是推送不了

### ISSUE THREAD

**Issue by 1035901787** [jpush/jpush-react-native#126]
init成功了，getinfo也获取到了，就是推送不了

**Comment by KenChoi1992** [comment]
@1035901787 有没有拿到 registrationId？

**Comment by 1035901787** [comment]
@KenChoi1992 解决了，是android里面激光插件中mainfest中"${applicationId}"好像没有引用到，一直接收不到推送，我把使用到这个引用的地方全部改为我的包名就可以了，希望作者改良一下

**Comment by KenChoi1992** [comment]
@1035901787  兄弟，你没看文档啊，在 build.gradle 中改一下 applicationId 就行了。。
![image](https://cloud.githubusercontent.com/assets/8196928/22133113/5ff82fbc-def9-11e6-8f22-53d62a7e0164.png)
