### ISSUE TITLE
有关消息推送抵达的疑问

### ISSUE THREAD

**Issue by durongzhang** [jpush/jpush-react-native#130]
现在基本上任何android手机清掉进程，消息都无法抵达，怎么保证应用被杀掉，消息还能到达

**Comment by durongzhang** [comment]
https://github.com/liuchungui/react-native-umeng-push

**Comment by KenChoi1992** [comment]
@durongzhang 我们也有守护进程的 https://community.jiguang.cn/t/jpush/2815 参考一下这篇帖子，有关于推送的问题都可以在社区提问。
