### ISSUE TITLE
java.lang.IllegalArgumentException NULL context 

### ISSUE THREAD

**Issue by durongzhang** [jpush/jpush-react-native#131]
![image](https://cloud.githubusercontent.com/assets/15725537/22139156/6ba5a12a-df1f-11e6-8972-70843190cbe1.png)

sdk version: 1.3.5

**Comment by KenChoi1992** [comment]
@durongzhang 怎么出现的这个问题？

**Comment by KenChoi1992** [comment]
@durongzhang 新版本有个 addGetRegistrationIdListener，初次组册成功后，如果你添加了这个 Listener 就可以收到事件。直接调用 getRegistrationId 有可能会拿不到。
