### ISSUE TITLE
JPush 在iOS模拟器上配置成功没有反应：JPush WARNING! APNs is NOT supported on simulator

### ISSUE THREAD

**Issue by jacobcyl** [jpush/jpush-react-native#132]
按照文档配置好iOS，但是好像没有连上，
> 没有满足条件的推送目标
> 如果是群发：则此应用还没有一个客户端用户注册。请检查 SDK 集成是否正常。
> 如果是推送给某别名或者标签：则此别名或者标签还没有在任何客户端SDK提交设置成功。
> 如果是根据 Registration ID 推送：则此 Registration ID 不存在。

xcode 控制台看到有这句话：JPush WARNING! APNs is NOT supported on simulator，是不是不支持模拟器调试？

**Comment by huangminlinux** [comment]
是的不支持模拟器
