### ISSUE TITLE
Android点击通知无法将后台的App换至前台

### ISSUE THREAD

**Issue by rollandlau** [jpush/jpush-react-native#133]
App启动后点击home键，发送推送，然后点击推送消息，App会重新启动而不是恢复原有运行状态
我参考了
https://community.jiguang.cn/t/topic/11850/
这个讨论，但是仍然没有解决

**Comment by KenChoi1992** [comment]
@rollandlau 你用了新版本没有，之前的更新有是否运行在后台的判断，如果在后台运行，将会跳转到 app 首页，当然你也可以定制化这一块。

**Comment by rollandlau** [comment]
@KenChoi1992 用了新版本，原因似乎是需要把launchMode改为singleTask，虽然解决了但是仍然不是很理解

**Comment by KenChoi1992** [comment]
@rollandlau 因为之前的启动模式是 standard，跳转这块的代码判断 Activity 不在前台，就会重新创建一个 Activity 栈，然后把这个 Activity 放到堆栈里，造成重启的效果。改成 singleTask，就会判断是否在堆栈中有这个 Activity，然后把之前的 Activity 从堆栈中移出。这是 Android 的启动模式决定的。

**Comment by KenChoi1992** [comment]
@rollandlau 没什么问题的话就关掉这个 issue 了。
