### ISSUE TITLE
How to improve broadcast success rate

### ISSUE THREAD

**Issue by devhyunjae** [jpush/jpush-react-native#136]
Sent a push message targeting all user, and these are the result below.

```
iOS 
target 1736
success 825
```
```
Android
target 43822
success 895
```

In Android here, success rate is extremely low. How can I improve this?
Don't have any clue where to approach..
Can I get some more infos and comments about this?

**Comment by huangminlinux** [comment]
The staff will work tomorrow，We'll get back to you as soon as possible.

**Comment by KenChoi1992** [comment]
@devhyunjae Hello, please take a look at this https://community.jiguang.cn/t/jpush/5145/5 , the Android success rate is related with online users, if user was offline, the offline message mechanism will reserve 5 recent messages for 10 days, if user login in these days, they will receive messages.
