### ISSUE TITLE
app在唤起、后台、杀死进程的时候分别用哪个方法监听(iOS)

### ISSUE THREAD

**Issue by WangZiXiao-ChenDu** [jpush/jpush-react-native#139]

**Comment by huangminlinux** [comment]
接收到通知 是监听kJPFDidReceiveRemoteNotification 这个事件，
点击通知 是监听 kJPFOpenNotification 这个事件 （不管是通过点击唤起应用，还是应用内点击通知）

如果你的问题是和推送无关的话， 可以查 react native 生命周期的相关资料

**Comment by WangZiXiao-ChenDu** [comment]
![image](https://cloud.githubusercontent.com/assets/19464631/22624875/4272660c-ebc3-11e6-871a-f98b13bfdb4e.png)
还有这个方法是10以后的 那10之前用哪个呢

**Comment by huangminlinux** [comment]
iOS 10以前没有点击推送回调，，不过还是会有kJPFDidReceiveRemoteNotification 这个事件

**Comment by WangZiXiao-ChenDu** [comment]
openNotification 这个事件，只有在应用没有启动的时候（应用在后台不算）会触发，那我想让app在后台点击通知进来的时候拿到一些自定义的数据怎么办呢

**Comment by huangminlinux** [comment]
直接监听 openNotification 这个事件就可以获得推送字段了（不管应用的状态，应用可以是没有启动，也可以是后台，前台）。

**Comment by WangZiXiao-ChenDu** [comment]
我把程序退到后台点通知进入，在这里userInfo里是有我自定义的数据的，但在RN里面这些自定义的数据没有打印出来（OpenNotification这事件好像没有触发）
![image](https://cloud.githubusercontent.com/assets/19464631/22633897/1cb2c158-ec60-11e6-8c22-1aa5aef2f704.png)
这是RN里的调用
![image](https://cloud.githubusercontent.com/assets/19464631/22633462/9fa8d74a-ec5c-11e6-8740-86f34822ca29.png)

**Comment by huangminlinux** [comment]
https://github.com/jpush/jpush-react-native/blob/master/example/documents/iOS_Usage.md

native 里面的代码不全，，你按照文档的代码试试

**Comment by WangZiXiao-ChenDu** [comment]
感谢作者！问题解决了，openNotification这个事件只在杀死以后点击通知执行，在唤起和后台要用ReceiveNotification这个事件监听。

**Comment by huangminlinux** [comment]
openNotification  一定是要有点击推送那个栏的动作， 和应用的状态没有关系
