### ISSUE TITLE
react native0.39版本 #import <RCTJPushModule.h>头文件导入出错

### ISSUE THREAD

**Issue by JustFavor** [jpush/jpush-react-native#141]
如题

**Comment by huangminlinux** [comment]
试一下  JPush-react-native 1.3.8 的版本

**Comment by bktoky** [comment]
报错： Duplicate interface definition for class 'RCTBridge'

**Comment by huangminlinux** [comment]
在   RCTJPushModule.h  注释如下代码
```
//#import "RCTBridgeModule.h"
//#else
#import <React/RCTBridgeModule.h>
//#endif
```
在 RCTJPushModule.m 文件中注释如下代码
```
//#if __has_include("RCTBridgeModule.h")
//#import "RCTEventDispatcher.h"
//#import "RCTRootView.h"
//#import "RCTBridge.h"
//#else
#import<React/RCTEventDispatcher.h>
#import<React/RCTRootView.h>
#import<React/RCTBridge.h>
//#endif
```

很抱歉会尽快在下个版本中修复
@bktoky

**Comment by huangminlinux** [comment]
发了 1.3.9 修复版本。

**Comment by bktoky** [comment]
Build Phases中, Headers,Copy FIles 是不是要加上?

**Comment by huangminlinux** [comment]
@bktoky  找不到  头文件吗？

**Comment by huangminlinux** [comment]
如果找不到头文件可能要在   TARGETS-> BUILD SETTINGS -> Search Paths    添加如下如今

$(SRCROOT)/../node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule

**Comment by bktoky** [comment]
我在 Build Phases 中加了头文件就可以了

**Comment by huangminlinux** [comment]
0.40.0 后 rnpm link 现在不会自动把工程头文件目录自动加到  TARGETS-> BUILD SETTINGS -> Search Paths 了，  下版本中在配置脚本中加上。

**Comment by scriptfans** [comment]
@huangminlinux 新版本什么时候发布？

**Comment by huangminlinux** [comment]
@scriptfans   RN 0.40.0 之后使用 jpush-react-native 1.3.9版本的就可以了。

RN 0.40.0 以前的  jpush-react-native 1.3.6 版本，

1.3.9  和 1.3.6 ,只是适配了 react native 的一些改动，没有新功能
