### ISSUE TITLE
iOS项目报错‘RCTJPushModule.h’ not found

### ISSUE THREAD

**Issue by WhynoChinese** [jpush/jpush-react-native#142]
不管是自动配置还是手动配置，新创建项目后配置都是报这个错误

**Comment by huangminlinux** [comment]
如果找不到头文件可能要在 TARGETS-> BUILD SETTINGS -> Search Paths 添加如下如今

$(SRCROOT)/../node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule

**Comment by WhynoChinese** [comment]
项目是不报错了，但是启动报新错误：
Error: @providesModule naming collision: Duplicate module name: react-native-vector-icons

**Comment by WhynoChinese** [comment]
添加头文件后这个错误没有了，但是包新的错误：
This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/mac/Desktop/push/push/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/mac/Desktop/push/push/node_modules/jpush-react-native/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

**Comment by zix2002** [comment]
@WhynoChinese 删除 ./node_modules/jpush-react-native/node_modules/react-native 这个目录就好了

**Comment by WhynoChinese** [comment]
@zix2002 谢谢！完美解决
