### ISSUE TITLE
didn't find RCTJpushModule.xcodeproj in Libraries after run `rnpm link`

### ISSUE THREAD

**Issue by Xing-He** [jpush/jpush-react-native#143]

**Comment by Xing-He** [comment]
and this work for me : `react-native link jpush-react-native `

**Comment by huangminlinux** [comment]
Could your react native version ,and Jpush-react-native version?

**Comment by Xing-He** [comment]
rn : `0.41.2`  
jp : `1.3.9`

**Comment by huangminlinux** [comment]
I guess it's rnpm's problem. 

It ok in rnpm 1.7.0 and fail in 1.9.0.

I will update my document to use react-native link .

thank for your feedback
