### ISSUE TITLE
addReceiveNotificationListener 事件重复绑定

### ISSUE THREAD

**Issue by Martinzz** [jpush/jpush-react-native#144]
addReceiveNotificationListener 事件重复绑定 ，removeReceiveNotificationListener事件并没有移除订阅，使得重复执行N次打开APP，按返回退出，再打开，事件会重复触发N次，其它几个绑定事件也一样有这个问题。

**Comment by huangminlinux** [comment]
有在componentWillUnmount函数中实现。取消订阅指定事件吗？

```
var { NativeAppEventEmitter } = require('react-native');

var subscription = NativeAppEventEmitter.addListener(
  'ReceiveNotification',
  (notification) => console.log(notification)
);
...

subscription.remove();
```

**Comment by Martinzz** [comment]
我用的android，用了removeReceiveNotificationListener这个事件没效果

**Comment by KenChoi1992** [comment]
@Martinzz 试试 DeviceEventEmitter.removeAllListeners();

**Comment by KenChoi1992** [comment]
@Martinzz 你说的重复绑定问题，如何出现的？我运行 demo 没有问题。
