### ISSUE TITLE
react-native升级到0.41.2后RCTJPushModule.h找不到

### ISSUE THREAD

**Issue by MiRinZhang** [jpush/jpush-react-native#149]
> 这是我安装的包

```json
{
    "jcore-react-native": "^1.0.0",
    "jpush-react-native": "^1.4.4",
    "react": "~15.4.0",
    "react-native": "0.41.2",
}
```

> `search path`设置了还是报错

**Comment by huangminlinux** [comment]
在 iOS 工程中如果找不到头文件可能要在 TARGETS-> BUILD SETTINGS -> Search Paths -> Header Search Paths 添加如下如路径
```
$(SRCROOT)/../node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule
```

RN 在 0.40.0 之后 不会自动加入这个路径了，要手动加一下

**Comment by huangminlinux** [comment]
需要在主工程 target 中设置，参考下图，看看设置错地方没
<img width="1138" alt="2017-02-15 10 26 38" src="https://cloud.githubusercontent.com/assets/5852088/22978530/09527a70-f3ce-11e6-8f26-754793cf3a10.png">

**Comment by MiRinZhang** [comment]
@huangminlinux 你好，这样添加了`build`的时候能成功，但是`AppDelegate.m`中一直有错误。这样正常么？
![2017-02-16 11 01 00](https://cloud.githubusercontent.com/assets/12370585/23005556/cd493cac-f437-11e6-8a95-36f6b77e103d.png)

**Comment by huangminlinux** [comment]
@MiRinZhang  没问题， xcode 有时候会出一些小问题， 之前也试过 重启后就没有错误提示了

**Comment by MiRinZhang** [comment]
@huangminlinux 好的，谢谢啦
