### ISSUE TITLE
xcode8编译失败

### ISSUE THREAD

**Issue by dandingol03** [jpush/jpush-react-native#151]
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_JPUSHRegisterEntity", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by huangminlinux** [comment]
新版本的 sdk 不再支持 32位的模拟器了

**Comment by dandingol03** [comment]
好的
