### ISSUE TITLE
安卓初始化出错could not invoke JPushModule.initPush

### ISSUE THREAD

**Issue by xjrad** [jpush/jpush-react-native#152]
![qq 20170221103248](https://cloud.githubusercontent.com/assets/1243443/23148466/fb9cdb80-f820-11e6-937e-855d39321952.png)

**Comment by KenChoi1992** [comment]
@xjrad 配置正确了吗？如果是 debug 模式，需要与电脑连接同一个 Wi-Fi，并且在 devSetting 中设置一下 IP 和端口号。

**Comment by xjrad** [comment]
按照手动配置进行的，检查了几遍，应该没有漏的，唯一修改的两个地方是“node_modules\jpush-react-native\android”和"node_modules\jcore-react-native\android"的build.gradle中的buildToolsVersion，把"23.0.2"改为“23.0.3”，因为我机器上没有23.0.2的buildtool

**Comment by xjrad** [comment]
把JPushModel.initPush()注释掉后，我的程序是能正常debug的，不是debug配置的问题

**Comment by KenChoi1992** [comment]
@xjrad 有没有在 MainApplication 中添加 new JPushPackage() ?

**Comment by xjrad** [comment]
![qq 20170221122352](https://cloud.githubusercontent.com/assets/1243443/23150713/83e83250-f830-11e6-90f0-0baa89b17726.png)

**Comment by KenChoi1992** [comment]
@xjrad 你在什么时候调用的 initPush() ? demo 能运行起来嘛？

**Comment by xjrad** [comment]
![qq 20170221140656](https://cloud.githubusercontent.com/assets/1243443/23152987/ce7459ec-f840-11e6-9d87-22727adb546b.png)

**Comment by messense** [comment]
感觉 initPush 不应该让用户在 JS 中调用，而应该直接在 `MainApplication.onCreate` 中调用 `JPushInterface.init`，我目前的做法：

![image](https://cloud.githubusercontent.com/assets/1556054/23153055/402b8a06-f841-11e6-948f-c41fea06b116.png)

**Comment by KenChoi1992** [comment]
@messense 这是因为模仿的 JPush demo， 所以我们提供了方法，用户在这点上确实可以在 Native 中初始化。

**Comment by messense** [comment]
@KenChoi1992 iOS 是在 Native 中初始化的，JS 中不需要调用类似 `initPush` 这样的方法，感觉 Android 也统一一下在 Native 中初始化会好一些。

**Comment by KenChoi1992** [comment]
@messense 感想提供意见，我们会考虑一下这个做法。

**Comment by xjrad** [comment]
找到原因了，settings.gradle和build.gradle中需要加上jcore-react-native的依赖：
dependencies {
    ......
	compile project(':jpush-react-native')
	compile project(':jcore-react-native')
    ......
}

include ':app', ':jpush-react-native', ':jcore-react-native'
project(':jpush-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/jpush-react-native/android')
project(':jcore-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/jcore-react-native/android')


步骤说明里的手动配置没有jcore-react-native的配置说明

**Comment by xjrad** [comment]
多谢各位的关注！问题先关闭了
