### ISSUE TITLE
接收到一条推送，监听到多次，求大神帮忙解答一下

### ISSUE THREAD

**Issue by 1035901787** [jpush/jpush-react-native#153]
![image](https://cloud.githubusercontent.com/assets/17847087/23149535/7a4e1182-f827-11e6-8bfc-b226d1953955.png)
![image](https://cloud.githubusercontent.com/assets/17847087/23149541/858cf842-f827-11e6-8327-fb9fe2ba3770.png)

**Comment by huangminlinux** [comment]
```
var { NativeAppEventEmitter } = require('react-native');

var subscription = NativeAppEventEmitter.addListener(
  'ReceiveNotification',
  (notification) => console.log(notification)
);
```
// 千万不要忘记忘记取消订阅, 通常在componentWillUnmount函数中实现。
subscription.remove();

**Comment by 1035901787** [comment]
![image](https://cloud.githubusercontent.com/assets/17847087/23152302/30e7a4a8-f83c-11e6-8141-d6a2fbff92df.png)
我做了删除操作的，是在tab首页做的，是不是这的问题
![image](https://cloud.githubusercontent.com/assets/17847087/23152375/a41627c4-f83c-11e6-9642-17e85f47e4e3.png)

**Comment by huangminlinux** [comment]
添加监听是在 哪里添加的？

**Comment by 1035901787** [comment]
tab首页的componentDidMount事件里面

**Comment by lavystord** [comment]
我也遇到了同样的问题，在整个app启动时addListener，WillUnMount 时removeListener

**Comment by huangminlinux** [comment]
@lavystord @1035901787  ，检查一下WillUnMount 这个方法调用了没，  如果没有销毁就重复监听了

**Comment by 1035901787** [comment]
没有调用到

**Comment by lavystord** [comment]
@huangminlinux 感觉和监听事件本身有关，在控制台发送一条消息，通知栏一条消息，原生层调用一次，js层里有的手机会调一次，有的会调多次

**Comment by huangminlinux** [comment]
每次 Mount 的时候都会加一次监听， 一般 didmount 和 unmount 应该是对称的，  怎么会 只调用 didmount ， 是不是 多次 reload js了。

**Comment by huangminlinux** [comment]
@lavystord  @1035901787  刚发布了一个版本 1.4.6 ，是修复热更新重新订阅事件的 bug。 更新看看是否能解决你们的问题

**Comment by 1035901787** [comment]
是否需要同时升级jcore-react-native到相应的版本，
![image](https://cloud.githubusercontent.com/assets/17847087/23194325/66a3302e-f8e8-11e6-821b-6faa145ead82.png)

**Comment by huangminlinux** [comment]
不需要，使用当前版本就可以了。

**Comment by 1035901787** [comment]
解决了这个问题，非常感谢您的协助

**Comment by lavystord** [comment]
@huangminlinux 可能是多次reload导致的吧，1.4.6版本应要求rn版本>0.40吧，我现在用的1.3.6版本，只好先根据jmsgID在js层手动过滤了。
ps: getRegistationID的cb感觉也不是很稳定....第一次安装app肯定会执行cb，但之后reload js之后会出现不执行cb，并且从此之后再也不会执行了，😳

**Comment by huangminlinux** [comment]
1.4.6 做了预处理，现在支持 0.40.0 一下版本 RN 了， 文档还没来得及更新，

**Comment by stlemon** [comment]
能否帮忙看下为什么我的使用监听的程序在js端收不到原生传过来的notification啊？原生代码：
RCT_EXPORT_MODULE();
@synthesize bridge = _bridge;
-(void)iseCallback:(NSString*) result{
  NSLog(@"Here!");
  [self.bridge.eventDispatcher sendAppEventWithName:@"iseCallback" body:result];
}
js端代码：    
componentWillMount() {
        this.listener = NativeAppEventEmitter.addListener('iseCallback',(data)=>{
            console.log('收到原生数据！');
            console.log(data);
        });
    }

**Comment by huangminlinux** [comment]
你的代码是在哪里加的？  @stlemon

**Comment by stlemon** [comment]
oc端的是我单独写的一个测试类。js端是在程序的启动页内加的

**Comment by huangminlinux** [comment]
@stlemon   模块类需要使用单例，你参考 RCTJPushModule 的写法。

**Comment by lavystord** [comment]
@huangminlinux ,1.4.6支持0.40以下版本的话，可以考虑把package.json中的peerDependencies修改一下了，现在用还会报一个warning；另npmjs.org上的文档好像还没更新。
另一个小建议：package.json中可以加一个rnpm的参数，里面设置好sharedLibraries，这样ios就不需要再手动添加UserNotifications.framework、AdSupport.framework等官方库了

**Comment by huangminlinux** [comment]
@lavystord  感谢提醒，下个版本中会处理这些问题

**Comment by huangminlinux** [comment]
@lavystord  这些问题已在  1.5.0 版本中处理
