### ISSUE TITLE
iphone5和iphone4上报错？

### ISSUE THREAD

**Issue by LiuC520** [jpush/jpush-react-native#156]
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_JPUSHRegisterEntity", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in libRCTJPushModule.a(RCTJPushActionQueue.o)
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidCloseNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidLoginNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidReceiveMessageNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidRegisterNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidSetupNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

请问如何解决？

**Comment by huangminlinux** [comment]
note:
jpush sdk  3.0.0及以上版本将不再支持处理器为i386的模拟器。

如果使用模拟器的是需要使用 iphone 5s 以上模拟器

真机测试没有影响

**Comment by LiuC520** [comment]
好的，谢谢啦
