### ISSUE TITLE
[iOS]app的状态为not running时，数据能否传到js层？

### ISSUE THREAD

**Issue by lavystord** [jpush/jpush-react-native#157]
1.当app的状态为foreground or background时， 通过`this.receiveListener = NativeAppEventEmitter.addListener('ReceiveNotification', this._handleNotification);`可以在js层拿到相应的数据
2.但当app的状态为not running时，通过通知栏点击唤起app可以在oc的`didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`中拿到推送的相应数据，但无法传到js层。直接点击app唤醒，则是在oc层也拿不到数据。

另`  this.openListner = NativeAppEventEmitter.addListener('OpenNotification', this._handleNotification);`该事件好像并不会调用，求指教

**Comment by huangminlinux** [comment]
点击通知栏唤醒应用 是触发 OpenNotification  这个事件，你监听这个事件应该是可以获得。

只要点击通知就会调用 OpenNotification  这个事件。

如果 app not running 点击通知应该也是会调用 OpenNotification 这个事件的，可以在回调中打印日志， 打开系统日志看看，应该是没有问题的

**Comment by lavystord** [comment]
@huangminlinux app在后台或前台都能会调用，not running话这时js根本没有初始化，native层收到事件还能发到js层吗？

**Comment by huangminlinux** [comment]
jpush 插件做了缓存处理的， 只有 js 准备好后才把事件往上抛

**Comment by lavystord** [comment]
但真机在not running状态一直不成功，不知道哪里错了.....

**Comment by huangminlinux** [comment]
我这边测试确实没有问题，  是通过自动配置集成的吗？

手动配置的话有再native 添加如下代码吗？
```
// iOS 10 Support
- (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler {
  // Required
  NSDictionary * userInfo = response.notification.request.content.userInfo;
  if([response.notification.request.trigger isKindOfClass:[UNPushNotificationTrigger class]]) {
    [JPUSHService handleRemoteNotification:userInfo];
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPFOpenNotification object:userInfo];
  }
  completionHandler();  // 系统要求执行这个方法
}
```

**Comment by lavystord** [comment]
`- (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler {
  NSDictionary * userInfo = response.notification.request.content.userInfo;
  UIAlertView * alert = [[UIAlertView alloc] initWithTitle:@"didReceiveNotificationResponse" message:@"4" delegate:nil cancelButtonTitle:@"ok" otherButtonTitles: nil];
  [alert show];
  if([response.notification.request.trigger isKindOfClass:[UNPushNotificationTrigger class]]) {
    [JPUSHService handleRemoteNotification:userInfo];
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPFOpenNotification object:userInfo];
  }
  completionHandler();
}`
这段代码有的...我还加了句native层的alert，也会执行.....就是js层的监听事件不会执行...😶

**Comment by huangminlinux** [comment]
我这边测试没有确实是没有问题，， 要不加个 Q群 具体讨论吧 : 553406342
