### ISSUE TITLE
jpush-react-native 1.4.6 Crash

### ISSUE THREAD

**Issue by qinly** [jpush/jpush-react-native#158]
错误信息

    02-28 21:21:08.321 29312-5620/com.** I/art: Rejecting re-init on previously-failed class java.lang.Class<cn.jpush.android.api.JPushInterface>
    02-28 21:21:08.322 29312-5620/com.** E/CrashReport: CrashReport has not been initialed! pls to call method 'initCrashReport' first!
    02-28 21:21:08.402 29312-5619/com.** W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
    02-28 21:21:08.402 29312-5619/com.** W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {33254a80} sending message to a Handler 

相关版本：

    "jcore-react-native": "^1.0.0",
    "jpush-react-native": "^1.4.6",
    "react": "^15.4.2",
    "react-native": "^0.41.2",
    
    Android 5.1.1
只有屏蔽jpush-react-native代码才能显示RN界面

**Comment by KenChoi1992** [comment]
@qinly 看起来似乎是初始化失败了？jcore-react-native 有没有 link 成功？

**Comment by qinly** [comment]
react-native link 后缺少`jcore-react-native`部分，我手动配置上去`settings.gradle`后仍然无效:
project(':jcore-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/jcore-react-native/android')

**Comment by KenChoi1992** [comment]
@qinly 配置了 build.gradle 吗？
```
compile project(':jpush-react-native')
    compile project(':jcore-react-native')
```
这两个都要，另外你可以在本地初始化：
https://github.com/jpush/jpush-react-native/pull/160/commits/33193af1501a649dfe1cf15e2f1ca15995da929f

**Comment by qinly** [comment]
恢复使用，感谢！建议完善文档```jpush-react-native > 1.4.4```后升级变更部分。
