### ISSUE TITLE
Android按照文档集成失败

### ISSUE THREAD

**Issue by wjljack** [jpush/jpush-react-native#159]
rn是最新版本，react-native init新建一个项目，按照文档自动和手动配置都试过了，最后集成失败，现象是极光web推送端都没有发现注册设备，无法推送，另外有其他注册设备的项目推送所有机器时安卓端无法收到任何消息，包括通知栏推送和js的监听回调。希望开发者能够用新项目集成试试，我这边已经试了好几次了，配置完全按照文档来的

**Comment by KenChoi1992** [comment]
@wjljack 你的日志打印贴上来看看，如果集成失败会有显示的，另外设备注册成功后，如果你监听了 getRegistrationId 这个事件，将会收到 registrationId。

**Comment by wjljack** [comment]
@KenChoi1992 建议你可以自己集成试试看 新建一个空项目

**Comment by KenChoi1992** [comment]
@wjljack example 中的 PushDemo 就是一个例子，我还要再做一遍？如果是设备注册问题，你可以到[我们的社区](https://community.jiguang.cn/)搜一下解决方案。

**Comment by KenChoi1992** [comment]
@wjljack 有不少人安装了 jcore-react-native，但是没有配置成功，或许你可以看看[这篇文章](http://www.jianshu.com/p/6721a0360af9)，这个 issue 先关了，如果还有疑问你再打开。

**Comment by wjljack** [comment]
之前文档中缺少了初始化代码        JPushInterface.init(this);
看起来现在加了个手动配置链接里面提到了
