### ISSUE TITLE
jcore-react-native不能被link，但它是必须

### ISSUE THREAD

**Issue by durongzhang** [jpush/jpush-react-native#162]
jcore-react-native不能被link，但它是必须的，但首页的文档里却没有提及要加入它，导致有些人按文档也不能成功，首页文档也没有提及ReactActivity中onPause和onResume的必要性及作用。希望能优化下文档🙏

**Comment by KenChoi1992** [comment]
@durongzhang  文档已更新。onPause, onResume 如果没添加会出现弹窗警告。有关于 JPush SDK 本身的疑惑，[希望参考一下我们的官方文档。](https://docs.jiguang.cn/jpush/guideline/intro/)
