### ISSUE TITLE
关于 6009的问题

### ISSUE THREAD

**Issue by combing520** [jpush/jpush-react-native#166]
您好。我按照您给的步骤，然后配置是按照您 的 example中android 操作的，然后在激光的官网上注册了对应的信息的应用，当我使用您那边的  设置 tag 和 设置 alias的时候，全是返回 6009， 是不是不能按照您给的例子上面的写法？

**Comment by KenChoi1992** [comment]
@combing520 你提的问题重复了，关掉这个 issue 了。
