### ISSUE TITLE
关于代码中的例子无法正常运行

### ISSUE THREAD

**Issue by combing520** [jpush/jpush-react-native#167]
您给的 例子 不能成功运行? 我拿了您的例子里面的代码，然后在我的激光控制台，配置了相关的Android包名信息， 也按照了您的 步骤 ，先  InitPush ,然后设置　　别名　或者　Ｔａｇ，　但是会一直是　６００９，求指教

**Comment by KenChoi1992** [comment]
@combing520 6009 错误是权限问题导致 PushService 启动异常，麻烦看一下日志，看看报什么错。demo 运行是没有这个错误的。

**Comment by SuperRainX** [comment]
demo 当中出现了ld: library not found for -lRCTJCoreModel
这是什么愿意呢

**Comment by huangminlinux** [comment]
@SuperRainX  jcore-react-native 安装了没

**Comment by klforeverl** [comment]
Running application "PushDemo" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF，请问这个错误如何解决。

**Comment by GoldenForest** [comment]
iOS Demo 里边的[JPUSHService registerForRemoteNotificationConfig:entity delegate:self];
那个AppDelegate也没有实现JPUSHService的协议，。。。。。。

**Comment by SuperRainX** [comment]
@huangminlinux 十分感谢本以为安装好了,结果发现jcore安装失败,非常感谢.

**Comment by KenChoi1992** [comment]
@combing520 务必要记得配置 jcore，没有其他问题就关闭了。
