### ISSUE TITLE
 错误: 无法将类 JPushPackage中的构造器 JPushPackage应用到给定类型;

### ISSUE THREAD

**Issue by zhangrundong** [jpush/jpush-react-native#168]
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/smart/Documents/qsndyr/android/app/src/main/java/com/qsndyr/MainApplication.java:35: 错误: 无法将类 JPushPackage中的构造器 JPushPackage应用到给定类型;
            new JPushPackage()
            ^
  需要: boolean,boolean
  找到: 没有参数
  原因: 实际参数列表和形式参数列表长度不同
1 个错误
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

**Comment by KenChoi1992** [comment]
你需要穿两个布尔参数，表示是否关闭 Toast，以及日志。如：
```
new JPushPackage(false, false)
```
表示两者都不关闭。

**Comment by giantss** [comment]
建议默认设置`new JPushPackage(false, false)` ，然后文档中说明，不然build android是失败的

**Comment by vonch** [comment]
正好遇到这个问题楼上正解啊~~
