### ISSUE TITLE
Running application "PushDemo" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF

### ISSUE THREAD

**Issue by klforeverl** [jpush/jpush-react-native#171]
Running application "PushDemo" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF ，请问这个问题如何解决

**Comment by KenChoi1992** [comment]
@klforeverl 这并不是个错误，而是运行时打印的信息。

**Comment by KenChoi1992** [comment]
@klforeverl 没有其他问题就关闭了。
