### ISSUE TITLE
关于在IOS上无法推送的问题请教

### ISSUE THREAD

**Issue by wh469012917** [jpush/jpush-react-native#172]
如题，按照文档配置成功后，但是推送无效，具体情况如下（在IOS下）：

配置过程：
1.首先按照README配置走了一遍,就是这张截图的流程，先自动link，然后在手动配置。红框中的应该是link之后安卓部分的手动配置吧？？建议可以改一下README，让人更加清晰明了的知道自动配置之后还要手动配置，而且手动配置是分为安卓和IOS的。
![image](https://cloud.githubusercontent.com/assets/10496478/23940639/b3224f8e-09a0-11e7-90b7-9e31f1d24de6.png)
注：我在link的过程中，提示了link成功了，但是有提示一堆函数没找到，不知道是不是有影响（文档没说）
![image](https://cloud.githubusercontent.com/assets/10496478/23941081/702533f2-09a2-11e7-9282-a0ff4cd420ad.png)

2.再按照该以下文档的配置：
[https://github.com/jpush/jpush-react-native/blob/master/example/documents/iOS_Usage.md](url)
> 注：以上文档的配置我只是对AppDelegate.h做了导入头文件和设置accesskey的操作，对于AppDelegate.m里面方法的修改我并没有操作（因为已经看到里面有一堆代码了，应该是link的时候自动添加进去的）

3.在以上两步之前已经把IOS的推送证书（分为开发和生产），上传到了极光的后台，并且后台显示验证成功

4.在xcode里面设置推送打开：
![image](https://cloud.githubusercontent.com/assets/10496478/23940864/85d7c26a-09a1-11e7-933b-0e792224833b.png)

> 注：以上配置后成功的在xcode的library里面看到了RCTJPushModule这个模块，应该就表示集成SDK成功

以上配置后，通过xcode编译成功安装到了模拟器上，然后登录极光的web后台进行测试，测试过程：
1.选择的是群发推送，IOS开发环境，测试过程极光显示，没有满足推送要求的目标
注：极光推送不支持在模拟器上，但是在xcode上会有相应的日志提示，我在xcode控制台没有看到任何报错以及其他信息

> 我所有的操作都是按照文档走的，而且也成功编译安装到机器上，但是却无法推送，我还可以做哪些尝试？

以下是我的软件版本：
```
react  15.4.1
react-native  0.42.0
```

贴一张启动后xcode的日志图，由于没有ios开发经验，所以看不懂是否有错，烦请指教：
![image](https://cloud.githubusercontent.com/assets/10496478/23941749/0c285e62-09a5-11e7-85ac-504c598c06cb.png)

**Comment by huangminlinux** [comment]
推送功能不能在在模拟器上使用， 一定要真机才能正常使用。

关于 以上的几点建议，这边会采纳

**Comment by myp007** [comment]
我的是真机上也出现问题了

**Comment by bmxklYzj** [comment]
> iOS 推送功能不能在在模拟器上使用， 一定要真机才能正常使用。

这么关键的信息貌似文档没写在显眼的位置（或许是我没看到），浪费了小半天时间
