### ISSUE TITLE
请问大量的 JPush 2.1.9 版本已过期 warnings 要怎么处理？

### ISSUE THREAD

**Issue by Kennytian** [jpush/jpush-react-native#173]
macOS 10.12.3
React Native 41.0
jcore-react-native: ^1.0.0
jpush-react-native: ^1.5.0

/Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.m:384:17: warning: 'setLocalNotification:alertBody:badge:alertAction:identifierKey:userInfo:soundName:' is deprecated: JPush 2.1.9 版本已过期 [-Wdeprecated-declarations]
  [JPUSHService setLocalNotification:fireDate
                ^
In file included from /Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.m:10:
In file included from /Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.h:19:
/Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/JPUSHService.h:332:1: note: 'setLocalNotification:alertBody:badge:alertAction:identifierKey:userInfo:soundName:' has been explicitly marked deprecated here
+ (UILocalNotification *)setLocalNotification:(NSDate *)fireDate
^
/Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.m:404:17: warning: 'showLocalNotificationAtFront:identifierKey:' is deprecated: JPush 2.1.9 版本已过期 [-Wdeprecated-declarations]
  [JPUSHService showLocalNotificationAtFront:notification identifierKey:notificationKey];
                ^
In file included from /Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.m:10:
In file included from /Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.h:19:
/Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/JPUSHService.h:368:1: note: 'showLocalNotificationAtFront:identifierKey:' has been explicitly marked deprecated here
+ (void)showLocalNotificationAtFront:(UILocalNotification *)notification
^
/Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.m:413:17: warning: 'deleteLocalNotificationWithIdentifierKey:' is deprecated: JPush 2.1.9 版本已过期 [-Wdeprecated-declarations]
  [JPUSHService deleteLocalNotificationWithIdentifierKey:notificationKey];
                ^
In file included from /Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.m:10:
In file included from /Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.h:19:
/Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/JPUSHService.h:376:1: note: 'deleteLocalNotificationWithIdentifierKey:' has been explicitly marked deprecated here
+ (void)deleteLocalNotificationWithIdentifierKey:(NSString *)notificationKey __attribute__((deprecated("JPush 2.1.9 版本已过期")));
^
/Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.m:420:17: warning: 'deleteLocalNotification:' is deprecated: JPush 2.1.9 版本已过期 [-Wdeprecated-declarations]
  [JPUSHService deleteLocalNotification:localNotification];
                ^
In file included from /Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.m:10:
In file included from /Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.h:19:
/Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/JPUSHService.h:382:1: note: 'deleteLocalNotification:' has been explicitly marked deprecated here
+ (void)deleteLocalNotification:(UILocalNotification *)localNotification __attribute__((deprecated("JPush 2.1.9 版本已过期")));
^
/Users/kenny/projects/node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.m:430:26: warning: 'findLocalNotificationWithIdentifier:' is deprecated: JPush 2.1.9 版本已过期 [-Wdeprecated-declarations]
  callback([JPUSHService findLocalNotificationWithIdentifier:notificationKey]);
                         ^

**Comment by huangminlinux** [comment]
可以忽略警告 ，这是一些过期不建议使用的接口

**Comment by Kennytian** [comment]
@huangminlinux  我其实是想你们能不能更新一下代码，别再调用过期的方法 😃

**Comment by huangminlinux** [comment]
@Kennytian  这些方法功能没有问题的，只是新版本有更推荐的实现， 如果删除会导致之前用户的代码出错。

新版本的几个接口还没加上，会在下个版本中添加
