### ISSUE TITLE
Crash in Android after receiving notification when app is killed

### ISSUE THREAD

**Issue by sunkibaek** [jpush/jpush-react-native#175]
After receiving notification when app is not active or not in background (no process running) it crashes with following error in jiguan.

```
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so
	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:314)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
	at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:20)
	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
	at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
	at com.facebook.react.bridge.Arguments.createMap(Arguments.java:29)
	at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:280)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2743)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1431)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

Any ideas how to go about it?

Thanks!

**Comment by KenChoi1992** [comment]
@sunkibaek Which version are you using ? Because line 280 in the newest version can't cause this error.

**Comment by sunkibaek** [comment]
I am using 1.5.3.

I takes about 10 min to receive push notification and then the app crashes when it receives it. Using react-native 0.41.2.

**Comment by KenChoi1992** [comment]
@sunkibaek If your app is not running before, when it receives notifications will save as local notifications, that should be finished in 10 seconds after receiving notification. 10 minutes delay is possible within the period of fastigium. Maybe we should catch throwable errors here. See if this issue can help you: https://github.com/facebook/react-native/issues/2814

**Comment by sunkibaek** [comment]
@KenChoi1992  I will try those and get back to you soon. Thanks for the help!

**Comment by KenChoi1992** [comment]
@sunkibaek Did it work ?

**Comment by sunkibaek** [comment]
@KenChoi1992 Unfortunately no. It doesn't seem to work for our case.

I have applied the solutions above by adding lines to `build.gradle`:

```
android {
    defaultConfig {
        ...
        packagingOptions {
            exclude '/lib/mips64/**'
            exclude '/lib/arm64-v8a/**'
            exclude '/lib/x86_64/**'
        }
    }
...
```

And then I have this error in jPush dashboard
```
java.lang.ExceptionInInitializerError
	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
	at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
	at com.facebook.react.bridge.Arguments.createMap(Arguments.java:29)
	at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:278)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2743)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1431)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.RuntimeException: SoLoader.init() not yet called
	at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:335)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:238)
	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
	at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:20)
	... 13 more
```

Thanks!

**Comment by KenChoi1992** [comment]
@sunkibaek Have you add SoLoader.init() in MainApplication#onCreate ?
```
    @Override
    public void onCreate() {
        super.onCreate();
        SoLoader.init(this, false);
    }
```

**Comment by sunkibaek** [comment]
I was actually wasn't sure where to put `SoLoader.init` -- let me try your suggestion.

**Comment by sunkibaek** [comment]
@KenChoi1992

It WORKED! 

Now I have two new problems:
- Now I can see so many of those notifications until I turn on the app.
- When I tap on the notification, it does not open the app. It only dismisses it.

Thanks!

**Comment by KenChoi1992** [comment]
@sunkibaek If you receive notifications when app is killed, the ReactContext is null, so the best suggestion is that you custom your appointed Activity which click notification will jump to, and you can still use JS to render the Activity. Take demo's SecondActivity for example, you need to create a local Activity(Such as [SecondActivity](https://github.com/jpush/jpush-react-native/blob/master/example/android/app/src/com/pushdemo/SecondActivity.java)), don't forget to register Activity in AndroidManifest, then create JS file to render this Activity(Such as [second.js](https://github.com/jpush/jpush-react-native/blob/master/example/react-native-android/second.js)). After doing this, you need to change class name here:
```
 Intent intent = new Intent();
intent.setClassName(mRAC.getPackageName(), mRAC.getPackageName() + ".MainActivity");
```

**Comment by sunkibaek** [comment]
@KenChoi1992 Thanks for the suggestion. Is this optional to solve my problem or must?

If it is possible I would like to keep my app as a single activity.

**Comment by KenChoi1992** [comment]
@sunkibaek If your app just has a MainActivity, simply change this line to packageName + ".MainActivity"
![image](https://cloud.githubusercontent.com/assets/8196928/24697093/7dc6ab58-1a1e-11e7-9da9-a32edd0a9728.png)

For example, if your package name is com.test.jpush, then the second parameter will be "com.test.jpush.MainActivity".

**Comment by sunkibaek** [comment]
@KenChoi1992 

In our app case, `mRAC` is always null when the notification is opened when the app is not running. so this line

```
// https://github.com/jpush/jpush-react-native/blob/master/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java#L331
if (mRAC != null) {
```
always evaluates `false`.

So I added following lines after `if` block

```
} else {
                        Logger.i(TAG, "Context is null");

                        try {
                            Intent intent = new Intent();
                            intent.setClassName("com.hsmobile", "com.hsmobile.MainActivity");
                            intent.putExtras(bundle);
                            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP);
                            context.startActivity(intent);
                        } catch (Exception e1) {
                            e1.printStackTrace();
                            Logger.i(TAG, "Cannot find MainActivity, will discard onClick event.");
                        }
                    }
```

that solves my first problem.

Do you think there is a way to guess package name without relying on context?

**Comment by KenChoi1992** [comment]
@sunkibaek You don't need to guess package name, onReceive() method has two parameters, one is context, you can use it to get package name:

```
intent.setClassName(context.getPackageName(), context.getPackageName() + ".MainActivity");
```

**Comment by sunkibaek** [comment]
@KenChoi1992 I see. That works!

Then we might not need to check if `mRAC` is null or not here

```
// https://github.com/jpush/jpush-react-native/blob/master/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java#L331
if (mRAC != null) {
```

instead,  we can just use your solution to set class on intent whether `mRAC` is empty or not.

**Comment by KenChoi1992** [comment]
@sunkibaek In that case it is, but I supposed ```mRAC``` should not be null.

**Comment by sunkibaek** [comment]
@KenChoi1992 I see.

So far everything works fine. Except the user sees the same notification every 5 to 10 seconds until she opens it when the app is not running. If the user opens the notification, it stops coming.

Any ideas?

**Comment by KenChoi1992** [comment]
@sunkibaek We save the notifications as local notifications when received notifications while app is not running, try to deprecate the code in JPushModule:
```
if (!isApplicationRunning(context)) {
//                        Log.i(TAG, "应用尚未切换到前台运行过，启动 HeadlessService");
//                        Intent intent = new Intent(context, HeadlessService.class);
//                        intent.putExtra("data", bundle);
//                        context.startService(intent);
//                        HeadlessJsTaskService.acquireWakeLockNow(context);
                        // Save as local notification
                        // Start up application failed, will save notifications as local notifications.
                        Logger.i(TAG, "应用尚未切换到前台运行过, 保存为本地通知");
                        JPushLocalNotification notification = new JPushLocalNotification();
                        notification.setBuilderId(NOTIFICATION_BUILDER_ID);
                        NOTIFICATION_BUILDER_ID++;
                        notification.setNotificationId(System.currentTimeMillis());
                        notification.setContent(bundle.getString(JPushInterface.EXTRA_ALERT));
                        notification.setTitle(bundle.getString(JPushInterface.EXTRA_TITLE));
                        notification.setExtras(bundle.getString(JPushInterface.EXTRA_EXTRA));
                        notification.setBroadcastTime(System.currentTimeMillis() + 1000 * 10);
                        JPushInterface.addLocalNotification(context, notification);
                    }
```

**Comment by sunkibaek** [comment]
@KenChoi1992

Yeah, I think that is the point.

Maybe I should use the same notification id for the same notification.

**Comment by KenChoi1992** [comment]
@sunkibaek As we discussed in https://github.com/jpush/jpush-react-native/issues/78, I save the notifications as local notifications, if this change caused receiving same notification, I'll deprecate this change.

**Comment by sunkibaek** [comment]
Okay, let me try without local notifications. Thanks!

**Comment by KenChoi1992** [comment]
@sunkibaek I publish a new release, fix this bug, closing issue now.
