### ISSUE TITLE
自动配置和手动配置对项目文件的更改是不一致的

### ISSUE THREAD

**Issue by nouh** [jpush/jpush-react-native#176]
照着README走了一遍，但发现通过npm run configureJpush [APPKEY] [Modulename] 这个脚本跑出来的对项目文件的更改和参考手动配置进行的更改是不一致的，我到底应该follow哪个为准

**Comment by KenChoi1992** [comment]
@nouh 要装 jcore，跟着手动配置走吧，下个版本更新一下脚本。
