### ISSUE TITLE
IOS打包，release下会报错

### ISSUE THREAD

**Issue by RealAmissio** [jpush/jpush-react-native#177]
Showing All Messages
  "_kJPFNetworkDidSetupNotification", referenced from:

      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)

  "_kJPFNetworkDidRegisterNotification", referenced from:

      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)

  "_kJPFNetworkDidReceiveMessageNotification", referenced from:

      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)

  "_OBJC_CLASS_$_JPUSHService", referenced from:

      objc-class-ref in AppDelegate.o

      objc-class-ref in libRCTJPushModule.a(RCTJPushActionQueue.o)

      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)

  "_kJPFNetworkDidLoginNotification", referenced from:

      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)

  "_kJPFNetworkDidCloseNotification", referenced from:

      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)

  "_OBJC_CLASS_$_JPUSHRegisterEntity", referenced from:

      objc-class-ref in AppDelegate.o

ld: symbol(s) not found for architecture i386

clang: error: linker command failed with exit code 1 (use -v to see invocation)

debug下编译没问题，打包成release就会报错，请问是什么原因

**Comment by huangminlinux** [comment]
试试
```
TARGETS -> Build Settings -> Build Active Architecture Only -> release 设为 Yes
```
