### ISSUE TITLE
为什么只有clearAllNotifications方法，却没有clearNotificationById方法？

### ISSUE THREAD

**Issue by colin-han** [jpush/jpush-react-native#178]
Hi, 极光开发者，

jpush-react-native模块中为什么没有clearNotificationById方法？

我的RN应用中有一个界面列出了当前所有的消息，通过接收JPush的Notification，我会将新消息添加到消息列表中。当用户点击消息列表中的一个消息时，我会移除这个消息，同时，希望移除Android通知区里面的对应消息。

我看到JPUSH的Android SDK中包含两个清除通知区消息的方法：clearAllNotifications和clearNotificationById，但是，在jpush-react-native中却没有找到第二个方法。为什么？

谢谢

**Comment by KenChoi1992** [comment]
@colin-han 这个地方确实没有，下个版本加上。

**Comment by KenChoi1992** [comment]
@colin-han v1.5.5 已经加上了。

**Comment by colin-han** [comment]
Great, thanks a lot.
