### ISSUE TITLE
建议：重新调整修改文档

### ISSUE THREAD

**Issue by wh469012917** [jpush/jpush-react-native#181]
如题，文档写的可以说真的是非常非常烂~

给个建议可以这么写：
# 安装
只要写出通过哪条命令以及需要安装的包即可
```
npm install jpush-react-native --save
npm install jcore-react-native --save     //jpush-react-native 1.4.2 版本以后需要同时安装 jcore-react-native
```

# 配置
配置有两种方式，分为自动配置和手动配置。其中自动配置并非为全自动（以后版本或许会改进），还是需要部分手动操作。这里推荐使用自动配置
### 1.配置AppKey和ModuleName 
```
npm run configureJPush <yourAppKey> <yourModuleName>
```
module name 指的是你 Android 项目中的模块名字(对 iOS 没有影响，不填写的话默认值为 app，会影响到查找 AndroidManifest 问题，如果没找到 AndroidManifest，则需要手动修改，参考下面的 AndroidManifest 配置相关说明)

> 举个例子:
> npm run configureJPush d4ee2375846bc30fa51334f5 app

### 2.手动操作部分（自动配置并非为全自动，还是需要部分手动操作）
对于`Android`和`IOS`都需要部分的手动操作，具体操作如下：
#### 1.安卓部分（4个步骤）
- 修改 android 项目下的 settings.gradle 配置
- 检查一下 app 下的 AndroidManifest 配置，有没有增加 <meta-data> 部分
- 修改 app 下的 build.gradle 配置：
- 加入 [JPushPackage（不同RN的版本操作也不同）](https://github.com/jpush/jpush-react-native/blob/master/example/documents/Android%20Usage.md)
```
打开 app 下的 MainActivity，在 ReactInstanceManager 的 build 方法中加入 JPushPackage（0.29.0以下版本）
打开 app 下的 MainApplication.java 文件，然后加入 JPushPackage（0.29.0以上版本）
```
现在重新 sync 一下项目，应该能看到 jpush-react-native 以及 jcore-react-native 作为 android Library 项目导进来了
#### 2.IOS部分（4个步骤）
- 在 iOS 工程中设置 TARGETS-> BUILD Phases -> LinkBinary with Libraries 找到 UserNotifications.framework 把 status 设为 optional
- 在 iOS 工程中如果找不到头文件可能要在 TARGETS-> BUILD SETTINGS -> Search Paths -> Header Search Paths 添加如下如路径
```
$(SRCROOT)/../node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule
```

- 在 xcode8 之后需要点开推送选项： TARGETS -> Capabilities -> Push Notification 设为 on 状态
- 参看[https://github.com/jpush/jpush-react-native/blob/master/example/documents/iOS_Usage.md]()
> 以上四个步骤中，其中第四个步骤部分在自动生成中已经配置好了，注意不要重复配置

## 手动配置
手动配置就不说了

# 使用
使用的话`Android`和`IOS`的用法也有点不一样，但是有几个API是一样的：
### 3.IOS下的API

# 写在后面
#### Common API for Android and iOS.
- setTags(array, successCallback, failedCallback)

#### In Android, you must call initPush first.
- getRegistrationID(callback)
- setAlias(alias, successCallback, failedCallback)

#### 1.中英文混排
外面的文档是中文，这里面却要用英文，如果要以多语言来展示，就应该要出一份全英文和全中文的，而不是这样中英文混排
#### 2.对于后面两个API的描述
那句**In Android, you must call initPush first**，这个是对后面两个API的描述，**并不应该是二级标题啊**！！！这样写的话会给人一种感觉，后面两个API是属于安卓专用的，IOS不能使用。所以正确应该这样写：
#### Common API for Android and iOS.
- setTags(array, successCallback, failedCallback)
- getRegistrationID(callback)
- setAlias(alias, successCallback, failedCallback)

> 在安卓下，其中`getRegistrationID`和`setAlias`这两个API在使用之前必须先init，IOS下则不用。

**Comment by huangminlinux** [comment]
非常抱歉文档给你造成的麻烦，同时非常感谢以使用者的角度给我们提的建议。
我们会重新整理文档的格式，修改容易让人误解的地方。

**Comment by KenChoi1992** [comment]
@wh469012917 文档已经改版了，看下还有没有什么问题。
