### ISSUE TITLE
JPushModule 监听入口你们是放那个地方的？

### ISSUE THREAD

**Issue by jacobcyl** [jpush/jpush-react-native#184]
我使用`RN 0.42 + react-native-router-flux + redux` 架构，想知道JPushModule的监听方法该放那个入口。我的app启动第一个scene是Home首页，我目前是放这个Home component的componentWillMount方法里面，然后注销监听就放这个文件的componentUnMount方法里面，不知道这样放可不科学。想听听大家的是怎么放的。

**Comment by huangminlinux** [comment]
建议尽可能放到 程序的初始阶段，并且避免监听放到异步操作中，以防出现  唤起应用的时候事件还没被监听就抛上来的问题  （比如点击推送唤起应用无法收到事件，这种常见问题）
