### ISSUE TITLE
example react-native run-android 错误

### ISSUE THREAD

**Issue by zavven** [jpush/jpush-react-native#186]
## 我做了什么
1. git clone jpush-react-native
2. cd example
3. yarn install
4. react-native run-android

## 我得到什么
```
ENOENT: no such file or directory, open 'app/src/main/AndroidManifest.xml'
```

**Comment by zavven** [comment]
我按照 readme 的做法，已经成功在自己的 Android 项目下运行。但是官方的example还是没有成功。

**Comment by zavven** [comment]
3. 我对比了一下自己的项目（rn-cli 初始化的）和官方的example，发现 `android` 的目录结构是不一样的。根据官方readme的描述，我自己的项目目录结构应该是正确的。下面贴一下对比图：

<img width="828" alt="jpush-react-native android" src="https://cloud.githubusercontent.com/assets/3387572/24331033/985c1920-125e-11e7-91c7-4f5bf8eae929.png">

**Comment by KenChoi1992** [comment]
@zavven 你好，我们官方的 demo 采用的项目结构是 Android Studio 和 Eclipse 是通用的。这个目录结构并不影响，只需要你在 build.gradle 中配置一下即可。
```
sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            jniLibs.srcDirs = ['libs']
            java.srcDirs = ['src']
            aidl.srcDirs = ['src']
            resources.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }
    }
```

**Comment by KenChoi1992** [comment]
@zavven 至于你说 demo 无法运行，你需要用 Android Studio 打开 example 下的 android 文件夹，将 app 下的 build.gradle 中的 AppKey 和 applicationId 改成自己的，然后编译下即可运行。

**Comment by zavven** [comment]
@KenChoi1992 谢谢你的解答。
> 我们官方的 demo 采用的项目结构是 Android Studio 和 Eclipse 是通用的。

我在 `example` 中的 build.gradle 有看到相关的配置，也将 AppKey 和 applicationId 改成自己的，并尝试重新 `react-native run-android`，在我本地依然会有这个错误：
```
ENOENT: no such file or directory, open 'app/src/main/AndroidManifest.xml'
```

无论如何，我跟着官方的 `readme` 是能够正确使用的。或许 `example` 的失败是我本地环境造成的，也没有其它人出现类似情况。我先关闭这个 issue 吧。
