### ISSUE TITLE
an't locate file for: -ljcore-ios

### ISSUE THREAD

**Issue by since66** [jpush/jpush-react-native#187]
官方例子下载后运行xcode提示
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -ljcore-ios
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -ljcore-ios is not an object file (not allowed in a library)

**Comment by huangminlinux** [comment]
jcore-react-native 成功安装没

**Comment by since66** [comment]
npm install jcore-react-native --save
PushDemo@0.0.1 /Users/HGJ/Downloads/jpush-react-native-master/example
└── jcore-react-native@1.0.0 

提示是成功的

**Comment by huangminlinux** [comment]
加一下 群  我了解一下具体情况

**Comment by since66** [comment]
群号码是？

**Comment by huangminlinux** [comment]
更新了 iOS example 代码, 可以正常运行了

**Comment by since66** [comment]
辛苦了

**Comment by apenshar** [comment]
我也是这个问题，重新下载了jcore-react-native 还是报错
