### ISSUE TITLE
link jcore-react-native 失败

### ISSUE THREAD

**Issue by ZheJiangEflying** [jpush/jpush-react-native#188]
jpush-react-native能link成功，检查jcore-react-native已经安装在node_modules下了，但是link jcore-react-native 失败。

Gradle sync failed: Project with path ':jcore-react-native' could not be found.
          Consult IDE log for more details (Help | Show Log)

**Comment by KenChoi1992** [comment]
@ZheJiangEflying 看看文档，检查一下是否已经自动配置成功了。

**Comment by ZheJiangEflying** [comment]
@KenChoi1992 这个jcore-react-native link不进去，需要到Android里面手动添加，现在可以使用了，谢谢啊
