### ISSUE TITLE
iOS 程序后台运行，应用能收到消息，但是RN的监听代码NativeAppEventEmitter 却获取不到

### ISSUE THREAD

**Issue by GoldenForest** [jpush/jpush-react-native#189]
application jpushNotificationCenter didReceiveNotificationResponse
已收到消息，但是NativeAppEventEmitter获取不到
NativeAppEventEmitter.addListener(
                'ReceiveNotification',
                (notification) => {
                    console.log(notification)
                
                }
            );
导致程序后台运行时，RN拿不到消息，大家这方面是怎么解决的

**Comment by GoldenForest** [comment]
用官方的的PushNotificationIOS.addEventListener('notification', this._getNotification());
这个可以收到

**Comment by huangminlinux** [comment]
使用的是什么系统？

**Comment by GoldenForest** [comment]
XCode 8.2  iOS 10.2.1   ReactNative 0.42.0

**Comment by huangminlinux** [comment]
我这边可以啊

**Comment by huangminlinux** [comment]
如果你指的是 backgroud mode，你需要额外的配置

1. Target -> Capabilities -> Background Modes -> Remote notification 点选

2.  服务端推送 要设置参数  content-available = 1;  （如果是控制台点选就可以了）
