### ISSUE TITLE
JPushModule.getRegistrationID这个方法，android4-5分钟才能拿到id

### ISSUE THREAD

**Issue by 1610449813** [jpush/jpush-react-native#190]
使用JPushModule.getRegistrationID这个方法，ios几秒就能拿到id，但是android1要4-5分钟，我是用了二台手机都是差不多4-5分钟，我是使用wifi的

**Comment by KenChoi1992** [comment]
@1610449813 试试这个
```
JPushModule.addGetRegistrationIdListener((registrationId) => {
            console.log("Device register succeed, registrationId " + registrationId);
        });
```
在应用打开后，如果拿到了 registrationId，立即返回，只运行一次。

**Comment by 1610449813** [comment]
这个监听是ios和android共用的吗？

**Comment by KenChoi1992** [comment]
@1610449813 只有安卓有。

**Comment by 1610449813** [comment]
是不是初始化拿到registrationId都要4-5分钟？

**Comment by 1610449813** [comment]
@KenChoi1992 是不是初始化拿到registrationId都要4-5分钟？

**Comment by xwartz** [comment]
@KenChoi1992   为什么获取 getRegistrationID 需要这么长时间？

**Comment by xwartz** [comment]
魅族手机在调用 `JPushModule.getRegistrationID` 方法，发现 `getCurrentActivity` 返回的是 NULL，会造成 crash。 jpush 版本是 1.3.5。

`addGetRegistrationIdListener ` 是为了解决什么样的问题呢

**Comment by KenChoi1992** [comment]
@xwartz 这个是 SDK 初次注册成功后返回的。可以看看[我们的文档](https://docs.jiguang.cn/jpush/client/Android/android_api/#registrationid-api)，而 getRegistrationId 这个方法则是在注册成功后让用户可以多次调用。

**Comment by KenChoi1992** [comment]
@1610449813 @xwartz 正常来讲，SDK 注册是很快的，最近会更新一下 JPush SDK。

**Comment by KenChoi1992** [comment]
新版本更新了 SDK，先关掉这个 issue 了。
