### ISSUE TITLE
能否简化配置到无需手动操作

### ISSUE THREAD

**Issue by nouh** [jpush/jpush-react-native#191]
因为经常要删除ios和android的工程，所以最好能够通过react-native link一条命令完成重新配置

**Comment by KenChoi1992** [comment]
@nouh 目前来说，link 绝不能完成所有配置，因为 appKey 这个是要加上去的。

**Comment by nouh** [comment]
那是否可以完成所有配置，只留下appkey让用户自己手动替换呢

**Comment by nouh** [comment]
`npm run configureJPush <yourAppKey> <yourModuleName>`
中的ModuleName到底是否用默认的app就可以了，还是应该用哪个模块名？

**Comment by KenChoi1992** [comment]
@nouh 换成你自己的，如果不知道的话就是默认的。
