### ISSUE TITLE
RCTJPushModule.h  file not found

### ISSUE THREAD

**Issue by basilbai** [jpush/jpush-react-native#193]
![0239703e-9f16-4fcd-882d-059b4fc6a169](https://cloud.githubusercontent.com/assets/26473415/24826275/5e6f9d8a-1c64-11e7-946c-0fb04079cc21.png)
xcode 里面提示AppDelegate.m:11:9: 'RCTJPushModule.h' file not found

**Comment by huangminlinux** [comment]
估计是忽略了  iOS 手动操作部分 （3个步骤）

在 iOS 工程中设置 TARGETS-> BUILD Phases -> LinkBinary with Libraries 找到 UserNotifications.framework 把 status 设为 optional

在 iOS 工程中如果找不到头文件可能要在 TARGETS-> BUILD SETTINGS -> Search Paths -> Header Search Paths 添加如下路径

$(SRCROOT)/../node_modules/jpush-react-native/ios/RCTJPushModule/RCTJPushModule
在 xcode8 之后需要点开推送选项： TARGETS -> Capabilities -> Push Notification 设为 on 状态

**Comment by basilbai** [comment]
我已经执行了这一步操作《在 iOS 工程中如果找不到头文件可能要在 TARGETS-> BUILD SETTINGS -> Search Paths -> Header Search Paths 添加如下路径》，情况仍然存在

**Comment by basilbai** [comment]
@huangminlinux 我已经执行了这一步操作《在 iOS 工程中如果找不到头文件可能要在 TARGETS-> BUILD SETTINGS -> Search Paths -> Header Search Paths 添加如下路径》，情况仍然存在

**Comment by huangminlinux** [comment]
- react-native link 了吗？    
- 再者检查一下， 安装插件是否错安装到 全局了，  
- 检查一下所添加的路径 能不能找到

**Comment by huangminlinux** [comment]
不知道问题解决没， 我先关闭这个 issue 如果还没解决重新再打开

**Comment by basilbai** [comment]
@huangminlinux 已经解决了，麻烦你了，谢谢！

**Comment by qq326646683** [comment]
rn:0.39.2,"
jcore-react-native": "^1.1.0",
"jpush-react-native": "^1.6.0",

debug可以，但release还会报这个错

**Comment by huangminlinux** [comment]
@qq326646683  使用真机

或者 TARGETS -> Build Settings -> Build Active Architecture Only -> release 设为 Yes
