### ISSUE TITLE
JSON value '2017-04-13 06:52:28 +0000' of type NSDate cannot be converted to a date

### ISSUE THREAD

**Issue by beautycss** [jpush/jpush-react-native#197]
5s真机调试example，本地推送通知总是报错，点了按钮“添加本地推送”就报错提示：
JSON value '2017-04-13 06:52:28 +0000' of type NSDate cannot be converted to a date

ios 10.2
react native 0.42

JSON value '2017-04-13 06:52:28 +0000' of type NSDate cannot be converted to a date

+[RCTConvert NSDate:]
    RCTConvert.m:220
__41-[RCTModuleMethod processMethodSignature]_block_invoke.155
-[RCTModuleMethod invokeWithBridge:module:arguments:]
-[RCTBatchedBridge callNativeModule:method:params:]
__33-[RCTBatchedBridge handleBuffer:]_block_invoke.477
<redacted>
<redacted>
_dispatch_main_queue_callback_4CF
<redacted>
<redacted>
CFRunLoopRunSpecific
GSEventRunModal
<redacted>
UIApplicationMain
main
<redacted>

换了台5s 10.2.1 也是同样问题。
但是远程推送通知又没问题，开发环境都能推送成功。

**Comment by huangminlinux** [comment]
example 是有点问题， 已修复，可以更新下代码

**Comment by beautycss** [comment]
可以了 👍
