### ISSUE TITLE
点击推送无法跳转到指定页面

### ISSUE THREAD

**Issue by RealAmissio** [jpush/jpush-react-native#198]
根据这篇文章http://www.jianshu.com/p/7c03db422c6d，打开app可以跳转到指定页面了，但是app后台或者关闭时无法根据点开通知消息跳转到指定页面，只能跳转到主页，请问这是什么原因？无论是在componentDidMount里还是在componentWillMount里都无法跳转，控制台报Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Navigator component.

**Comment by lzctbyong** [comment]
@RealAmissio ,楼主解决了吗？

**Comment by KenChoi1992** [comment]
@RealAmissio  你是怎么做的？你有创建原生的界面吗？

**Comment by RealAmissio** [comment]
@KenChoi1992 创了啊，完全按照简书上的操作的，JPushModule.addReceiveOpenNotificationListener((map) => {
      this.props.navigator.push({component:My})
    });
然后这边跳转就是不过去，一直报上面的警告

**Comment by lzctbyong** [comment]
@KenChoi1992 
意思是用navigator去跳转，不在安卓原生修改跳转页面，可行吗？

**Comment by KenChoi1992** [comment]
@RealAmissio @lzctbyong 应该是不行的，因为 app 之前没运行过，收到推送后必须由本地启动，因此不能直接用 navigator 跳转。要在原生的地方跳转。文章里已经介绍了用原生的方法跳转，但是界面你们还是可以用 JS 来写。

**Comment by Woodswu** [comment]
这个不是在 readme 里面有详细的描述了么，按照他们的方法写一个active 就可以实现了，界面还是可以像楼上说的那样去实现

**Comment by lzctbyong** [comment]
@Woodswu active ?

**Comment by RealAmissio** [comment]
@KenChoi1992 
Error:(254, 53) 错误: 找不到符号
符号:   类 SecondActivity
位置: 类 JPushReceiver
按照上面找不到这个类。。

**Comment by KenChoi1992** [comment]
@RealAmissio 你要这样写：
```
Intent intent = new Intent();
                        intent.setClassName(context.getPackageName(), context.getPackageName() + ".SecondActivity");
                        intent.putExtras(bundle);
                        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP);
                        context.startActivity(intent);
```

**Comment by KenChoi1992** [comment]
@RealAmissio 还有什么关于跳转的问题可以加下我们的 Q 群：553406342

**Comment by Kerita** [comment]
jPUsh 社区一个官方回复里说，"跳转到指定界面现在统一在JS处处理"，所以可以不用写原生的 Activity 了吗？

帖子在这里：https://community.jiguang.cn/t/topic/18835

@KenChoi1992
