### ISSUE TITLE
run link 报错

### ISSUE THREAD

**Issue by WhynoChinese** [jpush/jpush-react-native#199]
CodePush.h" header already imported.
"jsCodeLocation" already pointing to "[CodePush bundleURL]".
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/mac/Code/Deadpool/ios/"$(SRCROOT)/deadpool/Info.plist"'

**Comment by KenChoi1992** [comment]
@WhynoChinese 你是不是用的第三方的插件，而不是我们的？

**Comment by WhynoChinese** [comment]
就是你们的啊，我之前的时候已经加入codepush了，然后runlink之后报错这个，我自己手动添加的库文件，倒是可以用了，但是希望你们解决下

**Comment by huangminlinux** [comment]
加一下  q 群 ：553406342 了解一下具体情况

**Comment by zhangmingnjun** [comment]
获取注册id的时候，得到的是个空串，麻烦帮助分析一下，是缺少了什么东西。

提供的demo倒是可以获取到注册id的

**Comment by huangminlinux** [comment]
@zhangmingnjun  iOS 还是 android ？问题和本 issue 无关，建议新建 issue
