### ISSUE TITLE
建议增加TypeScript的定义文件

### ISSUE THREAD

**Issue by Lxxyx** [jpush/jpush-react-native#200]
jpush-react-native很好用，希望可以增加 typescript definition file。
方便TypeScript开发者使用。

**Comment by KenChoi1992** [comment]
@Lxxyx 感谢提供建议，后续应该会加上的。

**Comment by oeddyo** [comment]
+1

**Comment by huhuanming** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jpush-react-native/index.d.ts

**Comment by Lxxyx** [comment]
Awesome.

**Comment by huhuanming** [comment]
yarn add @types/jpush-react-native
