### ISSUE TITLE
Android 安卓接收一個背景推播訊息後，不斷彈出相同訊息直至重新開啟 App

### ISSUE THREAD

**Issue by VansonLeung** [jpush/jpush-react-native#205]
Android 安卓接收一個背景推播訊息後，不斷彈出相同訊息，直至我重新開啟 App後才沒有繼續彈出
極光開發者服務中心顯示只發送了一條，故此我猜這是APP 的問題
請問有人遇到同樣問題嗎?
背後原因會是什麼？

**Comment by KenChoi1992** [comment]
@VansonLeung 升级一下版本。
