### ISSUE TITLE
about android badger

### ISSUE THREAD

**Issue by neo125874** [jpush/jpush-react-native#209]
Excuse me, i want ask about that is this library support the app badge display in Android?

Or i need to install the 3rd party lib to handle the badge display in Android?

thanks.

**Comment by KenChoi1992** [comment]
@neo125874 Badge display is not support in this library, you can use 3rd party library like [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger) or [ShortcutHelper](https://github.com/xuyisheng/ShortcutHelper)

**Comment by neo125874** [comment]
@KenChoi1992 thanks, so if i implement the badger, where could i deal the notification when press or when enter the app?

i know the onOpenNotification, how about directly enter the app? which event will be triggered?

**Comment by KenChoi1992** [comment]
@neo125874 Receive or click notification will trigger `onReceive` method in `JPushModule`, each has the corresponding event to handle. When you click notification, will open MainActivity by default, you can customize, too. Just need to modify click event.

**Comment by neo125874** [comment]
@KenChoi1992  how about just click the app icon, not by notification?  will it trigger any event?
Or jpush only deal the notification click event? thanks

**Comment by KenChoi1992** [comment]
@neo125874 Yeah, JPush only deal the events that related to notifications.

**Comment by neo125874** [comment]
@KenChoi1992 thanks for your information, i got it work by combine the react-native-shortcut-badger(something like that) and the jpush.

it works like a charm, btw would this lib plans to announce the react-native-badger feature inside?

**Comment by KenChoi1992** [comment]
@neo125874 Many mobile phone manufacturers have customized their system to support badge display, but Android official has not yet supported.

**Comment by KenChoi1992** [comment]
@neo125874 Closing now.
