### ISSUE TITLE
Multiple dex files define Lcn/jpush/a/a

### ISSUE THREAD

**Issue by younthu** [jpush/jpush-react-native#212]
环境:
react-native 4.4
"jcore-react-native": "^1.1.0",
"jpush-react-native": "^1.6.0",

编译的时候抛错：
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcn/jpush/a/a;
    UNEXPECTED TOP-LEVEL EXCEPTION:
....

**Comment by KenChoi1992** [comment]
@younthu 升级的时候，检查一下有没有替换掉之前的 jar。

**Comment by feisan** [comment]
通过 npm  安装或者升级之后，发现3.0.1版本的jar混杂在其中了，请维护者检查一下，谢谢！

`% find . -name "jpush-*.jar"`

`./node_modules/jpush-react-native/android/build/intermediates/bundles/release/libs/jpush-android_v3.0.1.jar
./node_modules/jpush-react-native/android/build/intermediates/jniLibs/release/jpush-android_v3.0.1.jar
./node_modules/jpush-react-native/android/libs/jpush-android_v3.0.5.jar`

**Comment by macoto-liu** [comment]
i solved this issue by replacing `"jpush-react-native": "^1.6.0"` with `"jpush-react-native": "1.6.0"`

**Comment by macoto-liu** [comment]
I solved this issue by replacing `"jpush-react-native": "^1.6.0",` with `"jpush-react-native": "1.6.0",`

**Comment by KenChoi1992** [comment]
@younthu @feisan 我升级了一下，没有出现这个问题啊。

**Comment by TrustTheBoy** [comment]
@younthu 请问你解决没

**Comment by zer0Black** [comment]
同样遇到此问题，仅android部分出问题，ios部分正常

**Comment by zer0Black** [comment]
将 jpush-react-native 切换到1.5.6版本解决此问题

**Comment by TrustTheBoy** [comment]
@zer0Black 删除./node_modules/jpush-react-native/android/build/intermediates/bundles/release/libs/jpush-android_v3.0.1.jar
可以解决此问题，(或3.0.5)

**Comment by younthu** [comment]
已解决

方法，找出所有的jpush-android* jar包，然后把build目录下的都清楚掉：
```
find . -name "jpush-android*"
rm -rf ./node_modules/jpush-react-native/android/build
```

**Comment by KenChoi1992** [comment]
@younthu build 文件夹是自动生成的，你升级后要 clean 一下项目。

**Comment by KenChoi1992** [comment]
那么这个问题就关闭了，原来是升级后和升级前 build 的 libs 冲突了，建议大家每次升级后都 clean 一下项目。

**Comment by kala888** [comment]
跟升级没关系吧，我把build和node_module  都删了还是有同样的问题

**Comment by twairball** [comment]
问题没解决, 你们 package manager 看一下 `.npmignore` 或之类的吧， 估计 `android/build/` 被包进去 npm 了。 

````
# jcore 1.1.3, jpush 1.6.6
$ npm install 
$ find . -name "jpush-*.jar" 
./node_modules/jpush-react-native/android/build/intermediates/bundles/release/libs/jpush-android_v3.0.1.jar
./node_modules/jpush-react-native/android/build/intermediates/jniLibs/release/jpush-android_v3.0.1.jar
./node_modules/jpush-react-native/android/libs/jpush-android_v3.0.6.jar
````

Workaround:
````
$ rm -rf node_modules/jpush-react-native/android/build/
$ react-native run-android
`````
