### ISSUE TITLE
can't locate file for: -ljcore-ios

### ISSUE THREAD

**Issue by basilbai** [jpush/jpush-react-native#213]
之前一直正常，升级xcode8.3.2之后用xcode运行调试就会报错，在vscode中用命令行react-native run-ios正常运行模拟器正常，请问这个问题怎么解决？谢谢！🙏🙏🙏
![qq20170506-101909](https://cloud.githubusercontent.com/assets/26473415/25769174/7cb3688e-3245-11e7-832a-e0d1901da09a.png)

**Comment by basilbai** [comment]
**重新npm i jcore-react-native --save后已解决问题**
**希望可以帮到其他朋友**
此问题可以关闭，谢谢！

**Comment by huhuanming** [comment]
Thx, friend!!
You save my time!!!
