### ISSUE TITLE
Failed to start example project

### ISSUE THREAD

**Issue by macoto-liu** [jpush/jpush-react-native#215]
I tried to run-android with example project.

However I got below errors 
Starting JS server...
ENOENT: no such file or directory, open 'app/src/main/AndroidManifest.xml'

If you look at the screenshot below, there is no such file - `app/src/main/AndroidManifest.xml`.
![image](https://cloud.githubusercontent.com/assets/10680110/25781191/04d2cc68-3369-11e7-95be-7dd754c439d9.png)

**Comment by macoto-liu** [comment]
jpush-react-native is "jpush-react-native": "^1.6.0",

**Comment by KenChoi1992** [comment]
@macoto-liu You should use Android Studio build this project the first time.

**Comment by macoto-liu** [comment]
Ok, thanks. I just tried to build through android studio it works.

I think we can build this example project without touching android studio that would be great.

**Comment by KenChoi1992** [comment]
@macoto-liu Because you haven't download some necessary libs or build tools, Android Studio helps you to do that, you can build any Android project the next time. :)
