### ISSUE TITLE
How can I make change without touching file node_modules/..../JPushModule.java

### ISSUE THREAD

**Issue by macoto-liu** [jpush/jpush-react-native#216]
How can I make cusotmized logic without touching file `node_modules/jpush-react-native/android/src/..../JPushModule.java` ?

I learnt from below I need to modify the customized logic in JPushModule. However, this is a bult-in class that references from `node_modules/jpush-react-native/android/src/..../JPushModule.java` which is part of node_modules. As the best practice, I think we shouldn't touch the code in node_modules directly, because the changes in node_modules will be ignored by git.

> 关于点击通知跳转到指定界面
> 
> demo 增加了 JPushModuleDemo 类（其中点击通知的地方做了一下跳转）， 可以在应用处于前台，后台或者为启动状态时，点击通知跳转到指定界面（SecondActivity）。 对应的 JS 文件为 second.js，详情可以参考这两个文件。

**Comment by macoto-liu** [comment]
Also the example project can't be run from my local. I have raised the issue in #215 .

**Comment by KenChoi1992** [comment]
@macoto-liu `JPushModuleDemo` is for reference, I know it will be ignored by git, but if you want to customize the logic that click notification jump to appointed widget, currently I suppose you should modify `JPushModule.java`. We may design a better way to do that.

**Comment by macoto-liu** [comment]
I just got a workaround for this.

1. Register the your/path/JPushPackage instead of node_modules/.../JPushPackage.java in MainApplication.java
2. Register your JPushReceiver in android/app/src/main/AndroidManifest.xml like below.

```
<receiver
        android:name="your.JPushModule$JPushReceiver"
        android:enabled="true">
        ...
      </receiver>
```
3. Turn off the built-in JPushReceiver in android/app/src/main/AndroidManifest.xml like below.

```
<receiver
        android:name="cn.jpush.reactnativejpush.JPushModule$JPushReceiver"
        android:enabled="false"
        tools:replace="android:enabled" />
```

**Comment by KenChoi1992** [comment]
@macoto-liu It depends on your strategy.

**Comment by KenChoi1992** [comment]
@macoto-liu Now release v1.6.6, you can receive openNotification event at any time, even your app has not start up, it means you can switch page in JS side, no need to modify native code any more. Try it.
