### ISSUE TITLE
这个报错是什么意思？

### ISSUE THREAD

**Issue by daffy6537** [jpush/jpush-react-native#222]
[myapp:jpush-react-native:unspecified] /Users/XXXXX/Desktop/my_project/myapp/android/app/build/intermediates/exploded-a
ar/myapp/jpush-react-native/unspecified/AndroidManifest.xml:32:5-78 Warning:
        Element uses-permission#android.permission.SYSTEM_ALERT_WINDOW at [myapp:jpush-react-native:unspecified] AndroidManif
est.xml:32:5-78 duplicated with element declared at [myapp:jpush-react-native:unspecified] AndroidManifest.xml:15:5-78
[myapp:jpush-react-native:unspecified] /Users/XXXXX/Desktop/my_project/myapp/android/app/build/intermediates/exploded-aar/myapp/
jpush-react-native/unspecified/AndroidManifest.xml:32:5-78 Warning:
        Element uses-permission#android.permission.SYSTEM_ALERT_WINDOW at [myapp:jpush-react-native:unspecified] AndroidManif
est.xml:32:5-78 duplicated with element declared at [myapp:jpush-react-native:unspecified] AndroidManifest.xml:15:5-78

**Comment by KenChoi1992** [comment]
@daffy6537 是这样，我们的 jpush-react-native 申请了 SYSTEM_ALERT_WINDOW 权限，你的 app 下就不用再申请了。

**Comment by KenChoi1992** [comment]
@daffy6537 没什么问题就关闭 issue 了。
