### ISSUE TITLE
xcode 控制台提示初始化JPUSH

### ISSUE THREAD

**Issue by Xing-He** [jpush/jpush-react-native#224]
![image](https://cloud.githubusercontent.com/assets/11990205/26023556/231f1fd2-37f1-11e7-8d2b-5b39f1de78e2.png)

- rn : 0.41.2
- jpush : 3.0.5
- jcore : 1.1.3

已查看配置，打开了push notifications 也初始化了

**Comment by huangminlinux** [comment]
是通过自动安装脚本安装的吗? 

检查一下 Appdelegate.m 这个文件重要有没有添加如下的代码 [自动配置部分]（https://github.com/jpush/jpush-react-native/blob/master/example/documents/iOS_Usage.md）
