### ISSUE TITLE
addReceiveOpenNotificationListener 方法 不调用

### ISSUE THREAD

**Issue by allyju** [jpush/jpush-react-native#226]
Android app进程杀死。收到通知后，点击通知能打开app ，但addReceiveOpenNotificationListener 这个方法不调用

**Comment by KenChoi1992** [comment]
@allyju 测试在退出后，如果系统设置了应用保护，那么是可以调用的。

**Comment by allyju** [comment]
@KenChoi1992 有点不理解你的意思，我现在的情况是应用在前台与在后台都能调用addReceiveOpenN.……的这个方法。但是杀死进程以后，就只会打开应用。 addReceiveOpenN……这个方法就不走了

**Comment by allyju** [comment]
有点不理解你的意思，我现在的情况是应用在前台与在后台都能调用addReceiveOpenNotificationListener的这个方法。但是杀死进程以后，就只会打开应用。 addReceiveOpenNotificationListener这个方法就不走了

**Comment by KenChoi1992** [comment]
@allyju 因为杀死进程后，要重新初始化 RN，所以在启动后如果没有执行
```

    @Override
    public void initialize() {
        super.initialize();
        mLatch = new CountDownLatch(1);
        mLatch.countDown();
        mRAC = getReactApplicationContext();
    }
```
那么可能这个事件就丢了。

**Comment by allyju** [comment]
@KenChoi1992  我看了下JPushModule里面的这个initialize()   这里只是重写了，没有调用执行的地方。怎么在启动后再一次执行呢？还是说，这个事件丢了有什么解决办法？？

**Comment by KenChoi1992** [comment]
@allyju 这是 RN 初始化完成后就会调用的方法。

**Comment by allyju** [comment]
@KenChoi1992 那么，这个事件丢了有什么解决办法？？

**Comment by KenChoi1992** [comment]
@allyju 目前的解决方案只能是保留这个事件，在初始化后完成后再调用这个，这样可以吗？

**Comment by allyju** [comment]
。。保留这个事件，就是代表 ，现在这个方法 ，还是不能调用。对么？？

**Comment by allyju** [comment]
@KenChoi1992 在初始化完成——这个应用的页面已经加载完成了，就属于初始化完成吧？ 。。保留这个事件，就是代表 ，现在这个方法 ，还是不能调用。对么？？

**Comment by KenChoi1992** [comment]
@allyju 并非如此，界面虽然启动了，但是 RN 可能还没初始化完成啊。没初始化的话，就肯定不能调用 JS 的方法，明白吗

**Comment by allyju** [comment]
@KenChoi1992 嗯，对这个事件做了保留 。但，这个等一会有很多的不确定因素。可能等很久也不会执行这个事件里面的内容。

**Comment by KenChoi1992** [comment]
@allyju 那就有点为难了，毕竟我也不知道要多久 RN 才能初始化完成。

**Comment by KenChoi1992** [comment]
@allyju 现在的方案是让你们在 JS 中主动调用一个方法，然后我就知道 JS 已经准备好了，然后下发事件。下个版本更新。

**Comment by allyju** [comment]
@KenChoi1992  嗯 。什么时候可能版本更新呢？等着呢。

**Comment by KenChoi1992** [comment]
@allyju 今天下午

**Comment by KenChoi1992** [comment]
@allyju 现在更新了，试试看。

**Comment by luojinghui** [comment]
@KenChoi1992 
> @allyju 现在的方案是让你们在 JS 中主动调用一个方法，然后我就知道 JS 已经准备好了，然后下发事件。下个版本更新。

我想在js完成加载页面时告诉原生端加载完毕了，在添加监听事件。我看你们讨论也提到了这一点，请问在更新的版本中，加入了哪一个`js中主动调用的方法`，我需要用到它，求告知。谢谢

**Comment by wanxsb** [comment]
+1，是啊，没有给出具体的答案就关闭了

**Comment by luojinghui** [comment]
@wanxsb ios是有对应的通知事件的，你在源代码里面找找。android我当时是这么处理的：先在启动的时候缓存push的消息，然后在首页加载完毕后发送了一个通知，告诉监听者加载完毕js了，然后执行push消息的显示，你可以试一下

**Comment by MoShenGuo** [comment]
ios有哪些对应通知时间呢
