### ISSUE TITLE
DexException: Multiple dex files define Lcn/jpush/a/a in react-native for android

### ISSUE THREAD

**Issue by Davidyoyo** [jpush/jpush-react-native#228]
我在react-native for android中都是按照教程配置的jpush，为什么在编译的时候一直出现以下错误呢？
* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.pro
cess.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.
DexException: Multiple dex files define Lcn/jpush/a/a;

能否帮忙看下是什么原因呢？

**Comment by KenChoi1992** [comment]
@Davidyoyo https://github.com/jpush/jpush-react-native/issues/212 你的问题和之前的是一样的，提问前可以搜索一下。
