### ISSUE TITLE
应用进入后台后，收到通知点击无法切换到前台的原因

### ISSUE THREAD

**Issue by HouseShine** [jpush/jpush-react-native#23]
1、应用进入后台后，收到通知点击无法切换到前台的可能原因
2、杀死应用进程后，无法再收到通知的可能原因

**Comment by KenChoi1992** [comment]
@HouseShine  第一点如果不能打开应用的话，试着用之前版本的代码，可以看[这个issue](https://github.com/jpush/jpush-react-plugin/issues/22) ，第二点要在你手机上装了其他集成了 JPush SDK 的应用，这样就可以拉起。

**Comment by HouseShine** [comment]
@KenChoi1992 android在未杀死进程状态下每点击一次通知发现又开启一次该应用，不是应用的重启，而是原来应用还在，新开启的应用覆盖在原来应用上面

**Comment by KenChoi1992** [comment]
@HouseShine 没有出现你说的覆盖在原来应用上面的情况啊，还是只有一个应用。你的测试环境是什么？

**Comment by HouseShine** [comment]
环境：
react-native 版本：0.30.0
jpush-react-native 版本：1.1.3
android 版本：三星Galaxy Note 2 (SCH-N719)

**Comment by KenChoi1992** [comment]
@HouseShine 我的是：
react native: 0.30.0
jpush-react-native: 1.1.3
android: 乐视 LeX620
没出现你说的情况，你换一下手机试试

**Comment by HouseShine** [comment]
我调试了一下  发现JPushModule中的mModule.mContext一直为空 这个一般什么情况下才为空

**Comment by HouseShine** [comment]
@KenChoi1992 使用getCurrentActivity一直获取不了值，可能的原因是什么

**Comment by KenChoi1992** [comment]
@HouseShine 可能原因是在后台运行的时候，无法获得当前的 context，目前没有找到解决方案。

**Comment by xiDaiDai** [comment]
@HouseShine 实现LifecycleEventListener    onHostResume()里getCurrentActivity [issues](https://github.com/facebook/react-native/commit/49f20f41546e3ba8e7fe43c84c4c701684d0434d)
