### ISSUE TITLE
[IOS] 怎么进行页面统计

### ISSUE THREAD

**Issue by MiRinZhang** [jpush/jpush-react-native#231]
`React-native`中怎么使用**页面统计**啊，我看文档里面说是可以使用`JAnalytics`，但是示例里面是`OC`的代码，不知道在`RN`里面有没有相关的统计方法。

**Comment by huangminlinux** [comment]
RN 的统计方法还没有加上

**Comment by MiRinZhang** [comment]
@huangminlinux 好的，谢谢。
