### ISSUE TITLE
android 集成报错

### ISSUE THREAD

**Issue by zzzeee** [jpush/jpush-react-native#234]
自动运行脚本失败，手动配置后，运行 react-native run-android后报错，怎么破？

![qho6mvg4n9 n v5_xelm4 k](https://cloud.githubusercontent.com/assets/26219025/26239612/4f973220-3cb0-11e7-8754-d37efaedbd6d.png)

MainActivity.java 文件内容如下：
package com.******;
import com.facebook.react.ReactActivity;
public class MainActivity extends ReactActivity {
    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "jingtao";
    }
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        JPushInterface.init(this);
    }
    @Override
    protected void onPause() {
        super.onPause();
        JPushInterface.onPause(this);
    }
    @Override
    protected void onResume() {
        super.onResume();
        JPushInterface.onResume(this);
    }
}

删除MainActivity.java后添加的内容后： 
![image](https://cloud.githubusercontent.com/assets/26219025/26239990/fed8270c-3cb1-11e7-8d9e-2f8b30b86fc2.png)

**Comment by KenChoi1992** [comment]
@zzzeee 首先用 Android Studio 打开项目，clean 一下，然后编译一下项目，引入必要的类即可。MainActivity 是要的，其次，看下我们的文档，JPushPackage 是有参数的。

**Comment by KenChoi1992** [comment]
@zzzeee 没什么问题就关闭了。
