### ISSUE TITLE
点击通知后进入应用 OpenNotification方法不执行

### ISSUE THREAD

**Issue by BumpMonster** [jpush/jpush-react-native#236]
能收到通知，我用的是tags，收到通知也执行ReceiveNotification回调，但是app在后台点击通知进入app的时候，还是只执行ReceiveNotification方法，不执行OpenNotification回调方法，这是我的代码
componentDidMount() {
        if (Platform.OS === 'ios'){
            this.subscription = NativeAppEventEmitter.addListener(
                'ReceiveNotification',
                (notification) => console.log(`--ios-receive--notification---` + notification)
            );

            this.openSubscription = NativeAppEventEmitter.addListener(
                'OpenNotification',
                (notification) => console.log(`-ios--open--notification---` + notification)
            );
            // JPushModule.setBadge(5, (success) => {
            //     console.log(success)
            // });
        }else {
            JPushModule.addReceiveNotificationListener((map) => {
                console.log(`-android--receive--notification---` + map)
            });
            JPushModule.addReceiveOpenNotificationListener((map) => {
                console.log(`--android-open--notification---` + map)
            });
        }
}

**Comment by huangminlinux** [comment]
是 iOS 几的系统？

**Comment by BumpMonster** [comment]
对了，忘了 ，只支持10以后的，那怎么办，10之前的版本点击通知处理不了了吗？

**Comment by BumpMonster** [comment]
知道了 ，谢谢
