### ISSUE TITLE
JPushModule.addReceiveCustomMsgListener can not receive anything

### ISSUE THREAD

**Issue by neilzhengzx** [jpush/jpush-react-native#237]
today，when i updata the server in jpush。JPushModule.addReceiveCustomMsgListener dont work.
"jcore-react-native": "1.1.0","jpush-react-native": "1.6.0",  is ok.

**Comment by KenChoi1992** [comment]
@neilzhengzx don't forget to call `notifyJSDidLoad`, see releases for more detail.

**Comment by neilzhengzx** [comment]
添加了notifyJSDidLoad解决了我的问题,谢谢。 @KenChoi1992
