### ISSUE TITLE
在IOS Home 界面能收到消息，但是监听事件失效

### ISSUE THREAD

**Issue by dongodngtang** [jpush/jpush-react-native#238]
在IOS Home 界面能收到消息，但是监听事件失效。那样我就无法处理业务，请问怎样才能做到在Home界面，App内部一样可以处理业务

**Comment by huangminlinux** [comment]
1. 什么消息？ 应用内消息 还是 推送
2. 监听什么事件？ Receivenotification 还是 openNotification？
3. 所说的 Home 界面是否只的是 应用不在前台运行？

**Comment by dongodngtang** [comment]
1、是推送消息
2、Receivenotification、openNotification、networkDidReceiveMessage都设置了监听
3、Home界面，应用不在前台

补充：应用在前台，Receivenotification能接受到推送消息

**Comment by huangminlinux** [comment]
有人提了和你一样的 issue ，可以参考这个 #220

**Comment by dongodngtang** [comment]
我的情况和他的一样，我的是0.43.4RN，我改了.m文件重的方法。还是没好，可以看看你的demo吗

**Comment by dongodngtang** [comment]
谢谢OK了
