### ISSUE TITLE
jpushModule.notifyJSDidLoad is not a function

### ISSUE THREAD

**Issue by RealAmissio** [jpush/jpush-react-native#241]
我在componentdidmount中 addlistener之前执行了 jpushModule.notifyJSDidLoad(),
进去之后一直报jpushModule.notifyJSDidLoad is not a function的黄色警告，
并且双端点击都无法跳转到对应的页面，
刚刚升级的1.6.6，但是我在componentdidmount之前加了async 不知道是否有关？

**Comment by RealAmissio** [comment]
加到主页面的话就知道报错了，提示不是一个方法，jpushModule.notifyJSDidLoad()这样写不对吗？

**Comment by KenChoi1992** [comment]
@RealAmissio JPushModule 有没有正确引入？ReactPackager 有没有重启？我测试没问题呀。

**Comment by KenChoi1992** [comment]
@RealAmissio 没有回复就关闭问题了。

**Comment by huanxsd** [comment]
我这边也是报这个错误，package已经是最新版本"jpush-react-native": "^1.6.6",
但是index.js里面没有找到这个方法：
// Type definitions for jpush-react-native 1.6

省略若干代码

    /**
     * Android
     */
    static resumePush(): void;

    /**
     * Android
     */
    static clearAllNotifications(): void;

**Comment by riugduso** [comment]
notifyJSDidLoad is only for android platform @huanxsd @RealAmissio

**Comment by cj768025549** [comment]
这是安卓的方法，使用前注意判断平台，iOS调用会报错
