### ISSUE TITLE
请问app杀死后，点击通知，不能调到指定的页面

### ISSUE THREAD

**Issue by BumpMonster** [jpush/jpush-react-native#242]
请问app杀死后，点击外面的通知，不管是iOS10之前调用
this.subscription = NativeAppEventEmitter.addListener(
                    'ReceiveNotification',
                    (notification) => {})
还是10以后调用
this.openSubscription = NativeAppEventEmitter.addListener(
                'OpenNotification',
                (notification) => {})
都不能调到指定的页面，只能打开app，notifyJSDidLoad方法是针对安卓的，那iOS呢，请问怎么解决呢

**Comment by huangminlinux** [comment]
1. 升级 jpush-react-native 到最新版本（旧版本还没做缓存处理，新版本已修复）
2. 检查监听 OpenNotification 的操作是否异步调用，有用户应为在异步回调中才执行监听操作，导致事件已经上抛到 js 层但 js 层还没执行监听操作的问题， 另外尽可能把 NativeAppEventEmitter.addListener 的代码 放到程序启动的地方

**Comment by atlas1119** [comment]
我是1.6.6的版本，是最新的版本， 也是一样的情况，需要打开app后，才能监听到，， 什么情况？

**Comment by huangminlinux** [comment]
@atlas1119 iOS 9 ？

**Comment by atlas1119** [comment]
ios10

**Comment by atlas1119** [comment]
@huangminlinux

**Comment by huangminlinux** [comment]
@atlas1119  建议把监听代码往前移动，监听事件代码  放到 index.ios.js  看看能否监听到

**Comment by atlas1119** [comment]
已经放到最开始的地方，还是没有弹窗出来
![image](https://user-images.githubusercontent.com/9478646/27719637-5cd73380-5d86-11e7-8da6-e97933ccee8e.png)

**Comment by atlas1119** [comment]
@huangminlinux

**Comment by huangminlinux** [comment]
这边测试是没有问题的  @atlas1119  ，不太清楚那边环境， 如果可以弄个demo 项目上传到你的github ，我拉下了看看什么问题

**Comment by atlas1119** [comment]
android app退出后， 收不到通知了。。。为啥？ app 后台运行 是可以的
