### ISSUE TITLE
android java.lang.unsupporteoperationException

### ISSUE THREAD

**Issue by PatWu16** [jpush/jpush-react-native#243]
![image](https://cloud.githubusercontent.com/assets/23301139/26496191/16ff16fe-4259-11e7-9633-777623b7953d.png)
照着安装流程下来，然后就报错了，请问是什么原因？

**Comment by KenChoi1992** [comment]
@PatWu16 用 Android Studio 打开你的项目，编译下看报什么错误。

**Comment by PatWu16** [comment]
![qq 20170603164744](https://cloud.githubusercontent.com/assets/23301139/26752160/48ccbde8-487c-11e7-9630-bbb27bad363a.png)
android studio也是同样的报错，并没有更多信息，百度搜到是java错误，请问有谁遇到这样的情况？

**Comment by PatWu16** [comment]
@KenChoi1992 求救

**Comment by KenChoi1992** [comment]
@PatWu16 你同时用了 JMessage 吗？如果只用了 jpush-react-native 那么 clean 一下工程就行了。

**Comment by PatWu16** [comment]
@KenChoi1992 没有使用过，clean尝试过，重建初始项目只安装该模块运行报的是同样的错误，很纳闷，网上也没找到解决方案

**Comment by zhangmingnjun** [comment]
我也遇到了这个错，我是同时使用了jmessage。有时候清理完项目就不报这个错了

**Comment by KenChoi1992** [comment]
@PatWu16 删掉 jpush-react-native 下的 build 文件夹，然后重新编译运行。

**Comment by KenChoi1992** [comment]
新版本去掉了 build 文件夹，应该没有这个问题了。
