### ISSUE TITLE
集成的安卓SDK是否有常驻后台机制

### ISSUE THREAD

**Issue by CDog34** [jpush/jpush-react-native#245]
测试中发现使用这个库的安卓app只要关闭app（在多任务菜单中划出，并非应用设置页的强制结束进程）就收不到推送。

请问这个库中集成的安卓SDK是否有官方SDK的常驻后台以及互相唤醒机制？

如果有，如何开启？
如果没有，如何保证安卓推送送达率？

**Comment by KenChoi1992** [comment]
@CDog34 有的，只要设置了允许自启动，就可以相互拉起。

**Comment by CDog34** [comment]
好的
