### ISSUE TITLE
android在key错误的情况下，能否不在页面上提示

### ISSUE THREAD

**Issue by neilzhengzx** [jpush/jpush-react-native#246]
问题同标题

**Comment by KenChoi1992** [comment]
@neilzhengzx 你的意思是不弹出 toast？在加入 JPushPackage 时设置参数就能关掉了，可以看下文档。

**Comment by neilzhengzx** [comment]
不是 toast，是android在key与包名不匹配时，刚打开应用时有消息通知，提示包名与key不匹配

**Comment by KenChoi1992** [comment]
@neilzhengzx 这是 SDK 弹出的
