### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by xwartz** [jpush/jpush-react-native#248]
fabric 捕获的错误，根据错误信息，似乎和 jpush 有关，我对 Java 代码不熟悉，能否帮忙看下呢，谢谢了。

![image](https://cloud.githubusercontent.com/assets/4149827/26760459/e886b054-494a-11e7-8b00-517a36157232.png)

### 版本信息

jpush-react-native： 1.3.5
react-native: 0.37.0

**Comment by KenChoi1992** [comment]
@xwartz 升级一下 RN 版本 和 jpus-react-native 的版本。

**Comment by xwartz** [comment]
这个报错的原因，能说一下吗？ 目前还升级不了 RN 版本...

**Comment by KenChoi1992** [comment]
@xwartz 旧的 RN 版本是没有这个 `SoLoader.init()` 这个方法的。

**Comment by xwartz** [comment]
@KenChoi1992   谢谢
