### ISSUE TITLE
Android getCurrentActivity() return activity instance is null 

### ISSUE THREAD

**Issue by Mercury-Dai** [jpush/jpush-react-native#252]
Hey , 'mContext = getCurrentActivity() ' code from getRegistrationID mothed of JPushModule. The mContext is null, getRegistrationID mothed judge context is null or not,if null throw IllegalArgumentException,then my app crash.

**Comment by Mercury-Dai** [comment]
if not throw exception ,my app will be good.

**Comment by KenChoi1992** [comment]
@Mercury-Dai You can upgrade version, we did catch this exception in new version.

**Comment by Mercury-Dai** [comment]
thx，i have upgraded to newest version and fixed it
