### ISSUE TITLE
npm上的android下面jpush-react-native-release.aar有问题导致gradle编译报重复的类

### ISSUE THREAD

**Issue by beansoftapp** [jpush/jpush-react-native#254]
jpush-react-native/android/build/outputs/aar/jpush-react-native-release.aar!/libs
其中竟然包含了两个不同版本的jpush jar, 导致Gradle编译时报错. dex发现重复类.

手工解决是打开AAR文件删除其中的一个jpush jar, 希望能改下npm上这个的问题.

**Comment by KenChoi1992** [comment]
@beansoftapp 把 build 文件夹删掉就行了。下个版本 npm 上会删掉这个文件夹。

**Comment by KenChoi1992** [comment]
@beansoftapp 新版本删掉了这个文件夹。
