### ISSUE TITLE
setAlias调用无效

### ISSUE THREAD

**Issue by wanghche** [jpush/jpush-react-native#256]
JPush.setAlias()方法调用后successCallback, failedCallback两个均未执行，alias也没有设置成功。不知道是什么原因？
Android，IOS都不行

**Comment by cq920702** [comment]
我也遇到了跟你一样的问题，不过iOS可以，安卓有问题，请问你解决了吗？

**Comment by wanghche** [comment]
@cq920702 还没有解决

**Comment by KenChoi1992** [comment]
有没有打印什么返回码？返回信息？

**Comment by zhangyanlf** [comment]
@wanghche 我调用也设置不了，你的解决了没？

**Comment by KenChoi1992** [comment]
@wanghche @zhangyanlf 这个问题没有跟进的话就关闭了。
