### ISSUE TITLE
关于addReceiveOpenNotificationListener的问题

### ISSUE THREAD

**Issue by xialei92** [jpush/jpush-react-native#258]
现在按返回键退出APP，这个时候点击收到的一条推送，打开APP，这个时候只有 退出前的APP的addReceiveOpenNotificationListener可以收到回调，新打开的APP收不到addReceiveOpenNotificationListener的回调，请问这个该怎么处理

**Comment by KenChoi1992** [comment]
@xialei92 在 `addReceiveOpenNotificationListener ` 执行之前调用 `notifyJSDidLoad`

**Comment by xialei92** [comment]
@KenChoi1992 notifyJSDidLoad调用了的，现在的问题是：当程序在后台时，点击通知，走的是后台的addReceiveOpenNotificationListener回调，然后紧接着又打开了一个新的程序，等于看到的新的程序什么也没做

**Comment by KenChoi1992** [comment]
@xialei92 不太明白你的意思

**Comment by xialei92** [comment]
@KenChoi1992 这么说吧，我要在addReceiveOpenNotificationListener里面跳转页面，这个现在能做吗

**Comment by atlas1119** [comment]
IOS 也是这样的情况，我是在构造函数里面监听这个。。。请问问什么？
![image](https://user-images.githubusercontent.com/9478646/27684604-4dae0e4e-5cfd-11e7-99b4-306344aa7aba.png)

**Comment by KenChoi1992** [comment]
@xialei92 看下新版本 https://github.com/jpush/jpush-react-native/releases/tag/1.6.7 测试杀死 app 后也能跳转到指定界面。
