### ISSUE TITLE
addReceiveOpenNotificationListener

### ISSUE THREAD

**Issue by gosherry** [jpush/jpush-react-native#260]
现在按返回键退出APP，这个时候点击收到的一条推送，打开APP，这个时候APP会自动重新启动到MainActivity, 并执行在addReceiveOpenNotificationListener写的跳转操作，执行这个操作就会报错，因为当程序还没初始化完成的时候addReceiveOpenNotificationListener方法已经执行了，里面的this.props.router.push根本就获取不到值。addReceiveOpenNotificationListener这个方法是只要点击通知栏，就会调用吗，有办法让让程序启动完成之后再调用吗

**Comment by KenChoi1992** [comment]
@gosherry 调了 `notifyJSDidLoad` 这个方法没有？

**Comment by gosherry** [comment]
在构造函数里调用过了 @KenChoi1992

**Comment by gosherry** [comment]
"jcore-react-native": "^1.1.3",
    "jpush-react-native": "^1.6.6",
@KenChoi1992

**Comment by KenChoi1992** [comment]
@gosherry 你需要在 addReceiveOpenNotificationListener 调用前再调用一次，构造函数中调用的话，可能有问题。
```
componentDidMount() {
		JPushModule.notifyJSDidLoad();
		JPushModule.addReceiveCustomMsgListener((map) => {
			this.setState({
				pushMsg: map.message
			});
			console.log("extras: " + map.extras);
		});
		JPushModule.addReceiveNotificationListener((map) => {
			console.log("alertContent: " + map.alertContent);
			console.log("extras: " + map.extras);
			// var extra = JSON.parse(map.extras);
			// console.log(extra.key + ": " + extra.value);
		});
		JPushModule.addReceiveOpenNotificationListener((map) => {
			console.log("Opening notification!");
			console.log("map.extra: " + map.key);
		});
		JPushModule.addGetRegistrationIdListener((registrationId) => {
			console.log("Device register succeed, registrationId " + registrationId);
		});
	}
```

**Comment by gosherry** [comment]
componentDidMount() {
	  JPushModule.notifyJSDidLoad();		
		if (Platform.OS === 'ios') {
			console.log("  ios 通知 ----- ");
			this.notifySubscription = NativeAppEventEmitter.addListener('ReceiveNotification',(notification) => {
			  	console.log('收到 iOS 通知: ',notification)
			  }
			);
			// 监听 OpenNotification 事件，点击推送的时候会执行这个回调
			this.openNotifySubscription = NativeAppEventEmitter.addListener('OpenNotification',(notification) => {
		  	console.log('iOS 10 -- 点击 通知 ----',notification)
		  	console.log("----通知打开app ",this.props.router);
		  	const currentRoute = this.props.router.getCurrentRoute();
		  	if (currentRoute.key === 'MESSAGE_DETAIL_PAGE') return this.props.router.pop();
		  	if (currentRoute.key !== 'MESSAGE_PAGE') this.props.router.push(RouteType.ROUTE_MESSAGE_LIST);
			  }
			);
			// 监听 networkDidReceiveMessage 事件，接受自定义消息
			this.messageSubscription = NativeAppEventEmitter.addListener('networkDidReceiveMessage',(message) => {
					console.log('收到 iOS 自定义消息: ',message)
					this.props.router.push(RouteType.ROUTE_MESSAGE_DETAIL,{id: 12123123,type: 0})
				}
			);
		} else {
			JPushModule.addReceiveCustomMsgListener((message) => {
		    // this.setState({pushMsg: message});
		    console.log("收到 android 自定义消息 ",message);
		  });
		  JPushModule.addReceiveNotificationListener((message) => {
		    console.log("收到 Android 通知: ",message);
		  })
		  // 点击通知后，将会触发此事件
		  JPushModule.addReceiveOpenNotificationListener((message) => {
		    console.log("Android 点击通知 触发", message);
		    // this.props.dispatch(openNotification(true));
		  	const currentRoute = this.props.router.getCurrentRoute();
		  	if (currentRoute.key === 'MESSAGE_PAGE' || currentRoute.key === 'MESSAGE_DETAIL_PAGE') this.props.dispatch(updateMsgList());		  	
		  	if (currentRoute.key === 'MESSAGE_DETAIL_PAGE') return this.props.router.pop();
		  	if (currentRoute.key !== 'MESSAGE_PAGE') this.props.router.push(RouteType.ROUTE_MESSAGE_LIST);
		  });
		}
		JPushModule.getRegistrationID((data) => {
			console.log('----getRegistrationID ',data);
		});
		AppState.addEventListener('change', this._handleAppStateChange);
	}
@KenChoi1992 ExceptionsManager.js:71 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Navigator component 还是不能自动跳转，只能启动APP

**Comment by KenChoi1992** [comment]
@gosherry 现在有个建议就是在 JS 收到 openNotification 事件时，在 React 界面中启动原生界面，原生界面还是用 JS 来写。

**Comment by KenChoi1992** [comment]
https://github.com/jpush/jpush-react-native/releases/tag/1.6.7 看下新版本，测试解决这个问题了。
