### ISSUE TITLE
Android 关闭 crash log report

### ISSUE THREAD

**Issue by messense** [jpush/jpush-react-native#261]
iOS 默认是关闭的，Android 似乎是默认打开了，希望默认值一致（关闭），提供打开 API

**Comment by KenChoi1992** [comment]
@messense 并没有默认打开，需要在添加 JPushPackage 时自己设置。文档有写啊

**Comment by messense** [comment]
并没有设置后台也看到 Android 错误报告了。

**Comment by KenChoi1992** [comment]
`JPushPackage` 参数如果设置为 true，则不会打印调试 Log 和弹出 toast。

**Comment by messense** [comment]
并不是 Log 和 Toast，而是后台统计里面的「错误分析」

![image](https://user-images.githubusercontent.com/1556054/28004135-0783e0d0-6575-11e7-9a65-7215bd6ca1e5.png)

**Comment by messense** [comment]
并不需要用 JPush 来收集错误报告，希望能关闭。

**Comment by KenChoi1992** [comment]
@messense 下个版本会提供这两个接口，参考文档 https://docs.jiguang.cn/jpush/client/Android/android_api/#crashlog

**Comment by KenChoi1992** [comment]
已更新
