### ISSUE TITLE
error：cb is not function

### ISSUE THREAD

**Issue by hlwfx** [jpush/jpush-react-native#262]
I need help when run react-native android
	/**
	 * iOS,  Android	
	 */
	static getRegistrationID(cb) {
		JPushModule.getRegistrationID((id) => {
			cb(id);
		});
	}
in jpush-react-native\index.js:222:3,Thanks!

**Comment by KenChoi1992** [comment]
```
onGetRegistrationIdPress() {
		JPushModule.getRegistrationID((registrationId) => {
			this.setState({
				registrationId: registrationId
			});
		});
	}
```

**Comment by KenChoi1992** [comment]
#hlwfx Since you didn't reply these days, closing now.

**Comment by hlwfx** [comment]
Thanks very much！It‘s solved

**Comment by vitozyf** [comment]
> Thanks very much！It‘s solved

How to solve this problem?
