### ISSUE TITLE
Android不要弹出Toast调试信息

### ISSUE THREAD

**Issue by beansoftapp** [jpush/jpush-react-native#265]
public class JPushModule extends ReactContextBaseJavaModule {

    @ReactMethod
    public void initPush() {
        mContext = getCurrentActivity();
        JPushInterface.init(getReactApplicationContext());
        Logger.toast(mContext, "Init push success");
        Logger.i(TAG, "init Success!");
    }

正式版也弹...

**Comment by KenChoi1992** [comment]
@beansoftapp  #263  这个跟你一样，`JPushPackage` 有参数的。

**Comment by beansoftapp** [comment]
抱歉, 首次用RN接入...多多包涵. 关闭.
