### ISSUE TITLE
在点击通知时，监听函数内不能收到推送的附加参数extras

### ISSUE THREAD

**Issue by hlwfx** [jpush/jpush-react-native#267]
JPushModule.addReceiveOpenNotificationListener((map) => {
			console.log("Opening notification!");
			console.log(map);
            this.savePush(map)；
		});

在JPushModule中打印extras也为空。
在自定义消息的监听器中能收到
 JPushModule.addReceiveCustomMsgListener((map) => {
            console.log("receive CustomMsg: ");
            console.log(map);
            console.log("extras: " + map.extras);
        });
但因为在点击时需要完成一些操作，所以希望能在点击通知时也能收到extras，望大神求解。

**Comment by KenChoi1992** [comment]
@hlwfx 在 JPushModule 中已经把 extras 拿出来了，而且也传到了 JS，我测试是可以拿到的：
![image](https://user-images.githubusercontent.com/8196928/28098308-232e247a-66e8-11e7-9b8c-fa5aa4a1150a.png)

**Comment by hlwfx** [comment]
我在JPushModule中的RECEIVE_CUSTOM_MESSAGE使用
map.putString("extras", mCachedBundle.getString(JPushInterface.EXTRA_EXTRA));能取到extras
但是在OPEN_NOTIFICATION中使用
mCachedBundle.getString(JPushInterface.EXTRA_EXTRA)取不到extras，
是因为权限设置有问题吗？

**Comment by KenChoi1992** [comment]
@hlwfx 我可以取到，不知道你为啥不能。不是权限的问题。你确定你设置了 extra ？

**Comment by KenChoi1992** [comment]
@hlwfx 这个问题没有回复就先关闭了

**Comment by RoarRain** [comment]
解决了吗？
