### ISSUE TITLE
升级jpush-react-native 版本，IOS和Android需要重新配置吗？

### ISSUE THREAD

**Issue by huangxubo23** [jpush/jpush-react-native#271]
之前使用的是1.6.7，如果升级到目前最新的1.7.1，之前IOS和Android手动配置部分需要重新配置吗？

**Comment by huangminlinux** [comment]
升级指南可以参考 Release 中的改动说明
https://github.com/jpush/jpush-react-native/releases

**Comment by KenChoi1992** [comment]
@huangxubo23 Android 这边升级后不用重新配置

**Comment by KenChoi1992** [comment]
@huangxubo23 没问题就关闭了
