### ISSUE TITLE
在安卓和iOS  为什么分别是 receiveNotification 和ReceiveNotification  事件

### ISSUE THREAD

**Issue by niuniubuniu** [jpush/jpush-react-native#275]
而且 iOS 的事件 接口没有在index 文件 添加；
RECEIVE_CUSTOM_MESSAGE（receivePushMsg） 这个是安卓中独有的自定义消息事件么 ？

**Comment by KenChoi1992** [comment]
@niuniubuniu Android 明明是 addReceiveNotificationListener

**Comment by huangminlinux** [comment]
开始做的时候这个地方没有做好统一， 下个版本统一一下

**Comment by niuniubuniu** [comment]
@KenChoi1992 你说的是方法名 我说的是 定义的事件  
@huangminlinux 感谢你们的回答   
那我就暂时自己修改下 用了

**Comment by KenChoi1992** [comment]
@niuniubuniu 现在统一了。
