### ISSUE TITLE
jpush-react-native添加到已有原生应用后编译报错，找不到React/RCTDefines.h

### ISSUE THREAD

**Issue by miss-yadi** [jpush/jpush-react-native#276]
不是使用react-native init方式创建的项目，原生应用和RN代码分开，不能使用rnpm link添加关联。
手动将RCTJPushModule项目拖入到原生应用中，配置header search path，添加libRCTJPushModule.a文件及相关framework后编译报错，错误信息为：fatal error: 'React/RCTDefines.h' file not found 

添加方式是否正确？或者是否可以使用cocoapods的方式或者其他方式添加？

**Comment by huangminlinux** [comment]
可以通过手动集成的方式集成， 
- 把工程内的 [文件](https://github.com/jpush/jpush-react-native/tree/master/ios/RCTJPushModule/RCTJPushModule) 导入到工程中。
- 下载 jcore 库文件导入自己的工程，[链接](https://sdkfiledl.jiguang.cn/cocoapods/jcore/JCore-iOS-1.1.5.2.zip)
- 然后手动配置一下代码 [参考](https://github.com/jpush/jpush-react-native/blob/master/example/documents/iOS_Usage.md)

**Comment by miss-yadi** [comment]
@huangminlinux 编译成功，十分感谢！

**Comment by miss-yadi** [comment]
![default](https://user-images.githubusercontent.com/10703305/28403161-0b3a113e-6d56-11e7-84d3-bdd9078028c9.png)
拖入项目中的效果，给大家做参考~
