### ISSUE TITLE
版本1.1.3，发布后ios无法获取registrationId

### ISSUE THREAD

**Issue by wjm117** [jpush/jpush-react-native#280]
这个是之前的项目，以前两个平台推送都正常，现在推送android是正常的，ios查了发现没有获取到registrationId，无法收到推送消息。但是本地调试的时候能正常获取到registrationId，发布以后的registrationId就是空的。这个可能是因为版本太低了吗？

**Comment by huangminlinux** [comment]
使用新版本测试没有出现这个问题，建议升级到最新版本

**Comment by wjm117** [comment]
好的
