### ISSUE TITLE
app IOS上角标怎么自增， 无论接受多少条都显示1。

### ISSUE THREAD

**Issue by KsssAlleria** [jpush/jpush-react-native#281]
App环境：
   react-native: "^0.44.0",
   jcore-react-native: "^1.1.5",
   jpush-react-native: "^1.7.1",

**Comment by huangminlinux** [comment]
后台推送的时候  badge 字段 设为 +1 ，就会每次推送自动加一了

**Comment by KsssAlleria** [comment]
是nodejs sdk 吗？

**Comment by huangminlinux** [comment]
所有的服务端 SDK 都提供了这个功能

**Comment by KsssAlleria** [comment]
nodejs SDK ios推送是有提供这个字段，但是文档是这样描述的 “badge字段 接受参数 如果为 null，表示不改变角标数字；否则把角标数字改为指定的数字；为 0 表示清除”。并没有+1的参数

**Comment by huangminlinux** [comment]
这个问题可以到 (node issue)[https://github.com/jpush/jpush-api-nodejs-client/issues] 中提问

**Comment by KsssAlleria** [comment]
哦，好的，麻烦你了~~

**Comment by jiexishede** [comment]
谢谢这个问题。挺好的。　我有个疑问，为什么这些东西不写到官方文档里呢？？？

**Comment by jiexishede** [comment]
@KsssAlleria
