### ISSUE TITLE
生产环境的registrationid是用开发环境的证书打包的

### ISSUE THREAD

**Issue by wjm117** [jpush/jpush-react-native#283]
如题，我们发布了生产版本，ios还是推送异常，排查发现获取到的registrationid是用开发环境的证书打包的，这个异常一直找不到原因。
![image](https://user-images.githubusercontent.com/20735485/28512292-dc68a5a6-7083-11e7-8254-54740607e572.png)发布的时候这个也已经改成true的。能否帮忙提示出现问题的可能原因，非常感谢🙏🙏🙏

**Comment by huangminlinux** [comment]
- 你是如何测试生产环境的，（一般需要 打包 adhoc ipa 来测试）？
- 生产环境的推送证书配置好没？
- 服务端推送有选择推生产环境吗？

**Comment by wjm117** [comment]
@huangminlinux 首先非常感谢能抽时间回答，其次：
1.生产环境测试都是发布出去之后再测试，最近ios推送异常就发设备ID，消息ID给极光推送相关技术支持帮忙排查，告诉我们ios端是推送环境错误。
2.生产环境的推送证书这些都有配置好的，android端的推送现在都是正常的。

**Comment by huangminlinux** [comment]
后台推送的时候，有没选择生产环境

**Comment by wjm117** [comment]
嗯，这个我们反复确认过后台推送接口是生产环境的

**Comment by huangminlinux** [comment]
通过什么进行推送 Rid 还是 tag 还是 alias

**Comment by wjm117** [comment]
我们是登陆的时候获取registrationId保存到后台进行推送

**Comment by huangminlinux** [comment]
建议打包 成 adhoc 进行测试， 这种方式是生产环境。

**Comment by wjm117** [comment]
好的，非常感谢
