### ISSUE TITLE
setStyleCustom()这个方法 ，调用了怎么没有变化？

### ISSUE THREAD

**Issue by eyingyang** [jpush/jpush-react-native#287]
我是按文档上写的， 但是和默认的通知样式一样，没有相应的变化

**Comment by KenChoi1992** [comment]
你有没有添加资源文件

**Comment by eyingyang** [comment]
我添加过了， node_modules和 项目的anroid下都添加了.xml , 我是复制v1.7.1的， 我感觉 是不是模拟器的原因？
这是模拟器的参数：
Nexus S API 23.2   
Target: google_apis [Google APIs] (API level 23)  android 6.0

**Comment by KenChoi1992** [comment]
@eyingyang 你用真机测试过了吗

**Comment by KenChoi1992** [comment]
@eyingyang 这个问题你没有跟进就先关掉了

**Comment by eyingyang** [comment]
没用， 用的模拟器
