### ISSUE TITLE
setAlias不调用！

### ISSUE THREAD

**Issue by zhangyanlf** [jpush/jpush-react-native#288]
componentDidMount(){

        console.log('componentDidMount');

        JPushModule.setAlias('James', () => {
            Alert.alert('成功', 'tags 成功',[{text: 'OK'}]);
            console.log('成功');
        }, () => {
            Alert.alert('失败','设置alias 失败',[{text:'fail'}]);
            console.log('失败');
        });
}

进入首页后设置Alias，不调用方法！设置不成功！

**Comment by huangminlinux** [comment]
问题是 3.0.5 不兼容 1.1.5 的 jcore， 下个版本会发布 jpush 新版本来支持。

jcore 插件 可以回会退到之前版本，运行下面代码。
```
npm install jcore-react-native@1.1.5 --save
```
