### ISSUE TITLE
ios端打包的ad_hoc包能收到推送，但是发布出去就收不到

### ISSUE THREAD

**Issue by wjm117** [jpush/jpush-react-native#291]
你好，请问本地打包的ad_hoc包安装，能正常收到推送，点击推送也能进到app。但是，app发布出去之后就无法收到推送，查极光后台也没有相关信息，应该是无法获取到Reg.ID,请问出现这种问题的原因可能是什么？非常感谢

**Comment by huangminlinux** [comment]
线上的  jpush 和 jcore 什么版本

**Comment by wjm117** [comment]
@huangminlinux  谢谢帮忙，线上的jpush版本是1.3.6，这个好像没用到jcore，因为是之前的项目，react-native版本是0.40以下的。

**Comment by wjm117** [comment]
@huangminlinux 问题解决了，这个是react-native的热更新无法把原来的jpush SDK一起更新，把新版本重新上架appStore就可以了
