### ISSUE TITLE
升级jpush版本到最新版，安卓notifyJSDidLoad(cb)里 cb为undefined

### ISSUE THREAD

**Issue by JamesWen1993** [jpush/jpush-react-native#292]
RN版本 0.31.0

`
	static notifyJSDidLoad(cb) {
		JPushModule.notifyJSDidLoad((resultCode) => {
			cb(resultCode);
		});
	}
`
cb是undefined

**Comment by JamesWen1993** [comment]
日志报错
W/JIGUANG-JCore(  544): [AndroidUtil] hasPermissionDefined error:com.ruhrcloud.permission.JPUSH_MESSAGE
E/JIGUANG-JCore(  544): [AndroidUtil] The permission should be defined - com.ruhrcloud.permission.JPUSH_MESSAGE

W/JIGUANG-JPush(  544): [AndroidUtil] AndroidManifest.xml missing intent filter for DaemonService: cn.jpush.android.intent.DaemonService
E/JIGUANG-JPush(  544): [AndroidUtil] AndroidManifest.xml missing required intent filter for PushActivity: cn.jpush.android.ui.PushActivity

**Comment by JamesWen1993** [comment]
推送是收的到的

**Comment by KenChoi1992** [comment]
新版本 notifyJSDidLoad 有回调的：
```
JPushModule.notifyJSDidLoad((resultCode) => {
			if (resultCode === 0) {
			}
		});
```

**Comment by JamesWen1993** [comment]
@KenChoi1992 
notifyJSDidLoad方法进去了 返回值也是0
但是还是收不到监听事件

`if (Platform.OS === 'android') {

         //andorid
         JPushModule.notifyJSDidLoad((resultCode) => {
             if (resultCode === 0) {

             }
         });

         JPushModule.addReceiveCustomMsgListener((map) => {

             console.log("extras: " + map.extras);
             alert(map.extras);
         });
         JPushModule.addReceiveNotificationListener((map) => {
             console.log("alertContent: " + map.alertContent);
             console.log("extras: " + map.extras);
             alert("addReceiveNotificationListener")
             // var extra = JSON.parse(map.extras);
             // console.log(extra.key + ": " + extra.value);
         });

         JPushModule.addReceiveOpenNotificationListener((map) => {
             console.log("Opening notification!");
             console.log("map.extra: " + map.extras);
             alert("addReceiveOpenNotificationListener")
         });
         JPushModule.addGetRegistrationIdListener((registrationId) => {
             console.log("Device register succeed, registrationId " + registrationId);
             alert("addGetRegistrationIdListener")
         });
`

**Comment by KenChoi1992** [comment]
@JamesWen1993 看样子你应该是没有配置好，检查一下你的配置吧

**Comment by JamesWen1993** [comment]
我的AndroidManifest.xml

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.ruhrcloud"
    android:versionCode="1"
    android:versionName="1.0">

    <permission
        android:name="com.ruhrcloud.permission.JPUSH_MESSAGE"
        android:protectionLevel="signature" />
    
    <uses-permission android:name="com.ruhrcloud.permission.JPUSH_MESSAGE"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.RECEIVE_USER_PRESENT" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />



    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" android:required="false"/>
    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false"/>

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
        <meta-data
            android:name="com.baidu.lbsapi.API_KEY"
            android:value="tESqd6wa5Ezp1WYptKAWXb2Uq7afonnH"/>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
          android:windowSoftInputMode="stateAlwaysHidden|adjustPan">

        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>



        
        <activity
            android:name="cn.jpush.android.ui.PushActivity"
            android:configChanges="orientation|keyboardHidden"
            android:theme="@android:style/Theme.NoTitleBar"
            android:exported="false">
            <intent-filter>
                <action android:name="cn.jpush.android.ui.PushActivity" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="com.ruhrcloud" />
            </intent-filter>
        </activity>

        
        <activity
            android:name="cn.jpush.android.ui.PopWinActivity"
            android:theme="@style/MyDialogStyle"
            android:exported="false">
        </activity>


        
        
        <service
            android:name="cn.jpush.android.service.PushService"
            android:process=":mult"
            android:exported="false">
            <intent-filter>
                <action android:name="cn.jpush.android.intent.REGISTER" />
                <action android:name="cn.jpush.android.intent.REPORT" />
                <action android:name="cn.jpush.android.intent.PushService" />
                <action android:name="cn.jpush.android.intent.PUSH_TIME" />
            </intent-filter>
        </service>

        
        
        <service
            android:name="cn.jpush.android.service.DaemonService"
            android:enabled="true"
            android:exported="true">
            <intent-filter>
                <action android:name="cn.jpush.android.intent.DaemonService" />
                <category android:name="com.ruhrcloud" />
            </intent-filter>

        </service>

        
        <receiver
            android:name="cn.jpush.android.service.PushReceiver"
            android:enabled="true"
            android:exported="false">
            <intent-filter android:priority="1000">
                <action android:name="cn.jpush.android.intent.NOTIFICATION_RECEIVED_PROXY" />   
                <category android:name="com.ruhrcloud" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.USER_PRESENT" />
                <action android:name="android.net.conn.CONNECTIVITY_CHANGE" />
            </intent-filter>
            
            <intent-filter>
                <action android:name="android.intent.action.PACKAGE_ADDED" />
                <action android:name="android.intent.action.PACKAGE_REMOVED" />

                <data android:scheme="package" />
            </intent-filter>
        </receiver>

        
        <receiver android:name="cn.jpush.android.service.AlarmReceiver" android:exported="false"/>


        
        <meta-data android:name="JPUSH_CHANNEL" android:value="developer-default"/>
        <meta-data android:name="JPUSH_APPKEY" android:value="MY_APP_Key" /> 

      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>



</manifest>
`

**Comment by KenChoi1992** [comment]
@JamesWen1993 你为什么要写这么多东西？插件都帮你弄好了，何必呢？你只要加入 `<meta-data>` 部分即可。

**Comment by JamesWen1993** [comment]
@KenChoi1992 
好的，那我把其他的都删掉只留meta-data部分试试

**Comment by JamesWen1993** [comment]
删除以后是这样
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.ruhrcloud"
    android:versionCode="1"
    android:versionName="1.0">


    
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.RECEIVE_USER_PRESENT" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />



    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" android:required="false"/>
    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false"/>

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
        <meta-data
            android:name="com.baidu.lbsapi.API_KEY"
            android:value="tESqd6wa5Ezp1WYptKAWXb2Uq7afonnH"/>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
          android:windowSoftInputMode="stateAlwaysHidden|adjustPan">

        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>

        
        <meta-data android:name="JPUSH_CHANNEL" android:value="developer-default"/>
        <meta-data android:name="JPUSH_APPKEY" android:value="7370153228b59cd6e2eb63c3" /> 

      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>



</manifest>
`

然后setTag报错 6009并且接受不到通知了

**Comment by JamesWen1993** [comment]
@KenChoi1992 
日志报错
W/JIGUANG-JPush(31671): [AndroidUtil] AndroidManifest.xml missing intent filter for DaemonService: cn.jpush.android.intent.DaemonService
E/JIGUANG-JPush(31671): [AndroidUtil] AndroidManifest.xml missing required intent filter for PushActivity: cn.jpush.android.ui.PushActivity
W/JIGUANG-JCore(31671): [AndroidUtil] hasPermissionDefined error:com.ruhrcloud.permission.JPUSH_MESSAGE
E/JIGUANG-JCore(31671): [AndroidUtil] The permission should be defined - com.ruhrcloud.permission.JPUSH_MESSAGE
W/JIGUANG-JPush(32439): [AndroidUtil] AndroidManifest.xml missing intent filter for DaemonService: cn.jpush.android.intent.DaemonService

**Comment by KenChoi1992** [comment]
@JamesWen1993 兄弟，你看了文档么，我说的是这个插件的文档，你把官网的文档和我们的文档搞混了，你一边用着这个插件，一边用官网的文档来配置……

**Comment by JamesWen1993** [comment]
@KenChoi1992 问题解决了，请问下android我后台程序杀死后就接收不到通知了是什么情况？

**Comment by KenChoi1992** [comment]
@JamesWen1993 建议在社区中搜索一下此类问题。这个 issue 就先关闭了。

**Comment by Spirit3** [comment]
Activity class {com.jpush/com.jpush.MainActivity} does not exist.
