### ISSUE TITLE
两个setTag会报错

### ISSUE THREAD

**Issue by neilzhengzx** [jpush/jpush-react-native#295]
调试时relaoad后，重新执行setTags，报错。

**Comment by huangminlinux** [comment]
什么系统出现的问题？

**Comment by neilzhengzx** [comment]
android系统，ios没有出现该问题

**Comment by KenChoi1992** [comment]
@neilzhengzx 报什么错？

**Comment by neilzhengzx** [comment]
![qq20170803-0](https://user-images.githubusercontent.com/12807303/28908047-e826e844-7853-11e7-882b-7888ef730076.png)

**Comment by sunny20131314** [comment]
同上，设置别名时，android也报了这个错误

**Comment by cloudsafe** [comment]
同上，别名和tags错误

**Comment by KenChoi1992** [comment]
今天再发个版本顺便适配一下 RN 0.47

**Comment by KenChoi1992** [comment]
新版本发布了，这个问题修复了

**Comment by xwartz** [comment]
@KenChoi1992   这个问题修复的版本是多少？

react-native: 0.47.1
jpush-react-native: "^2.1.0",

安卓调试时还是会遇到

**Comment by jjunk1989** [comment]
@xwartz  后来问题解决了么，遇到了同样的问题。

"react-native": "0.42",
"jpush-react-native": "^2.1.6",

**Comment by xwartz** [comment]
@jjunk1989   还没有解决

**Comment by KenChoi1992** [comment]
什么问题

**Comment by jjunk1989** [comment]
@KenChoi1992  调试的时候 reload 会报上面 neilzhengzx 贴的那个错。

**Comment by sapjax** [comment]
Android 双击物理后退键退出程序，再次进入也会出现这个问题。
