### ISSUE TITLE
升级react native到0.47.1启动失败，jpush插件报错

### ISSUE THREAD

**Issue by fuxianwei** [jpush/jpush-react-native#297]
升级react native到0.47.1启动安卓jpush插件报错

/Users/ff/Desktop/work/github/HoldBanna/node_modules/jpush-react-native/android/src/main/java/cn/jpush/reactnativejpush/JPushPackage.java:27: 错误: 方法不会覆型的方法
    @Override
    ^

版本
react native： 0.47.1
jpush-react-native: 2.0.0

**Comment by KenChoi1992** [comment]
0.47 去掉了 createJSModules 接口，所以你去掉 JPushPackage 中的 createJSModules 方法就行了，下个版本支持 0.47

**Comment by KenChoi1992** [comment]
@fuxianwei 新版本发布了，修复了这个问题。

**Comment by scriptfans** [comment]
@KenChoi1992 但是0.46版本报错了：

JPushPackage.java:12: 错误: JPushPackage不是抽象的, 并且未覆盖ReactPackage中的抽象方法createJSModules()

请问我应该把jpush插件的版本锁定到哪一个呢？因为目前很多插件都还没有更新支持0.47，只能先用着0.46的RN。
