### ISSUE TITLE
没有移除别名的api

### ISSUE THREAD

**Issue by Guodadada** [jpush/jpush-react-native#298]
没有移除别名的api，用户退出无法移除已经添加的别名

**Comment by KenChoi1992** [comment]
@Guodadada 用 `deleteAlias` 接口

**Comment by Guodadada** [comment]
点进jpush-react-native/index 没搜索到 deleteAlias。

**Comment by KenChoi1992** [comment]
@Guodadada deleteAlias 需要 jpush-react-native 2.0.0 以上版本。
