### ISSUE TITLE
同时使用 jpush-react-native 和 react-native-jmessag 报错

### ISSUE THREAD

**Issue by sunny20131314** [jpush/jpush-react-native#300]
同时使用 jpush-react-native 和 react-native-jmessag，两个包有冲突，都使用了jcore，程序无法运行...

环境：
"react": "16.0.0-alpha.12",
"react-native": "0.45.1",
"jpush-react-native": "^1.6.0",
"react-native-jmessage": "^0.2.1",

去掉其中jpush-react-native 依赖的 jcore-react-native后，
ios报错如下：
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -ljcore-ios
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -ljcore-ios is not an object file (not allowed in a library)

android:
打包后闪退

求指教

**Comment by KenChoi1992** [comment]
删掉其中一个 jcore 就行了，但是要确保 jpush  和 jmessage 使用的 jcore 版本都是相同的。

**Comment by huangminlinux** [comment]
估计第三方开发的 react-native-jmessag 这个库没有做 jcore 分离，所以两个包冲突了，
iOS： 手动在 Build Settings 里面将 Other librarian Flags 里面的 -ljcore-ios 这个参数删掉。

**Comment by sunny20131314** [comment]
我试了下 @huangminlinux  说的方法... 结果... 报错了....
Undefined symbols for architecture arm64:
  "_JCOREDisplayVersion", referenced from:
      +[JMSGBridge setupWithOption:appKey:channel:apsForProduction:imSupport:] in JMessage(JMSGClientController.o)
      ___92+[JPUSHService commonSetupWithOption:appKey:channel:apsForProduction:advertisingIdentifier:]_block_invoke in libRCTJPushModule.a(JPUSHService.o)
  "_JCOREGetBuildVersion", referenced from:
      ___92+[JPUSHService commonSetupWithOption:appKey:channel:apsForProduction:advertisingIdentifier:]_block_invoke in libRCTJPushModule.a(JPUSHService.o)
  "_JPUSHAlert", referenced from:
      -[JPUSHService getTagAliasInvocationWithCallback:target:] in libRCTJPushModule.a(JPUSHService.o)
  "_JPUSHBase64", referenced from:
      -[JMSGBadgeNumberReportRequest p_generateRequestHead] in JMessage(JMSGBadgeNumberReport.o)
      -[JPUSHBadgeNumberReportRequest p_generateRequestHead] in libRCTJPushModule.a(JPUSHBadgeNumberReport.o)
  "_JPUSHConvertTokenDataToString", referenced from:
      -[JMSGClientController updateDeviceToken:] in JMessage(JMSGClientController.o)
      -[JPUSHClientController updateDeviceToken:] in libRCTJPushModule.a(JPUSHClientController.o)
  "_JPUSHDecodeDataFromBuffer", referenced from:

**Comment by huangminlinux** [comment]
很有可能是 JMessage JPush 所依赖的 jcore 版本不匹配，建议到官网下载最新的 SDK 手动替换一下

**Comment by sunny20131314** [comment]
恩，确实是jcore版本不匹配，我把jcore版本使用 1.1.2 就可以用了，1.0.0 的版本使用不了，谜一样的解决了
