### ISSUE TITLE
最新支持RN47的版本是否兼容RN35？谢谢！

### ISSUE THREAD

**Issue by kingctan** [jpush/jpush-react-native#303]
最新支持RN47的版本是否兼容RN35？谢谢！

**Comment by cloudsafe** [comment]
.45的还都没兼容好。

**Comment by scriptfans** [comment]
反正我0.46的没法用……

**Comment by kingctan** [comment]
咋这么多问题啊？兼容最好的版本是哪一个啊？

**Comment by scriptfans** [comment]
希望能尽快解决

**Comment by KenChoi1992** [comment]
RN 0.47 以下的版本和 0.47 以上的不兼容。因为它彻底改变了 ReactPackage 接口，而不是标注过期。升级 JPush 插件会导致 RN 0.47 版本以下的编译不通过，需要手动修改 `JPushPackage`，加上 
```
@Override
    public List<ViewManager> createJSModules(ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }
```

**Comment by scriptfans** [comment]
@kingctan 我看了几个三方库的更新，他们仅仅只是把@Override注解这句移除了，保留createJSModules方法的声明，好像这样就能兼容之前的老版本了？如果是的话可否处理一下？不太懂java，谢谢了。

**Comment by scriptfans** [comment]
@KenChoi1992 比方说这个：
https://github.com/rebeccahughes/react-native-device-info/commit/1dd6234d4b511575842bfa7f052f0777ebb21f53

**Comment by KenChoi1992** [comment]
已更新
