### ISSUE TITLE
请问 android 用 jumpToPushActivity 跳转时怎么传参数?

### ISSUE THREAD

**Issue by likeben** [jpush/jpush-react-native#304]
现在android打开推送消息时, 无法直接用导航器跳转页面, 使用新方法 jumpToPushActivity 可以跳转成功, 但需要向新页面传递参数, 请问该怎么做

**Comment by cloudsafe** [comment]
你在extra消息里面把参数带着不就行了？然后，在跳转的导航器上加上对应的extra.xxx即可。
我是navigation.navigate(extra.component,{xxx:xxx});

**Comment by likeben** [comment]
我用的是老版本的导航器
`
this.props.navigator.push({
            name: "MessageDetail",
            component: MessageDetail,
            params: {
                subject: notification.subject,
                content: notification.cont,
                push_type: notification.push_type,
                createdAt: notification.createdAt
            }
        });
`
但是在最新的 jpush 中这样做没有效果, 点击通知直接重新打开应用, 使用
`
JPushModule.jumpToPushActivity('MessageDetailActivity');
`
可以跳转成功, 但是不知道该怎样传递参数

**Comment by cloudsafe** [comment]
看了下这个函数，只支持android而且，我看着JPushModule的这个函数里面，貌似不能传其他参数。。。。
https://github.com/jpush/jpush-react-native/blob/master/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java#L565

**Comment by likeben** [comment]
那还有其他解决方法吗, 为什么最新版本的 jpush 中点击通知会直接打开应用, 请问一下这个默认行为怎么改

**Comment by cloudsafe** [comment]
额，我不是官方的，我也是用户，昨天提交了两个bug，貌似修复了跟没修复差不多。。。坐等下一版本。

**Comment by likeben** [comment]
好吧, 谢谢了

**Comment by KenChoi1992** [comment]
@likeben 更新了，可以看看 demo 怎么用

**Comment by likeben** [comment]
好的, 我试试
