### ISSUE TITLE
Android 推送通知如何显示？

### ISSUE THREAD

**Issue by twairball** [jpush/jpush-react-native#305]
可以收到通知、但是要到通知中心才看到。
Android 方面还需要调整什么才能让推送通知自己弹出来？

**Comment by KenChoi1992** [comment]
@twairball 你可以在 JPushReceiver 收到事件的时候，创建为本地通知。

**Comment by KenChoi1992** [comment]
@twairball 应该还和手机系统有关，现在很多厂商自己做了深度定制，你可以试试在设置中找到应用管理，然后查看通知栏设置，看看有没有打开显示横幅通知什么的。

**Comment by KenChoi1992** [comment]
@twairball 没有问题就关闭了
