### ISSUE TITLE
自动配置失败

### ISSUE THREAD

**Issue by scriptfans** [jpush/jpush-react-native#306]
您好，我按照文档中说的，执行自动配置脚本的时候报错了，日志如下：

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Jerry\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'configureJPush',
1 verbose cli   'c5ffaef7ff3fb040fd452420' ]
2 info using npm@4.6.1
3 info using node@v8.2.1
4 verbose stack Error: missing script: configureJPush
4 verbose stack     at run (C:\Users\Jerry\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Users\Jerry\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Users\Jerry\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Users\Jerry\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Users\Jerry\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Users\Jerry\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Users\Jerry\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:311:12
4 verbose stack     at C:\Users\Jerry\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:513:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)
5 verbose cwd C:\Users\Jerry\Documents\workspace\CdataRentalMobile
6 verbose Windows_NT 10.0.15063
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jerry\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "configureJPush" "c5ffaef7ff3fb040fd452420"
8 verbose node v8.2.1
9 verbose npm  v4.6.1
10 error missing script: configureJPush
11 verbose exit [ 1, true ]

请问是哪里有问题呢？谢谢了。

**Comment by scriptfans** [comment]
不好意思，自己找到原因了，原来是之前用yarn add装过jpush插件，这个不会修改package.json文件加入配置脚本，改用npm来装就能找到命令了。

**Comment by scriptfans** [comment]
按照配置要求一步一步的来，最后也不能用，RN版本是0.46

**Comment by huangminlinux** [comment]
能否描述一下不能用是指哪些功能？
iOS / Android 哪些功能有问题？

**Comment by scriptfans** [comment]
@huangminlinux 两个问题：
我已经重新初始化了项目，然后按文档来配置，第一个问题是，package.json文件在安装完之后没有自动添加configureJPush这个命令脚本，需要手工加进去；第二个问题是执行react-native run-android的时候报错了，我再试一遍，如果遇到同样的问题，把日志贴上来。

**Comment by scriptfans** [comment]
@huangminlinux 刚才重新配置了一遍，还是上述的问题，无法自动添加configureJPush，我自己手动加上去了。然后，安卓编译的错误日志如下：

:jpush-react-native:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
C:\Users\Jerry\Documents\workspace\CdataRentalMobile\node_modules\jpush-react-native\android\src\main\java\cn\jpush\reactnativejpush\JPushPackage.java:12: 错误: JPushPackage不是抽象的, 并且未覆盖ReactPackage中的抽象方法createJSModules()
public class JPushPackage implements ReactPackage {
       ^
注: C:\Users\Jerry\Documents\workspace\CdataRentalMobile\node_modules\jpush-react-native\android\src\main\java\cn\jpush\reactnativejpush\JPushModule.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
1 个错误
:jpush-react-native:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jpush-react-native:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by scriptfans** [comment]
RN版本0.46.4，jpush-react-native版本2.0.1，看起来跟修改支持RN 0.47那个补丁有关？

**Comment by scriptfans** [comment]
还是说因为第一步postInstall没成功添加命令导致的？

**Comment by scriptfans** [comment]
# #303

**Comment by scriptfans** [comment]
2.0.2版已经可以正常编译了，感谢开发者。

**Comment by KenChoi1992** [comment]
@scriptfans 最新的版本修复了 bug，要升级到 2.0.4

**Comment by scriptfans** [comment]
@KenChoi1992 多谢提醒，直接修改package.json的声明再安装就可以了吧？还需要再配置一遍吗？
