### ISSUE TITLE
 undefined is not an object(evaluating 'this._component.getScrollableNode')

### ISSUE THREAD

**Issue by BetterFanKai** [jpush/jpush-react-native#307]
iOS端添加  "jcore-react-native": "^1.1.7",  "jpush-react-native": "^2.0.1",之后，编译成功，项目能运行起来，但是每一个有点击事件的地方都会崩溃，并报错 undefined is not an object(evaluating 'this._component.getScrollableNode')，我把"jpush-react-native"和"jcore-react-native"去掉之后就可以正常点击跳转。react-native版本0.44.0
![error](https://user-images.githubusercontent.com/29403831/29009100-c8b54094-7b52-11e7-9fb7-01486984d4d5.png)

**Comment by huangminlinux** [comment]
你说的点击事件是 点击推送？
