### ISSUE TITLE
setAlias 等方法报错 sCacheMap 为空

### ISSUE THREAD

**Issue by Vinkugor** [jpush/jpush-react-native#309]
报错信息大概这样：
Exception in native call
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference
at cn.jpush.reactnativejpush.JPushModule.setAlias(JPushModule.java:288)
at java.lang.reflect.Method.invoke(Native Method)
.........
源码
public void setAlias(String alias, Callback callback) {
        int sequence = getSequence();
        Logger.i(TAG, "Set alias, sequence: " + sequence);
        sCacheMap.put(sequence, callback);
        JPushInterface.setAlias(getReactApplicationContext(), sequence, alias);
    }
报错原因是由于sCacheMap 这个变量为空，因此所有含有sCacheMap的方法都不能用。这个问题怎么解决呢？

**Comment by KenChoi1992** [comment]
@Vinkugor 你用的不是最新版本吧

**Comment by Vinkugor** [comment]
"dependencies": {
		"jcore-react-native": "^1.1.7",
		"jpush-react-native": "^2.0.0",
		"react": "16.0.0-alpha.6",
		"react-native": "0.44.3",
		"react-native-qrcode": "^0.2.3",
		"react-native-storage": "^0.2.2",
		"react-navigation": "^1.0.0-beta.11",
		"socket.io": "^2.0.3"
	},
我是这个，需要换成什么版本吗

**Comment by KenChoi1992** [comment]
@Vinkugor 最新的是 2.0.1，你升级后需要在 JPushPackage 中加上
```
public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
```

**Comment by Vinkugor** [comment]
@KenChoi1992 感谢指导!
不过虽然不报错了,但是setAlias 没回调,getAlias也没反应。
好尴尬啊

**Comment by Vinkugor** [comment]
@KenChoi1992 再次感谢一下，也提醒一下跟我遇到同样问题的小伙伴吧
虽然setAlias getAlias 没任何回调,但已经可以别名推送了！这个应该是个bug吧,只能等官方修复了。

**Comment by KenChoi1992** [comment]
@Vinkugor 没有回调？有没有打印日志，我们把接口方式改了，官网的文档是没有回调的，但我们这个插件改成了回调的形式。

**Comment by Vinkugor** [comment]
@KenChoi1992 我的代码：
JPushModule.setAlias(alias, (result) => {
        console.log('成功',result);
    });
Console没有打印出来

**Comment by likeben** [comment]
同求, setAlias 失效

**Comment by KenChoi1992** [comment]
@Vinkugor @likeben  这估计是 JPush SDK 的问题，没有进入到 JPushMessageReceiver，我先试试更新 JPush SDK 版本。

**Comment by KenChoi1992** [comment]
@Vinkugor @likeben 你们再更新一下，最新的是 2.0.4版本，应该没问题了。测试时 example 加入的改动没有更新到 npm 这边

**Comment by Vinkugor** [comment]
@KenChoi1992 thank 
测试成功,非常感谢！
