### ISSUE TITLE
我写了 ts 的类型支持，可以直接提 pr 吗？

### ISSUE THREAD

**Issue by huhuanming** [jpush/jpush-react-native#311]
类型文件在这里
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jpush-react-native/index.d.ts

**Comment by KenChoi1992** [comment]
@huhuanming 感谢提交，可以先提交到 dev 分支

**Comment by huhuanming** [comment]
#312

**Comment by KenChoi1992** [comment]
@huhuanming 合了 :D
