### ISSUE TITLE
iOS编译错误

### ISSUE THREAD

**Issue by scriptfans** [jpush/jpush-react-native#314]
您好，我按文档集成了插件，编译iOS的时候报了这个错，请问要怎么解决？

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by huangminlinux** [comment]
插件什么版本？

**Comment by scriptfans** [comment]
@huangminlinux 2.0.4, RN 版本是0.46.4

**Comment by scriptfans** [comment]
是不是还需要手工去添加这些配置？
https://github.com/jpush/jpush-react-native/blob/master/example/documents/iOS_Usage.md

**Comment by huangminlinux** [comment]
@scriptfans 什么设备上做的测试？

**Comment by scriptfans** [comment]
在模拟器上，怀疑是自动配置那一步失败了，我再确认下

**Comment by huangminlinux** [comment]
https://github.com/jpush/jpush-react-native/releases  看看 这个release  的升级指南有做一遍吗？

**Comment by scriptfans** [comment]
@huangminlinux 没有，囧。我照着做一下试试，谢谢

**Comment by scriptfans** [comment]
@huangminlinux 按照升级指南做了之后果然没报错了，建议以后发布新版本如果有注意事项的话，把操作说明也放到README里面，以免遗漏，谢谢啦。

**Comment by neilzhengzx** [comment]
@scriptfans  jcore 需要link一下，我也碰到这个问题了，link后就好了

**Comment by kingctan** [comment]
link不成功，手动将jcore-react-native加到项目Libraries，然后在General ---> Linked Frameworks and Libraries中增加libRCTJCoreModule.a，就OK了。
