### ISSUE TITLE
设置别名对应的JAVA方法报错

### ISSUE THREAD

**Issue by duanyachao** [jpush/jpush-react-native#315]
在监听事件里面监听用户登录成功，然后把用户名设置为推送的别名，`
this.loginListener=DeviceEventEmitter.addListener('loginSuccess',(msg)=>{
            // console.info(msg)
            JPushModule.setAlias(msg, (map) => {
				if (map.errorCode === 0) {
					console.log("set alias succeed");
				} else {
					console.log("set alias failed, errorCode: " + map.errorCode);
				}
			});
        })`
但是执行后，出现报错信息：‘setAlias’ JPushModel.java:286 有错误

**Comment by KenChoi1992** [comment]
@duanyachao 是最新的版本吗？

**Comment by duanyachao** [comment]
@KenChoi1992  这个更新到最新版本，没有问题了  呵呵
