### ISSUE TITLE
addReceiveOpenNotificationListener   addOpenNotificationLaunchAppListener   ios 上都不生效，哪有文档说明，或者示例么？谢谢！

### ISSUE THREAD

**Issue by kingctan** [jpush/jpush-react-native#316]
`
"react": "^15.3.1",
"react-native": "0.35.0",
`

**Comment by huangminlinux** [comment]
jpush-react-native 使用的是最新版本吗？

**Comment by huangminlinux** [comment]
更新了 demo 示例，可以运行一下 demo。

**Comment by kingctan** [comment]
@huangminlinux 是最新版本。
好。我运行一下demo试试。谢谢！

**Comment by kingctan** [comment]
@huangminlinux 你好，demo没有改动啊。。。。。是否上传上来了呢？谢谢！

**Comment by kingctan** [comment]
@huangminlinux  试了dev分支中新加的内容，没改什么东西。addReceiveOpenNotificationListener addOpenNotificationLaunchAppListener 这两个函数，都不起作用啊。

**Comment by huangminlinux** [comment]
这边测试是没有问题的。

- 确定能收到推送吗？
- 另外提供 xcode 的日志

**Comment by kingctan** [comment]
@huangminlinux 你在QQ3群 276533421 里么？谢谢！

**Comment by huangminlinux** [comment]
有 jpush-react-native  QQ群 553406342
