### ISSUE TITLE
设置保留最近通知条数

### ISSUE THREAD

**Issue by thirteenthEyes** [jpush/jpush-react-native#317]
所谓保留最近的，意思是，如果有新的通知到达，之前列表里最老的那条会被移除。 
例如，设置为保留最近 5 条通知。假设已经有 5 条显示在通知栏，当第 6 条到达时，第 1 条将会被移除。

**Comment by huangminlinux** [comment]
没有这个 api。

**Comment by KenChoi1992** [comment]
他说的是 Android 这边的，下个版本加上。

**Comment by KenChoi1992** [comment]
@thirteenthEyes  https://github.com/jpush/jpush-react-native/releases/tag/2.0.7 更新了。
