### ISSUE TITLE
iOS 编译错误

### ISSUE THREAD

**Issue by hkwin** [jpush/jpush-react-native#318]
您好，我按文档集成了插件，编译iOS的时候报了这个错，请问要怎么解决？

duplicate symbol _OBJC_CLASS_$_JPUSHUserDeviceReportRequest in:
    /Users/hkwin/Library/Developer/Xcode/DerivedData/LemonPush-dcbmbmihgevcrfgepfzqtmeytyyg/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHUserDeviceReport.o)
    /Users/hkwin/Library/Developer/Xcode/DerivedData/LemonPush-dcbmbmihgevcrfgepfzqtmeytyyg/Build/Products/Debug-iphoneos/libRCTJPushModule.a(JPUSHUserDeviceReport.o)
duplicate symbol _OBJC_METACLASS_$_JPUSHUserDeviceReportRequest in:
    /Users/hkwin/Library/Developer/Xcode/DerivedData/LemonPush-dcbmbmihgevcrfgepfzqtmeytyyg/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHUserDeviceReport.o)
    /Users/hkwin/Library/Developer/Xcode/DerivedData/LemonPush-dcbmbmihgevcrfgepfzqtmeytyyg/Build/Products/Debug-iphoneos/libRCTJPushModule.a(JPUSHUserDeviceReport.o)
duplicate symbol _OBJC_CLASS_$_JPUSHUserDeviceReportResponse in:
    /Users/hkwin/Library/Developer/Xcode/DerivedData/LemonPush-dcbmbmihgevcrfgepfzqtmeytyyg/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHUserDeviceReport.o)
    /Users/hkwin/Library/Developer/Xcode/DerivedData/LemonPush-dcbmbmihgevcrfgepfzqtmeytyyg/Build/Products/Debug-iphoneos/libRCTJPushModule.a(JPUSHUserDeviceReport.o)
duplicate symbol _OBJC_IVAR_$_JPUSHReportCacheController._syncBlock in:
    /Users/hkwin/Library/Developer/Xcode/DerivedData/LemonPush-dcbmbmihgevcrfgepfzqtmeytyyg/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHReportCacheController.o)
    /Users/hkwin/Library/Developer/Xcode/DerivedData/LemonPush-dcbmbmihgevcrfgepfzqtmeytyyg/Build/Products/Debug-iphoneos/libRCTJPushModule.a(JPUSHReportCacheController.o)
duplicate symbol _OBJC_IVAR_$_JPUSHReportCacheController._sendingPackageCache in:
    /Users/hkwin/Library/Developer/Xcode/DerivedData/LemonPush-dcbmbmihgevcrfgepfzqtmeytyyg/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHReportCacheController.o)
    /Users/hkwin/Library/Developer/Xcode/DerivedData/LemonPush-dcbmbmihgevcrfgepfzqtmeytyyg/Build/Products/Debug-iphoneos/libRCTJPushModule.a(JPUSHReportCacheController.o)
ld: 651 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

备注：JPush版本 1.7.1
           JCore版本 1.1.8
           RN版本 0.44.0

这只是截取了一部分的错误，不过错误都是有关于JPUSH的。请问怎么解决？谢谢了！

**Comment by huangminlinux** [comment]
jpush 要升级到最新版本

**Comment by huangminlinux** [comment]
这个issue 和 #314  是一样的先关了这个issue

**Comment by hkwin** [comment]
@huangminlinux 好的，问题已经解决了，就是JPush和JCore 都安装最新版，然后按照配置步骤就可以了。
