### ISSUE TITLE
jpush 安卓 杀死进程后,接收不到通知

### ISSUE THREAD

**Issue by myetc** [jpush/jpush-react-native#319]
检查 /node_modules/jpush-react-native/android/src/main/androidManifest.xml
发现无以下代码,是否正常.

#         
        <receiver
            android:name="cn.jpush.android.service.PushReceiver"
            android:enabled="true" >
          <intent-filter android:priority="1000"> 
                <action android:name="cn.jpush.android.intent.NOTIFICATION_RECEIVED_PROXY" /> 
                <category android:name="您应用的包名"/> 
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.USER_PRESENT" />
                <action android:name="android.net.conn.CONNECTIVITY_CHANGE" />
            </intent-filter>
            
            <intent-filter>
                <action android:name="android.intent.action.PACKAGE_ADDED" />
                <action android:name="android.intent.action.PACKAGE_REMOVED" />
                <data android:scheme="package" />
            </intent-filter>
        </receiver>

IOS测试正常.
安卓测试不满足功能如下,求大神指点.
1:进程杀死,接收不到通知, 重启应用通知80%概率会再次推送  ,打开应用后台再发送一条通知 100%遗失通知会被通知(AS进程杀死后台无打印,确定无接收)
2:点击通知,在应用未打开状态下,50%概率能够打开应用,50%点击通知,通知消息,应用无反应.
3:点击通知,应用打开状态下有可能会执行两次 addReceiveOpenNotificationListener 

调试环境如下:
OS:mac
CODE:
"jcore-react-native": "^1.1.8",
    "jpush-react-native": "^2.0.4",
    "react": "15.4.2",
    "react-native": "0.42.3"

补:
在jcore-react-native中,查找到了以上代码
as打印显示, 通知,服务,接收一切正常.

现在就尴尬了,找不到啥子原因,导致进程被杀,接收不到通知,QQ 微信这些,还有其他APP,都是好的

Could not find method android.app.Instrumentation.callActivityOnSaveInstanceState, referenced from method cn.jiguang.a.a.d.a.a.d.callActivityOnSaveInstanceState

**Comment by KenChoi1992** [comment]
@myetc 在手机设置里，设置一下允许应用自启动试试

**Comment by myetc** [comment]
@KenChoi1992  设置了,坑的不停的测试,结果是,部分安卓机可以,但 延迟30分钟左右.
部分安卓机,完全收不到

**Comment by starsion** [comment]
请问一下，app进程杀死后，还可以接收通知，我没有找到相应的api啊？

**Comment by KenChoi1992** [comment]
@starsion 不知道你想表达什么。

**Comment by scriptfans** [comment]
我这边坚果Pro，也是杀了进程就收不到了，不知道有没有办法解决？ @KenChoi1992

**Comment by scriptfans** [comment]
@KenChoi1992 刚才按照上面说的，在设置里面开启了“允许自启动”之后就正常了，但是我想问一下，这个选项是默认关闭的吗？是不是所有安卓机都要提醒用户去开启这个权限才行？还是只是某些特定机型的问题？

**Comment by Sura-zm** [comment]
为什么我开启‘允许自启动’后也不行，求解
环境：
"jcore-react-native": "^1.2.2",
"jpush-react-native": "^2.1.3",
"react-native": "0.44.3",
设备：小米4S  华为Mate8

**Comment by KenChoi1992** [comment]
@myetc 现在绝大多数厂商都定制了系统，一般都会关闭这个 允许自启动 的选项。

**Comment by KenChoi1992** [comment]
@Sura-zm 如果你的手机装了其他包含 JPush SDK 的应用，都可以相互拉起的。

**Comment by neo125874** [comment]
@Sura-zm 請教後來有解決嗎？
