### ISSUE TITLE
IOS APP首次启动提示需要获取通知权限，点击不管是同意还是不同意软件就退了。

### ISSUE THREAD

**Issue by cloudsafe** [jpush/jpush-react-native#322]
哪里配置不对么

**Comment by huangminlinux** [comment]
有日志没？

**Comment by cloudsafe** [comment]
我xcode运行，死活收不到推送（我是用的Push API，之前正常。且开发版正常）。。。。所以日志也没法获取。。。
还有，软件关闭状态。
addOpenNotificationLaunchAppListener   怎么只返回了registrationId。
如果要进入到指定界面，我得需要读取到通知内容才可以。

**Comment by cloudsafe** [comment]
监听appstate报的错。
