### ISSUE TITLE
每一个消息, 会触发4次addReceiveNotificationListener, 请问这是为什么?

### ISSUE THREAD

**Issue by likeben** [jpush/jpush-react-native#327]

**Comment by huangminlinux** [comment]
`addReceiveNotificationListener` 这个方法是不是监听了多次，

建议在 `componentWillUnmount ` 方法中调用 `removeOpenNotificationListener` 方法。

**Comment by likeben** [comment]
检查过了, 监听就设置了一次, 已进行了事件移除
拷贝官方示例代码, 进行测试, 也是触发了4次

**Comment by huangminlinux** [comment]
这边测试并没有出现你那种情况，环境是什么？

jpush-react-native 版本是什么？
iOS、Android？
iOS 测试系统是什么版本？

**Comment by likeben** [comment]
ios 8,
react-native 0.38,
jpush-react-native 是最新的

**Comment by kingctan** [comment]
自定义消息，确实会发出4次出来。

RN0.35.
jpush-react-native最新。

**Comment by kingctan** [comment]
[JPUSHService setupWithOption:launchOptions appKey:appKey
                        channel:channel apsForProduction:isProduction];
[[NSNotificationCenter defaultCenter] removeObserver:self];     <======此句。
发现加上这句，就没问题了。

**Comment by likeben** [comment]
我试试, 谢谢

**Comment by likeben** [comment]
不行, 而且不是自定义消息, 是推送通知也触发了 4次, 只有 ios 端是这样, android 正常

**Comment by huangminlinux** [comment]
@likeben  在下面这段代码中打个断点，看一下执行了几次
<img width="972" alt="ffccbfb8-c2be-4086-8796-90cf4e9982d5" src="https://user-images.githubusercontent.com/5852088/29550672-84325d12-8741-11e7-9e76-61b7bfa408f1.png">

**Comment by likeben** [comment]
![image](https://user-images.githubusercontent.com/24544714/29551183-27f872cc-8744-11e7-9d4e-00cdf99478ed.png)
这块的代码执行了两次, 
不是触发了四次, addReceiveNotificationListener总共触发了两次
这次测试使用的真机, ios 版本是 10.2.1, RN 版本0.38, jpush-react-native 最新

**Comment by RowgerGo** [comment]
我也是, addReceiveNotificationListener方法被触发多次,只监听一次,并且有调用 removeOpenNotificationListener 方法。

**Comment by hnliyuan** [comment]
addReceiveNotificationListener 调用多次。
