### ISSUE TITLE
iOS编译报错referenced from

### ISSUE THREAD

**Issue by whg1412** [jpush/jpush-react-native#328]
iOS编译报错,RN0.45.1, 插件版本2.0.4
 "_kJPFNetworkIsConnectingNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidSetupNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidRegisterNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidReceiveMessageNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in libRCTJPushModule.a(RCTJPushActionQueue.o)
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidLoginNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
      -[RCTJPushModule reactJSDidload] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidCloseNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
      -[RCTJPushModule reactJSDidload] in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPUSHRegisterEntity", referenced from:
      objc-class-ref in AppDelegate.o

**Comment by huangminlinux** [comment]
日志不全， 
是不是在iphone4s 以前的模拟器运行了？
换成真机，或者 5s 以后模拟器试试

**Comment by whg1412** [comment]
Undefined symbols for architecture i386:
  "_kJPFNetworkIsConnectingNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidSetupNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidRegisterNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidReceiveMessageNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in libRCTJPushModule.a(RCTJPushActionQueue.o)
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidLoginNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
      -[RCTJPushModule reactJSDidload] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidCloseNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
      -[RCTJPushModule reactJSDidload] in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPUSHRegisterEntity", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
是用7plus的模拟器运行的

**Comment by huangminlinux** [comment]
ld: symbol(s) not found for architecture i386     7plus 应该会提示  architecture x86_64

**Comment by whg1412** [comment]
是不能在模拟器上运行吗?该如何解决这个问题?

**Comment by huangminlinux** [comment]
可以在 5s 以上模拟器 运行

**Comment by whg1412** [comment]
我在5s(10.3.1)上运行也报相同的错,是引入的哪个步骤出错了吗?

**Comment by huangminlinux** [comment]
试试真机有没有问题？

**Comment by whg1412** [comment]
真机没问题,可以运行

**Comment by huangminlinux** [comment]
是不是编译选了 release？

**Comment by whg1412** [comment]
是这个问题,谢谢,解决了

**Comment by xuanheScript** [comment]
@huangminlinux 我现在也遇到了这个问题，测试场景是iphone 5 模拟器编译会出现这个错误。请问这个情况是正常的吗？是因为xcode升级导致的？

**Comment by huangminlinux** [comment]
编译 release 版本的话换成真机试试， debug 版本的话用5s 的模拟器试试。
