### ISSUE TITLE
removeReceiveOpenNotificationListener接口里面的这个好像不好用。出现点击推送，对应函数多次执行的情况，打开多次窗口的情况，unmount里面增加了这个移除函数。

### ISSUE THREAD

**Issue by cloudsafe** [jpush/jpush-react-native#330]
removeReceiveOpenNotificationListener接口里面的这个好像不好用。出现点击打开多次窗口的情况，unmount里面增加了这个移除函数。我用的react-navigation,有多次reset到home 页面，移除监听如果失效的话，肯定会出现这种情况。
我看到在另一个issue里面提到了removeOpenNotificationListener，这个接口好像不存在了吧？

**Comment by huangminlinux** [comment]
不好用是什么意思？ 是这个无效，还是指什么？  确定成功移除监听了吗？
贴一下你的监听和取消监听的代码。

removeOpenNotificationListener 接口存在。

**Comment by Eggplant-Cui** [comment]
许多人反应这个问题啊，我现在也遇到了这个问题
代码应该没问题，是从之前一个完美运行的项目直接搬过来的，只有消息体逻辑的变化，注册和删除listener都没改变
不同的是以前都是注册在class里面，现在是注册在navigation tab里面，我觉得大家遇到的推送两次，推送三次，推送四次的问题很有可能就在这里

**Comment by fengye1** [comment]
@Eggplant-Cui 请问你的问题解决了吗。我现在也遇到了同样的问题
