### ISSUE TITLE
Android error : undefined is not a function (evaluting 'cb(rsultCode)')

### ISSUE THREAD

**Issue by Jiujiale** [jpush/jpush-react-native#331]
![image](https://user-images.githubusercontent.com/15116421/29546604-0328b8c4-8728-11e7-9d28-d331656e583a.png)

"react-native": "0.44.2"
npm : 5.2.0
node: v6.10.0

**Comment by KenChoi1992** [comment]
你用的时候要这样：
```
JPushModule.notifyJSDidLoad((resultCode) => {
	// do something
});
```

**Comment by Jiujiale** [comment]
谢啦。搞定
