### ISSUE TITLE
在魅族Pro 5上接收不到推送

### ISSUE THREAD

**Issue by MonkeyEatBanana** [jpush/jpush-react-native#332]
我试了一下，在魅族Pro 5上接收不到，其他手机上可以接收到，是魅族Pro5上不兼容吗？？？

**Comment by KenChoi1992** [comment]
@MonkeyEatBanana 看下你的手机设置有没有屏蔽通知

**Comment by MonkeyEatBanana** [comment]
没有，通知栏消息是开着的，而且，我在两台手机上安装的，但是极光网站上只显示有一台可以推送的，根本没检测到魅族Pro5这台手机

**Comment by KenChoi1992** [comment]
@MonkeyEatBanana 昨天有可能是网络问题，今天再试试？

**Comment by MonkeyEatBanana** [comment]
嗯嗯，有可能，今天自己就好用了，谢谢
