### ISSUE TITLE
iOS的API中如何获取应用当前badge的值?或者可以在本体通过API实现应用badge的运算吗？

### ISSUE THREAD

**Issue by YanGin** [jpush/jpush-react-native#335]
想要实现像QQ等其他应用那样，在进入页面点击查看推送来的信息时，会逐条递减应用的badge的值。而不是一下子全部清空，这样好做标记提醒。setBadge的第一个参数只是实现了将应用的badge具体设某个值，但我不知道当前应用的badge总值，所以也就不知道接下来查看后，我应该将badge具体设置为几了。

**Comment by huangminlinux** [comment]
下个版本中提供，获取应用当前 badge 的接口。

**Comment by huangminlinux** [comment]
可以升级到 2.0.5 版本

**Comment by YanGin** [comment]
@huangminlinux 好的，谢谢！

**Comment by huangminlinux** [comment]
调整了方法名， 可以参考 https://github.com/jpush/jpush-react-native/releases/tag/2.0.6
