### ISSUE TITLE
iOS下面，应用未打开状态不会执行addReceiveOpenNotificationListener

### ISSUE THREAD

**Issue by davehandong** [jpush/jpush-react-native#336]
addReceiveOpenNotificationListener在Android系统下面正常，iOS系统中只有在应用打开状态才能执行，如果应用在处于关闭状态，收到消息不会执行addReceiveOpenNotificationListener

**Comment by huangminlinux** [comment]
监听这个事件 addOpenNotificationLaunchAppListener

**Comment by davehandong** [comment]
我想要做的是收到消息以后会执行的操作，不是点击消息以后会执行的操作。跟addOpenNotificationLaunchAppListener事件没关系

**Comment by huangminlinux** [comment]
#220  可以参考这个 issue

**Comment by davehandong** [comment]
就是说在iOS下面，如果应用关了确实就不会执行addReceiveOpenNotificationListener了是吗？

**Comment by davehandong** [comment]
按照#220的办法设置context-avilable就好了！！！
