### ISSUE TITLE
请问为何现在集成IOS会报错呀？

### ISSUE THREAD

**Issue by chujian** [jpush/jpush-react-native#339]
试着换了好多的版本,都是有错误，错误各不相同，现在是0.47.2 

Undefined symbols for architecture x86_64:
  "_JCOREDisplayVersion", referenced from:
      +[JPUSHService commonSetupWithOption:appKey:channel:apsForProduction:advertisingIdentifier:] in libRCTJPushModule.a(JPUSHService.o)
  "_JCOREGetBuildVersion", referenced from:
      +[JPUSHService commonSetupWithOption:appKey:channel:apsForProduction:advertisingIdentifier:] in libRCTJPushModule.a(JPUSHService.o)
  "_kJPFNetworkDidCloseNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
      -[RCTJPushModule reactJSDidload] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidLoginNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
      -[RCTJPushModule reactJSDidload] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidReceiveMessageNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidRegisterNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidSetupNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkIsConnectingNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by huangminlinux** [comment]
jcore  link  成功没？

**Comment by chujian** [comment]
默认装了以后jcore-react-native  是1.1.8-beta  但node_modules 目录下的jpush-react-native 下的ios 目录，并没有xxx.xcodeproj文件，只有一个libjcroe-ios.a 和 version_1.1.52个文件

**Comment by chujian** [comment]
执行react-native link 后，xcode里面没发现有jcore库

**Comment by huangminlinux** [comment]
建议卸载 jcore-react-native 重装。
jcore-react- 新版本应该是有个工程文件的
https://github.com/jpush/jcore-react-native/tree/dev/ios

**Comment by huangminlinux** [comment]
@chujian  link 有提示成功了吗？
失败就手动 link。

**Comment by chujian** [comment]
@huangminlinux  原来beta版本是没有工程文件的，我指定1.1.8就可以了，现在编译通过了，谢谢

**Comment by yangyj1358** [comment]
我也遇到这个问题了，但是解决了！
1、按照官网的文档 执行link后，RCTJPushModule和RCTJCoreModule并没有自动添加到library文件夹下，所以我就通过addfile的方法，找到这两个文件的.xcodeproj文件手动添加了；
2、然后就查看build phases--》Link binary with libraries里面是否包含libRCTJPushModule.a和libRCTJCoreModule.a,此处必须注意！！！网上给的截图只看到添加了libRCTJPushModule.a，如果此处不添加libRCTJCoreModule.a必然会报错！！！
3、如上操作后就能正常运行了~
