### ISSUE TITLE
安卓版本将appkey放在node_modules里配置是否有所不妥

### ISSUE THREAD

**Issue by viix** [jpush/jpush-react-native#34]
node_modules可能会被删除，导致配置失效
我不懂安卓开发 是否有方法放在ios类似AppDelegate中 这样似乎比较好

**Comment by clh161** [comment]
同意
加上mode_modules不會放在git裡，設定放在mode_modules的話，設定就沒有存到git裡

**Comment by KenChoi1992** [comment]
安卓和 iOS 不一样，iOS 之所以把 AppKey 放到 AppDelegate 是因为JPush SDK 初始化需要带 AppKey，而安卓则不需要。

**Comment by clh161** [comment]
建議android 的appkey也在js裡面設定,因為node_module一般會立入.gitignore
這樣的話，appkey就沒有在git裡更新

**Comment by viix** [comment]
对的 或者考虑放到AndroidManifest.xml里？

**Comment by lotosbin** [comment]
我是将npm run configureJPush xxx 添加到 postinstall 里面了

**Comment by lotosbin** [comment]
@KenChoi1992 npm run configureJPush 更换appkey 执行的时候无效，appkey 没有更新
jpush-react-native@1.1.

**Comment by pannz** [comment]
安卓appKey配置在node_modules里面实在是厉害，使用node fs读写文件去修改config文件也是厉害啊

真是大开眼界啊。。。

**Comment by KenChoi1992** [comment]
@pannz  下个版本更新一下

**Comment by KenChoi1992** [comment]
版本已更新至 1.2.2， 修复了这个问题。
