### ISSUE TITLE
DEBUG模式下不报错 RELEASE模式下报链接错误 

### ISSUE THREAD

**Issue by jivi20029** [jpush/jpush-react-native#340]
DEBUG模式下不报错 RELEASE模式下报链接错误

**Comment by jivi20029** [comment]
![image](https://user-images.githubusercontent.com/1896572/29952702-b2284fd8-8efd-11e7-9e96-c7b4272e78ff.png)

**Comment by huangminlinux** [comment]
之前有人提过这个问题了， 可以参考这个 #104 。
