### ISSUE TITLE
iOS 监听不到ReceiveNotification事件，但是能收到通知

### ISSUE THREAD

**Issue by JamesWen1993** [jpush/jpush-react-native#343]
我debug了xcode发现有进入- (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger))completionHandler方法，但是就是收不到通知

`
    componentDidMount() {

 this.listener = RCTDeviceEventEmitter.addListener('isLogin', (value) => {
            this._load();
        });
        this._load();
        this._jpush();
    }

    _jpush(){

        RCTDeviceEventEmitter.addListener(
            'ReceiveNotification',
            (notification) => {
                console.log(notification);
                console.log(notification.aps.alert);
                this.setState({
                    messageDetail: notification.aps.alert,
                })
                alert(notification.aps.alert, '', [
                    {text: '取消', onPress: () => console.log('q'), style: 'default'},
                    {text: '确定', onPress: () => this.pushPage()},
                ]);
            }
        );
        var subscription2 = RCTDeviceEventEmitter.addListener(
            'networkDidReceiveMessage',
            (message) => {
                // alert("networkDidReceiveMessage");
                console.log(message)
            }
        );
        var subscription4 = RCTDeviceEventEmitter.addListener(
            'OpenNotification',
            (notification) => {
                console.log(notification)
                this.setState({
                    messageDetail: notification.aps.alert,
                })
                this.pushPage();

            }
        );

        var subscription3 = RCTDeviceEventEmitter.addListener(
            'OpenNotificationToLaunchApp',
            (notification) => {
                this.setState({
                    messageDetail: notification.aps.alert,
                })
                this.pushPage();
            }
        );

        JPushModule.setBadge(0, (badgeNumber) => {
            console.log(badgeNumber)
        });
    }
`

**Comment by huangminlinux** [comment]
需要应用在前台收到推送?

**Comment by huangminlinux** [comment]
#120 可以参考这个 issue

**Comment by JamesWen1993** [comment]
@huangminlinux 我加了参数，声音是有了，但是还是接受不到通知

**Comment by JamesWen1993** [comment]
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    if ([[UIDevice currentDevice].systemVersion floatValue] >= 10.0) {
 #ifdef NSFoundationVersionNumber_iOS_9_x_Max
    JPUSHRegisterEntity * entity = [[JPUSHRegisterEntity alloc] init];
      entity.types = UNAuthorizationOptionAlert|UNAuthorizationOptionBadge|UNAuthorizationOptionSound;
      [JPUSHService registerForRemoteNotificationConfig:entity delegate:self];
 
#endif
    } else if ([[UIDevice currentDevice].systemVersion floatValue] >= 8.0) {
      [JPUSHService registerForRemoteNotificationTypes:(UIUserNotificationTypeBadge |
                                                        UIUserNotificationTypeSound |
                                                        UIUserNotificationTypeAlert)
                                            categories:nil];
    }else {
      [JPUSHService registerForRemoteNotificationTypes:(UNAuthorizationOptionBadge |
                                                        UNAuthorizationOptionSound |
                                                        UNAuthorizationOptionAlert)
                                            categories:nil];
    }
  
  [JPUSHService setupWithOption:launchOptions appKey:@"xxxxxx"
                        channel:nil apsForProduction:false];
  
  
  
  NSURL *jsCodeLocation;
  
  jsCodeLocation = [NSURL URLWithString:@"http://192.168.1.106:8081/index.ios.bundle?platform=ios&dev=true"];
  
  //  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"newRuhr2"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
  
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  
  
  return YES;
}

**Comment by JamesWen1993** [comment]
- (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger))completionHandler {
 NSDictionary * userInfo = notification.request.content.userInfo;
 if([notification.request.trigger isKindOfClass:[UNPushNotificationTrigger class]]) {
 [JPUSHService handleRemoteNotification:userInfo];
 [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo];
    }
 completionHandler(UIUserNotificationTypeAlert | UIUserNotificationTypeSound | UIUserNotificationTypeBadge);


}

**Comment by huangminlinux** [comment]
什么系统， iOS 10 才提供了推送前台展示的能力，更早系统推送无法在前台展示。

**Comment by JamesWen1993** [comment]
iOS 10.3.0 我是重构了APP，之前的版本RN是0.3x是都是好的，重构后用了RN用了0.47，安卓端是好的，ios端JS监听不到任何通知事件

**Comment by JamesWen1993** [comment]
@huangminlinux 解决了，是通知冲突了

**Comment by Guodadada** [comment]
也遇到了同样的问题，通知冲突是什么意思？

**Comment by luojinghui** [comment]
@JamesWen1993 通知冲突是什么意思？

**Comment by GoldenForest** [comment]
@JamesWen1993 通知冲突是什么意思？
