### ISSUE TITLE
安卓还没搞，iOS目前能接收通知，但是接收不到“自定义消息”

### ISSUE THREAD

**Issue by jiexishede** [jpush/jpush-react-native#346]
ｉＯＳ　自定义消息。　官方后台接收不到消息啊。

**Comment by huangminlinux** [comment]
在官网中 自定义消息页面和推送消息页面不一样，确定发送的是自定义消息吗？

如果是后台，自定义消息有个额外的字段。

**Comment by jiexishede** [comment]
＠huangminlinux  https://community.jiguang.cn/t/rn-ios-jpush-react-native/20779

**Comment by jiexishede** [comment]
@huangminlinux 　我是发送的自定义消息啊。

**Comment by huangminlinux** [comment]
有可能是 jpush 依赖旧版本的 jcore 可能会出现这个问题，把 jpush 和 jcore 升级到最新版本试试。

jpush-react-native@2.0.6
jcore-react-native@1.1.8

**Comment by huangminlinux** [comment]
先关闭这个问题，如果问题还没解决可以重新打开
