### ISSUE TITLE
在安卓上推送消息，点击跳转到对应页面没用啊

### ISSUE THREAD

**Issue by yt7649757** [jpush/jpush-react-native#347]
按照最新的demo来写的，，，

jumpSecondActivity() {
		console.log("jump to SecondActivity");
		// JPushModule.jumpToPushActivityWithParams("SecondActivity", {
		// 	hello: "world"
		// });
		this.props.navigation.navigate("Push");
	}

JPushModule.addReceiveOpenNotificationListener((map) => {
			console.log("Opening notification!");
			console.log("map.extra: " + map.extras);
			this.jumpSecondActivity();
			// JPushModule.jumpToPushActivity("SecondActivity");
		});
函数都执行了，，，就是this.props.navigation.navigate("Push"); 跟没生效一样，，不知道怎么回事？

**Comment by yt7649757** [comment]
我是弄到自己的项目上去的，就不生效，，推送消息的能收到，就是点击跳转没效果，

**Comment by yt7649757** [comment]
主要是参照你那个最新的demo写的，，我的项目用的也是navigation,,,这些监听代码我是写在我的首页文件中，，， 我要跳转的页面也在路由文件中配置了，，，console.log("jump to SecondActivity");，这句话控制台打印了， this.props.navigation.navigate("我的文件") 就是这句代码貌似没生效。。;

**Comment by KenChoi1992** [comment]
demo 没有问题啊

**Comment by yt7649757** [comment]
核心代码就是 你在这个push_activity.js文件中写的吧！ 路由文件中还需要额外配置什么吗？？ 或者还少配置了什么？？？我主要就是拷贝的你这个文件中的代码，，其他的没管

**Comment by yt7649757** [comment]
//跳转到对应页面
    jumpToAssignActivity() {
        console.log("jump to AssignActivity");
        /*JPushModule.jumpToPushActivityWithParams("AssignActivity", {
        hello: "world"
        });*/
        console.log(this.props.navigation)
        this.props.navigation.navigate("Sign"); //暂固定跳转到，测试
    }

    // componentWillMount(){
    //     BackHandler.addEventListener('hardwareBackPress', this.onBackAndroid);
    // }
    //

    componentDidMount() {
        SplashScreen.hide();

        JPushModule.getInfo((map) => {
            this.setState({
                imei: map.myImei,
                deviceId: map.myDeviceId,
            });
        });

        JPushModule.notifyJSDidLoad((resultCode) => {
            if (resultCode === 0) {}
        });
        JPushModule.addReceiveCustomMsgListener((map) => {
            this.setState({
                pushMsg: map.message
            });
            console.log("extras: " + map.extras);
        });
        JPushModule.addReceiveNotificationListener((map) => {
            console.log("alertContent: " + map.alertContent);
            console.log("extras: " + map.extras);
            // var extra = JSON.parse(map.extras);
            // console.log(extra.key + ": " + extra.value);
        });
        JPushModule.addReceiveOpenNotificationListener((map) => {
            console.log("Opening notification!");
            console.log("map.extra: " + map.extras);
            this.jumpToAssignActivity();
            // JPushModule.jumpToPushActivity("SecondActivity");
        });
        JPushModule.addGetRegistrationIdListener((registrationId) => {
            console.log("Device register succeed, registrationId " + registrationId);
        });

        //init and get RegistrationID save to server db.
        JPushModule.initPush();
        JPushModule.getRegistrationID((registrationId) => {
            this.setState({
                registrationId: registrationId
            },()=>{
                // alert(this.state.registrationId)
            });
        });
    }

    componentWillUnmount() {
        //BackHandler.removeEventListener('hardwareBackPress', this.onBackAndroid);
        JPushModule.removeReceiveCustomMsgListener(receiveCustomMsgEvent);
        JPushModule.removeReceiveNotificationListener(receiveNotificationEvent);
        JPushModule.removeReceiveOpenNotificationListener(openNotificationEvent);
        JPushModule.removeGetRegistrationIdListener(getRegistrationIdEvent);
        console.log("Will clear all notifications");
        JPushModule.clearAllNotifications();
    }

**Comment by yt7649757** [comment]
boy,,,麻烦帮我看看，，我用到了就这一部分代码，，sign是我要跳转的页面

**Comment by yt7649757** [comment]
import React, {
    Component,
} from 'react';
import {
    Text,
    View,
    AsyncStorage,
    StyleSheet,
    ListView,
    Dimensions,
    Image,
    BackHandler,
    ToastAndroid,
} from 'react-native';


import  NavItem  from   '../components/NavItem'
import  IconData  from   '../constants/data'
import SplashScreen from 'react-native-splash-screen'
// import  ExitApp  from   '../utils/ExitApp'
import  Touch  from  '../components/Touch'
import {Carousel} from 'teaset'
import JPushModule from 'jpush-react-native';

const receiveCustomMsgEvent = "receivePushMsg";
const receiveNotificationEvent = "receiveNotification";
const openNotificationEvent = "openNotification";
const getRegistrationIdEvent = "getRegistrationId";

const _width = Dimensions.get('window').width

class  Menu  extends  Component {

    constructor(props){
        super(props)
        this.state = {
            users:'',
            imei: 'IMEI',
            deviceId: 'DeviceId',
            pushMsg: 'PushMessage',
            registrationId: 'registrationId',
        };
        this.jumpToAssignActivity = this.jumpToAssignActivity.bind(this);
    }

    //跳转到对应页面
    jumpToAssignActivity() {
        console.log("jump to AssignActivity");
        /*JPushModule.jumpToPushActivityWithParams("AssignActivity", {
        hello: "world"
        });*/
        console.log(this.props.navigation)
        this.props.navigation.navigate("Sign"); //暂固定跳转到，测试
    }

    // componentWillMount(){
    //     BackHandler.addEventListener('hardwareBackPress', this.onBackAndroid);
    // }
    //

    componentDidMount() {
        SplashScreen.hide();

        JPushModule.getInfo((map) => {
            this.setState({
                imei: map.myImei,
                deviceId: map.myDeviceId,
            });
        });

        JPushModule.notifyJSDidLoad((resultCode) => {
            if (resultCode === 0) {}
        });
        JPushModule.addReceiveCustomMsgListener((map) => {
            this.setState({
                pushMsg: map.message
            });
            console.log("extras: " + map.extras);
        });
        JPushModule.addReceiveNotificationListener((map) => {
            console.log("alertContent: " + map.alertContent);
            console.log("extras: " + map.extras);
            // var extra = JSON.parse(map.extras);
            // console.log(extra.key + ": " + extra.value);
        });
        JPushModule.addReceiveOpenNotificationListener((map) => {
            console.log("Opening notification!");
            console.log("map.extra: " + map.extras);
            this.jumpToAssignActivity();
            // JPushModule.jumpToPushActivity("SecondActivity");
        });
        JPushModule.addGetRegistrationIdListener((registrationId) => {
            console.log("Device register succeed, registrationId " + registrationId);
        });

        //init and get RegistrationID save to server db.
        JPushModule.initPush();
        JPushModule.getRegistrationID((registrationId) => {
            this.setState({
                registrationId: registrationId
            },()=>{
                // alert(this.state.registrationId)
            });
        });
    }

    componentWillUnmount() {
        //BackHandler.removeEventListener('hardwareBackPress', this.onBackAndroid);
        JPushModule.removeReceiveCustomMsgListener(receiveCustomMsgEvent);
        JPushModule.removeReceiveNotificationListener(receiveNotificationEvent);
        JPushModule.removeReceiveOpenNotificationListener(openNotificationEvent);
        JPushModule.removeGetRegistrationIdListener(getRegistrationIdEvent);
        console.log("Will clear all notifications");
        JPushModule.clearAllNotifications();
    }



    static navigationOptions = {
         // header: null
        headerTitle:'---',
        headerBackTitle:null,
        headerLeft:null,
        headerStyle: {
            backgroundColor:'#2e8ccb',
            elevation: 0,   //如果想去掉安卓导航条底部阴影,iOS下用shadowOpacity: 0。
            height:50,
        },
        headerTitleStyle: {  //设置导航条文字样式
            alignSelf:'center',  // 设置文字居中
            color: '#fff'
        },
    }

    // onBackAndroid = () => {
    //     //那么你的返回值就决定了是否要调用默认行为：true为不调用，false为调用
    //         if (this.lastBackPressed && this.lastBackPressed + 2000 >= Date.now()) {
    //             //最近2秒内按过back键，可以退出应用。
    //             return false
    //         }
    //         this.lastBackPressed = Date.now()
    //         ToastAndroid.show('再按一次退出应用', ToastAndroid.SHORT)
    //         return true;
    // }


    render() {
        return (
            <View style = {styles.box}>
                <Carousel style={{height: 150, width:_width}} control={true}>
                    <Image style={{width: _width, height: 150}} resizeMode='cover' source={require('../assets/images/swiper-1.jpg')} />
                    <Image style={{width: _width, height: 150}} resizeMode='cover' source={require('../assets/images/swiper-2.jpg')} />
                    <Image style={{width: _width, height: 150}} resizeMode='cover' source={require('../assets/images/swiper-3.jpg')} />
                </Carousel>
                <View>
                    <NavItem data = {IconData} nav = {this.props.navigation}></NavItem>
                </View>
            </View>
        )
    }


}


const styles = StyleSheet.create({
    box: {
        justifyContent:'flex-start',
        alignItems: 'flex-start',
        flex:1,
    }
})


export  default  Menu

**Comment by KenChoi1992** [comment]
@yt7649757 我在 native 也增加了代码，具体你看看 demo 的 SecondActivity 和 AndroidManifest

**Comment by yt7649757** [comment]
功能是好的，之前我跳转地址写错了，不过你这个支持退出app了还能收到通知吗？

**Comment by KenChoi1992** [comment]
@yt7649757 可以在我们社区里搜一下，有很多人的疑问跟你一样。https://community.jiguang.cn/
