### ISSUE TITLE
自定义消息的使用场景是什么哦？？

### ISSUE THREAD

**Issue by jiexishede** [jpush/jpush-react-native#348]
通知是让用户在没有前台运行ａｐｐ的情况下，通过保持长连接，给用户发送消息，促使用户打开ａｐｐ。　
这个自定义消息具体的应用，哪个大师，来指导下。　感谢大家。

**Comment by jiexishede** [comment]
我能看到通知的内容　和听到声音。　　发送一定消息的时候，完全没有提示啊。　


　只有我是使用　　　`　　      Alert.alert("addReceiveCustomMsgListener=======" +JSON.stringify( map.content))`
这个代码的时候才可以啊。　

应用在后台，　我打开应用的时候，发现收到了消息了。应用在前台时直接显示这个消息。

**Comment by huangminlinux** [comment]
应用没有启动的情况下，自定义消息有离线保存功能， 自定义消息对用户不可见，开发者可以做额外的业务操作。看自己的业务需求选择自定义消息还是推送。

**Comment by jiexishede** [comment]
@huangminlinux  谢谢。
