### ISSUE TITLE
收到自定义消息后点击打开extras为空，

### ISSUE THREAD

**Issue by RoarRain** [jpush/jpush-react-native#351]
Android
收到消息的监听方法 打印出来的 为 extras:"{"from":"JPush","module":"1"}"
但是点击消息打开后 extras:"{}"
iOS 点击开则没有extras字段
什么原因呢？

**Comment by huangminlinux** [comment]
iOS 和 android 不太一样
比如说
android ：
```
var module = notification.extras.module  
```
那在 iOS 上则是
```
var module = notification.module
```

**Comment by RoarRain** [comment]
谢谢~, 经鉴定 是后端写的问题.
