### ISSUE TITLE
安卓JPushModule.addReceiveNotificationListener方法没有调用，ios正常使用，要修改哪里？

### ISSUE THREAD

**Issue by qb1515751487** [jpush/jpush-react-native#354]
JPushModule.addReceiveNotificationListener((map) => {
            console.log("alertContent: " + map.alertContent);
            console.log("extras: " + map.extras);
            // var extra = JSON.parse(map.extras);
            // console.log(extra.key + ": " + extra.value);
        });

**Comment by qb1515751487** [comment]
我用的是"jpush-react-native": "^2.0.4",  "react-native": "0.44.3" 版本

**Comment by KenChoi1992** [comment]
@qb1515751487 
![image](https://user-images.githubusercontent.com/8196928/30629979-288469ba-9e11-11e7-9cd9-4a3e0b13292d.png)
这个写了吗？

**Comment by qb1515751487** [comment]
@KenChoi1992 
加上了就报undefined is not a function (evaluating 'cb(resultCode)')错误

**Comment by KenChoi1992** [comment]
@qb1515751487 重新 build 或者 cache clean 一下

**Comment by qq326646683** [comment]
undefined is not a function (evaluating 'cb(resultCode)')

**Comment by qq326646683** [comment]
请问具体怎么解决啊？ @KenChoi1992
