### ISSUE TITLE
apsForProduction: true not working

### ISSUE THREAD

**Issue by flavordaaave** [jpush/jpush-react-native#357]
### Environment:
- `react-native` version: 0.47.1
- `jpush-react-native` version: 2.0.8

In my `AppDelegate.m` file I'm initiating jpush like this:
```
[JPUSHService setupWithOption:launchOptions appKey:@"XXX" channel:nil apsForProduction:true];
```
and later ion my JS code I call `setupPush()` to request push permissions.

When using `apsForProduction:false` I get push messages that are sent through the development (iOS开发环境) environment from the jpush dashboard.
But when I change to `apsForProduction:true` I do NOT get any pushes that are sent through production (iOS生产环境) environment.

Strangly, when `apsForProduction:true` is set I still get pushes that are sent with development environment. So it seems that `apsForProduction` is always `false` and I can not change it. Am I issing something?

(I use the jpush dashboard to send messages and tried both, 证书 and Token authorization)

**Comment by huangminlinux** [comment]
Whether it is `apsForProduction:false` or `apsForProduction:true` if you build your code and run it with xcode directly，it alway development environment.

if you what to test production environment, you need archive code to ipa(Ad Hoc). and install the ipa to you device.
