### ISSUE TITLE
这个registrationId是根据设备自动生成的吗，每台手机上生成的都不一样

### ISSUE THREAD

**Issue by yt7649757** [jpush/jpush-react-native#358]
假如我一个账号在这一条手机上登录，，会生成对应的registrationId传给后台，然后后台根据这个值针对性对我这个手机推送消息，其它手机就收不到推送！
但是我把这个手机放到另外一台手机上，，再把registrationId传给后台（我每次进入页面都会重新获取这个registrationId值然后传给后台），，后台发推送，，怎么还是推给我之前的手机上了啊？

**Comment by KenChoi1992** [comment]
@yt7649757 https://docs.jiguang.cn/jpush/client/Android/android_api/#registrationid-api 看下 registrationId 的定义。

**Comment by yt7649757** [comment]
我还想再问一个问题， // 初始化 JPush
        JPushModule.initPush();
        // 恢复接收通知
        JPushModule.resumePush();
这两个方法调用成功后，在页面底部会默认自动弹出两个toast提示框，怎么取消掉啊？

**Comment by KenChoi1992** [comment]
@yt7649757 看一下文档，有说明的。
