### ISSUE TITLE
执行单元测试时，import JPushModule from "jpush-react-native" 会报错

### ISSUE THREAD

**Issue by pmavio** [jpush/jpush-react-native#359]
### Environment:

单元测试时，不管是所测试的js还是测试用的js，只要导入了“jpush-react-native”，即import JPushModule from "jpush-react-native"，执行测试npm test时就会报如下错误：

 FAIL  __tests__\actions\user.js
  ● Test suite failed to run

    **************************\node_modules\jpush-react-native\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import {
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runner/node_modules/jest-runtime/bui
ld/script_transformer.js:306:17)

去掉这一行import以及注释掉用到JPushModule的代码，再执行测试时可以正常通过。

希望能够得到解决问题的方向。

P.S 实际的真机运行没有问题。

**Comment by KenChoi1992** [comment]
@pmavio 看一下 index.js  的开头：
```
import {
	NativeModules,
	Platform,
	DeviceEventEmitter
} from 'react-native';
```
第一行没毛病吧

**Comment by pmavio** [comment]
@KenChoi1992 没毛病
不过我把index.js拷贝出来使用就没这问题了

**Comment by huangminlinux** [comment]
在 package.json 中加入配置项 

```
  "jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.js?$": "babel-jest"
    },
    "transformIgnorePatterns": [
      "!node_modules/react-runtime"
    ]
  }
```
