### ISSUE TITLE
reactnative 点击推送过来的消息，没有进回调通知执行跳转页面 急急急急

### ISSUE THREAD

**Issue by nigo995** [jpush/jpush-react-native#366]
## 你的运行环境

* 插件版本:2.0.4
* react-native 版本：0.46.4

两种接收通知的方法都使用过来 均没有反应，求大神解惑，
```
JPushModule.addReceiveOpenNotificationListener((map) => {
       
         if(this.state.talkmsg.length!=0){

             this.pushTraningMyMessage(this.state.talkmsg);
         }

     });


     subscription = NativeAppEventEmitter.addListener(
             'OpenNotification',
             (notification) => {
                 alert("跳转成功")
             }
         )
```

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by huangminlinux** [comment]
JPushModule.addReceiveOpenNotificationListener 接口需要 iOS 10+ 才有效，系统是 iOS 10+ 吗

**Comment by nigo995** [comment]
我的手机系统是ios10.3.3  也没有用啊
----- 原始邮件 -----
发件人：huangminlinux <notifications@github.com>
收件人：jpush/jpush-react-native <jpush-react-native@noreply.github.com>
抄送人：nigo995 <nalren_xia@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[jpush/jpush-react-native]_reactnative_点击推送过来的消息，没有进回调通知执行跳转页面_急急急急_(#366)
日期：2017年09月28日 09点39分

JPushModule.addReceiveOpenNotificationListener 接口需要 iOS 10+ 才有效，系统是 iOS 10+ 吗

&mdash;

**Comment by huangminlinux** [comment]
升级到最新版本试试，另外需要注意应用的状态，应用不同的状态需要监听不同的事件 https://github.com/jpush/jpush-react-native/blob/master/example/documents/common_problems.md#事件的解析
