### ISSUE TITLE
请问有推送的开关吗

### ISSUE THREAD

**Issue by MonkeyEatBanana** [jpush/jpush-react-native#369]
* 插件版本:  2.0.4
* react-native 版本：0.47.1
## 期望效果

有个开关，打开就可以接收推送，关闭就不能接收推送，
请问有打开和关闭的方法吗

**Comment by starsion** [comment]
[https://github.com/jpush/jpush-react-native/blob/master/example/documents/APIs.md](url)
initPush

Init JPush。Suggest invokes in MainActivity 's onCreate method：

JPushInterface.init(this);
stopPush

Stop push. Suggest invokes in MainActivity 's onStop method：

JPushInterface.onStop(this);
resumePush

Resume push. Suggest invokes in MainActivity 's onResume method：

JPushInterface.onResume(this);

不知道你说的是不是这个？

**Comment by KenChoi1992** [comment]
@MonkeyEatBanana 就是楼上说的

**Comment by WhereareUmylove** [comment]
没吊用
