### ISSUE TITLE
按照文档来配置编译不过

### ISSUE THREAD

**Issue by gooddaddy** [jpush/jpush-react-native#372]
Showing All Issues
  "_JCOREDisplayVersion", referenced from:

      ___92+[JPUSHService commonSetupWithOption:appKey:channel:apsForProduction:advertisingIdentifier:]_block_invoke in libRCTJPushModule.a(JPUSHService.o)

  "_JCOREGetBuildVersion", referenced from:

      ___92+[JPUSHService commonSetupWithOption:appKey:channel:apsForProduction:advertisingIdentifier:]_block_invoke in libRCTJPushModule.a(JPUSHService.o)

  "_JPUSHBase64", referenced from:

      -[JPUSHBadgeNumberReportRequest p_generateRequestHead] in libRCTJPushModule.a(JPUSHBadgeNumberReport.o)

  "_JPUSHConvertTokenDataToString", referenced from:

      -[JPUSHClientController updateDeviceToken:] in libRCTJPushModule.a(JPUSHClientController.o)

  "_JPUSHDecodeDataFromBuffer", referenced from:

      -[JPUSHAliasResponse initWithBuffer:length:] in libRCTJPushModule.a(JPUSHAliasOperation.o)

      -[JPUSHTagsResponse initWithBuffer:length:] in libRCTJPushModule.a(JPUSHTagsOperation.o)

  "_JPUSHGetCurrentTimestamp", referenced from:

      -[JPUSHTagAliasManagerController tagOperate:type:andCompletion:andSeq:] in libRCTJPushModule.a(JPUSHTagAliasManagerController.o)

      -[JPUSHTagAliasManagerController aliasOperate:type:andCompletion:andSeq:] in libRCTJPushModule.a(JPUSHTagAliasManagerController.o)

      -[JPUSHTagAliasManagerController handleServerUnavaiableResponseWith:andContent:] in libRCTJPushModule.a(JPUSHTagAliasManagerController.o)

      -[JPUSHTagAliasManagerController isFreezeReport] in libRCTJPushModule.a(JPUSHTagAliasManagerController.o)

      -[JPUSHTagAlias setTagAliasUsingCallback:] in libRCTJPushModule.a(JPUSHTagAlias.o)

  "_JPUSHJSONData", referenced from:

      -[JPUSHAliasRequest packData] in libRCTJPushModule.a(JPUSHAliasOperation.o)

      -[JPUSHTagsRequest packData] in libRCTJPushModule.a(JPUSHTagsOperation.o)

      -[JPUSHBadgeNumberReportRequest packetData] in libRCTJPushModule.a(JPUSHBadgeNumberReport.o)

      -[JPUSHSetTagAlias requestJsonData] in libRCTJPushModule.a(JPUSHSetTagAlias.o)

  "_JPUSHJSONObject", referenced from:

      -[JPUSHAliasResponse initWithBuffer:length:] in libRCTJPushModule.a(JPUSHAliasOperation.o)

      -[JPUSHTagsResponse initWithBuffer:length:] in libRCTJPushModule.a(JPUSHTagsOperation.o)

      -[JPUSHTagAlias doSetTagsAliasCallbackWithRetJson:] in libRCTJPushModule.a(JPUSHTagAlias.o)

  "_JPUSHStringHashingByMD5", referenced from:

      -[JPUSHBadgeNumberReportRequest p_generateRequestHead] in libRCTJPushModule.a(JPUSHBadgeNumberReport.o)

  "_OBJC_CLASS_$_JCOREClientController", referenced from:

      objc-class-ref in libRCTJPushModule.a(JPUSHSetTagAlias.o)

      objc-class-ref in libRCTJPushModule.a(JPUSHTagAlias.o)

**Comment by gooddaddy** [comment]
原来是我没有下载完jcore-react-native 导致的，估计是之前公司网络有问题。

**Comment by yangyj1358** [comment]
我也遇到相同的问题，但是我的插件下载都是完整的，就是编译的时候过不去，该怎么办？
