### ISSUE TITLE
自动安装报错

### ISSUE THREAD

**Issue by Geek-ch** [jpush/jpush-react-native#373]
请问下，执行了npm run configureJPush xxxxxx app
xxx是我的AppKey
然后就报错，没法自动安装，帮忙看下是什么原因，谢谢

##  环境 "react-native": "0.44.3", mac
 "jcore-react-native": "^1.1.8-beta2",
    "jpush-react-native": "^2.0.9",

报错这样的： 

chdeMac-mini:YSZ ch$ npm run configureJPush xxxxxx app

> yishenzhen@0.0.1 configureJPush /Users/ch/Git/YSZ
> node node_modules/jpush-react-native/JPushConfiguration.js "b89055f9f23ccafcc41b55b3" "app"

没有输入 moduleName, 将使用默认模块名： app
fs.js:955
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat '/Users/ch/Git/YSZ/ios/Pods/tingyunApp/nbs-newlens-ios-2.7.0/tingyunApp.framework/Resources'
    at Object.fs.statSync (fs.js:955:11)
    at eachFileSync (/Users/ch/Git/YSZ/node_modules/jpush-react-native/JPushConfiguration.js:208:17)
    at /Users/ch/Git/YSZ/node_modules/jpush-react-native/JPushConfiguration.js:216:4
    at Array.forEach (<anonymous>)
    at eachFileSync (/Users/ch/Git/YSZ/node_modules/jpush-react-native/JPushConfiguration.js:215:9)
    at /Users/ch/Git/YSZ/node_modules/jpush-react-native/JPushConfiguration.js:216:4
    at Array.forEach (<anonymous>)
    at eachFileSync (/Users/ch/Git/YSZ/node_modules/jpush-react-native/JPushConfiguration.js:215:9)
    at /Users/ch/Git/YSZ/node_modules/jpush-react-native/JPushConfiguration.js:216:4
    at Array.forEach (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yishenzhen@0.0.1 configureJPush: `node node_modules/jpush-react-native/JPushConfiguration.js "xxxxxx" "app"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yishenzhen@0.0.1 configureJPush script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ch/.npm/_logs/2017-10-12T09_20_33_919Z-debug.log
chdeMac-mini:YSZ ch$ npm run configureJPush b89055f9f23ccafcc41b55b3 app

**Comment by KenChoi1992** [comment]
@Geek-ch 自动安装的 ModuleName 是指 Android 这边的，默认是 app，若你的 rn 工程没修改的话，默认就行了。
