### ISSUE TITLE
ios端监听打开推送和收到推送的事件问题

### ISSUE THREAD

**Issue by chuhangyu** [jpush/jpush-react-native#374]
## 你的运行环境

* 插件版本:jpush-react-native@1.7.1
* react-native 版本：react-native@0.45.1 

## 期望效果

在ios端我使用NativeAppEventEmitter监听了 ReceiveNotification 和 OpenNotification两个事件，希望对接收到推送和打开推送进行不同的事件处理。
```
		NativeAppEventEmitter.addListener(
			'ReceiveNotification',
			(notification) => {
				console.warn('收到推送');
				console.warn(notification)
			}
		);
               NativeAppEventEmitter.addListener(
			'OpenNotification',
			(notification) => {
				console.warn('打开推送');
				console.warn(notification)
			}
		);
```

## 实际效果

但是实际上我在收到推送的时候不会触发ReceiveNotification这个事件，而是自动触发了OpenNotification这个事件，在点击推送的时候也会触发OpenNotification这个事件

**Comment by huangminlinux** [comment]
建议更新到最新版本。
