### ISSUE TITLE
"jpush-react-native": "^2.0.7", 安卓端其他正常，但是角标不显示了

### ISSUE THREAD

**Issue by thirteenthEyes** [jpush/jpush-react-native#376]
## 你的运行环境
"jpush-react-native": "^2.0.7"
"jcore-react-native": "^1.1.8-beta2",
* 插件版本:

* react-native 版本：
"react-native": "0.47.1",

## 期望效果

告诉我们你希望达到什么效果。

安卓角标以前都是可以正常显示

## 实际效果

告诉我们实际是什么效果。

安卓端不再有角标了

## 重现步骤

  1. ...
  2. ...
  3. ...
  4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by KenChoi1992** [comment]
@thirteenthEyes 角标我们没有提供，Android 系统提供的
