### ISSUE TITLE
ios 端应用未启动时，能收到消息，但是不走addOpenNotificationLaunchAppListener 回调。

### ISSUE THREAD

**Issue by Jiujiale** [jpush/jpush-react-native#379]
## 你的运行环境
macOS 10.12.6

* 插件版本:
    "jcore-react-native": "^1.1.8",
    "jpush-react-native": "^2.0.8",
* react-native 版本：0.44.3

## 期望效果
ios 端应用未启动时，点击消息能跳转（能走addOpenNotificationLaunchAppListener 回调）

## 实际效果
ios 端应用未启动时，能收到消息，但是不走addOpenNotificationLaunchAppListener 回调。

## 重现步骤

    componentWillMount(){
        if (IOS){
            JPushModule.addnetworkDidLoginListener(() => {
                log('极光sdk登录成功');
            });

            JPushModule.addConnectionChangeListener((result) => {
                if (result) {
                    log('网络已连接');
                } else {
                    log('网络已断开');
                }
            })

            JPushModule.addOpenNotificationLaunchAppListener((result) => {
                log('addOpenNotificationLaunchAppListener', 'the notification is :' + JSON.stringify(result))
                this._messageTodo(result);
            })

            JPushModule.addReceiveOpenNotificationListener((result) => {
                log('addReceiveOpenNotificationListener',JSON.stringify(result))
                this._messageTodo(result);
            })

            JPushModule.addReceiveNotificationListener((result) => {
                log('addReceiveNotificationListener',JSON.stringify(result))
            })
        }
    }

    componentWillUnmount(){
        if(IOS){
            DeviceEventEmitter.removeAllListeners();
            NativeAppEventEmitter.removeAllListeners();
            JPushModule.removeOpenNotificationLaunchAppEventListener();
        }else {
            JPushModule.clearAllNotifications();
        }
    }

**Comment by huangminlinux** [comment]
确保 `addOpenNotificationLaunchAppListener`  方法在事件触发之前调用， 

在 index 中试试有没有事件回调。

**Comment by Jiujiale** [comment]
我这个事件处理在 addOpenNotificationLaunchAppListener 回调内啊 this._messageTodo(result); ，肯定在后面的吧

**Comment by huangminlinux** [comment]
我指的是方法调用时间，不是回调时间。

**Comment by huangminlinux** [comment]
如果没有问题我先关闭这个 issue 如果还有问题可以重新打开

**Comment by jeffzing** [comment]
同样的，能收到通知，但是就是不走这个JPushModule.addOpenNotificationLaunchAppListener(block);

**Comment by mark5566** [comment]
> 同样的，能收到通知，但是就是不走这个JPushModule.addOpenNotificationLaunchAppListener(block);

same issue +1
