### ISSUE TITLE
有 swift 4 的集成文档吗

### ISSUE THREAD

**Issue by xwartz** [jpush/jpush-react-native#381]
## 你的运行环境

* 插件版本: 2.1.0
* react-native 版本：0.47.1

## 期望效果

告诉我们你希望达到什么效果。

希望有 swift 4 的集成文档

## 实际效果

告诉我们实际是什么效果。

还没有、

**Comment by huangminlinux** [comment]
该插件和 swift 关系不大， jpush 原生 SDK 在 swift4 版本中的用法会在 [jpush-swift-demo](https://github.com/jpush/jpush-swift-demo) 这个库中更新，近期会有跟新
