### ISSUE TITLE
添加极光推送后在android4.4环境下运行崩溃

### ISSUE THREAD

**Issue by ftb2010** [jpush/jpush-react-native#382]
## 你的运行环境

* 插件版本:"jcore-react-native": "^1.1.8-beta2",
    "jpush-react-native": "^2.1.0"

* react-native 版本：0.45.1

## 期望效果

告诉我们你希望达到什么效果。

安卓4.4能运行

## 实际效果

告诉我们实际是什么效果。

安卓4.4启动直接崩溃

## 重现步骤

  1.配置极光
  2.连接安卓4.4手机运行，直接闪退

## Debug logs

包括 Android 或 iOS 的日志：
到不了debug，直接崩溃

**Comment by KenChoi1992** [comment]
@ftb2010 刚刚用 4.4 的手机测试了一下，没毛病。

**Comment by ftb2010** [comment]
@KenChoi1992 能提供个demo吗？我这边RN0.45.1确实一打开就崩溃

**Comment by KenChoi1992** [comment]
@ftb2010 demo 就在 example 目录下呀

**Comment by KenChoi1992** [comment]
@ftb2010 没有回复就关闭了
