### ISSUE TITLE
关于sendLocalNotification的参数extra无限循环的问题

### ISSUE THREAD

**Issue by 349989153** [jpush/jpush-react-native#384]
看到https://github.com/jpush/jpush-react-native/pull/375
但是应该没有上到npm吧，什么时候上去呢？

另外有个疑惑，sendLocalNotification里面接收的extra参数类型应该是object，但是addReceiveOpenNotificationListener里面的extras参数类型又是string

既然如此，sendLocalNotification接收的参数搞成string不挺好的吗，还少个bug

**Comment by KenChoi1992** [comment]
@349989153 现在试试
