### ISSUE TITLE
不知名的报错，不知道怎么描述，直接上图

### ISSUE THREAD

**Issue by Sura-zm** [jpush/jpush-react-native#387]
## 你的运行环境

* 插件版本:2.1.1
* react-native 版本：0.4.3

## 期望效果

在ios下能正常运行

## 实际效果

ios下运行报错，所有配置都按GitHub上的来的

## 重现步骤

配置好后直接在Xcode中运行项目

## Debug logs

![image](https://user-images.githubusercontent.com/19429264/31985858-112a18b0-b92c-11e7-935a-a2ac4aa08636.png)

**Comment by huangminlinux** [comment]
jcore 成功 link 没？

**Comment by Sura-zm** [comment]
我是按网上说的手动link的，没看到关于jcore的link内容

**Comment by huangminlinux** [comment]
执行
```
npm install jcore-react-native --save
react-native link jcore-react-native
```

**Comment by Sura-zm** [comment]
而且官网的代码也没有关于link jcore的信息

**Comment by huangminlinux** [comment]
认真看配置部分，

**Comment by Sura-zm** [comment]
非常感谢，我终于运行起来了
