### ISSUE TITLE
将Android和iOS版获取RegistrationID的接口统一

### ISSUE THREAD

**Issue by RnMss** [jpush/jpush-react-native#392]
## 运行环境

* 插件版本: jpush-react-native@2.0.9
* 运行平台: Android

## 实际效果

Android版App安装后首次初始化JPush，只能用 `JPushModule.addGetRegistrationIdListener` 获取 RegistrationID，而 `JPushModule.getRegistrationID` 无效。

而后续运行该App，初始化JPush后，`JPushModule.addGetRegistrationIdListener` 的事件不再触发，而只能用 `JPushModule.getRegistrationID` 获取 RegistrationID。

## 建议

应该无论何时都允许统一使用 `JPushModule.getRegistrationID` 获取 RegistrationID。否则新人将会在这里耗费很多的时间。

伪代码：

```javascript
JPushModule.getRegistrationID_2 = function (callback) {
  if ( 已经注册设备 ) {
    JPushModule.getRegistrationID(callback);
  } else {
    JPushModule.addGetRegistrationIdListener(callback);
  }
}
```

**Comment by RnMss** [comment]
我现在只能手动进行如下封装：

```typescript
export class JPushAndroidNotificationService implements NotificationService {

    private regIdResolver: (s: string) => void = null;
    private regId = new Promise<string>((resolve, reject) => {
        this.regIdResolver = resolve; // Dirty Code!
    });

    constructor(public delegate: NotificationServiceEventHandler) {
        JPush.initPush();
        // 其他初始化操作 ...
        JPush.addGetRegistrationIdListener(this._didGetRegId);
        JPush.getRegistrationID(this._didGetRegId);
    }

    _didGetRegId = (regId) => {
        if (regId != "" && this.regIdResolver) {
            this.delegate.onRegister(regId);
            this.regIdResolver(regId);
            this.regIdResolver = null;
        }
    }

    getRegId(): Promise<string> {
        return this.regId;
    }
}
```

但我认为库应该封装好才对

**Comment by KenChoi1992** [comment]
@RnMss addGetRegistrationIdListener 只在刚启动 app 时，如果服务器返回了 registrationId 才会调用一次。而 getRegistrationID 在注册成功后才能拿到。这两者的时机不同，应该让开发者决定何时调用。

**Comment by RnMss** [comment]
@KenChoi1992  可是
1. 缺少文档。现在iOS版中已经是像我说的那样工作了，但Android却没有这样。而文档又没有说明，我也是经过多次实验以及大量的搜索才知道使用的方法。
2. 所谓库，作用就是封装，用户使用时，应该不关心registration的流程，只要得到这个registrationID就够了。
3. 如果两者真的有必要分开调用，那我个人认为也应该再提供一个统一的接口直接获得ID（个人认为把接口统一化比写文档的成本还要低）。

**Comment by KenChoi1992** [comment]
新版本统一使用 getRegistrationId
