### ISSUE TITLE
typeError   undefined is  not an object

### ISSUE THREAD

**Issue by AKMaS** [jpush/jpush-react-native#393]
## 你的运行环境

* 插件版本:jpush-react-native@2.1.3
* react-native 版本：0.49.3

## 期望效果
正常使用
 

## 实际效果
![Uploading WX20171110-173926.png…]()

##代码
componentDidMount() {

    if (Platform.OS === 'android') {
      JPushModule.notifyJSDidLoad((resultCode) => {
        console.log('11');
      });
    }

    JPushModule.addReceiveOpenNotificationListener((map) => {
      console.log("map.extra: " + map.extras);
      console.log("Opening notification!");
      JPushModule.jumpToPushActivity("SecondActivity");
    });
  }

**Comment by KenChoi1992** [comment]
@AKMaS 看不懂

**Comment by AKMaS** [comment]
我文档没明白，集成有问题。现在没问题了
