### ISSUE TITLE
开发者服务SDK问题

### ISSUE THREAD

**Issue by heart-bool** [jpush/jpush-react-native#394]
为啥我已经集成了 Jpush SDK 和 janalytics SDK, 也能够收到推送的情况下， 在统计页面却依然提示我 您还没有集成极光开发者服务SDK?  还是说 这个 开发者服务SDK 是另一个SDK？ @javenfang

**Comment by huangminlinux** [comment]
Jpush 和 janalytics Appkey 有保持一致吗？  janalytics 有调用 setup 方法吗？

**Comment by heart-bool** [comment]
遇到新问题 debug 没问题 打release包报错 

Warning: cn.jpush.android.c.a: can't find superclass or interface com.huawei.hms.api.HuaweiApiClient$ConnectionCallbacks
Warning: cn.jpush.android.c.a: can't find superclass or interface com.huawei.hms.api.HuaweiApiClient$OnConnectionFailedListener
Warning: cn.jpush.android.c.a$1: can't find superclass or interface com.huawei.hms.support.api.client.ResultCallback
Warning: cn.jpush.android.service.PluginHuaweiPlatformsReceiver: can't find superclass or interface com.huawei.hms.support.api.push.PushReceiver
Warning: cn.jpush.android.service.PluginMeizuPlatformsReceiver: can't find superclass or interface com.meizu.cloud.pushsdk.MzPushMessageReceiver
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find superclass or interface com.xiaomi.mipush.sdk.PushMessageReceiver
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.ConnectionResult
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiAvailability
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiClient
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiClient$Builder
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiClient$ConnectionCallbacks
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiClient$OnConnectionFailedListener
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.support.api.client.PendingResult
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.support.api.push.HuaweiPush
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.support.api.push.HuaweiPushApi
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.support.api.push.HuaweiPush
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.support.api.push.HuaweiPush
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.ConnectionResult
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiAvailability
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiAvailability
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiAvailability
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiClient
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiClient
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiClient$Builder
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiClient$Builder
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiClient$Builder
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiClient$Builder
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiClient$Builder
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.support.api.client.PendingResult
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.support.api.push.HuaweiPushApi
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.HuaweiApiClient
Warning: cn.jpush.android.c.a: can't find referenced class com.huawei.hms.api.ConnectionResult
Warning: cn.jpush.android.c.a$1: can't find referenced class com.huawei.hms.support.api.client.ResultCallback
Warning: cn.jpush.android.c.a$1: can't find referenced class com.huawei.hms.support.api.push.TokenResult
Warning: cn.jpush.android.c.a$1: can't find referenced class com.huawei.hms.support.api.client.ResultCallback
Warning: cn.jpush.android.c.a$1: can't find referenced class com.huawei.hms.support.api.push.TokenResult
Warning: cn.jpush.android.c.b: can't find referenced class com.huawei.hms.api.HuaweiApiClient
Warning: cn.jpush.android.c.b: can't find referenced class com.huawei.hms.api.HuaweiApiClient
Warning: cn.jpush.android.c.c: can't find referenced class com.huawei.hms.api.HuaweiApiClient
Warning: cn.jpush.android.c.c: can't find referenced class com.huawei.hms.api.HuaweiApiClient
Warning: cn.jpush.android.c.c: can't find referenced class com.huawei.hms.api.HuaweiApiClient
Warning: cn.jpush.android.c.c: can't find referenced class com.huawei.hms.api.HuaweiApiClient
Warning: cn.jpush.android.c.d: can't find referenced class com.meizu.cloud.pushsdk.PushManager
Warning: cn.jpush.android.c.d: can't find referenced class com.meizu.cloud.pushsdk.PushManager
Warning: cn.jpush.android.c.d: can't find referenced class com.meizu.cloud.pushsdk.PushManager
Warning: cn.jpush.android.c.i: can't find referenced class com.huawei.hms.support.api.push.HuaweiPush
Warning: cn.jpush.android.c.i: can't find referenced class com.xiaomi.mipush.sdk.MiPushClient
Warning: cn.jpush.android.c.i: can't find referenced class com.huawei.hms.support.api.push.HuaweiPush
Warning: cn.jpush.android.c.i: can't find referenced class com.xiaomi.mipush.sdk.MiPushClient
Warning: cn.jpush.android.c.j: can't find referenced class com.xiaomi.mipush.sdk.MiPushClient
Warning: cn.jpush.android.c.j: can't find referenced class com.xiaomi.mipush.sdk.MiPushClient
Warning: cn.jpush.android.c.j: can't find referenced class com.xiaomi.mipush.sdk.MiPushClient
Warning: cn.jpush.android.c.j: can't find referenced class com.xiaomi.mipush.sdk.MiPushClient
Warning: cn.jpush.android.c.j: can't find referenced class com.xiaomi.mipush.sdk.MiPushClient
Warning: cn.jpush.android.service.PluginHuaweiPlatformsReceiver: can't find referenced class com.huawei.hms.support.api.push.PushReceiver
Warning: cn.jpush.android.service.PluginHuaweiPlatformsReceiver: can't find referenced class com.huawei.hms.support.api.push.PushReceiver$Event
Warning: cn.jpush.android.service.PluginHuaweiPlatformsReceiver: can't find referenced class com.huawei.hms.support.api.push.PushReceiver$Event
Warning: cn.jpush.android.service.PluginHuaweiPlatformsReceiver: can't find referenced class com.huawei.hms.support.api.push.PushReceiver
Warning: cn.jpush.android.service.PluginHuaweiPlatformsReceiver: can't find referenced class com.huawei.hms.support.api.push.PushReceiver
Warning: cn.jpush.android.service.PluginHuaweiPlatformsReceiver: can't find referenced class com.huawei.hms.support.api.push.PushReceiver
Warning: cn.jpush.android.service.PluginHuaweiPlatformsReceiver: can't find referenced class com.huawei.hms.support.api.push.PushReceiver
Warning: cn.jpush.android.service.PluginHuaweiPlatformsReceiver: can't find referenced class com.huawei.hms.support.api.push.PushReceiver$Event
Warning: cn.jpush.android.service.PluginHuaweiPlatformsReceiver: can't find referenced class com.huawei.hms.support.api.push.PushReceiver$Event
Warning: cn.jpush.android.service.PluginHuaweiPlatformsReceiver: can't find referenced class com.huawei.hms.support.api.push.PushReceiver$Event
Warning: cn.jpush.android.service.PluginMeizuPlatformsReceiver: can't find referenced class com.meizu.cloud.pushsdk.MzPushMessageReceiver
Warning: cn.jpush.android.service.PluginMeizuPlatformsReceiver: can't find referenced class com.meizu.cloud.pushsdk.notification.PushNotificationBuilder
Warning: cn.jpush.android.service.PluginMeizuPlatformsReceiver: can't find referenced class com.meizu.cloud.pushsdk.platform.message.RegisterStatus
Warning: cn.jpush.android.service.PluginMeizuPlatformsReceiver: can't find referenced class com.meizu.cloud.pushsdk.MzPushMessageReceiver
Warning: cn.jpush.android.service.PluginMeizuPlatformsReceiver: can't find referenced class com.meizu.cloud.pushsdk.MzPushMessageReceiver
Warning: cn.jpush.android.service.PluginMeizuPlatformsReceiver: can't find referenced class com.meizu.cloud.pushsdk.notification.PushNotificationBuilder
Warning: cn.jpush.android.service.PluginMeizuPlatformsReceiver: can't find referenced class com.meizu.cloud.pushsdk.platform.message.RegisterStatus
Warning: cn.jpush.android.service.PluginMeizuPlatformsReceiver: can't find referenced class com.meizu.cloud.pushsdk.platform.message.PushSwitchStatus
Warning: cn.jpush.android.service.PluginMeizuPlatformsReceiver: can't find referenced class com.meizu.cloud.pushsdk.platform.message.RegisterStatus
Warning: cn.jpush.android.service.PluginMeizuPlatformsReceiver: can't find referenced class com.meizu.cloud.pushsdk.platform.message.UnRegisterStatus
Warning: cn.jpush.android.service.PluginMeizuPlatformsReceiver: can't find referenced class com.meizu.cloud.pushsdk.platform.message.SubTagsStatus
Warning: cn.jpush.android.service.PluginMeizuPlatformsReceiver: can't find referenced class com.meizu.cloud.pushsdk.platform.message.SubAliasStatus
Warning: cn.jpush.android.service.PluginMeizuPlatformsReceiver: can't find referenced class com.meizu.cloud.pushsdk.notification.PushNotificationBuilder
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.MiPushCommandMessage
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.MiPushMessage
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.PushMessageReceiver
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.MiPushCommandMessage
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.MiPushCommandMessage
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.MiPushCommandMessage
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.MiPushMessage
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.MiPushMessage
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.MiPushMessage
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.PushMessageReceiver
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.MiPushMessage
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.MiPushMessage
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.MiPushMessage
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.MiPushCommandMessage
Warning: cn.jpush.android.service.PluginXiaomiPlatformsReceiver: can't find referenced class com.xiaomi.mipush.sdk.MiPushCommandMessage

**Comment by heart-bool** [comment]
@huangminlinux

**Comment by KenChoi1992** [comment]
#397
