### ISSUE TITLE
添加对Android Studio 3.0的支持

### ISSUE THREAD

**Issue by qinly** [jpush/jpush-react-native#395]
## 你的运行环境

* 插件版本:
* react-native 版本：0.50

## 期望效果

升级Android Studio 3.0后相应的都进行了升级，jpush缺少依赖，需要在 build.gradle 添加 google()仓库

buildscript {
    repositories {
        // 新增此行
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
    }
}

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

 * What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:AndResGuardLocatorSevenZip'.
   > A problem occurred configuring project ':jpush-react-native'.
      > Could not resolve all files for configuration ':jpush-react-native:classpath'.
         > Could not find com.android.tools.build:gradle:3.0.0.
           Searched in the following locations:
               https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
               https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar
           Required by:
               project :jpush-react-native

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by KenChoi1992** [comment]
@qinly 在你的项目的 build.gradle 改一下就可以了
