### ISSUE TITLE
app在前台的时候如何点击推送打开url？

### ISSUE THREAD

**Issue by saigyouyou** [jpush/jpush-react-native#399]
## 你的运行环境

* 插件版本:
"jcore-react-native": "^1.2.2",
"jpush-react-native": "^2.1.3",
* react-native 版本：
"react-native": "0.48.3"

因为已经做了url调用app的设置，所以希望能点击推送的通知能直接打开url，这样可以直接跳转到对应的app页面。查了一下发现官网并没有类似的功能，全世界都在问怎么跳转到对应的页面。而富媒体url强制要求http://开头，而不能使用类似于myapp://的格式。

无奈之下只能修改JPushModule.java，但是我对java不是很熟，只能依样画葫芦。

在525行附近插入了代码
```
    Logger.d(TAG, "用户点击打开了通知");
    // 通知内容
    String alertContent = mCachedBundle.getString(JPushInterface.EXTRA_ALERT);
    // extra 字段的 json 字符串
    String extras = mCachedBundle.getString(JPushInterface.EXTRA_EXTRA);
    //打开链接
    try {
        JSONObject jo = new JSONObject(extras);
        String url = jo.getString("url");
        if (url != "") {
            Uri uri = Uri.parse(url);
            Intent i = new Intent(Intent.ACTION_VIEW, uri);
            i.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            context.startActivity(i);
        }
    } catch (Exception e) {
          e.printStackTrace();
    }
```
当app在关闭的时候点击能跳转到对应的页面，但是当app已经打开的时候点击无效，请问需要怎么改。总不见得在前台的时候再去js里面写一层路由控制吧。

ps: 希望能增加点击通知打开自定义url scheme的功能，mipush就有这个功能。

**Comment by KenChoi1992** [comment]
@saigyouyou 你的意思 app 在前台就不能打开页面了？

**Comment by saigyouyou** [comment]
@KenChoi1992 
一开始是这样的，后来我卸载了包重装之后好了。但还是希望能有点击通知打开url schemes的功能。
另外就是通知栏经常会显示搜索GPS，而实际上应用本身我们目前并不需要地域统计，甚至会给用户带来困扰，因此我把包里有关GPS权限的permission注释掉了，是否会影响其他功能的使用？

**Comment by KenChoi1992** [comment]
@saigyouyou 不会，可以前往[这里](https://docs.jiguang.cn/jpush/resources/)下载 Google Play 版本，然后替换 sdk。
