### ISSUE TITLE
 bug：最新版 setBadge getBadge方法调用 报类型转换错误

### ISSUE THREAD

**Issue by giantss** [jpush/jpush-react-native#404]
这是一个bug setBadge getBadge如果返回的是NSnumber就会报错
![50fcd7030cfb2eb347cca120b9cdb2fe](https://user-images.githubusercontent.com/13778798/33168732-eacbb4b8-d07c-11e7-9b9e-19978bdd8c22.jpg)

![image](https://user-images.githubusercontent.com/13778798/33168687-c0fc481e-d07c-11e7-9f73-391059dec06f.png)

**Comment by huangminlinux** [comment]
返回的是 number 类型， 不要做字符串的操作。

**Comment by giantss** [comment]
`//设置应用 badge 值`
    `setBadge = () => {`
        `JPushModule.setBadge(5, (success) => {`
           ` Alert.alert(success)`
        `});`
   ` };`

` Alert.alert(success)`是字符串操作啊？

**Comment by huangminlinux** [comment]
Alert.alert  这个方法的参数需要为 string ，可以看看这个接口的说明。

**Comment by giantss** [comment]
好吧 我复制demo里面的
