### ISSUE TITLE
ios 真机上运行报错

### ISSUE THREAD

**Issue by sunny20131314** [jpush/jpush-react-native#405]
## 运行环境

* 插件版本:
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "jcore-react-native": "1.2.1",
    "jpush-react-native": "2.1.3",

## 期望效果
在ios运行

## 实际效果
build 成功之后刚运行时：
报错如下：
![image](https://user-images.githubusercontent.com/13795567/33307471-396ccc94-d3dc-11e7-9fc5-323d5c5d2fe1.png)

## 重现步骤
  1、原安装jpush 1.6.0 版本，现因业务需求需升级为2.1.3版本， jcore 更新为1.2.1版本。
  2、react-native unlink jpush-react-native
  3、react-native link jpush-react-native， react-native link jcore-react-native
  4、模拟器上可运行，真机上运行报错

## Debug logs
2017-11-28 15:32:42.972 cc[317:47565] +[JCOREInterface pushConfigController]: unrecognized selector sent to class 0x100d971f8
2017-11-28 15:32:42.977 cc[317:47565] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[JCOREInterface pushConfigController]: unrecognized selector sent to class 0x100d971f8'
*** First throw call stack:
(0x1838aadb0 0x182f0ff80 0x1838b1b44 0x1838aebec 0x1837acc5c 0x100a24b84 0x1019d9a3c 0x1019da8b4 0x100a24aa0 0x100a24780 0x1000343d8 0x188a7e9c0 0x188cae184 0x188cb25f0 0x188caf764 0x18524b7ac 0x18524b618 0x18524b9c8 0x18386109c 0x183860b30 0x18385e830 0x183788c50 0x188a7794c 0x188a72088 0x1000352b4 0x1833268b8)
libc++abi.dylib: terminating with uncaught exception of type NSExceptio

**Comment by huangminlinux** [comment]
jcore 升级到最新版本 1.2.2 试试。

**Comment by sunny20131314** [comment]
恩，升级后可以了...  建议文档更新下
