### ISSUE TITLE
iOS版本有没有停止推送和恢复推送的接口？

### ISSUE THREAD

**Issue by Geek-ch** [jpush/jpush-react-native#406]
目前有安卓的推送开关，请问iOS的有吗？在api里面没有找到

JPushModule.stopPush;
JPushModule.resumePush;

**Comment by huangminlinux** [comment]
iOS 没有提供这种借口。

**Comment by Geek-ch** [comment]
@huangminlinux 那这个是iOS本身不支持，还是说极光目前的版本不支持，之后有可能推出呢？

**Comment by huangminlinux** [comment]
iOS 本身不支持。

**Comment by lvao813** [comment]
额，我好想在别的方法里面看到过这个功能啊，具体看这里
https://github.com/zo0r/react-native-push-notification

**Comment by huangminlinux** [comment]
ok 我参考一下，下个版本加上。

**Comment by huangminlinux** [comment]
可以升级到  [2.1.6](https://github.com/jpush/jpush-react-native/releases/tag/2.1.6) 版本
stopPush 停用推送。
setupPush 恢复推送。

**Comment by Geek-ch** [comment]
好的,感谢
