### ISSUE TITLE
ios11真机上 clearAllLocalNotifications方法无效

### ISSUE THREAD

**Issue by sunny20131314** [jpush/jpush-react-native#407]
## 你的运行环境

* 插件版本:
 "react": "16.0.0-alpha.12",
 "react-native": "0.45.1",
 "jcore-react-native": "1.2.2",
 "jpush-react-native": "2.1.3",

## 期望效果
调用该方法时，清除所有调用sendLocalNotification方法展示的通知

## 实际效果
在ios11系统真机上调用无效果。

## 重现步骤
代码如下：
import {
  Alert,
  PushNotificationIOS,
  NativeModules,
  NativeAppEventEmitter,
} from 'react-native';
const JPushNative = NativeModules.JPushModule;

// 展示通知调用
JPushNative.sendLocalNotification({
        buildId: 1,
        id: 1,
        title: 'aaa',
        content: '您正在使用本应用录音～～～',
        extra: {data: 1})},
        fireTime: Date.now() + 3000,
        badge: 0,
      });

//随后调用
JPushNative.clearAllLocalNotifications()；

## Debug logs
无

**Comment by huangminlinux** [comment]
调用 setBadge 接口，将 badge 值设为 0,就可以清除通知栏上的通知。

**Comment by huangminlinux** [comment]
iOS 还没支持这个方法，下个版本中加上该接口。

**Comment by huangminlinux** [comment]
可以升级到  [2.1.6](https://github.com/jpush/jpush-react-native/releases/tag/2.1.6) 版本
