### ISSUE TITLE
大量手机 RegistrationID 获取失败 

### ISSUE THREAD

**Issue by bianbiandashen** [jpush/jpush-react-native#409]
JPushModule.getRegistrationID((registerId) => {
         
        });
这个方法调用了 但是获取不到 为啥呢  有些手机
ios 是要在JPush.addnetworkDidLoginListener这个的回调 后面 处理这个问题吗？
那么 android呢

**Comment by KenChoi1992** [comment]
@bianbiandashen 要确保第一时间调用了 notifyJSDidLoad

**Comment by KenChoi1992** [comment]
@bianbiandashen 这个问题没有回复先关闭了。

**Comment by shopshow** [comment]
iOS 此问题比较严重

**Comment by xwartz** [comment]
iOS 使用 addnetworkDidLoginListener 接口之后，获取有改善吗？ @bianbiandashen @shopshow
