### ISSUE TITLE
集成问题

### ISSUE THREAD

**Issue by panhs** [jpush/jpush-react-native#410]
集成完以後沒有收到消息，集成的時候沒有執行npm run configureJPush，而直接执行了link，后面单独执行npm run configureJPush，没有成功过 一直报没有匹配到 然后一直卡住
## 你的运行环境
mac10.13.1- wbstorm201.2.3
* 插件版本:最新
* react-native 版本：0.50.4

## 期望效果

正常收到消息

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

  1. ...
  2. ...
  3. ...
  4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by KenChoi1992** [comment]
@panhs 看看文档手动配置部分
