### ISSUE TITLE
iOS通知权限申请怎么写

### ISSUE THREAD

**Issue by showtan001** [jpush/jpush-react-native#412]
老铁     通知的权限申请怎么写   我ios不会     谢了

**Comment by huangminlinux** [comment]
https://github.com/jpush/jpush-react-native/blob/master/example/documents/APIs_zh.md#setuppush

**Comment by showtan** [comment]
不是这，我意思是怎么编辑开启通知权限 
![Uploading D2CB1417093EF3F679AA5DC4EFD7FEFB.png…]()

**Comment by showtan** [comment]
例如开启访问相机是    <key>NSCameraUsageDescription</key>
	                           <string>APP需要使用你的相机</string>

**Comment by showtan** [comment]
`<key>NSCameraUsageDescription</key>
	<string>APP需要使用你的相机</string>`

**Comment by huangminlinux** [comment]
建议看第一条 https://www.jianshu.com/p/f4651157eb18

**Comment by showtan** [comment]
老哥 我集成android sdk 用jcenter 自动集成不行 如下
:app:generateBundledResourcesHashDebug
4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945
                                                                 :app:processDeb
ugManifest 97% > :app:processDebugManifest
[cn.jiguang.sdk:jpush:3.0.3] D:\project\cbor_app_dczl\android\app\build\intermed
iates\exploded-aar\cn.jiguang.sdk\jpush\3.0.3\AndroidManifest.xml:123:13-45 Erro
r:
     Attribute meta-data#JPUSH_CHANNEL@value at [cn.jiguang.sdk:jpush:3.0.3] And
roidManifest.xml:123:13-45 requires a placeholder substitution but no value for
<JPUSH_CHANNEL> is provided.
> Building 97% > :app:processDebugManifest
See http://g.co/androidstudio/manifest-merger for more information about the man
ifest merger.

D:\project\cbor_app_dczl\android\app\src\main\AndroidManifest.xml Error:
       Attribute meta-data#JPUSH_CHANNEL@value at AndroidManifest.xml requires a
 placeholder substitution but no value for <JPUSH_CHANNEL> is provided.
> Building 97% > :app:processDebugManifest
See http://g.co/androidstudio/manifest-merger for more information about the man
ifest merger.

:app:processDebugManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#JPUSH_CHANNEL@value at AndroidMan
ifest.xml requires a placeholder substitution but no value for <JPUSH_CHANNEL> i
s provided.

**Comment by KenChoi1992** [comment]
@showtan001 老哥，看看 ReadMe
