### ISSUE TITLE
客户端没有用户注册怎么解决？

### ISSUE THREAD

**Issue by DIVIBEAR** [jpush/jpush-react-native#413]
## 你的运行环境
* 插件版本:
* react-native 版本：
0.51.0

## 期望效果
我想收到推送消息

## 实际效果

没有满足条件的推送目标
如果是群发：则此应用还没有一个客户端用户注册。请检查 SDK 集成是否正常。
如果是推送给某别名或者标签：则此别名或者标签还没有在任何客户端SDK提交设置成功。
如果是根据 Registration ID 推送：则此 Registration ID 不存在。

## 重现步骤
我在安卓真机上测试。
我在输出台打印出的init信息，我也在入口页的设置了
![image](https://user-images.githubusercontent.com/22066302/34412445-2e6f326a-ec18-11e7-99ab-04888b041df4.png)

![image](https://user-images.githubusercontent.com/22066302/34412474-5ebc3d28-ec18-11e7-8898-88004097fbea.png)

**Comment by Chenfyuan** [comment]
我也遇到这个问题，好烦

**Comment by KenChoi1992** [comment]
https://community.jiguang.cn/t/register-failed-with-server-error-code-1008/23881/13 估计服务端注册有点问题，稍后跟进一下。

**Comment by jwkiller** [comment]
我也遇到这个问题
