### ISSUE TITLE
react-native JPushModule.setTags报错

### ISSUE THREAD

**Issue by Chenfyuan** [jpush/jpush-react-native#415]
## 你的运行环境

* 插件版本: "jcore-react-native": "^1.2.2",
                   "jpush-react-native": "^2.1.6",
* react-native 版本：0.41.2

## 期望效果

成功设置标签

## 实际效果
调用JPushModule.setTags后报错
官方文档的api说明如下:
#### setTags

- setTags(tags, callback)

  - tags:  [String] tag 集合
    - 每次调用至少设置一个 tag
    - 有效的标签组成：字母（区分大小写）、数字、下划线、汉字。
    - 限制：每个 tag 命名长度限制为 40 字节，最多支持设置 1000 个 tag，但总长度不得超过5K字节。（判断长度需采用UTF-8编码）
    - 单个设备最多支持设置 1000 个 tag。App 全局 tag 数量无限制

  ```javascript
  JPushModule.setTags(['tag1','tag2'], (success) => {})
  ```
我项目代码直接copy如上代码
 ```javascript
  JPushModule.setTags(['tag1','tag2'], (success) => {})
  ```

实际react-native红屏报错
Attempt to invoke virtual method 'java.lang.Object
java.util.HashMap.put(java.lang.Object,java.lang.object)' on a null object reference

**Comment by KarlStony** [comment]
遇到一样的问题，现象与[https://github.com/jpush/jpush-react-native/issues/309](https://github.com/jpush/jpush-react-native/issues/309)一样。
不过问题只出现在reload之后，初次打开app不会有这个问题

**Comment by KenChoi1992** [comment]
@Chenfyuan 是必现的 bug 吗？我的测试环境是
- 插件版本: "jcore-react-native": "^1.2.2",
 "jpush-react-native": "^2.1.6",
- react-native 版本：0.49.2
没有出现这个问题。

**Comment by KenChoi1992** [comment]
@KarlStony @Chenfyuan  看下上面的提交，解决了这个问题。

**Comment by KarlStony** [comment]
@KenChoi1992  这边试了下，确实可以了:thumbsup:

**Comment by sapjax** [comment]
@KenChoi1992   最新的版本是多少，2.1.6 貌似没有变化。

**Comment by sapjax** [comment]
https://github.com/jpush/jpush-react-native/issues/295

**Comment by KenChoi1992** [comment]
@sapjax  发布了 2.1.7

**Comment by sapjax** [comment]
@thanks !!!

**Comment by andyhuai** [comment]
这个问题解决了没有?
更新到2.1.7还是有这个问题,android,rn 0.51
