### ISSUE TITLE
推送一条通知会多次调用addReceiveNotificationListener的问题

### ISSUE THREAD

**Issue by Eggplant-Cui** [jpush/jpush-react-native#417]
## 你的运行环境
ios真机version9.0
* 插件版本:2.1.3
* react-native 版本：0.47.1

## 期望效果

逻辑只执行一遍

## 实际效果

如果app在前台，是只执行一遍的
如果app切到了后台，从顶部点击回到app界面，逻辑就执行了两边
锁屏状态下也一样，点击消息解锁屏幕后，回到app界面，逻辑执行了两边

整段注册删除listener代码都是按照说明写的，而且都是从我上一个项目中照搬的
上一个项目没有类似问题
区别是上一个项目注册的地方是首页，是一个页面
本项目是一个tab页面
请问什么原因会导致这种情况

## 重现步骤

  1. ...
  2. ...
  3. ...
  4. ...

## Debug logs

包括 Android 或 iOS 的日志：
推送因为没有开发证书只能用真机和正式包调试

**Comment by huangminlinux** [comment]
检查逻辑，是否存在重复调用  JPushModule.addReceiveNotificationListener 方法的可能。

**Comment by Eggplant-Cui** [comment]
只在componentDidMount中注册的listener，并且也断点检查过，没有执行两边的情况，另外在android上是没有这个问题的

**Comment by hnliyuan** [comment]
我的问题相似，IOS端推送的时候加上content-available 就执行两次addReceiveNotificationListener 
 不加只执行一次

**Comment by huangminlinux** [comment]
iOS 9：如果开启了 backgroup mode 在应用不在前台会收到一个 ReceiveNotification，如果用户点击了该条推送会再调用一次 ReceiveNotification 方法（由于 iOS 9 没有提供 openNotification 的事件），接收和点击是走同一个事件，且这两个 _j_msgid 一致。
如果需要处理一次，可以通过 _j_msgid 来过滤不想要的推送。

如果是 iOS 10+ 的话，不再前台接收推送会触发 ReceiveNotification 事件回调，点击推送会触发 openNotification 事件。

**Comment by zoujunda** [comment]
Android也存在这个问题。首页componentDidMount里注册的监听，componentWillUnmount 把所有监听都移除了，且确定移除方法执行了。切换用户操作，登录、首页来回切换，首页进入几次，addReceiveNotificationListener就会执行几次。应该是移除方法无效导致。2.1.7版本

**Comment by huangminlinux** [comment]
检查一下代码 addReceiveNotificationListener 添加的 function 不能重复添加。

**Comment by SurfeeS** [comment]
JPushModule.removeReceiveCustomMsgListener();
    JPushModule.removeReceiveNotificationListener();
    JPushModule.removeReceiveOpenNotificationListener();
    JPushModule.removeOpenNotificationLaunchAppEventListener();
    JPushModule.clearAllNotifications();



在unmount里执行了上述方法，还是会受到推送

**Comment by JoshLipan** [comment]
@SurfeeS 你是想不接收推送吗，调用JPushModule.stopPush();

**Comment by zoujunda** [comment]
已经解决了。按照样例中的移除写法是不行的，看了下源码，这样写就行了：
const receiveNotification = (message) => {
          //你的处理
        .....
｝

registJPushHandler = ( ) => {
            JPushModule.addReceiveNotificationListener(receiveNotification);
    }

 removeJPushHandler = () => {
        JPushModule.removeReceiveNotificationListener(receiveNotification)
    }

**Comment by SurfeeS** [comment]
@zoujunda 这么写也还是不行啊

**Comment by SurfeeS** [comment]
@JoshLipan  确实如此。

调用了JPushModule.stopPush(); 之后 ，要想再获得推送，还得执行JPushModule.resumePush();
