### ISSUE TITLE
React-native android setAlias()报错,HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by andyhuai** [jpush/jpush-react-native#418]
## 你的运行环境

* 插件版本: 2.1.7
* react-native 版本：0.51

## 期望效果

正确设置

## 实际效果

无法设置

## 重现步骤

setAlias(alias) {
    console.log("set alias succeed:" + alias);
    if (alias!== undefined) {
      JPushModule.setAlias(alias, (map) => {
        if (map.errorCode === 0) {
          console.log("set alias succeed:" + alias);
        } else {
          console.log("set alias failed, errorCode: " + map.errorCode);
        }
      })
    }
  }

## Debug logs

包括 Android 或 iOS 的日志：
Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference
setAlias
    JPushModule.java:307
invoke
    Method.java
invoke
    JavaMethodWrapper.java:374
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:154
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:761

**Comment by contineu0818** [comment]
@andyhuai 我也遇到了这个问题，请问你是怎么解决的呀？

**Comment by andyhuai** [comment]
@contineu0818 升级一下最新版,然后清理缓存,就好了

**Comment by contineu0818** [comment]
@andyhuai 解决了
