### ISSUE TITLE
ios clearNotificationById 清除顶部通知栏通知失败

### ISSUE THREAD

**Issue by fadeli1** [jpush/jpush-react-native#419]
## 你的运行环境
ios 11.2.1 手机

* 插件版本:
"jcore-react-native": "^1.2.2",
"jpush-react-native": "^2.1.6",

* react-native 版本：
"react-native": "0.46.4",

## 期望效果

期望应用内调用clearNotificationById清除顶部通知栏通知

## 实际效果

应用内调用clearNotificationById清除顶部通知栏通知失败

## 重现步骤

  1. 应用能正常收到任何通知
  2. api后台发送通知
  3. 应用内分别得到通知的_j_uid和_j_msgid参数
  4. 应用内部尝试用_j_uid或_j_msgid参数，调用clearNotificationById，清除顶部通知栏通知失败
  5. 尝试调用clearAllNotifications，清除所有顶部通知栏通知，也失败了

**Comment by fadeli1** [comment]
ios是不是没有清除顶部通知栏通知的方法？

**Comment by fadeli1** [comment]
iios 中推送消息到手机后，应用图标上没有角标，但是顶部通知栏有相应的消息出现

**Comment by fadeli1** [comment]
我可能找到原因?
测试发现：web版发送通知，应用图标角标会+1，api发送通知，应用图标角标未+1
会不会是这个的原因呢？

**Comment by huangminlinux** [comment]
api 发送推送的时候 badge 参数是多少？

**Comment by fadeli1** [comment]
@huangminlinux 
api发送的时候，没有设置badge，看文档说是会自动+1，实际测试下来，并没有。
后续api设置了badge，当应用打开的时候时，应用图标上的badge没有显示，当应用关闭时，应用图标上的badge是成功的。
后续继续测试了官网web发送推送消息，也无法在应用内调用clearNotificationById来清除顶部通知栏的消息。

**Comment by huangminlinux** [comment]
iOS 需要通过 setbadge 这个接口 将badge 设为 0 来清除。

**Comment by fadeli1** [comment]
@huangminlinux  恩，待会我试试，那如何准确清除某一条通知了？

**Comment by fadeli1** [comment]
刚才在issues看到api可以传递badge="+1"这种操作，我试试，貌似可以解决自动+1的问题
