### ISSUE TITLE
Android中app返回到桌面（app未退出）情况下点击通知无法打开app，

### ISSUE THREAD

**Issue by codelixin** [jpush/jpush-react-native#421]
## 你的运行环境

* 插件版本:最新版
* react-native 版本：0.51

## 期望效果
app返回到桌面（app未退出）情况下点击通知打开app并跳转到指定页面，

## 实际效果
在QQ或其他应用界面点击通知可以实现跳转到App并导航到指定页面，但是点击返回到手机桌面之后（应用未退出），可以接收到推送，但点击推送后无法自动打开app

## 重现步骤

  1. 导航，初始化加载PushActivity
const PushDemoApp = StackNavigator({
    Home: {
        screen: PushActivity,
        navigationOptions:{
            header:null,
        }
    },
    Setting: {
        screen: SetActivity,
        navigationOptions:{
            header:null,
        }
    },
    Message:{
        screen: Message,
        navigationOptions:{
            header:null,
        }
    }
})
  2. PushActivity组件添加监听
    componentDidMount() {
        //必须加上的方法
        JPushModule.notifyJSDidLoad((resultCode) => {
        });
        //监听自定义内容
        JPushModule.addReceiveCustomMsgListener((map) => {
        });
        //收到通知触发的方法
        JPushModule.addReceiveNotificationListener((map) => {
        });
        //点击App通知触发的事件
        JPushModule.addReceiveOpenNotificationListener((map) => {
            this.props.navigation.navigate("Message");
        });
    }
  3.卸载相关监听  
componentWillUnmount() {
        JPushModule.removeReceiveCustomMsgListener(receiveCustomMsgEvent);
        JPushModule.removeReceiveNotificationListener(receiveNotificationEvent);
        JPushModule.removeReceiveOpenNotificationListener(openNotificationEvent);
        JPushModule.removeGetRegistrationIdListener(getRegistrationIdEvent);
        JPushModule.clearAllNotifications();
    }
  4. 后台调用API 通知可达，在app内点击通知或在其他app界面点击通知均可以跳转到指定界面，
但是点击返回到手机桌面之后（应用未退出），可以接收到推送，但点击推送后无法自动打开app

**Comment by KenChoi1992** [comment]
@codelixin 不要在某个页面的 componentWillUnmount 中调用 removeReceiveOpenNotificationListener，而是在应用退出后再调用。

**Comment by rongxiangcai** [comment]
我也遇到了这样的问题，谁有解决方案吗，我一直解决不了这个问题

**Comment by codelixin** [comment]
@KenChoi1992 这样做还是没有用
@rongxiangcai 暂时还没有解决

**Comment by panhs** [comment]
@codelixin 我这边也出现有时候不能收到回调  但是有时候又可以  很奇怪
