### ISSUE TITLE
ios 本地通知sendLocalNotification   

### ISSUE THREAD

**Issue by yoonzm** [jpush/jpush-react-native#422]
## 你的运行环境

* 插件版本:
* react-native 版本：

    "react-native": "0.51.0"

## 期望效果

告诉我们你希望达到什么效果。

sendLocalNotification 调用结果可以正常通知

## 实际效果

告诉我们实际是什么效果。

Xcode一直提示如下，设置无效：
JIGUANG | E - [JIGUANGLocalNotificationController] 请设置有效的触发推送方式，region、dateComponents、timeInterval对其中一个属性设置有效值即可

## 重现步骤

  1. ...
  2. ...
  3. ...
  4. ...

## Debug logs

包括 Android 或 iOS 的日志：
JIGUANG | E - [JIGUANGLocalNotificationController] 请设置有效的触发推送方式，region、dateComponents、timeInterval对其中一个属性设置有效值即可

并且调用setLocalNotification 无震动和声音，请问setLocalNotification只能触发应用内的通知吗 App在后台运行时调用此方法手机不会收到通知？

**Comment by huangminlinux** [comment]
提供一下调用代码， 和具体传的参数。

**Comment by codelixin** [comment]
看看你手机是否开启相关通知权限，还有调用sendLocalNotification 方法传入参数是否正确。
 var notification = {
		 	buildId: 1,
			id: 5,
			title: 'jpush',
			content: 'This is a test!!!!',
			extra: {
		 		key1: 'value1',
				key2: 'value2'
			},
			fireTime: 2000,
		 }
JPushModule.sendLocalNotification(notification);

**Comment by yoonzm** [comment]
/**
     * 本地通知
     * @param id
     * @param title
     * @param content
     * @param badge ios小红点数字
     */
    sendLocalNotification(id, title, content, badge) {
        JPushModule.sendLocalNotification({
            id,
            buildId: 1,
            title,
            content,
            extra: {},
            fireTime: new Date().getTime(),
        });
        if (Platform.OS === 'ios') {
            JPushModule.setLocalNotification(new Date(new Date().getTime() + 200), content, -1, '', '', {}, null);
        }
    }

这是我之前在收到自定义消息后调用的方法,检查了很多次,传参应该没有什么问题

比较关注的问题主要为ios端app前台运行的情况下收到自定义消息,调用此方法后会显示通知提醒,但是没有铃声和震动  也尝试启用新项目测试 同样的问题

**Comment by yoonzm** [comment]
目前已没有使用自定义消息了,全部改为通知消息实现了,所以也没有深究.

**Comment by Yinlujia** [comment]
sendLocalNotification ios11.2.0测试 没有声音没有震动，希望可以更新下，

**Comment by y00rb** [comment]
同样的问题， 最新的版本。
在真机开发环境中，使用如下代码进行测试，android可以发送local notification。但是iOS不工作，并且在xcode的console中显示一下error信息。
![image](https://user-images.githubusercontent.com/444876/37442038-35ebd616-283f-11e8-9c86-be3961d4666d.png)
<img width="450" alt="image" src="https://user-images.githubusercontent.com/444876/37442052-4c0aeaea-283f-11e8-99de-e08db7890a91.png">

**Comment by huangminlinux** [comment]
参考 https://github.com/jpush/jpush-react-native/blob/master/documents/api_en.md#sendlocalnotification

**Comment by y00rb** [comment]
Works! 我之前是按照example的代码写的，example的代码有问题--firetime只在android下工作。

**Comment by iamsee** [comment]
同样的错误，请问怎么解决的

**Comment by iamsee** [comment]
@y00rb  请问下你是怎么解决ios下这个问题的

**Comment by niuniubuniu** [comment]
@y00rb 请问解决了么 我也遇到这个问题了

**Comment by y00rb** [comment]
@niuniubuniu 
<img width="877" alt="image" src="https://user-images.githubusercontent.com/444876/43149562-486df504-8f9a-11e8-8049-fb7a0de724f7.png">
<img width="989" alt="image" src="https://user-images.githubusercontent.com/444876/43149569-4c794112-8f9a-11e8-87d3-8824884995df.png">

**Comment by huangminlinux** [comment]
一个 js 层获取的时间，一个 原生层获取的时间，肯定是 js 获取的时间早啊。

**Comment by niuniubuniu** [comment]
@huangminlinux 可是这个时间间隔59s就有点大了 ，我考虑到调用先后会有时间差，所以用(new Date()).getTime()+3000 ，依然不行的， 安卓的ok的  ；而且 interval为0 不会触发本地通知的； 我手动设置为1 就可以
