### ISSUE TITLE
点击通知事件回调和获取消息回调没有用

### ISSUE THREAD

**Issue by showtan** [jpush/jpush-react-native#424]
## 你的运行环境  ios

* 插件版本: jpush 2.1.6 jcore 1.2.2
* react-native 版本：0.49.3

## 期望效果
我点击通知消息获得回调，消息回调信息处理。
代码(放在启动页里面)
‘//获取点击通知事件
            NativeAppEventEmitter.addListener(
                'OpenNotification',
                (notification) => {
                console.log(notification)
                JPushModule.setBadge(0, (badgeNumber) => {
                    console.log(badgeNumber);
                })
                }
            );
//回调获取通知
            NativeAppEventEmitter.addListener(
                'ReceiveNotification',
                (notification) => console.log(notification)
            );
’

## 实际效果
回调获取通知没有获取
点击通知消息什么都没有,logo的角标的number也还是1  没去掉

谢谢！

**Comment by showtan** [comment]
@huangminlinux    那ios跟android一样了？

**Comment by huangminlinux** [comment]
具体哪个方法是通用的要参考文档
https://github.com/jpush/jpush-react-native/blob/master/example/documents/APIs_zh.md

**Comment by panhs** [comment]
@huangminlinux 打不开

**Comment by huangminlinux** [comment]
https://github.com/jpush/jpush-react-native/blob/master/documents/api.md
