### ISSUE TITLE
使用最新版遇到的问题.

### ISSUE THREAD

**Issue by GG526** [jpush/jpush-react-native#425]
CRASH: -[Swift._NSContiguousString jmsg_checkAppKeyValidWithUpdate]: unrecognized selector sent to instance 0x608000249930

**Comment by GG526** [comment]
#define JMESSAGE_VERSION @"3.4.1"

**Comment by GG526** [comment]
这个crash报错是因为去掉Other Linker Flags中-ObjC, 如果加上就会报错.

**Comment by GG526** [comment]
语言是Swift4.

**Comment by GG526** [comment]
去掉Other Linker Flags中-ObjC报错, 因为jpush-extension-ios-1.0.0这个库.我在项目中删除掉这个库就可以编译成功.

**Comment by huangminlinux** [comment]
集成方式是什么，用的是 jpush-react-native 这个插件？

**Comment by GG526** [comment]
直接引用的库文件, 没有用 jpush-react-native.

**Comment by huangminlinux** [comment]
同一个 target 中 jpush-extension-ios-xxx 和 jpush-ios-xxx 只能留一个。

应该 swift 语言版本没有关系。 用这个项目（swift4）可以正常使用 https://github.com/jpush/jpush-swift-demo

**Comment by GG526** [comment]
OK

**Comment by GG526** [comment]
谢谢!
