### ISSUE TITLE
app退出但不杀死进程 无法收到通知

### ISSUE THREAD

**Issue by panhs** [jpush/jpush-react-native#426]
## 你的运行环境

* 插件版本:
* react-native 版本：
0.50.+

## 期望效果
可以收到消息

## 实际效果

不能收到消息

**Comment by huangminlinux** [comment]
iOS 还是 android？

**Comment by panhs** [comment]
android的还有问题 , ios的也有已经解决了

**Comment by KenChoi1992** [comment]
@panhs 退出后不要调用 stopPush

**Comment by KenChoi1992** [comment]
没有回复的话就关闭了。

**Comment by Natuka** [comment]
目前也遇到同样的问题
