### ISSUE TITLE
有在APP中自定义开关消息通知的方法吗？就是类似其他APP关闭消息通知一样

### ISSUE THREAD

**Issue by showtan** [jpush/jpush-react-native#427]
老铁！给个方法呀  急用  谢谢

**Comment by huangminlinux** [comment]
关闭推送
https://github.com/jpush/jpush-react-native/blob/master/example/documents/APIs.md#stoppush

开启
iOS：https://github.com/jpush/jpush-react-native/blob/master/example/documents/APIs.md#setuppush
android： https://github.com/jpush/jpush-react-native/blob/master/example/documents/APIs.md#resumepush

**Comment by showtan** [comment]
不会原生安卓   跟 ios   开启该怎么写
