### ISSUE TITLE
集成最新版本后无法在真机运行程序

### ISSUE THREAD

**Issue by wjm117** [jpush/jpush-react-native#429]
## 你的运行环境
 iOS
* 插件版本:

为了兼容iphonex今天升级推送，由原来的   
"jcore-react-native": "^1.1.8",
 "jpush-react-native": "^2.0.4",
升级到：
"jcore-react-native": "^1.2.0",
 "jpush-react-native": "2.1.6"

安装后手动配置
* react-native 版本：
"react-native": "^0.44.3",
"react": "16.0.0-alpha.6",

## 期望效果

程序正常运行

## 实际效果

卡在loading图那里了，Xcode报错如下截图
![image](https://user-images.githubusercontent.com/20735485/35089032-a7192ae6-fc70-11e7-830e-94abe75585e6.png)

## 重现步骤

didFinishLaunchingWithOptions中极光推送代码如图：
![image](https://user-images.githubusercontent.com/20735485/35089130-f8377cca-fc70-11e7-8842-eab6a0160b84.png)

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by zerotalk** [comment]
把didFinishLaunchingWithOptions中的代码改成下面的试试
JPUSHRegisterEntity * entity = [[JPUSHRegisterEntity alloc] init];
  entity.types = UNAuthorizationOptionAlert|UNAuthorizationOptionBadge|UNAuthorizationOptionSound;
  [JPUSHService registerForRemoteNotificationConfig:entity delegate:self];
  
  [JPUSHService setupWithOption:launchOptions appKey:JPUSH_APP_KEY
                        channel:JPUSH_CHANNEL apsForProduction:JPUSH_PRODUCTION];

**Comment by huangminlinux** [comment]
jcore 和 jpush 版本要匹配， 试试将 jcore-react-native 和 jpush-react-native 升级到最新版。
