### ISSUE TITLE
npm run configureJPush 报错

### ISSUE THREAD

**Issue by cnzhangxl** [jpush/jpush-react-native#431]
## 你的运行环境
* 插件版本:
    "jcore-react-native": "^1.2.3",
    "jpush-react-native": "^2.1.7",
* react-native 版本：
     "react-native": "0.51.0",

## 期望效果

告诉我们你希望达到什么效果。

npm run configureJPush cc0edc57e6c7170a0cxxx   正常执行

## 实际效果

告诉我们实际是什么效果。
     

npm run configureJPush cc0edc57e6c717xxxxxxxx

> my_app@0.0.1 configureJPush /Users/xxx/sites/self/my_app
> node node_modules/jpush-react-native/JPushConfiguration.js "cc0edc57e6c717xxxxxxxx"

没有输入 moduleName, 将使用默认模块名： app
the file is appdelegate:/Users/xxx/sites/self/my_app/ios/build/Index/DataStore/v5/records/8P/AppDelegate.m-2VZCO27OAI78P
没有匹配到 didFinishLaunchingWithOptions,将自动插入改方法
IDX:xxxx一堆乱码

有匹配到 函数 didRegisterForRemoteNotificationsWithDeviceToken,将自动插入改方法
没有匹配到 函数 didReceiveRemoteNotification,将自动插入改方法
没有匹配到 函数 didReceiveRemoteNotification fetchCompletionHandler,将自动插入改方法
没有匹配到 函数 willPresentNotification,将自动插入改方法
没有匹配到 函数 didReceiveRemoteNotification,将自动插入改方法
没有匹配到 函数 didReceiveLocalNotification,将自动插入改方法
the file is appdelegate:/Users/xxx/sites/self/my_app/ios/my_app/AppDelegate.m
没有匹配到 函数 didRegisterForRemoteNotificationsWithDeviceToken,将自动插入改方法
没有匹配到 函数 didReceiveRemoteNotification,将自动插入改方法
没有匹配到 函数 didReceiveRemoteNotification fetchCompletionHandler,将自动插入改方法
没有匹配到 函数 willPresentNotification,将自动插入改方法
没有匹配到 函数 didReceiveRemoteNotification,将自动插入改方法
没有匹配到 函数 didReceiveLocalNotification,将自动插入改方法
find build.gradle in android project /Users/xxx/sites/self/my_app/android/app/build.gradle
Configure appKey error, should configure manually.
find build.gradle in android project /Users/xxx/sites/self/my_app/android/build.gradle
Did not find "compile" in path: /Users/xxx/sites/self/my_app/android/build.gradle
Configure appKey error, should configure manually.
find settings.gradle in android project /Users/xxx/sites/self/my_app/android/settings.gradle

## 重现步骤

  1.npm install jpush-react-native --save
  2.npm install jcore-react-native --save
  3.npm run configureJPush cc0edc57e6c7170xxx
 

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by huangminlinux** [comment]
iOS: 检查 Appdelegate.m 的代码是否已经自动加入[相关代码](https://github.com/jpush/jpush-react-native/blob/master/example/documents/iOS_Usage.md)

**Comment by KenChoi1992** [comment]
@cnzhangxl 按照手动的步骤检查一下

**Comment by KenChoi1992** [comment]
@cnzhangxl 新版本修复了这个问题。
