### ISSUE TITLE
ios   集成jspush编译报错

### ISSUE THREAD

**Issue by shiios** [jpush/jpush-react-native#435]
## 你的运行环境

* 插件版本: "jcore-react-native": "^1.1.7",
    "jpush-react-native": "^2.0.1",
* react-native 版本："react-native": "0.43.4",

## 期望效果

告诉我们你希望达到什么效果。
编译通过不报错

## 实际效果

告诉我们实际是什么效果。

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -ljcore-ios
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -ljcore-ios is not an object file (not allowed in a library)

## 重现步骤

  1. ...command + b 编译报错
  2. ...
  3. ...
  4. ...

## Debug logs

包括 Android 或 iOS 的日志：
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -ljcore-ios
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -ljcore-ios is not an object file (not allowed in a library)

**Comment by huangminlinux** [comment]
jcore-react-native 有 link 成功吗？

**Comment by koangel** [comment]
我目前也是，有link

**Comment by koangel** [comment]
d: library not found for -ljpush-ios-3.0.7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by koangel** [comment]
解決了，重新link一次就好了
