### ISSUE TITLE
[Android]app未启动时，点击通知栏消息，能够打开app，但无法获取到消息内容

### ISSUE THREAD

**Issue by hstarorg** [jpush/jpush-react-native#443]
## 你的运行环境

* Android版本：Android 6.0
* 插件版本:2.1.9
* react-native 版本：0.52.1

## 期望效果

app未启动时，点击通知栏消息，能够打开app，**并能获取到消息内容**

## 实际效果

app未启动时，点击通知栏消息，能够打开app，**但无法获取到消息内容，**

## 重现步骤

1. 注册的事件有 `addReceiveNotificationListener, addOpenNotificationLaunchAppListener` 也已经保证调用了 `initPush`
2. 关闭App
3. 发送一条通知，并点击
4. 此时app被唤醒，但是不会触发1中注册的两个事件，会触发：`notifyJSDidLoadAndroid`

**注意：环境受限，未测试iOS**

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by KenChoi1992** [comment]
@hstarorg addOpenNotificationLaunchAppListener 是 iOS 的方法。你要调用 addReceiveOpenNotificationListener

**Comment by hstarorg** [comment]
`addReceiveOpenNotificationListener` 这个事件在点击通知栏消息的时候能够触发（需要App开启状态）。如果App未启动时，点击消息，只能打开app，并不能触发这个事件。

**Comment by KenChoi1992** [comment]
@hstarorg 刚刚用 demo 测试过了，可以触发这个事件。

**Comment by hstarorg** [comment]
能提供下Demo代码么？感谢。

**Comment by KenChoi1992** [comment]
@hstarorg 看看 example

**Comment by hstarorg** [comment]
I'll try it, thanks.

**Comment by hstarorg** [comment]
Invalid issue, succeed when execute notifyJSDidLoad before register events.
