### ISSUE TITLE
IOSAPP退到后台运行或者锁屏状态下时,语音不会播报

### ISSUE THREAD

**Issue by hnliyuan** [jpush/jpush-react-native#444]
## 你的运行环境

* 插件版本:
"jcore-react-native": "1.2.2",
"jpush-react-native": "^2.1.3",
* react-native 版本：		
"react-native": "0.51.0",

## 期望效果
 Android 前台会执行addReceiveNotificationListener的回调
 Android 在“后台运行”或者“锁屏”会执行addReceiveNotificationListener的回调

## 实际效果
 IOS 前台会执行addReceiveNotificationListener的回调
 IOS 在“后台运行”或者“锁屏” 不会执行任何回调

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by beSmallFish** [comment]
遇到一样的问题 最后怎么解决的啊？
