### ISSUE TITLE
苹果审核被拒，ipv6环境下获取不到RegistrationID

### ISSUE THREAD

**Issue by yoyo0427** [jpush/jpush-react-native#447]
## 你的运行环境

* 插件版本:
 "jcore-react-native": "^1.2.2"
 "jpush-react-native": "^2.1.3"

* react-native 版本：0.44.3

## 期望效果

在ipv6环境下获取RegistrationID

## 实际效果

我现在在登录页面获取RegistrationID（登录的参数之一），正常测试都没有问题都可以获取，但是在苹果商店提交审核却被拒绝了，原因是获取不到RegistrationID，登录不了app

## 重现步骤

1. login.js
`componentDidMount() {
        JPushModule.getRegistrationID((id)=>{
            // alert(id);
            console.log(id);
            this.state = {
                registrationID:id
            };
        });
}`
2.
![default](https://user-images.githubusercontent.com/12933263/35665186-e9fb9ee4-075f-11e8-9aff-33d212874de6.png)

3. 审核出现的问题
![default](https://user-images.githubusercontent.com/12933263/35665250-459dad50-0760-11e8-85f0-0e1efda83ab5.png)

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by huangminlinux** [comment]
社区上提了一个和你相同的问题可以到那边跟进。https://community.jiguang.cn/t/ios10-ipv6/8867/8
