### ISSUE TITLE
Alias 删除报错

### ISSUE THREAD

**Issue by llkss** [jpush/jpush-react-native#448]
## 你的运行环境
Mac
* 插件版本:
* react-native 版本：0.51

## 期望效果
调用JPushModule.deleteAlias删除Alias

## 实际效果
报了一个 cb is not a function的错误
告诉我们实际是什么效果。

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by huangminlinux** [comment]
提供调用代码。

**Comment by hstarorg** [comment]
怀疑是你的deleteAlias用法问题。
