### ISSUE TITLE
去不掉 iOS 应用上的角标，也就是变为 0。

### ISSUE THREAD

**Issue by longmingfeng** [jpush/jpush-react-native#449]
## 你的运行环境

* 插件版本:
* react-native 版本：0.44.3

## 期望效果

去掉IOS应用上的角标

## 实际效果

去不掉，一直是1

## 重现步骤

**Comment by huangminlinux** [comment]
可以调用 setBadge(0) 这个接口

**Comment by longmingfeng** [comment]
this.ReceiveNotification = NativeAppEventEmitter.addListener(
            'ReceiveNotification',
            (notification) => {
                console.log("content: " + JSON.stringify(notification));
                JPushModule.setBadge(0, (badgeNumber) => {
                    console.log(badgeNumber)
                });
            }
        );

        this.OpenNotification = NativeAppEventEmitter.addListener(
            'OpenNotification',
            (notification) => {
                console.log("content: " + JSON.stringify(notification));
                JPushModule.setBadge(0, (badgeNumber) => {
                    console.log(badgeNumber)
                });
            }
        );
我就是这样调用的，没反应

**Comment by huangminlinux** [comment]
安装的插件版本是多少？

**Comment by longmingfeng** [comment]
刚发现，如果是群发的，就没法清空，如果按别名去清空，就可以了

**Comment by xwartz** [comment]
@longmingfeng   请问你是怎么解决的？如何按照别名去清空
