### ISSUE TITLE
Error Code: 6003

### ISSUE THREAD

**Issue by MQZhangThu** [jpush/jpush-react-native#45]
已按照要求配置，提示 init success后，提示 'Error Code 6003'. 请问什么原因？

**Comment by MQZhangThu** [comment]
注释掉 JPushModule.setAlias 就好了。但是getRegistrationID的结果是空。

**Comment by KenChoi1992** [comment]
@MQZhangThu 有没有日志打印？

**Comment by MQZhangThu** [comment]
我已找到问题所在：我用的dependencies是com.android.tools.build:gradle: 1.2.3，获取registrationId也为空，用2.1.0貌似就可以。但是有一个严重的问题，gradle 2.1.0在很多手机上会安装失败，这是一个[已知的issue](https://github.com/facebook/react-native/issues/2720)，RN官方也推荐出现该问题，降低为1.2.3。所以JPush是否有计划兼容gradle 1.2.3。

**Comment by KenChoi1992** [comment]
@MQZhangThu 看了一下这个issue，发现并不是只要将 Gradle 版本降到1.2.3就能解决问题，可能是还要考虑手机版本的问题，如果是这样的话这个适配性的问题就比较复杂了。Gradle 2.1.0导致在很多手机上安装失败的问题我目前没有遇到过（测试过三星，华为，小米，魅族等手机）。如果真的出现了安装问题，修改各自的 Gradle 版本号或许是一个开销较小的改动，毕竟如果降级到 1.2.3，或许别人也会出现安装不了的问题。

**Comment by MQZhangThu** [comment]
我在魅族m2手机上测试出现无法安装，而且奇怪的是release打包也无法成功。但是在三星手机上安装成功。对于RN，Gradle 1.2.3的适配性好过2.1.0，原因未知。详情[点这里](http://facebook.github.io/react-native/releases/0.33/docs/troubleshooting.html#shell-command-unresponsive-exception)。对于RN + Gradle 1.2.3，基本上大部分手机都能安装。

**Comment by MQZhangThu** [comment]
不清楚为什么这个plugin对于Gradle 1.2.3获取到的registrationId会是空，难道是有什么依赖？如果能去除对特定gradle版本的依赖，就能解决这个问题了。

**Comment by pampang** [comment]
目前正在使用jpush-react-native: v1.1.8，在安卓下同样无法获取得到registrationID，是否有其他方法获取得到？

**Comment by KenChoi1992** [comment]
@pampang  获取 registrationID 要联网，可能需要多次获取才能成功。

**Comment by KenChoi1992** [comment]
@MQZhangThu  关于 plugin 对于 Gradle 版本依赖的问题，我不太清楚。我测试 Gradle 1.5.0 和 2.1.0 都可以正常安装以及获取 registrationID。
