### ISSUE TITLE
CI 报错，提示找不到 .travis.yml

### ISSUE THREAD

**Issue by arniu** [jpush/jpush-react-native#450]
## 你的运行环境

* 插件版本: none
* react-native 版本：none

## 期望效果

CI 能够正常运行

## 实际效果

Could not find .travis.yml, using standard configuration.
mode of ‘/usr/local/clang-5.0.0/bin’ changed from 0777 (rwxrwxrwx) to 0775 (rwxrwxr-x)
...

## 重现步骤

正常提交触发测试即可

## Debug logs

CI 日志见 [Build #560](https://travis-ci.org/jpush/jpush-react-native/builds/336092711)

**Comment by arniu** [comment]
@javenfang @sunnylqm @baurine @messense @war22moon

**Comment by KenChoi1992** [comment]
删掉了
