### ISSUE TITLE
React Native 怎么统计页面

### ISSUE THREAD

**Issue by ysq1051838264** [jpush/jpush-react-native#451]
## 你的运行环境

* 插件版本:none 
* react-native 版本：
"jcore-react-native": "^1.2.5",
		"jpush-react-native": "^2.1.10",
		"react": "16.0.0-alpha.6",
		"react-native": "0.44.0",

## 期望效果

告诉我们你希望达到什么效果。

## 实际效果
用react 可以统计页面

**Comment by KenChoi1992** [comment]
@ysq1051838264 https://github.com/jpush/janalytics-react-native
