### ISSUE TITLE
react-native 0.52.2 按官方文档集成无法收到消息

### ISSUE THREAD

**Issue by seavman** [jpush/jpush-react-native#453]
## 你的运行环境
安卓
* 插件版本:
* react-native 版本：0.52.2

## 期望效果
按照正常集成，能够正常收到后台发送的信息

## 实际效果
所有步骤严格按照文档集成，无法收到消息，后台告警如下：
如果是群发：则此应用还没有一个客户端用户注册。请检查 SDK 集成是否正常。
如果是推送给某别名或者标签：则此别名或者标签还没有在任何客户端SDK提交设置成功。
如果是根据 Registration ID 推送：则此 Registration ID 不存在。

## 重现步骤
按官方集成步骤集成
## Debug logs

包括 Android 或 iOS 的日志：
 E/JIGUANG-JCore: [AndroidUtil] AndroidManifest.xml missing required service: cn.jpush.android.service.PushService
 E/JIGUANG-JCore: [AndroidUtil] AndroidManifest.xml missing required service: cn.jpush.android.service.PushService
 E/JIGUANG-JCore: [AndroidUtil] AndroidManifest.xml missing required service: cn.jpush.android.service.PushService
 W/JIGUANG-JPush: [AndroidUtil] AndroidManifest.xml missing required service: cn.jpush.android.service.DaemonService
 E/JIGUANG-JPush: [AndroidUtil] AndroidManifest.xml missing required activity: cn.jpush.android.ui.PushActivity
 W/JIGUANG-JPush: [TagAliasOperator] onTagaliasTimeout error:Attempt to invoke virtual method 'java.lang.String java.lang.String.intern()' on a null object reference
 E/JIGUANG-JCore: [AndroidUtil] AndroidManifest.xml missing required service: cn.jpush.android.service.PushService
 E/JIGUANG-JCore: [AndroidUtil] AndroidManifest.xml missing required service: cn.jpush.android.service.PushService

**Comment by KenChoi1992** [comment]
@seavman 你 jcore 正确集成了吗？

**Comment by seavman** [comment]
就是查不出为啥jcore初始化会失败，老是提示missing required service:cn.jpush.android.service.PushService，AppId 和Key都确认过没问题，在安卓里面把日志打开也是报jcore init failed

**Comment by seavman** [comment]
等下我弄个干净的工程按照流程走一下看看，我怀疑是不是和集成的某个包冲突了

**Comment by KenChoi1992** [comment]
没有回复的话就关闭了。
