### ISSUE TITLE
Android通知栏不显示消息

### ISSUE THREAD

**Issue by amyliu1062** [jpush/jpush-react-native#457]
![image](https://user-images.githubusercontent.com/6679526/35966947-4eae3f78-0cfa-11e8-981b-f3f308be5bc8.png)
1. 发送通知：通知栏可以显示消息
2.自定义消息和富媒体消息：通知栏不显示消息，但是执行了addReceiveCustomMsgListener／addReceiveNotificationListener，是需要自己实现Notification？

**Comment by KenChoi1992** [comment]
@amyliu1062 需要自己实现。
