### ISSUE TITLE
android点击通知，会重启APP（addReceiveOpenNotificationListener）

### ISSUE THREAD

**Issue by andylidong** [jpush/jpush-react-native#460]
## 你的运行环境
mac 10.13.3
* 插件版本:
* react-native 版本：
    "jpush-react-native": "2.1.10",
    "react": "16.2.0",
    "react-native": "0.53.3",

## 实际效果
ios点击通知会收到数据，而Android并没有收到，addReceiveOpenNotificationListener，这个事件ios可以触发，而Android并没有触发，而且Android收到了通知，就是点击的时候有问题，APP会重新启动,又会触发init事件
![image](https://user-images.githubusercontent.com/18454971/36624699-addcec2e-194d-11e8-871f-a1b1eba405b4.png)

## 日志
![image](https://user-images.githubusercontent.com/18454971/36624676-2177df46-194d-11e8-8237-5c58571b9d58.png)

**Comment by KenChoi1992** [comment]
@andylidong 你的意思是进程没杀死的情况下重新启动了？

**Comment by andylidong** [comment]
是的

**Comment by KenChoi1992** [comment]
![image](https://user-images.githubusercontent.com/8196928/36624960-a7c06cb8-1951-11e8-8773-78d516bd65f7.png)

这是我的日志，可以参考一下 demo 的写法，可以看到点击通知并没有 init

**Comment by andylidong** [comment]
我是Jmessage发的消息，是不是这个导致的

**Comment by KenChoi1992** [comment]
跟这个没关系

**Comment by andylidong** [comment]
我刚才测试时候发现，发送通知是ok的，不会重新启动，而且接收到了消息，

**但是点击Jmessage发送的聊天通知的时候，就是重新启动APP（只有android会出现这个问题）**

**Comment by KenChoi1992** [comment]
JMessage 的通知跟 JPush 的通知不是一回事，点击通知走的回调不一样，你自己看看点击通知执行了什么逻辑。

**Comment by andylidong** [comment]
NotificationClickEvent这个事件来监听jmessage的通知信息，现在可以了

**Comment by andylidong** [comment]
谢谢了
