### ISSUE TITLE
点击通知的时候，先发送Event,后启动APP的

### ISSUE THREAD

**Issue by andylidong** [jpush/jpush-react-native#462]
## 你的运行环境
mac 10.13.3
* 插件版本:
* react-native 版本：
    "jpush-react-native": "2.1.10",
    "react": "16.2.0",
    "react-native": "0.53.3",

## 实际效果
当点击退出键的时候（没有杀死程序），发送通知，APP收到通知，当点击通知的时候，先发送event，然后在启动APP，与预想的效果不一致。（应该先启动APP，然后在发送event）
![image](https://user-images.githubusercontent.com/18454971/36649221-5e267cec-1ad6-11e8-9983-2f375446a494.png)

![image](https://user-images.githubusercontent.com/18454971/36649153-d3567770-1ad5-11e8-8edb-99c6333ab6c9.png)

**Comment by KenChoi1992** [comment]
![image](https://user-images.githubusercontent.com/8196928/36652240-82a15d96-1ae8-11e8-9836-5b24350d1135.png)
先启动的 app

**Comment by andylidong** [comment]
我在原生端用异步处理，js端的处理会比较流畅
