### ISSUE TITLE
IOS react-native link 无效

### ISSUE THREAD

**Issue by Sudors** [jpush/jpush-react-native#463]
* 插件版本:
    jcore-react-native: ^1.2.5
    jpush-react-native: ^2.1.11
* react-native 版本：
  react-native: 0.50.3

项目中本身已经集成了pod , link的时候 podfile 里面会自动添加 
pod 'JPushRN', :path => '../node_modules/jpush-react-native'
  pod 'JCoreRN', :path => '../node_modules/jcore-react-native'

但看Libraries 并没有生成项目。
编译有如下两个错误：
 1、[JPUSHService registerForRemoteNotificationConfig:entity delegate:self]; 提示如下错误：
Cannot initialize a parameter of type 'id<JPUSHRegisterDelegate>' with an lvalue of type 'AppDelegate *const __strong'
2、Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_JPUSHRegisterEntity", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

之前也集成过一个项目，但不是pod 的时可以用的。

**Comment by Sudors** [comment]
pod install 时 一直如下所示，是不是因为 慢的原因
Installing JCoreRN (1.2.5)
Installing JPushRN (2.1.11)

**Comment by huangminlinux** [comment]
安装成功后 在 Pods -》 development pods 目录中有没新增相关类库？

**Comment by Sudors** [comment]
安装的问题解决了。相关类库也生成了。但是出现了个新问题。因为安装pod ,ios 里会添加 react 依赖项目，这个项目和 node_modules 的 package.json 冲突

**Comment by huangminlinux** [comment]
报什么错误？

**Comment by Sudors** [comment]
Pods/React/package.json 和 node_modules/react-native/package.json 冲突

**Comment by Sudors** [comment]
解决了，podfile 文件里要手动加入
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'React', :path => ‘../node_modules/react-native', :subspecs => [
'Core',
'ART',
'RCTActionSheet',
'RCTGeolocation',
'RCTImage',
'RCTNetwork',
'RCTPushNotification',
'RCTSettings',
'RCTText',
'RCTVibration',
'RCTWebSocket',
'RCTLinkingIOS',
]

系统自动生成的 会带有 package.json 文件，这和node_modules/react-native/package.json 冲突
