### ISSUE TITLE
安卓8.0无法收到推送

### ISSUE THREAD

**Issue by hhahh2011** [jpush/jpush-react-native#464]
如题

**Comment by IwantBEStrong** [comment]
我的在EMUI 8.0杀死进程后也无法收到推送，不知道题主解决了吗

**Comment by KenChoi1992** [comment]
只有 8.0 的手机收不到推送吗？

**Comment by IwantBEStrong** [comment]
我的好像不止，只要杀了进程就收不到消息了，自启动已经开启了

**Comment by KenChoi1992** [comment]
@IwantBEStrong 你说的是杀死进程收不到。这种情况下，只要你的手机上装了有 JPush SDK 的应用，收到通知，就能相互拉起。这种方式通常是延迟收到通知的。你可以在手机上装一个 JPush demo app 试试，然后在控制台上发送推送，看看你自己的 app 有没有被拉起。

**Comment by KenChoi1992** [comment]
@hhahh2011 估计不是 8.0 的问题，是你的配置出问题了，参考一下 ReadMe。

**Comment by hhahh2011** [comment]
其它版本的安卓都可以正常工作唯独8.0不行

**Comment by wuyunqiang** [comment]
那如果只有一个安装了jpush,其他软件没有安装JPush SDK，在杀死进程的情况下是不是就无法收到通知啊？
