### ISSUE TITLE
华为EMUI 8.0杀死进程后无法收到推送

### ISSUE THREAD

**Issue by IwantBEStrong** [jpush/jpush-react-native#465]
## 你的运行环境

* 插件版本:"jcore-react-native": "^1.2.5","jpush-react-native": "^2.1.11",
* react-native 版本：^0.50.4

## 期望效果

我期望的效果是杀死进程后任然能收到推送

## 实际效果
 
华为EMUI 8.0杀死进程后无法收到推送

**Comment by IwantBEStrong** [comment]
我的自启动已经开启了  还是收不到

**Comment by KenChoi1992** [comment]
你的手机要装了其他集成了 JPush SDK 的应用才能相互唤醒。
