### ISSUE TITLE
ios下收到通知事件，extras字段不存在

### ISSUE THREAD

**Issue by z372183629** [jpush/jpush-react-native#471]
运行环境
node: 7.4.0
xcode: 9.2
* 插件版本:  2.1.12
* react-native 版本：0.54

问题描述：
使用极光控制台发送通知消息，携带额外数据。在ios平台下收到事件对象结构有问题，没有extras字段，额外数据存在事件对象中，Android中则是正常的。自定义消息两端也是正常的。
看下面日志的对比：
ios下的Debug logs：
![1521632211944](https://user-images.githubusercontent.com/26563923/37707835-75654f84-2d3f-11e8-830e-367f0ad78d26.jpg)
android下的Debug logs：
![1521632866218](https://user-images.githubusercontent.com/26563923/37708234-d1157eca-2d40-11e8-9108-45c8cb694ce0.jpg)

期望效果：
两平台统一结构

**Comment by huangminlinux** [comment]
下个版本统一两平台的字段。

**Comment by ma569322307** [comment]
你好！我再iOS端集成的时候有很多问题实在解决不了 想跟你沟通一下  你能不能加一下我的微信知道一下呢   这是我的微信  ma569322307   期待你的知道  谢谢！

**Comment by huangminlinux** [comment]
Readme 有 react-native Q 群，你可以加一下 @ma569322307

**Comment by huangminlinux** [comment]
可以升级到 [2.2.1](https://github.com/jpush/jpush-react-native/releases/tag/2.2.1)，这个版本新增了 extras 字段。
