### ISSUE TITLE
Android App 退到后台后，点击通知的回调不执行

### ISSUE THREAD

**Issue by baurine** [jpush/jpush-react-native#473]
## 你的运行环境

* 插件版本: jcore-react-native: 1.2.5, jpush-react-native: 2.1.12
* react-native 版本：0.53.3
* Android 版本：8.0
* Android 手机型号：OnePlus 3T / 小米 Mix 2

## 期望效果

Android 应用退到后台以后，点击通知栏收到的通知，能执行点击通知的回调函数，APP 回到前台，并跳转到我想要的页面。

## 实际效果

实际效果是，点击通知后毫无反应，APP 没有回到前台，从 log 来看，根本没有进入到点击通知的回调函数中。

## 重现步骤

1. 运行 APP，接收通知，点击通知栏的通知栏，跳转到我想要的页面
2. 点击手机的 HOME 键，回到桌面，APP 退到后台
3. 发送通知，手机可以接收到通知，但点击通知栏后毫无反应
4. 再次打开 APP，使之重新回到前台，再次发送测试通知，手机可以接收到通知，点击通知栏的通知后，也能跳转到我想要的页面

## Debug logs

实现代码：

```
   componentDidMount() {
      // call notifyJSDidLoad before add listener
      JPushModule.notifyJSDidLoad((resultCode) => {
        if (resultCode === 0) {
          console.log('notifyJSDidLoad success')
        } else {
          console.log('notifyJSDidLoad failed')
        }
      });

      this.logAndroidNotification = this._logAndroidNotification.bind(this)
      JPushModule.addReceiveNotificationListener(this.logAndroidNotification)

      // when user click notification, will invoke OpenNotification event
      this.handleAndroidNotification = this._handleAndroidNotification.bind(this)
      JPushModule.addReceiveOpenNotificationListener(this.handleAndroidNotification)

      ...
    }

  componentWillUnmount() {
      console.log('compnentWillUnmount')
      JPushModule.removeReceiveNotificationListener(this.logAndroidNotification)
      JPushModule.removeReceiveOpenNotificationListener(this.handleAndroidNotification)
   }

    _logAndroidNotification(message) {
      console.log('========', message)
    }

    _handleAndroidNotification(message) {
      console.log(message)
      ...
    }
```

当 APP 在前台时，来了一条通知，`_logAndroidNotification` 回调函数会首先执行，点击通知后， `_handleAndroidNotification` 回调函数会执行。

log:

```
======== {extras: "{}", alertContent: "ttt", id: 191103510}
{extras: "{}", alertContent: "ttt", id: 191103510}
```

但如果 APP 退到后台以后，来了一条通知，只有 `_logAndroidNotification` 会执行，点击通知后，`_handleAndroidNotification` 并没有执行，因为没有相应的 log。

log:

```
======== {extras: "{}", alertContent: "ttt", id: 190382610}
```

当 APP 退到后台时，并没有触发 componentWillUnmount() 方法。

**Comment by baurine** [comment]
另外，我并没有在 MainActivity 中增加任何代码，比如 JPushInterface.init() / pause() / resume()。我把 init 的工作放在 JS 层做了，在 SplashPage 中调用了 JPushModule.initPush() 方法。不知道这会不会导致问题的原因之一。

**Comment by JoshLipan** [comment]
这个问题定位到原因了没有，还有问题可以提供log看下 @baurine

**Comment by baurine** [comment]
... 差点以为这个项目没人维护呢。

还没有定位到原因，最近在做别的 feature，这个搁在一边了，这几天我再看看，收集一下 log。

**Comment by baurine** [comment]
@JoshLipan 好的，谢谢！我下午试一下。

**Comment by baurine** [comment]
@JoshLipan 测试过了，2.2.2 没问题了，谢谢！
