### ISSUE TITLE
IOS后台未启动的情况下点击推送消息，监听不起作用

### ISSUE THREAD

**Issue by summmmer** [jpush/jpush-react-native#476]
## 你的运行环境

* 插件版本:2.1.3
* react-native 版本：0.48.1

## 期望效果

应用没有启动情况下，点击通知，JPushModule.addOpenNotificationLaunchAppListener 监听回掉消息，跳转页面

## 实际效果

ios杀掉APP的进程以后，点击通知消息，直接打开APP，没有走JPushModule.addOpenNotificationLaunchAppListener的回掉

## 重现步骤

1. 杀掉APP进程
2. 收到推送消息后，点击推送消息会自动打开APP
3. 没有监听到回掉

## Debug logs

包括 Android 或 iOS 的日志：暂无

**Comment by huangminlinux** [comment]
监听方法放到 index 入口试试。

**Comment by summmmer** [comment]
@huangminlinux 我用的react-native-router-flux作为路由管理，起始页是启动页（两秒后跳转），然后跳转到登录页面（判断登录），再跳转到index入口，我的监听是写在了index里面

**Comment by huangminlinux** [comment]
我的意思是 index.ios.js

**Comment by summmmer** [comment]
@huangminlinux 因为我监听数据是为了路由跳转，写在index里面，路由还没有建立，没法跳转

**Comment by summmmer** [comment]
@huangminlinux 写在index里面还是监听不到

**Comment by SanlinBlackball** [comment]
@summmmer 这个是怎么解决这个问题的 后来？

**Comment by summmmer** [comment]
@SanlinBlackball 还没解决

**Comment by huangminlinux** [comment]
jpush-react-native@2.2.0 添加了 getLaunchAppNotification 方法可以试试。
https://github.com/jpush/jpush-react-native/blob/master/index.js#L332

**Comment by sapjax** [comment]
@huangminlinux   getLaunchAppNotification 会调用事件监听，但是传的 message 是 undefined

**Comment by huangminlinux** [comment]
@sapjax  getLaunchAppNotification 方法只是获取 缓存的点击通知 和事件没什么关系。如果没有点击通知启动应用，那么 getLaunchAppNotification 这个方法返回的就是空。

**Comment by sapjax** [comment]
@huangminlinux  我上面说的不准确，  通过通知启动 app （app 任务关闭的情况下），getLaunchAppNotification的 callback 里面拿到的参数是 undefined。

**Comment by huangminlinux** [comment]
@sapjax  什么系统，本地通知还是远程通知？

**Comment by sapjax** [comment]
iOS 11.2   远程通知

**Comment by sapjax** [comment]
@huangminlinux 还是不生效

**Comment by huangminlinux** [comment]
@sapjax  可以加我Q：380108184 了解一下情况

**Comment by TylerPin** [comment]
点击通知 (iOS 和 Android 后台), (Android 杀死) addReceiveOpenNotificationListener 能取到 notification message,
杀死 iOS 点击通知 无法取到任何notification message...
已用
-getLaunchAppNotification 取到 undefined, 
-addReceiveOpenNotificationListener 没跑

**Comment by tza17313** [comment]
@huangminlinux  @sapjax 
解决方法是什么？

**Comment by inkCrazy** [comment]
可以了，iOS开启background mode， 后台设置content-available=1
addReceiveNotificationListener监听方法就可以执行。
