### ISSUE TITLE
ios在前台收到通知，addReceiveOpenNotificationListener监听自动执行

### ISSUE THREAD

**Issue by summmmer** [jpush/jpush-react-native#485]
## 你的运行环境

* 插件版本:2.1.6
* react-native 版本：0.48.1

## 期望效果

ios在前台收到通知，addReceiveOpenNotificationListener不执行，点击通知才执行

## 实际效果

ios在前台收到通知，addReceiveOpenNotificationListener没有点击通知，监听执行

## 重现步骤

1. ios端，app在前台
2. 只添加了addReceiveOpenNotificationListener监听
3. 当有通知时，监听自动执行，而不是点击执行

## Debug logs

包括 Android 或 iOS 的日志：暂无

**Comment by huangminlinux** [comment]
iOS 系统什么版本？

**Comment by summmmer** [comment]
@huangminlinux 11.2.6

**Comment by huangminlinux** [comment]
提供一下 Appdelegate.m 文件 ，将相关（敏感信息删掉 appkey）

**Comment by summmmer** [comment]
@huangminlinux 
#import "AppDelegate.h"
#import <React/RCTLinkingManager.h>
#import <RCTJPushModule.h>
#ifdef NSFoundationVersionNumber_iOS_9_x_Max
#import <UserNotifications/UserNotifications.h>
#endif


#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <AVFoundation/AVFoundation.h>
#import <AdSupport/AdSupport.h>

static NSString *appKey = @"xxxxxx";     //填写appkey
static NSString *channel = @"Publish channel";    //填写channel   一般为nil
static BOOL isProduction = true;  //填写isProdurion  平时测试时为false ，生产时填写true

@interface AppDelegate ()<JPUSHRegisterDelegate>

@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  return [RCTLinkingManager application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
}

// ios 9.0+
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<NSString*, id> *)options{
  return [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions{

//初始化APNs代码
    JPUSHRegisterEntity * entity = [[JPUSHRegisterEntity alloc] init];
    entity.types = UNAuthorizationOptionAlert|UNAuthorizationOptionBadge|UNAuthorizationOptionSound;
    [JPUSHService registerForRemoteNotificationConfig:entity delegate:self];

//初始化JPush代码
    [JPUSHService setupWithOption:launchOptions appKey:@"5e80862698801a0b87c79531" channel:nil apsForProduction:nil];


    NSURL *jsCodeLocation;

    //[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];  // allow
   //jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
    //jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"ios" withExtension:@"jsbundle"];
    jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"bundle/index.ios" withExtension:@"jsbundle"];

    RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"fudao"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
    rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    UIViewController *rootViewController = [UIViewController new];
    rootViewController.view = rootView;
    self.window.rootViewController = rootViewController;
    [self.window makeKeyAndVisible];
    return YES;
}
//注册APNs成功并上报DeviceToken
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    [JPUSHService registerDeviceToken:deviceToken];
}
//添加处理APNs通知回调方法

//6
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo];
}
//7
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)   (UIBackgroundFetchResult))completionHandler {
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo];
}

//10
- (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger))completionHandler {
    NSDictionary * userInfo = notification.request.content.userInfo;
    [JPUSHService handleRemoteNotification:userInfo];
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo];

    completionHandler(UNNotificationPresentationOptionAlert);
}
//10
- (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler {
    NSDictionary * userInfo = response.notification.request.content.userInfo;
    [JPUSHService handleRemoteNotification:userInfo];
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPFOpenNotification object:userInfo];

    completionHandler();
}
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:notification.userInfo];
}

//DeviceToken 获取失败
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
    NSLog(@"did Fail To Register For Remote Notifications With Error: %@", error);
}


@end

**Comment by huangminlinux** [comment]
用你的代码 在 jpush-react-native@2.1.13 测试没有问题,试试升级插件到最新版本。

**Comment by summmmer** [comment]
@huangminlinux 升级到了2.1.13还是同样的问题

**Comment by huangminlinux** [comment]
奇怪，我这边测试没有问题， 你用 demo 测试有这个问题吗？

**Comment by summmmer** [comment]
新建了项目，正常了，谢谢解答
