### ISSUE TITLE
收到通知App重启，杀死App无法收到推送

### ISSUE THREAD

**Issue by SanlinBlackball** [jpush/jpush-react-native#489]
你的运行环境

插件版本: "jcore-react-native": "^1.2.5", "jpush-react-native": "^2.1.12",
react-native 版本： "react-native": "0.54.0",
*Android 手机型号：三星手机
期望效果

1.在接到通知后点击直接跳转当目标界面
2.杀死app 收到推送 

实际效果

1.点击通知后重启app再跳转到目标界面
2.杀死APP无法收到推送

重现步骤

1.运行 APP，接收通知，在app界面中 点击通知栏
2.后台推送收不到推送信息 启动后收到发送的信息
Debug logs
无log输出

**Comment by JoshLipan** [comment]
1.你是自己集成导致跳转到目标界面需要重启app吗，可以试下官方的sample是没有这个问题的
2.APP被杀死后，长连接断开，手机要装了其他集成了 JPush SDK 的应用才能相互唤醒。

**Comment by fengye1** [comment]
这个解决了你第一个问题  https://github.com/jpush/jpush-react-native/issues/482

**Comment by SanlinBlackball** [comment]
@fengye1 @JoshLipan 感谢感谢
