### ISSUE TITLE
升级gradle 4.1 之后jpush-react-native 编译出现错误

### ISSUE THREAD

**Issue by fengyenet** [jpush/jpush-react-native#493]
因为反馈说二维码扫描不好用，则重新使用了react-native-camera 1.1.2
由于camera 报错 不能找到google()这个方法，所以升级了了gradle 2.14.1 -> gradle 4.1
升级后，classpath也从2.3.3升级到了com.android.tools.build:gradle:3.0.1
在使用com.android.tools.build:gradle 2.3.3/3.0.1的时候都会出现以下错误：
```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':jpush-react-native'.
      > Failed to notify project evaluation listener.
         > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependen
cyCacheDir(Ljava/io/File;)V
```
请问该如何解决

react-native version: 0.55.3
jpush-react-native version: 2.2.2

**Comment by JoshLipan** [comment]
重新react-native link试下，如果不行参照下我们文档的[手动配置](https://github.com/jpush/jpush-react-native#android-手动操作部分-3-个步骤)

**Comment by fengyenet** [comment]
@JoshLipan 重新link了，也重新手动配置过了，不行，同样的错误，顺带提一下，2.14.1版本的gradle是没问题的！
