### ISSUE TITLE
安卓版本

### ISSUE THREAD

**Issue by baicuhaha** [jpush/jpush-react-native#498]
## 你的运行环境
安卓
* 插件版本:
studio是3.2版本
* react-native 版本：
0.55.3
告诉我们实际是什么效果。
在link之后 ，项目报错0.55.3
包括 Android 或 iOS 的日志：
具体报错是:The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
<img width="572" alt="2018-05-27 6 32 54" src="https://user-images.githubusercontent.com/20334376/40584924-7021695a-61dc-11e8-9996-98a2afc6651f.png">
我该怎么处理？

**Comment by JoshLipan** [comment]
按照log提示，找到Android下的AndroidManifest.xml文件，去掉minSdkVersion配置试试

**Comment by baicuhaha** [comment]
我已解决

**Comment by Beats0** [comment]
> /node_modules/jpush-react-native/android/src/main/AndroidManifest.xml

注释minSdkVersion
```xml
<!--<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="22" />-->
```
重新启动android并sync即可

**Comment by plimerence** [comment]
额 这么注释 从新install 岂不是还要注释

**Comment by Beats0** [comment]
> 额 这么注释 从新install 岂不是还要注释

是的, 主要是因为官方不更新的问题, 很多长时间不维护的包都是这样解决的
