### ISSUE TITLE
* What went wrong: Execution failed for task ':app:processReleaseResources'. > Failed to execute aapt

### ISSUE THREAD

**Issue by houdzaiw** [jpush/jpush-react-native#501]
## 你的运行环境
Android Studio 3.1.2
Build #AI-173.4720617, built on April 14, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.4
* 插件版本:
* react-native 版本：
   "create-react-class": "^15.6.3",
    "install": "^0.11.0",
    "jcore-react-native": "^1.2.6",
    "jpush-react-native": "^2.2.3",
    "moment": "^2.22.1",
    "npm": "^5.8.0",
    "react": "16.3.1",
    "react-native": "0.55.2",
"gradle version":"4.3"
"Android Plugin Version":"3.0.1"
## 期望效果
执行./gradlew assembleRelease 打包
告诉我们你希望达到什么效果。
希望打出正常的包
## 实际效果
打包失败
告诉我们实际是什么效果。
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 9s

## Debug logs
debug 没问题，release打包就报错
包括 Android 或 iOS 的日志：
iOS没问题

**Comment by JoshLipan** [comment]
试试[混淆忽略](https://docs.jiguang.cn/jpush/client/Android/android_faq/#jpush-sdk-releasejar)

**Comment by houdzaiw** [comment]
@JoshLipan 谢谢🙏，非常的好用
