### ISSUE TITLE
react native link之后长时间没有反应.

### ISSUE THREAD

**Issue by pheromone** [jpush/jpush-react-native#505]
## 你的运行环境

* 插件版本:
* react-native 版本：    
   "react-native": "0.55.4",
   "jcore-react-native": "^1.2.6",
    "jpush-react-native": "^2.2.4",

## 期望效果

然后就一直卡住了.都半个小时了

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

1.cd 项目
2. npm install jpush-react-native jcore-react-native --save
3. npm install jcore-react-native --save
4. react-native link

## Debug logs

包括 Android 或 iOS 的日志：
![image](https://user-images.githubusercontent.com/14305431/41084398-a5a44ab0-6a66-11e8-9cda-ab5302c87fce.png)

**Comment by baicuhaha** [comment]
这个 是让你输入jpush的key。。。。

**Comment by pheromone** [comment]
@baicuhaha  key我已经输完了,截图箭头处就是key........

**Comment by huangminlinux** [comment]
应该是 RN link 的 bug， 可以手动 link 。
