### ISSUE TITLE
JPushModule.setBadge is not a function

### ISSUE THREAD

**Issue by ssqyht** [jpush/jpush-react-native#506]
## 你的运行环境
Mac  Android模拟器

* 插件版本:  "jcore-react-native": "^1.2.6","jpush-react-native": "^2.2.3",
* react-native 版本："react-native": "0.55.4",

## 期望效果
1.执行成功，应用图标报错 ，
2.IOS下面调用 JPushModule.sendLocalNotification(notification);能够显示提示通知

## 实际效果

1.报错：JPushModule.setBadge is not a function
2.没有反应，不显示通知

## 重现步骤

import JPushModule from "jpush-react-native";

JPushModule.setBadge(count, value => {
            cb(value)
        });

同样 JPushModule.setLocalNotification报同样的错

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by huangminlinux** [comment]
升级到最新版本，看还有没问题。
