### ISSUE TITLE
点击推送消息进入app,调用setBadge报错

### ISSUE THREAD

**Issue by syun0216** [jpush/jpush-react-native#507]
## 你的运行环境
macOS 10.13.4
* 插件版本:
"jcore-react-native": "^1.2.6",
"jpush-react-native": "^2.2.3",
* react-native 版本：
"react-native": "0.52.2",
## 期望效果

告诉我们你希望达到什么效果。

## 实际效果
JPushModule.addReceiveOpenNotificationListener(map => {
      if(Platform.OS == 'ios') {
       JPushModule.setBadge(0);
      }
    })
告诉我们实际是什么效果。
在手机上debug 点开推送到app报错
## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs
![image](https://user-images.githubusercontent.com/18444325/41187559-6be04648-6bde-11e8-9b57-5d282085132c.png)

包括 Android 或 iOS 的日志：

**Comment by huangminlinux** [comment]
https://github.com/jpush/jpush-react-native/blob/master/documents/api.md#setbadge

**Comment by syun0216** [comment]
可以了 谢谢大佬O(∩_∩)O
