### ISSUE TITLE
使用npm下载的jpush-react-native 下无example目录

### ISSUE THREAD

**Issue by webwyb** [jpush/jpush-react-native#508]
## 你的运行环境
maxos 10.13.4
* 插件版本: 
    jcore-react-native: "^1.2.6",
    jpush-react-native: "^2.2.3",
* react-native  @版本：0.55.4

## 期望效果

使用npm下载的jpush-react-native 下有完整的example目录和相关依赖
## 实际效果
使用 npm 下载的 jpush-react-native 下没有有完整的example目录和相关依赖，将项目导入android studio sync 后报错

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by JoshLipan** [comment]
sample路径下需要先安装插件：npm install jpush-react-native jcore-react-native --save
