### ISSUE TITLE
sendLocalNotification or setLocalNotification 没有显示通知

### ISSUE THREAD

**Issue by ssqyht** [jpush/jpush-react-native#512]
你的运行环境

Mac Android模拟器

插件版本: "jcore-react-native": "^1.2.6","jpush-react-native": "^2.2.5",
react-native 版本："react-native": "0.55.4",
期望效果

1.Android下调用JPushModule.sendLocalNotification(notification);能够显示提示通知
2.IOS下面调用 JPushModule.sendLocalNotification(notification);能够显示提示通知

实际效果

1.Android没有反应，不显示通知
2.IOS 没有反应，不显示通知

重现步骤
if (this.isAndroid()) {
          
            JPushModule.sendLocalNotification(notification);
        } else {
            JPushModule.setLocalNotification(
                200,
                notification.content,
                99
            );
        }

Debug logs

包括 Android 或 iOS 的日志：

**Comment by JoshLipan** [comment]
看下你传的参数

**Comment by ssqyht** [comment]
@JoshLipan 参数修改如下，依然如此
message(id, title, content, extra = {}) {
        if (this.isAndroid()) {
            JPushModule.sendLocalNotification({
                buildId: 1,
                id: id,
                title: title,
                subtitle: null,
                content: `${content}`,
                extra: extra,
                fireTime: 1,
                badge: 999,
            });
        } else {
            JPushModule.setLocalNotification(
                new Date(),
                content,
                99,
                '打开',
                '',
                {},
                null
            );
        }
    }

**Comment by JoshLipan** [comment]
fireTime参数是毫秒单位的时间戳

**Comment by ssqyht** [comment]
@JoshLipan 我发现IOS下面好像初始化失败， 初始化有日志提示吗？我ios设备调用JPushModule.initPush()
以后，然后官网推送平台上面 找不到设备，就是没有可以推送的用户，有没有方法可以查看iOS下注册成功还是失败 就是调用JPushModule.initPush() 的结果

**Comment by JoshLipan** [comment]
initPush是Android特有方法，ios初始化调用setupPush，请仔细阅读文档

**Comment by ssqyht** [comment]
@JoshLipan 你们源码没有标注：而且调用initPush 一会自动切换为setupPush


export default class JPush {
  /**
   * 初始化JPush 必须先初始化才能执行其他操作
   */
  static initPush () {
    if (Platform.OS == "android") {
      JPushModule.initPush()
    } else {
      JPush.setupPush()
    }
  }
  /**
   * 停止推送，调用该方法后将不再受到推送
   */
  static stopPush () {
    JPushModule.stopPush()
  }

  /**
   * 恢复推送功能，停止推送后，可调用该方法重新获得推送能力
   */
  static resumePush () {
    if (Platform.OS == "android") {
      JPushModule.resumePush()
    } else {
      JPush.setupPush()
    }
  }

调用 setupPush没有用，我换成调用setupPush

接着IOS我手动配置过一遍以后，现在报错如下：
![image](https://user-images.githubusercontent.com/9328988/41754220-2383b512-7604-11e8-8f81-5065dd98a60d.png)

很奇怪

**Comment by huangminlinux** [comment]
iOS 和 android 同时支持  `sendLocalNotification` 这个方法，现在也是建议使用这个方法，试试下面的测试代码。
```
const notification = {
      buildId: 1,
      id: 5,
      title: 'jpush',
      content: 'This is a test!!!!',
      extra: {
        key1: 'value1',
        key2: 'value2'
      },
      fireTime: 2000
    }
    JPushModule.sendLocalNotification(notification)
```

**Comment by huangminlinux** [comment]
@ssqyht  找不到 设备有很多原因:
- 证书有没正确配置。
- 在 xcode8 之后需要点开推送选项： TARGETS -> Capabilities -> Push Notification 设为 on 状态。

如果这两项确定没问题，可以提供具体原生日志出来。

**Comment by ssqyht** [comment]
@huangminlinux 有什么办法可以看到关于jpush-r-n的原生日志，我用浏览器debug模式看不到

**Comment by huangminlinux** [comment]
xcode 来看。

**Comment by ssqyht** [comment]
@huangminlinux 看如下的日志是支持成功了哦 但是提示不支持simulator？


2018-06-22 16:50:00.837701+0800 Celesea[12505:3271025] 
--------------------------- JPush Log ----------------------------
--------------------JPush SDK Version:3.0.7--build:45----------
--------------------JCore Lib Version:1.1.6--build:29----------
-----------------AppKey:5646aabb206f1c499b97e7c5----------------
----------------------------------------------------------------
2018-06-22 16:50:00.837850+0800 Celesea[12505:3271025] JPush WARNING! APNs is NOT supported on simulator
2018-06-22 16:50:00.839 [info][tid:main][RCTCxxBridge.mm:210] Initializing <RCTCxxBridge: 0x6080001c7530> (parent: <RCTBridge: 0x6080000df6b0>, executor: (null))

**Comment by huangminlinux** [comment]
这个插件的大部分功能本来就不支持模拟器。 要真机。

**Comment by huangminlinux** [comment]
看日志是 没有成功获取 devicetoken。 

检查我之间说的这个 https://github.com/jpush/jpush-react-native/issues/512#issuecomment-399302769

**Comment by ssqyht** [comment]
@huangminlinux 谢谢 我重新删除编译安装 IOS可以收到极光远程推送过来的消息了 
IOS本地消息通知还是不行  没有任何响应   Android是OK的
const notification = {
            buildId: 1,
            id: 5,
            title: 'jpush',
            content: 'This is a test!!!!',
            extra: {
                key1: 'value1',
                key2: 'value2'
            },
            fireTime: 2000
        }
        JPushModule.sendLocalNotification(notification);

**Comment by huangminlinux** [comment]
应该是这段代码：
```
      var currentDate = new Date()
      var notification = {
        buildId: 1,
        id: 5,
        title: 'jpush',
        content: 'This is a test!!!!',
        extra: {
          key1: 'value1',
          key2: 'value2'
        },
        fireTime: currentDate.getTime() + 3000,
      }


      JPushModule.sendLocalNotification(notification)
```
