### ISSUE TITLE
iPhone 5 运行闪退！

### ISSUE THREAD

**Issue by sandywk** [jpush/jpush-react-native#513]
## 你的运行环境
iPhone 5

* 插件版本:
react-native 0.51.0
jpush-react-native 2.1.10

## 实际效果
发布后安装到 iPhone 5 运行APP闪退

## 重现步骤
iPhone 5s及以上都正常，iPhone 5 和 iPhone 4S 目前测试运行出错

## Debug logs
用 Xcode 9.2 测试 iPhone 5 运行报以下错误：（iPhone 5s及以上都正常）
` "_OBJC_CLASS_$_JPUSHRegisterEntity", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
      objc-class-ref in libRCTJPushModule.a(RCTJPushActionQueue.o)
  "_OBJC_CLASS_$_JPushNotificationContent", referenced from:
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPushNotificationIdentifier", referenced from:
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPushNotificationRequest", referenced from:
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPushNotificationTrigger", referenced from:
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidCloseNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
      -[RCTJPushModule reactJSDidload] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidLoginNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
      -[RCTJPushModule reactJSDidload] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidReceiveMessageNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidRegisterNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidSetupNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkIsConnectingNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by huangminlinux** [comment]
iphone5 是什么系统的？

**Comment by sandywk** [comment]
@huangminlinux  
iPhone 5 iOS 10.3.3

**Comment by huangminlinux** [comment]
看你的错误是使用了模拟器导致的，sdk 不支持 i386 arch 的 cpu， 要用 5s 以上的模拟器，
如果真机的话没有限制。

**Comment by sandywk** [comment]
@huangminlinux
就是发布后用真机出现闪退才用模拟器测试的
真机的环境：iPhone 5 iOS 10.3.3

**Comment by huangminlinux** [comment]
提供真机的错误日志
