### ISSUE TITLE
addReceiveOpenNotificationListener回调会走两遍

### ISSUE THREAD

**Issue by shenxuhui1993** [jpush/jpush-react-native#514]
刚安装好app时，接收到推送后，addReceiveOpenNotificationListener回调会走两遍，试了几遍之后，就正常了。试了三次了，每次重新装的时候都是这样

**Comment by JoshLipan** [comment]
看下是不是多次调用了addReceiveOpenNotificationListener

**Comment by captianli** [comment]
我也遇到这样的问题

**Comment by huangminlinux** [comment]
是 iOS 还是 android 出现这个问题？

**Comment by shenxuhui1993** [comment]
android和iOS都有这个问题，而且只是在刚安装app的前几次推送会出现这个问题，后面在推送就都正常了@huangminlinux

**Comment by Silence-more** [comment]
您好，请问您的这个问题解决了吗 @shenxuhui1993

**Comment by huangshihao666** [comment]
我也遇到了同样的问题，请问解决了吗？@shenxuhui1993

**Comment by xiaomansjw** [comment]
我也遇到了同样的问题，请问解决了吗？

**Comment by huangminlinux** [comment]
用的 demo 测试没有问题，不清楚实际情况，如果可以可以重现一个有问题的 demo 发我 QQ：380108184。

**Comment by Silence-more** [comment]
addReceiveCustomMsgListener监听每登陆一次就会执行一次，removeReceiveCustomMsgListener无法清除监听。

**Comment by huangminlinux** [comment]
保证 addReceiveCustomMsgListener 和 removeReceiveCustomMsgListener 传入的是同一个function
