### ISSUE TITLE
iOS和Android收到的自定义消息内容不一致

### ISSUE THREAD

**Issue by x13945** [jpush/jpush-react-native#515]
## 你的运行环境

* 插件版本: 2.1.10
* react-native 版本：0.51.0

## 期望效果

下面这个api在iOS和Android下收到的自定义消息内容是一致的
```js
 JPushModule.addReceiveCustomMsgListener(map => {
      console.log('JPush Message: ' + JSON.stringify(map));
    
    });
```
## 实际效果
iOS和Android平台下收到的`map`变量内容不一样：

**iOS收到的消息**
```json
{
  "content": "设备数据变化",
  "content_type": "DEVICE_UPDATE",
  "extras": {
    "type": 18
  }
}
```
**Android**平台收到的消息：
```json
{
  "extras": {
    "type": 18
  },
  "id": 0,
  "message": "设备数据变化"
}
```
## 重现步骤

1. 通过服务器或极光后台发送自定义消息
2. 在Android和iOS平台接收并打印消息

## Debug logs

无

**Comment by x13945** [comment]
我提交了一个pr来修复这个问题，鉴于该pr还没有合入。着急使用的同学可以直接使用这个pr中的commit ：#dcd630236fd7e7182d0dfe6947b6ea50433cd405

**Comment by JoshLipan** [comment]
谢谢你的支持，为了兼容之前的版本，保留了message字段，已合并pr
