### ISSUE TITLE
建议 android notifyJsDidLoad必须要执行的 为什么不写到文档里去呢

### ISSUE THREAD

**Issue by xiaozhicheng** [jpush/jpush-react-native#520]
我看里你们到example，Debug才知道这个方法是必须执行的
--

**Comment by xiaozhicheng** [comment]
我看里你们到example，找半天才知道这个方法是必须执行的

**Comment by JoshLipan** [comment]
仔细看看文档[API部分](https://github.com/jpush/jpush-react-native#api)
