### ISSUE TITLE
APP运行时，不能收到点击推送的回调，addReceiveOpenNotificationListener不进入

### ISSUE THREAD

**Issue by xiongyoudou** [jpush/jpush-react-native#521]
## 你的运行环境
iOS11.4系统 iPhone5s
* 插件版本:^2.1.3
* react-native 版本：0.50.3

## 期望效果
希望在APP运行时，当收到通知会在顶部展示推送消息，此时点击推送消息时希望能够进入回调方法addReceiveOpenNotificationListener。
## 实际效果
但是现在只会进入addReceiveNotificationListener方法

## 重现步骤

1. ... 极光网页发推送
2. ...APP运行时，顶部会收到推送，点击该推送消息
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by huangminlinux** [comment]
是点击没回调还是，前台不展示？

**Comment by xiongyoudou** [comment]
是点击没有回调

**Comment by huangminlinux** [comment]
iOS 什么系统？

**Comment by xiongyoudou** [comment]
iOS11.4 iPhone5s

**Comment by huangminlinux** [comment]
监听代码提供一下

**Comment by xiongyoudou** [comment]
不好意思，我发现原因了，原来Appdelegate中通知发错了
