### ISSUE TITLE
Execution failed for task ':jcore-react-native:processReleaseResources'

### ISSUE THREAD

**Issue by mrarronz** [jpush/jpush-react-native#523]
## 你的运行环境

* 插件版本: "jcore-react-native": "1.2.8", "jpush-react-native": "^2.2.7",
* react-native 版本：0.56.0

## 期望效果

编译成功

## 实际效果

编译失败

## 重现步骤

1. 按照文档集成了jpush，安装了jcore-react-native和jpush-react-native，确认过所有步骤都是正确的
2. react-native run-android
3. android编译不成功，报错信息见log。iOS是没有问题的

## Debug logs
android日志如下（XXX是项目路径）：

> :jcore-react-native:processReleaseResources/XXX/node_modules/jcore-react-native/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
> XXX/node_modules/jcore-react-native/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
> XXX/node_modules/jcore-react-native/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
    
> XXX/node_modules/jcore-react-native/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

> XXX/node_modules/jcore-react-native/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

> XXX/node_modules/jcore-react-native/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

 FAILED

BUILD FAILED

Total time: 4.979 secs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jcore-react-native:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by mrarronz** [comment]
values-v24.xml 代码:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Base.TextAppearance.AppCompat.Widget.Button.Borderless.Colored" parent="android:TextAppearance.Material.Widget.Button.Borderless.Colored"/>
    <style name="Base.TextAppearance.AppCompat.Widget.Button.Colored" parent="android:TextAppearance.Material.Widget.Button.Colored"/>
    <style name="TextAppearance.AppCompat.Notification.Info.Media"/>
    <style name="TextAppearance.AppCompat.Notification.Media"/>
    <style name="TextAppearance.AppCompat.Notification.Time.Media"/>
    <style name="TextAppearance.AppCompat.Notification.Title.Media"/>
    <style name="TextAppearance.Compat.Notification.Info.Media"/>
    <style name="TextAppearance.Compat.Notification.Media"/>
    <style name="TextAppearance.Compat.Notification.Time.Media"/>
    <style name="TextAppearance.Compat.Notification.Title.Media"/>
</resources>
```

**Comment by mrarronz** [comment]
values-v26.xml 代码：

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Base.Theme.AppCompat" parent="Base.V26.Theme.AppCompat"/>
    <style name="Base.Theme.AppCompat.Light" parent="Base.V26.Theme.AppCompat.Light"/>
    <style name="Base.V26.Theme.AppCompat" parent="Base.V23.Theme.AppCompat">
        <!-- We can use the platform styles on API 26+ -->
        <item name="colorError">?android:attr/colorError</item>
    </style>
    <style name="Base.V26.Theme.AppCompat.Light" parent="Base.V23.Theme.AppCompat.Light">
        <!-- We can use the platform styles on API 26+ -->
        <item name="colorError">?android:attr/colorError</item>
    </style>
    <style name="Base.V26.Widget.AppCompat.Toolbar" parent="Base.V7.Widget.AppCompat.Toolbar">
        <item name="android:touchscreenBlocksFocus">true</item>
        <item name="android:keyboardNavigationCluster">true</item>
    </style>
    <style name="Base.Widget.AppCompat.Toolbar" parent="Base.V26.Widget.AppCompat.Toolbar"/>
</resources>
```

**Comment by mrarronz** [comment]
问题就出在
```
<style name="Base.TextAppearance.AppCompat.Widget.Button.Borderless.Colored" parent="android:TextAppearance.Material.Widget.Button.Borderless.Colored"/>
    <style name="Base.TextAppearance.AppCompat.Widget.Button.Colored" parent="android:TextAppearance.Material.Widget.Button.Colored"/>
```
和
```
<item name="android:keyboardNavigationCluster">true</item>
```
这两段代码，对android了解不够深入，为什么编译时会生成这么多xml样式文件。怎么解决这个问题

**Comment by JoshLipan** [comment]
多次link了，可以参照[Android配置](https://github.com/jpush/jpush-react-native#android-%E6%89%8B%E5%8A%A8%E6%93%8D%E4%BD%9C%E9%83%A8%E5%88%86-3-%E4%B8%AA%E6%AD%A5%E9%AA%A4)把重复的配置去掉

**Comment by mrarronz** [comment]
@JoshLipan 我很确定并没有多次link，而且也没有重复的配置，不知道你从哪里看出来的

**Comment by mrarronz** [comment]
buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"

**Comment by JoshLipan** [comment]
看这个配置没啥问题，项目导入AS，重新clean，rebuild项目有试过吗

**Comment by mrarronz** [comment]
试过了，还是报错

**Comment by JoshLipan** [comment]
[混淆忽略](https://docs.jiguang.cn/jpush/client/Android/android_faq/#jpush-sdk-releasejar)加了吗， #501

**Comment by mrarronz** [comment]
已经解决了，gradle版本问题。/android/build.gradle修改如下：
```
dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```

/android/gradle/wrapper/gradle-wrapper.properties中修改：
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
```

**Comment by zhanguangao** [comment]
将模块的编译版本改成跟你app的编译版本一样，像我的编译版本是26，将所有模块的编译版本改成26就不会报错了

**Comment by Yan1** [comment]
@mrarronz 你打包成功了吗？我遇到的报错和你一模一样，根据你的提示更改gradle版本后，能运行成功，但打包时，报错
```
/Users/yanhong/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/da4f249f73fb47970c6eb50fdf7550c4/res/values-v24/values-v24.xml:3:5-157: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
/Users/yanhong/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/da4f249f73fb47970c6eb50fdf7550c4/res/values-v24/values-v24.xml:4:5-135: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
/Users/yanhong/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/da4f249f73fb47970c6eb50fdf7550c4/res/values-v26/values-v26.xml:13:5-16:13: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
    

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jcore-react-native:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```

**Comment by qiangf811** [comment]
> @mrarronz 你打包成功了吗？我遇到的报错和你一模一样，根据你的提示更改gradle版本后，能运行成功，但打包时，报错
> 
> ```
> /Users/yanhong/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/da4f249f73fb47970c6eb50fdf7550c4/res/values-v24/values-v24.xml:3:5-157: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
>     
> /Users/yanhong/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/da4f249f73fb47970c6eb50fdf7550c4/res/values-v24/values-v24.xml:4:5-135: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
>     
> /Users/yanhong/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/da4f249f73fb47970c6eb50fdf7550c4/res/values-v26/values-v26.xml:13:5-16:13: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
>     
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':jcore-react-native:verifyReleaseResources'.
> > com.android.ide.common.process.ProcessException: Failed to execute aapt
> ```

@Yan1 我也遇到了这个问题，你解决了吗？

**Comment by qiangf811** [comment]
> @Yan1 检查下你的gradle配置，compileSdkVersion和targetSdkVersion这些配置最好都保持一致，
> 
> ```
> buildToolsVersion = "26.0.3"
>     minSdkVersion = 16
>     compileSdkVersion = 26
>     targetSdkVersion = 26
>     supportLibVersion = "26.1.0"
> ```
> app/build.gradle中dependencies下面的配置中appcompat版本设置为v7:26+，与上面我定义的supportLibVersion一致就行
> 
> ```
> compile "com.android.support:appcompat-v7:26+" // 或v7:26.1.0
> ```

现在的配置：buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"

"com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}
取的就是统一的supportLibVersion，但是还是不行

**Comment by huangjianguohjg** [comment]
卧槽，老哥，我也遇到和你一模一样的问题@qiangf811

**Comment by iamsee** [comment]
same error
