### ISSUE TITLE
获取registrationID回调过慢

### ISSUE THREAD

**Issue by godot007** [jpush/jpush-react-native#524]
## 你的运行环境

* 插件版本:2.2.7
* react-native 版本：0.44.3

## 期望效果

获取registrationID能够快一点

## 实际效果

安装了ipa包，打开app，经常长时间才能回调拿到registrationID

**Comment by JoshLipan** [comment]
init成功后才能获取到registrationID，第一次需要后台验证账户

**Comment by haipengz** [comment]
同样的问题，获取registrationID回调过慢。
iOS端没init方法。

**Comment by jimhj** [comment]
唉，这个问题存在已久

**Comment by haipengz** [comment]
已照极光官方的getRegistrationID方法自己写了原生代码，去掉isLogin判断，直接返回RegistrationID即可。

**Comment by showtan001** [comment]
写在根目录index.js下  然后存全局

**Comment by huangminlinux** [comment]
可以升级到最新版本
