### ISSUE TITLE
你们的example 怎么用啊？jshare-react-native 是什么鬼？

### ISSUE THREAD

**Issue by ray-shawn** [jpush/jpush-react-native#525]
1.下载文件夹
2. npm
3. Xcode 打开更改签名就能用吗？

**Comment by qihong1983** [comment]
example 需要在按装jpush-react-native吗

**Comment by qihong1983** [comment]
需要走Readme.md里的步骤吗

**Comment by qihong1983** [comment]
git clone https://github.com/jpush/jpush-react-native.git
Cloning into 'jpush-react-native'...
fatal: unable to access 'https://github.com/jpush/jpush-react-native.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443

**Comment by ray-shawn** [comment]
这个不是包的问题， 你可以直接下载文件夹

**Comment by qihong1983** [comment]
ld: library not found for -lRCTJCoreModule
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by qihong1983** [comment]
error: cannot parse the debug map for "/Users/qihong/Library/Developer/Xcode/DerivedData/PushDemo-gwsfezkrmdbrfncsmhsytsyfwycp/Build/Products/Debug-iphoneos/PushDemo.app/PushDemo": No such file or directory

**Comment by huangminlinux** [comment]
路径已更新 @ray-shawn
