### ISSUE TITLE
大量 iOS 设备获取 RegistrationID 失败

### ISSUE THREAD

**Issue by xwartz** [jpush/jpush-react-native#526]
## 你的运行环境

* 插件版本:
"react-native": "0.51.0",
"jcore-react-native": "^1.2.5",
"jpush-react-native": "^2.2.0",

## 期望效果

iOS 设备获取 RegistrationID 正常

## 实际效果

大量 iOS 设备获取 RegistrationID 失败

## 重现步骤

1. 获取 RegistrationID 方法：

```js
getPushToken(): Promise<number | string> {
    return new Promise((resolve, reject) => {
      // if getRegistrationID no response over 10 second, will make it timeout
      const noResponseDelay = setTimeout(() => {
        tracker.captureMessage('get jpush registration id timeout')
        resolve(null)
      }, 10000)

      JPushModule.getRegistrationID((registrationId) => {
        noResponseDelay && clearTimeout(noResponseDelay)
        if (registrationId) {
          resolve(registrationId)
        } else if (__DEV__) {
          const SIMULATOR_PUSH_TOKEN = isiOS ? IOS_SIMULATOR_PUSH_TOKEN : ANDROID_EMULATOR_PUSH_TOKEN
          resolve(SIMULATOR_PUSH_TOKEN)
        } else {
          tracker.captureMessage('get jpush registration id failed')
          reject(new Error('registrationId_empty'))
        }
      })
    })
  }
```

2. 以上代码在 App 每次启动的时候会执行
理论上就算第一次获取失败(超时)，之后多次重试的过程中，应该大概率会获取成功，
但是从我们上报的数据来看，存在大量失败的设备。

设备分布，看下图：

![image](https://user-images.githubusercontent.com/4149827/43885955-f012815e-9bec-11e8-8df5-03b3f9c80997.png)

3. Android 设备正常，只有 iOS 出现这种情况

**Comment by xwartz** [comment]
有个疑问，通常获取 RegistrationID 需要多长时间？

**Comment by huangminlinux** [comment]
如果网络正常，很快就会返回。

**Comment by xwartz** [comment]
虽然可能会超时，但是在 App 每次重启的时候都会重新获取，理论上应该会有成功的，但是现在统计到差不多 1/3 的失败，不太正常。
你们那边有统计获取 registerId 一般多长时间吗 @huangminlinux

**Comment by xwartz** [comment]
我现在设置的超时时间是 10s，如果 10s 回调没有返回 registerId 就当做失败，所以如果统计出大量时间是超过 10s 的，那么还是有可能出现我现在这种情况的。

**Comment by huangminlinux** [comment]
直接调用 getRegistrationID 这个方法就行，如果网络正常基本很快可以获得回调。

可以先升级到最新版本 2.2.8，看还有没这个问题。
npm i jpush-react-native@2.2.8

**Comment by xwartz** [comment]
jpush-react-native@2.2.8 版本有这方面的更新吗？
主要是这么有重试机会还出现这么高的失败比例，非常的不正常。我看也有不少人获取不到 registerId 的情况。

**Comment by huangminlinux** [comment]
2.2.8 版本 如果已经成功获取了 RegistrationID 会直接走缓存，不会等待网络。
不过对第一次获取 RegistrationID 没什么影响。

**Comment by xwartz** [comment]
ok，我先升级试一下
