### ISSUE TITLE
设置tag标签不成功，但是能设置alias别名

### ISSUE THREAD

**Issue by xifumengmengda** [jpush/jpush-react-native#528]
## 运行环境
windows7
* 插件版本:
* react-native 版本：0.54.2
jcore-react-native 版本: "^1.2.6",
jpush-react-native 版本: "^2.2.5",
## 期望效果

能设置tag标签

## 实际效果

设置tag标签不成功，但是能设置alias别名,上周是可以设置tag标签的，代码没有任何变化

重现步骤

![jpush](https://user-images.githubusercontent.com/16473366/44070824-909cdcf4-9fb8-11e8-9ed0-04f7ceb6facd.png)
![jpush1](https://user-images.githubusercontent.com/16473366/44070825-910d8864-9fb8-11e8-94e7-1af72418af80.png)

**Comment by JoshLipan** [comment]
添加tag调用[addtags](https://github.com/jpush/jpush-react-native/blob/master/documents/api_en.md#addtags)

**Comment by xifumengmengda** [comment]
@JoshLipan 找到原因了，但是这个原因百度搜索以及官方文档也没给出为什么。并且现在才发现极光推送的错误提示码6021竟然全网搜索不到
![suc2](https://user-images.githubusercontent.com/16473366/44074265-87cd69a6-9fca-11e8-881b-d5a29677ac7f.png)
![Uploading suc3.png…]()

**Comment by JoshLipan** [comment]
[6021](https://docs.jiguang.cn/jpush/client/Android/android_api/#_153)是指ags操作正在进行中，暂时不能进行其他tags操作
