### ISSUE TITLE
Android 8.0和8.1崩溃

### ISSUE THREAD

**Issue by gelZK** [jpush/jpush-react-native#532]
## 你的运行环境

* 插件版本: 源码引入的，原来引入的是2.2.0版本的jar。现在引入的是3.1.3版本的jar 和对应的so，并且引入了jcore.
* react-native 版本：0.33.0

## 期望效果

告诉我们你希望达到什么效果。

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

java.lang.IllegalStateException
Not allowed to start service Intent { flg=0x20 cmp=cn.rainbow.westore/cn.jpush.android.service.DaemonService }: app is in background uid null

1 android.app.ContextImpl.startServiceCommon(ContextImpl.java:1525)
--
2 android.app.ContextImpl.startService(ContextImpl.java:1481)
3 android.content.ContextWrapper.startService(ContextWrapper.java:650)
4 cn.jpush.android.service.l.run(Unknown Source:108)
5 java.lang.Thread.run(Thread.java:764)

**Comment by JoshLipan** [comment]
更新到最新的3.1.5的jar和对应so试试

**Comment by gelZK** [comment]
@JoshLipan  
我在社区中找到了相关的帖子
https://community.jiguang.cn/t/android-java-lang-securityexception-unable-to-start-service-intent/642/7
发现在16年的时候，你们回复的已经把这个问题解决掉了，并且已经集成了你们最新的版本。
但是在实际使用中，又出现了crash的情况。
3.1.5这个版本还会出现8.0和8.1crash吗？因为现在jpush的crash已经影响到了我们app的crash率了。

**Comment by Lris12J** [comment]
这个问题已经在3.1.0版本中就修复过了，理论上是不会还有问题的，你确认你捕获到的报错对应的 App 版本中集成的 极光 SDK 的版本在 3.1.0 以上？
https://community.jiguang.cn/t/cmp-video-vue-android-cn-jpush-android-service-daemonservice/22973/3

**Comment by gelZK** [comment]
@Lris12J 
确定使用的是3.1.0以上的版本，jpush-android-3.1.3.jar、jcore-android-1.2.0.jar和jcore120.so

**Comment by Lris12J** [comment]
报上来的错误所在的 App 是不是这个版本以上的，是否可能是你们未更新的旧版本报的错误。
该问题除了线上捕获到，你测试机上是否可以复现？如果可以复现，在[社区](https://community.jiguang.cn/)提供下完整的客户端日志信息以及：该错误在哪些设备机型和系统上出现？频率多高？根据上面的说明去掉拉起服务 DaemonService 呢？

**Comment by gelZK** [comment]
我这边采集到的崩溃版本号对应的是使用了Jpush3.1.3的版本，以VIVO X20 和VIVO X20A 且系统是Android8.1的版本 崩溃居多。不是所有8.0和8.1的手机都出现崩溃，

**Comment by gelZK** [comment]
[讨论](https://community.jiguang.cn/t/topic/29100)

**Comment by Lris12J** [comment]
你之前使用的是 JPush 3.1.3 和 JCore 1.2.0 还是 JCore 1.2.1？原生里面 3.1.3 对应的是 1.2.1 版本，你之前给的 so 是 1.2.0 的，如果是不匹配的版本理论上集成都会失败的，请确认下你的版本，我好提给研发对这个版本进行验证。

**Comment by gelZK** [comment]
当时下载的JPush-react-native中是3.1.3，对应下载的jcore-react-native中的jcore是1.2.0。

**Comment by Lris12J** [comment]
如果使用的 JPush 原生版本是 3.1.3，则 JCore 必须使用 1.2.1 版本及以上的；
当时下载的 JCore 插件最新是 1.2.0 的应是插件这边没有及时更新的缘故，你现在均升级到最新版本后就应不再有问题。你可以关注下原生 SDK 的更新说明，更新指南中的JPush 指定的 JCore 只能使用当前和更高版本而不能使用更低版本。
https://docs.jiguang.cn/jpush/updates/#jpush-android-sdk-v315

**Comment by gelZK** [comment]
好的，我现在已经更换到3.1.5和1.2.3了
