### ISSUE TITLE
编译debug包报错ios

### ISSUE THREAD

**Issue by Vongolatt** [jpush/jpush-react-native#533]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

已经在 Other Linker Flags添加 -lc++还是报错这个,

**Comment by huangminlinux** [comment]
集成步骤描述一下。
