### ISSUE TITLE
Cannot read property 'initPush' of undefined

### ISSUE THREAD

**Issue by zetianlaile** [jpush/jpush-react-native#535]
运行demo，发现以上错误
然后我进行了console.log
onInitPress () {
    console.log(JPushModule.initPush);  //第一行
    console.log(JPushModule.initPush());  //第二行
    //JPushModule.initPush()
  }
发现，第一行有输出，第二行报错
   **第一行输出是存在的：**
ƒ initPush() {
        if (_reactNative.Platform.OS == "android") {
          JPushModule.initPush();
        } else {
          JPush.setupPush();
        }
      }
**第二行报错：**node_modules\react-native\Libraries\Core\ExceptionsManager.js:63 Cannot read property 'initPush' of undefined

我使用的版本是：
    "jcore-react-native": "^1.2.9",
    "jpush-react-native": "^2.2.9",
    "react": "16.3.1",
    "react-native": "0.55.4",

**Comment by JoshLipan** [comment]
按照[文档](https://github.com/jpush/jpush-react-native#android-手动操作部分-3-个步骤)检查自己项目配置
