### ISSUE TITLE
希望react native版jpush可以新增检测用户是否开启了推送权限

### ISSUE THREAD

**Issue by sin911** [jpush/jpush-react-native#538]
## 你的运行环境
react naitve ios和android
* 插件版本:
* react-native 版本：
    "jcore-react-native": "1.2.6",
    "jpush-react-native": "2.1.12",
**### 问题**
如果用户初次安装app时,选择不允许推送,那么JPushModule.getRegistrationID方法就不会被执行
**### 希望达到的效果。**
希望react native版jpush可以新增检测用户是否开启了推送权限,这样的话,如果不允许推送,业务上我就不会去使用JPushModule.getRegistrationID方法而去用别的方法代替之.

**Comment by huangminlinux** [comment]
下个版本添加 haspermission 这个 api。

**Comment by huangminlinux** [comment]
可以升级到  + jpush-react-native@2.2.11 版本
```
npm i jpush-react-native@2.2.11
```

**Comment by sin911** [comment]
> 可以升级到 + jpush-react-native@2.2.11 版本
> 
> ```
> npm i jpush-react-native@2.2.11
> ```

多谢啦~
