### ISSUE TITLE
react native ios推送, 接收不到推送的内容

### ISSUE THREAD

**Issue by fisherli** [jpush/jpush-react-native#539]
代码如下.. 根本不会走到alert 

NativeAppEventEmitter.addListener(
            'OpenNotification',
            (notification) => {
                alert('打开推送'+notification);
            }
        )

        NativeAppEventEmitter.addListener(
            'ReceiveNotification',
            (notification) => {
                alert('-------------------收到推送----------------'+notification);
            }
        );

**Comment by fisherli** [comment]
通过后台发送通知. 手机可以收到.. 但是点击消息, 获取不到数据...监听的方法无效...

**Comment by huangminlinux** [comment]
https://github.com/jpush/jpush-react-native/blob/master/documents/api.md#点击推送事件

**Comment by fisherli** [comment]
谢谢. 已经搞定了... documents的目录很重要.  如果能在readme提醒下就更好了
