### ISSUE TITLE
rnpm-link ERR!

### ISSUE THREAD

**Issue by sundou** [jpush/jpush-react-native#54]
rnpm-link ERR! It seems something went wrong while linking. Error: Expected "/*", "//" or "{" but "<" found. 
Please file an issue here: https://github.com/rnpm/rnpm/issues 

rnpm 好像不行

**Comment by huangminlinux** [comment]
这边测试 是没有问题的

➜  jpush-react-plugin git:(master) npm install
·········
➜  jpush-react-plugin git:(master) ✗ sudo rnpm link jpush-react-native
Password:
rnpm-link info Android module jpush-react-native is already linked 
rnpm-link info iOS module jpush-react-native is already linked 



请问的react native 的版本是什么
