### ISSUE TITLE
iOS集成jpush-react-native报错

### ISSUE THREAD

**Issue by chenyao6134** [jpush/jpush-react-native#540]
## 你的运行环境

* 插件版本:
* react-native 版本：最新版本
    "jcore-react-native": "^1.2.9",
    "jpush-react-native": "^2.2.9",
    "native-base": "^2.8.0",
    "prop-types": "^15.6.2",
    "react": "16.4.1",
    "react-native": "0.56.0",
## 重现步骤

按照官方教程link完成以后，,执行pod install,连接真机调试，连接什么cpu架构的机器，就报对应架构的错误：
iPhone5：
![image](https://user-images.githubusercontent.com/8004916/45541632-35841100-b842-11e8-82e9-f73e581b12d2.png)
iPhone8：
![image](https://user-images.githubusercontent.com/8004916/45541752-7aa84300-b842-11e8-9f4c-68c716c2eb07.png)
issue看了一圈，百度也搜索了一圈，没发现解决办法。新建React Native工程也是报同样的错误。

Android上没有问题，可以正常接收推送通知

**Comment by chenyao6134** [comment]
QQ：515171844，紧急

**Comment by huangminlinux** [comment]
社区看到你的问题，在社区里面处理
