### ISSUE TITLE
Execution failed for task ':jcore-react-native:verifyReleaseResources'.

### ISSUE THREAD

**Issue by qiangf811** [jpush/jpush-react-native#541]
## 你的运行环境

* 插件版本:"jcore-react-native": "^1.2.10","jpush-react-native": "^2.2.9",
* react-native 版本：0.56.0

## 期望效果
打包成功

## 实际效果
打包失败：

## 重现步骤
link之后,自动配置如图
![image](https://user-images.githubusercontent.com/18138724/45861053-26024c00-bd9d-11e8-97b4-3d683fdfad90.png)
![image](https://user-images.githubusercontent.com/18138724/45861078-52b66380-bd9d-11e8-83d6-0f2a124720e5.png)

运行react-native run-android
遇到了和https://github.com/jpush/jpush-react-native/issues/523
一样的问题，于是
1. 更改android/build.gradle文件中的，
```
classpath 'com.android.tools.build:gradle:3.1.2'
```
2. /android/gradle/wrapper/gradle-wrapper.properties中修改：
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
```
3. 之后虽然编译成功，但是运行打包APK命令，却报错
4. ...

## Debug logs
```
/Users/qiangf/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/22e5a28dbe4c748e8ccc5a22e56784b8/res/values-v24/values-v24.xml:3:5-157: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/Users/qiangf/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/22e5a28dbe4c748e8ccc5a22e56784b8/res/values-v24/values-v24.xml:4:5-135: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

/Users/qiangf/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/22e5a28dbe4c748e8ccc5a22e56784b8/res/values-v26/values-v26.xml:13:5-16:13: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jcore-react-native:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aap
```

**Comment by JoshLipan** [comment]
把jcore模块的[compileSdkVersion](https://github.com/jpush/jcore-react-native/blob/master/android/build.gradle#L4)和[targetSdkVersion](https://github.com/jpush/jcore-react-native/blob/master/android/build.gradle#L9)也提升到26试下

**Comment by qiangf811** [comment]
> 把jcore模块的[compileSdkVersion](https://github.com/jpush/jcore-react-native/blob/master/android/build.gradle#L4)和[targetSdkVersion](https://github.com/jpush/jcore-react-native/blob/master/android/build.gradle#L9)也提升到26试下
设置了 也不行啊~
![image](https://user-images.githubusercontent.com/18138724/45864097-74b6e280-bdab-11e8-8bed-42d7b626b578.png)
![image](https://user-images.githubusercontent.com/18138724/45864118-85675880-bdab-11e8-87f2-1009d3436a9e.png)

**Comment by JoshLipan** [comment]
现在打包报什么错

**Comment by qiangf811** [comment]
> 把jcore模块的[compileSdkVersion](https://github.com/jpush/jcore-react-native/blob/master/android/build.gradle#L4)和[targetSdkVersion](https://github.com/jpush/jcore-react-native/blob/master/android/build.gradle#L9)也提升到26试下



> 现在打包报什么错

跟之前一样的错误
![image](https://user-images.githubusercontent.com/18138724/45864295-248c5000-bdac-11e8-833d-302f532d64f1.png)

**Comment by JoshLipan** [comment]
这就是说compileSdkVersion和support包版本不匹配的错误，你现在配置来看应该没问题的
你编译打包前clean一下工程，实在不行就把你能成功打包的项目的配置套上去试试

**Comment by JoshLipan** [comment]
把jpush模块的compileSdkVersion和targetSdkVersion也对应改下

**Comment by qiangf811** [comment]
@JoshLipan 万分感谢，可以了，但是出现下面提示，这个可有影响
![image](https://user-images.githubusercontent.com/18138724/45864799-cf513e00-bdad-11e8-97f9-7f195fae6859.png)

**Comment by JoshLipan** [comment]
正常过时API是不影响使用的，你可以测试下

**Comment by weiyy2012** [comment]
@qiangf811  怎么改好的呢  ？
jcore模块的compileSdkVersion和targetSdkVersion也提升到26  这个 在哪里提升？

**Comment by M45ter** [comment]
这些资源是哪里用到，官方没有其他方式解决吗？node_modules下的文件一般是不上传代码库的，自己本地修改感觉不是好的方式
