### ISSUE TITLE
【Android】消息静默推送API？

### ISSUE THREAD

**Issue by 12343954** [jpush/jpush-react-native#545]
## 你的运行环境

```
    "react": "16.4.1",
    "react-native": "0.56.0",
    "jcore-react-native": "^1.2.10",
    "jpush-react-native": "^2.2.11",
```

## 期望效果

iOS推送有静默模式，请问Android有这样的功能吗？

【Android】
APP在前台的时候，不想让消息推送显示到通知栏里，而是想直接显示到app里

## 实际效果

实际上Android的所有推送都显示在通知栏里，如果app在前台，这样UE很不友好。
刚看jpush才2天，可能对高级api还不了解

**Comment by JoshLipan** [comment]
[社区](https://community.jiguang.cn/t/topic/29877)解答，关闭
