### ISSUE TITLE
android报错missing required

### ISSUE THREAD

**Issue by jiangzhx129** [jpush/jpush-react-native#546]
* 插件版本:
    "jcore-react-native": "^1.2.10",
    "jpush-react-native": "^2.2.11"
* react-native 版本：
    "^0.55.4"

按照官网教程集成插件，iOS成功，android有问题：
E/JIGUANG-JPush: [AndroidUtil] AndroidManifest.xml missing required activity: cn.jpush.android.ui.PushActivity
E/JIGUANG-JCore: [AndroidUtil] AndroidManifest.xml missing required service: cn.jpush.android.service.PushService

**Comment by jiangzhx129** [comment]
配置都是根据说明来做的，试过新建项目集成是成功的。有其他排查问题的方式吗

**Comment by jiangzhx129** [comment]
似乎注册RegistrationID就失败了，检查包名也是正确的，配置的内容都对过，实在找不到问题出在哪里

**Comment by JoshLipan** [comment]
log里缺失的配置是在jcore里面配置的，jcore是否成功安装了，两个插件卸载重装试试呢

**Comment by jiangzhx129** [comment]
```
D/JIGUANG-JPush: [JPushInterface] action:init - sdkVersion:3.1.6, buildId:416
D/JIGUANG-JPush: [AndroidUtil] action:checkValidManifest
D/JIGUANG-JCore: [JCoreGlobal] action:init - sdkVersion:1.2.5, buildId:195
E/JIGUANG-JPush: [AndroidUtil] AndroidManifest.xml missing required activity: cn.jpush.android.ui.PushActivity
D/JIGUANG-JCore: [JCoreGlobal] manifest:channel - default
D/JIGUANG-JCore: [AndroidUtil] action:checkValidManifest
E/JIGUANG-JCore: [AndroidUtil] AndroidManifest.xml missing required service: cn.jpush.android.service.PushService
W/JIGUANG-JCore: [JCoreGlobal] JCore init code = 4
```

**Comment by JoshLipan** [comment]
更新最新版本v2.2.12再试下，还有导入AS进行clean和rebuild操作
