### ISSUE TITLE
无法撤回通知?

### ISSUE THREAD

**Issue by leeleoo** [jpush/jpush-react-native#548]
## 你的运行环境

* 插件版本:
    "jcore-react-native": "^1.2.9",
    "jpush-react-native": "^2.2.9",
* react-native 版本：0.54

## 期望效果

我发出了一个在两小时后生效的本地通知,  那么这两小时内有办法撤回这次通知吗

类似官方文档上的removeDeliveredNotifications

## 实际效果

并没有相关 api 

## 重现步骤
无

## Debug logs

无

**Comment by JoshLipan** [comment]
下个版本会添加

**Comment by JoshLipan** [comment]
更新至v2.2.12,新增[clearLocalNotifications](https://github.com/jpush/jpush-react-native/blob/master/documents/api_en.md#clearlocalnotifications)以及[removeLocalNotification](https://github.com/jpush/jpush-react-native/blob/master/documents/api_en.md#removelocalnotification)接口
