### ISSUE TITLE
meta-data 在哪里，没有找到JPUSH_APPKEY 读取的地方

### ISSUE THREAD

**Issue by gelZK** [jpush/jpush-react-native#550]

**Comment by gelZK** [comment]
build.gradle中已经配置了JPUSH_APPKEY，但是在Manifest文件中，没有meta-data

**Comment by JoshLipan** [comment]
按配置文档检查，没有就自己补上，其他配置也一样
![image](https://user-images.githubusercontent.com/16323137/47128737-122b0680-d2c5-11e8-98f6-e2980776018f.png)

**Comment by jamninetyfive** [comment]
@JoshLipan 请问能否增加api 获取 jpush_channel

**Comment by jamninetyfive** [comment]
@JoshLipan 请问能否增加api 获取 jpush_channel

**Comment by JoshLipan** [comment]
jpush_channel 是开发者自己设置的，暂时不提供获取接口
