### ISSUE TITLE
刚才更新mac系统,xCcode,以及最新的jpush后,报如下2张图的错误

### ISSUE THREAD

**Issue by sin911** [jpush/jpush-react-native#555]
* 插件版本:
* react-native 版本：
    "react-native": "^0.57.3",
    "jcore-react-native": "^1.2.10",
    "jpush-react-native": "^2.2.12",
## 期望效果
刚才更新了mac系统和xcode,然后一运行,jpush报错,所以我想着如果把jpush升级到最新版,大概可以解决问题,于是升级jpush和jcore,也react-natie link了一次,可还是报错,报错信息如下2张图,谢谢
http://wx1.sinaimg.cn/large/9ed5c127gy1fwi63bsde1j21el0nwkd5.jpg
http://wx3.sinaimg.cn/large/9ed5c127gy1fwi5xhcbb0j21270lt14v.jpg

**Comment by huangminlinux** [comment]
截图只看到了警告。
