### ISSUE TITLE
最新RN版的jpush的hasPermission方法只能用在ios上,那么安卓怎么检测呢?

### ISSUE THREAD

**Issue by sin911** [jpush/jpush-react-native#557]
首先感谢jpush的程序员开发了hasPermission功能,
但是我看代码里提到ios only,所以,安卓上要怎么判断用户是否允许推送呢?
谢谢
![image](https://user-images.githubusercontent.com/16552337/47550358-93bc0d80-d931-11e8-93a4-7e5b13eb08c8.png)

**Comment by JoshLipan** [comment]
Android 能不能收到推送取决于长连接状态，并不存在什么推送权限

**Comment by sin911** [comment]
> Android 能不能收到推送取决于长连接状态，并不存在什么推送权限

请问安卓判断连接状态,是不是就是图上的getConnectionState方法?谢谢

**Comment by JoshLipan** [comment]
是的
