### ISSUE TITLE
最新xcode10不兼容

### ISSUE THREAD

**Issue by fangkyi03** [jpush/jpush-react-native#558]
Undefined symbols for architecture i386:
  "_kJPFNetworkIsConnectingNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPushNotificationContent", referenced from:
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidSetupNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidCloseNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
      -[RCTJPushModule reactJSDidload] in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPushNotificationTrigger", referenced from:
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidRegisterNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPushNotificationIdentifier", referenced from:
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidLoginNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
      -[RCTJPushModule reactJSDidload] in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPUSHRegisterEntity", referenced from:
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
  "_kJPFNetworkDidReceiveMessageNotification", referenced from:
      -[RCTJPushModule init] in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPushNotificationRequest", referenced from:
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in libRCTJPushModule.a(RCTJPushModule.o)
      objc-class-ref in libRCTJPushModule.a(RCTJPushActionQueue.o)
ld: symbol(s) not found for architecture i386

**Comment by huangminlinux** [comment]
不支持 i386 模拟器，使用 x86 模拟器或真机。

**Comment by chj-damon** [comment]
我在archive的时候也报这个错。
