### ISSUE TITLE
ios archive 报错

### ISSUE THREAD

**Issue by syun0216** [jpush/jpush-react-native#559]
## 你的运行环境 
macOS mojave 版本10.14
* 插件版本:
"jcore-react-native": "^1.2.6",
"jpush-react-native": "^2.2.13",

* react-native 版本：
"react-native": "0.52.2"
## 期望效果
ios打包成功

告诉我们你希望达到什么效果。
ios打包成功

## 实际效果
![image](https://user-images.githubusercontent.com/18444325/47974481-c78ef400-e0e4-11e8-933b-a876126d99e8.png)

告诉我们实际是什么效果。
重新pod install后出现了上面问题,link Binary 已经添加了依赖
![image](https://user-images.githubusercontent.com/18444325/47974572-38cea700-e0e5-11e8-9738-04c3057bb946.png)

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：
Undefined symbols for architecture armv7:
  "_JCORECheckFormatOfMobileNumber", referenced from:
      -[JPUSHService setMobileNumber:completion:] in libjpush-ios-3.1.1.a(JPUSHService.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by huangminlinux** [comment]
jcore 和 jpush 版本是多少？ 可以升级到最新版本试试。

**Comment by syun0216** [comment]
有个问题 就是我既使用了 pod install 又使用了 react-native link是不是我要把link的东西都去掉

**Comment by huangminlinux** [comment]
是的。

**Comment by syun0216** [comment]
用yarn升级了一下jpush-react-native和jcore-react-native问题得到解决:D
