### ISSUE TITLE
[iOS] clearAllNotifications会清除应用的badge值

### ISSUE THREAD

**Issue by pakyo-pan** [jpush/jpush-react-native#566]
## 你的运行环境

* 插件版本:  2.3.0
* react-native 版本：0.57.4

## 期望效果

`clearAllNotifications`只清除通知，不清除应用的`badge`值，因为我可以自己调用setBadge方法。

## 实际效果

你们好，极光开发者！`clearAllNotifications`顾名思义就是清楚通知，但是应用的`badge`值也会被清除，我并不希望清除`badage`值，因为我可以自己调用`setBadge`方法。

**Comment by pakyo-pan** [comment]
我目前的做法，只能先`clearAllNotifications`，再重新`setBadge`。

**Comment by HuminiOS** [comment]
清除通知栏上的通知内部实现就是讲 badge值设为 0

**Comment by pakyo-pan** [comment]
好吧，谢谢，那只能先clearAllNotifications，再重新setBadge。

**Comment by pakyo-pan** [comment]
已解决，使用`clearLocalNotifications`将不会清除badage值
