### ISSUE TITLE
java.io.IOException: Unable to delete directory

### ISSUE THREAD

**Issue by TopGuo** [jpush/jpush-react-native#567]
## 你的运行环境
win10
* 插件版本:
* react-native 版本：
    "jcore-react-native": "^1.2.12",
    "jpush-react-native": "^2.3.0",
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3",
## 实际效果
react-native run-android 
抛异常：

## Debug logs
Configure project :jpush-react-native
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.4.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
包括 Android 或 iOS 的日志：
* What went wrong:
java.io.IOException: Unable to delete directory D:\chuangye\xcaoo\node_modules\jpush-react-native\android\build\generated\source\buildConfig\debug\cn\jpush.
> Unable to delete directory D:\chuangye\xcaoo\node_modules\jpush-react-native\android\build\generated\source\buildConfig\debug\cn\jpush.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by TopGuo** [comment]
## 删除了一个*/../cn的文件，项目跑起来了
但是提示的这个信息很怪异：
Configure project :jpush-react-native
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.4.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :jpush-react-native:compileDebugJavaWithJavac
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: D:\chuangye\xcaoo\node_modules\jpush-react-native\android\src\main\java\cn\jpush\reactnativejpush\JPushModule.java使用了未经检查或不安全的操作。注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :app:installDebug
Installing APK 'app-debug.apk' on 'MI 8 - 8.1.0' for app:debug
Installed on 1 device.
望解决

**Comment by JoshLipan** [comment]
Update to [v2.4.0](https://github.com/jpush/jpush-react-native/releases/tag/2.4.0) and update jcore to [v1.3.0](https://github.com/jpush/jcore-react-native/releases/tag/1.3.0).
