### ISSUE TITLE
Android 点击推送回调不执行

### ISSUE THREAD

**Issue by jarvys** [jpush/jpush-react-native#568]
## 你的运行环境

* 插件版本:
* react-native 版本：0.53.0
* jpush-react-native 版本：2.3.0
* jcore-react-native 版本：1.2.12
* 手机型号：小米 8
* MIUI 版本：9.6 稳定版

## 期望效果

Android 系统下点击推送消息，应该执行回调函数

## 实际效果

在 app 运行状态下，回调也没有执行。

**Comment by 452MJ** [comment]
+1
