### ISSUE TITLE
react-native run-android 报错

### ISSUE THREAD

**Issue by sumjur** [jpush/jpush-react-native#57]
错误日志：

> FAILURE: Build failed with an exception.
> - What went wrong:
>   A problem occurred configuring project ':jpush-react-native'.
>   failed to find Build Tools revision 23.0.2

但是在环境配置的时候，明确要 `Tools/Android SDK Build-tools`  **23.0.1** 这个版本。
- 是版本的问题吗？
- 还是现在环境已经不限制 **23.0.1** 了？

**Comment by KenChoi1992** [comment]
@sumjur 这个是你 Android Studio 相应的 Build Tools 版本，可以在 build.gradle 中修改为你当前的版本。

**Comment by sumjur** [comment]
感谢 @KenChoi1992，安装了 *23.0.2* 版本已解决。

按照 [文档](https://github.com/jpush/jpush-react-native#使用) 和 [example](https://github.com/jpush/jpush-react-native/blob/master/example/android/app/src/com/pushdemo/MainApplication.java)，出现如下错误

> MainApplication.java:19: 错误: 程序包cn.jpush.reactnativejpush不存在
import cn.jpush.reactnativejpush.JPushPackage;

版本
- "jpush-react-native": "^1.1.8",
- "react-native": "^0.32.0",

**Comment by KenChoi1992** [comment]
@sumjur 你在 Android Studio里面有没有看到 jpush-react-native 作为一个 library 导入进来了？

**Comment by KenChoi1992** [comment]
@sumjur  没有疑问的话关闭这个 issue 了。
