### ISSUE TITLE
请问能安装在expo中使用吗？

### ISSUE THREAD

**Issue by dgleung** [jpush/jpush-react-native#572]
## 你的运行环境

* 插件版本:
* react-native 版本：55.4  
expo 30.0.0
 请问能安装在expo中使用吗？

**Comment by huangminlinux** [comment]
占时不支持 expo。

**Comment by huangminlinux** [comment]
js 版（大概这几天会发布）的话可以直接在 expo 中用。

**Comment by deot** [comment]
Expo 37.0.0 开始使用`Bare workflow`; 可以接入极光

**Comment by chj-damon** [comment]
@deot 有文档吗？

**Comment by deot** [comment]
就按照`jpush-react-native`官方的做法就行了，然后修改一下`AppDelegate`

**Comment by chj-damon** [comment]
@deot 大佬，请问你在最新的RN环境里面集成过jPush吗？我这边debug的时候正常，但是release的时候报错。求指点

**Comment by deot** [comment]
iOS这这个部分：debug走的是动态的地址，release走的是本地的文件（也就是说你每次打包的时候要执行一次 `expo publish`, 再次检查下iOS下目录是否存在app.bundle文件）

另外附上我修改了的一个地方
```
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
    #ifdef DEBUG
        // 打开jsbundle, 默认main.jsbundle
        return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
    #else
        // Expo 暂时存在问题, 一直返回null, 给默认值app.bundle;
        return [[EXUpdatesAppController sharedInstance] launchAssetUrl] ?: [[NSBundle mainBundle] URLForResource:@"app" withExtension:@"bundle"];
    #endif
}
```

**Comment by Zhou-Bill** [comment]
@deot  expo 要eject ?

**Comment by Zhou-Bill** [comment]
你好，我安装官网的 pod install 的这种方案，并修改了AppDelegate.m 文件添加了appKey, 可是在模拟器上无法接受推送，想问问是不是模拟器不能接收推送

**Comment by Zhou-Bill** [comment]
@deot 请问，我按照官方的去做，也修改了appDelegate.m, 可是极光那边的推送目标预估人数还是为0，是我错过了什么了吗
以下是我的步骤

1. `yarn add jpush-react-native`
2. `yarn add jcore-react-native`
3.  `expo eject`
4. `npx react-native link jpush-react-native`
5. `npx react-native link jcore-react-native`
6. `cd ios && pod deintegrate`
7.  `pod install`
8 .  也上传了p12, 修改了bundle Id, 也修改了appDelegate.m

**Comment by dzcpy** [comment]
各位有成功用expo集成极光的了吗？

**Comment by bbhxwl** [comment]
还有人成功过么。
