### ISSUE TITLE
ios报错 stopPush is not a funtion

### ISSUE THREAD

**Issue by xiaoqian9** [jpush/jpush-react-native#573]
## 你的运行环境

* 插件版本:
* react-native 版本：0.44
jpush 版本 2.1.6
## 期望效果

告诉我们你希望达到什么效果。

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：
![image](https://user-images.githubusercontent.com/20238870/50211745-549bbd00-03b4-11e9-9d47-c5cfd92cfc03.png)

**Comment by xiaoqian9** [comment]
想做个用户在app中设置接收消息开关的功能

**Comment by xiaoqian9** [comment]
源码
` setStatus = () => {
    const status = !this.state.pushStatus;
    this.setState({ pushStatus: status });
    setPushStatus(status);
    if (!status) {
      if (Platform.OS === 'android')
        JPushModule.initPush();
        
      JPushModule.stopPush();
    } else {
      if (Platform.OS === 'ios') {
        JPushModule.setupPush();
      } else {
        JPushModule.resumePush();
      }
    }
  };`

`<Switch value={this.state.pushStatus} onValueChange={this.setStatus} />`

**Comment by xiaoqian9** [comment]
源码
`setStatus = () => {
    const status = !this.state.pushStatus;
    this.setState({ pushStatus: status });
    setPushStatus(status);
    if (!status) {
      if (Platform.OS === 'android')
        JPushModule.initPush();
      JPushModule.stopPush();
    } else {
      if (Platform.OS === 'ios') {
        JPushModule.setupPush();
      } else {
        JPushModule.resumePush();
      }
    }
  };`

`<Switch value={this.state.pushStatus} onValueChange={this.setStatus} />`

**Comment by xiaoqian9** [comment]
源码
`setStatus = () => {
    const status = !this.state.pushStatus;
    this.setState({ pushStatus: status });
    setPushStatus(status);
    if (!status) {
      if (Platform.OS === 'android') {
        JPushModule.initPush();
      }
      JPushModule.stopPush();
    } else {
      if (Platform.OS === 'ios') {
        JPushModule.setupPush();
      } else {
        JPushModule.resumePush();
      }
    }
  };`

‘<Switch value={this.state.pushStatus} onValueChange={this.setStatus} />’

**Comment by huangminlinux** [comment]
可以升级到 2.5.0

**Comment by xiaoqian9** [comment]
> 可以升级到2.5.0

试过了，貌似还是不行啊。
jcore 的需要升级吗？我用的是 1.1.3

**Comment by huangminlinux** [comment]
@xiaoqian9 其他的接口都没问题？ 如果其他接口也有问题可能是没有  link 成功。

**Comment by xiaoqian9** [comment]
所以 react-native link 试试？

**Comment by huangminlinux** [comment]
react-native link 也不能保证一定能成功，最好是检查  RCTJPushModule 有没添加到工程，如果没有添加，就手动 link。

**Comment by xiaoqian9** [comment]
重新link 解决问题
