### ISSUE TITLE
请问这个SDK是否包含极光VIP推送的功能，也就是各大厂商的SDK

### ISSUE THREAD

**Issue by jamninetyfive** [jpush/jpush-react-native#579]
请问这个SDK是否包含极光VIP推送的功能，也就是各大厂商的SDK

我们需要进行付费使用VIP功能，请问是否可以支持？

## 你的运行环境

* 插件版本:
* react-native 版本：

## 期望效果

告诉我们你希望达到什么效果。

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by jamninetyfive** [comment]
意思是买了VIP 个大厂商的功能就可以使用吗。不需要额外集成什么吧～

**Comment by JoshLipan** [comment]
需要加入几个厂商的SDK，但代码逻辑不需要改动，具体请咨询[商务](https://www.jiguang.cn/accounts/business_contact?fromPage=index)

**Comment by jamninetyfive** [comment]
加入厂商的SDK 也是 react-native 的方式去集成么？
不是按照厂商的文档来集成吧，因为厂商一般都不支持react-native～

**Comment by JoshLipan** [comment]
不涉及RN，厂商 Android 在原生目录集成，iOS 不需要额外集成，我们支持会指导你怎么做的。

**Comment by jamninetyfive** [comment]
好的 谢谢你的回复！
