### ISSUE TITLE
ios编译错误

### ISSUE THREAD

**Issue by http-lbw** [jpush/jpush-react-native#582]
"react-native": "0.52.2",
"jcore-react-native": "^1.2.9",
 "jpush-react-native": "^2.2.9",
ios跑真机报错
ld: 779 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
尝试过重新link之后还是无效

**Comment by huangminlinux** [comment]
看错误是 load 了重复的代码或库。
你的集成方式描述一下。

**Comment by http-lbw** [comment]
集成方式就是link的

**Comment by huangminlinux** [comment]
有完整错误日志吗？

**Comment by http-lbw** [comment]
duplicate symbol _OBJC_METACLASS_$_JPUSHLoggerNode in:
    /Users/hefoni/Documents/ride_app/node_modules/jcore-react-native/ios/RCTJCoreModule/libjcore-ios.a(JPUSHLog.o)
    /Users/hefoni/Library/Developer/Xcode/DerivedData/ride_app-guvoeuwidmgvmnbivfvhoqbrctxh/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHLog.o)
duplicate symbol _OBJC_IVAR_$_JPUSHLogMessage._threadID in:
    /Users/hefoni/Documents/ride_app/node_modules/jcore-react-native/ios/RCTJCoreModule/libjcore-ios.a(JPUSHLog.o)
    /Users/hefoni/Library/Developer/Xcode/DerivedData/ride_app-guvoeuwidmgvmnbivfvhoqbrctxh/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHLog.o)
duplicate symbol _OBJC_CLASS_$_JPUSHHeartbeatRequest in:
    /Users/hefoni/Documents/ride_app/node_modules/jcore-react-native/ios/RCTJCoreModule/libjcore-ios.a(JPUSHHeartbeat.o)
    /Users/hefoni/Library/Developer/Xcode/DerivedData/ride_app-guvoeuwidmgvmnbivfvhoqbrctxh/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHHeartbeat.o)
duplicate symbol _OBJC_METACLASS_$_JPUSHHeartbeatRequest in:
    /Users/hefoni/Documents/ride_app/node_modules/jcore-react-native/ios/RCTJCoreModule/libjcore-ios.a(JPUSHHeartbeat.o)
    /Users/hefoni/Library/Developer/Xcode/DerivedData/ride_app-guvoeuwidmgvmnbivfvhoqbrctxh/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHHeartbeat.o)
duplicate symbol _OBJC_CLASS_$_JPUSHHeartbeatResponse in:
    /Users/hefoni/Documents/ride_app/node_modules/jcore-react-native/ios/RCTJCoreModule/libjcore-ios.a(JPUSHHeartbeat.o)
    /Users/hefoni/Library/Developer/Xcode/DerivedData/ride_app-guvoeuwidmgvmnbivfvhoqbrctxh/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHHeartbeat.o)
duplicate symbol _OBJC_METACLASS_$_JPUSHHeartbeatResponse in:
    /Users/hefoni/Documents/ride_app/node_modules/jcore-react-native/ios/RCTJCoreModule/libjcore-ios.a(JPUSHHeartbeat.o)
    /Users/hefoni/Library/Developer/Xcode/DerivedData/ride_app-guvoeuwidmgvmnbivfvhoqbrctxh/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHHeartbeat.o)
duplicate symbol _OBJC_CLASS_$_JPUSHReportCacheController in:
    /Users/hefoni/Documents/ride_app/node_modules/jcore-react-native/ios/RCTJCoreModule/libjcore-ios.a(JPUSHReportCacheController.o)
    /Users/hefoni/Library/Developer/Xcode/DerivedData/ride_app-guvoeuwidmgvmnbivfvhoqbrctxh/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHReportCacheController.o)
duplicate symbol _OBJC_METACLASS_$_JPUSHReportCacheController in:
    /Users/hefoni/Documents/ride_app/node_modules/jcore-react-native/ios/RCTJCoreModule/libjcore-ios.a(JPUSHReportCacheController.o)
    /Users/hefoni/Library/Developer/Xcode/DerivedData/ride_app-guvoeuwidmgvmnbivfvhoqbrctxh/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHReportCacheController.o)
duplicate symbol _OBJC_IVAR_$_JPUSHReportCacheController._syncBlock in:
    /Users/hefoni/Documents/ride_app/node_modules/jcore-react-native/ios/RCTJCoreModule/libjcore-ios.a(JPUSHReportCacheController.o)
    /Users/hefoni/Library/Developer/Xcode/DerivedData/ride_app-guvoeuwidmgvmnbivfvhoqbrctxh/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHReportCacheController.o)
duplicate symbol _OBJC_IVAR_$_JPUSHReportCacheController._sendingPackageCache in:
    /Users/hefoni/Documents/ride_app/node_modules/jcore-react-native/ios/RCTJCoreModule/libjcore-ios.a(JPUSHReportCacheController.o)
    /Users/hefoni/Library/Developer/Xcode/DerivedData/ride_app-guvoeuwidmgvmnbivfvhoqbrctxh/Build/Products/Debug-iphoneos/libRCTJCoreModule.a(JPUSHReportCacheController.o)
ld: 779 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

还有很多类似这种的

**Comment by huangminlinux** [comment]
除了 jpush-react-native 和 jcore-react-native 还引入了什么其他库没？

**Comment by http-lbw** [comment]
amap-3d地图，还有播放语音的sound，

**Comment by TloyMa** [comment]
我也遇到了这个错误，没有其他库。只有jpush-react-native 和 jcore-react-native这两个库

**Comment by huangminlinux** [comment]
你们是不是 react-native link 之后有通过了pod install 安装了一次？
