### ISSUE TITLE
ios 报 symbol(s) not found for architecture arm64 

### ISSUE THREAD

**Issue by xiaoqian9** [jpush/jpush-react-native#583]
## 你的运行环境

* 插件版本:
* react-native 版本：0.44

## 期望效果
真机安装调试

## 实际效果
模拟器可以顺利安装并调试，真机一直提示这个错误。
我把 (~/Library/Developer/Xcode/DerivedData/) 的缓存全都清除了还是不行～

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs
Undefined symbols for architecture arm64:
  "_JCORECheckFormatOfMobileNumber", referenced from:
      -[JPUSHService setMobileNumber:completion:] in libRCTJPushModule.a(JPUSHService.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

![image](https://user-images.githubusercontent.com/20238870/50431046-cae37680-0902-11e9-8ccd-4dd0e855bba8.png)

**Comment by huangminlinux** [comment]
- 可能是 jcore 和 jpush 版本不匹配，将 jpush-react-native  和 jcore-react-native 插件升级到最新版本
- 也可能是 jcore 没有 link 成功。

**Comment by xiaoqian9** [comment]
我 jcore 用 1.2.5 应该没问题，还有我很确定link成功了

**Comment by huangminlinux** [comment]
```
jcore-react-native@1.3.0
jpush-react-native@2.3.0 
```
用这个版本没有问题，可以升级到这个版本，重新安装后建议 clean  rebuild

**Comment by xiaoqian9** [comment]
装了你说的版本，阔以鸟！！！

灰常感谢～！！

**Comment by freyzou** [comment]
@huangminlinux  Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64

**Comment by jaysonjh** [comment]
> @huangminlinux Undefined symbols for architecture arm64:
> "_OBJC_CLASS_$_JPUSHService", referenced from:
> objc-class-ref in AppDelegate.o
> ld: symbol(s) not found for architecture arm64
> 
> 注：用的你上面说的版本，求助大神，急啊
> 
> 下面是用CocoaPods集成出现的问题：
> Undefined symbols for architecture arm64:
> "_JPUSHStringHashingByMD5", referenced from:
> -[JPUSHBadgeNumberReportRequest p_generateRequestHead] in libjpush-ios-3.1.1.a(JPUSHBadgeNumberReport.o)
> "_OBJC_METACLASS_$_JPUSHReportResponse", referenced from:
> _OBJC_METACLASS_$_JPUSHMessageReportResponse in libjpush-ios-3.1.1.a(JPUSHMessageReport.o)
> _OBJC_METACLASS_$_JPUSHBadgeNumberReportResponse in libjpush-ios-3.1.1.a(JPUSHBadgeNumberReport.o)
> "_OBJC_METACLASS_$_JPUSHReportRequest", referenced from:
> _OBJC_METACLASS_$_JPUSHMessageReportRequest in libjpush-ios-3.1.1.a(JPUSHMessageReport.o)
> _OBJC_METACLASS_$_JPUSHBadgeNumberReportRequest in libjpush-ios-3.1.1.a(JPUSHBadgeNumberReport.o)
> "_OBJC_CLASS_$_JPUSHFileHelper", referenced from:
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHTagAlias.o)
> "_OBJC_CLASS_$_JPUSHRequest", referenced from:
> _OBJC_CLASS_$_JPUSHAliasRequest in libjpush-ios-3.1.1.a(JPUSHAliasOperation.o)
> _OBJC_CLASS_$_JPUSHTagsRequest in libjpush-ios-3.1.1.a(JPUSHTagsOperation.o)
> _OBJC_CLASS_$_JPUSHUserPropertyRequest in libjpush-ios-3.1.1.a(JPUSHUserProperty.o)
> _OBJC_CLASS_$_JPUSHSetTagAlias in libjpush-ios-3.1.1.a(JPUSHSetTagAlias.o)
> "_OBJC_CLASS_$_JPUSHReportResponse", referenced from:
> _OBJC_CLASS_$_JPUSHMessageReportResponse in libjpush-ios-3.1.1.a(JPUSHMessageReport.o)
> _OBJC_CLASS_$_JPUSHBadgeNumberReportResponse in libjpush-ios-3.1.1.a(JPUSHBadgeNumberReport.o)
> "_JPUSHGetCurrentTimestamp", referenced from:
> -[JPUSHTagAlias setTagAliasUsingCallback:] in libjpush-ios-3.1.1.a(JPUSHTagAlias.o)
> -[JPUSHTagAliasManagerController tagOperate:type:andCompletion:andSeq:] in libjpush-ios-3.1.1.a(JPUSHTagAliasManagerController.o)
> -[JPUSHTagAliasManagerController aliasOperate:type:andCompletion:andSeq:] in libjpush-ios-3.1.1.a(JPUSHTagAliasManagerController.o)
> -[JPUSHTagAliasManagerController handleServerUnavaiableResponseWith:andContent:] in libjpush-ios-3.1.1.a(JPUSHTagAliasManagerController.o)
> -[JPUSHTagAliasManagerController isFreezeReport] in libjpush-ios-3.1.1.a(JPUSHTagAliasManagerController.o)
> "_OBJC_CLASS_$_JPUSHReceivedPacketController", referenced from:
> _OBJC_CLASS_$_JPUSHAliasResponse in libjpush-ios-3.1.1.a(JPUSHAliasOperation.o)
> _OBJC_CLASS_$_JPUSHTagsResponse in libjpush-ios-3.1.1.a(JPUSHTagsOperation.o)
> "_JPUSHDecodeDataFromBuffer", referenced from:
> -[JPUSHAliasResponse initWithBuffer:length:] in libjpush-ios-3.1.1.a(JPUSHAliasOperation.o)
> -[JPUSHTagsResponse initWithBuffer:length:] in libjpush-ios-3.1.1.a(JPUSHTagsOperation.o)
> "_JPUSHJSONObject", referenced from:
> -[JPUSHAliasResponse initWithBuffer:length:] in libjpush-ios-3.1.1.a(JPUSHAliasOperation.o)
> -[JPUSHTagAlias doSetTagsAliasCallbackWithRetJson:] in libjpush-ios-3.1.1.a(JPUSHTagAlias.o)
> -[JPUSHTagsResponse initWithBuffer:length:] in libjpush-ios-3.1.1.a(JPUSHTagsOperation.o)
> "_JPUSHConvertTokenDataToString", referenced from:
> -[JPUSHDeviceTokenController judgeAndSetDeviceToken:] in libjpush-ios-3.1.1.a(JPUSHDeviceTokenController.o)
> "_OBJC_IVAR_$_JPUSHRequest._packetData", referenced from:
> -[JPUSHAliasRequest packData] in libjpush-ios-3.1.1.a(JPUSHAliasOperation.o)
> -[JPUSHTagsRequest packData] in libjpush-ios-3.1.1.a(JPUSHTagsOperation.o)
> -[JPUSHUserPropertyRequest packData] in libjpush-ios-3.1.1.a(JPUSHUserProperty.o)
> -[JPUSHSetTagAlias packData] in libjpush-ios-3.1.1.a(JPUSHSetTagAlias.o)
> "_OBJC_CLASS_$_JPUSHReportRequest", referenced from:
> _OBJC_CLASS_$_JPUSHMessageReportRequest in libjpush-ios-3.1.1.a(JPUSHMessageReport.o)
> _OBJC_CLASS_$_JPUSHBadgeNumberReportRequest in libjpush-ios-3.1.1.a(JPUSHBadgeNumberReport.o)
> "_JPUSHJSONData", referenced from:
> -[JPUSHAliasRequest packData] in libjpush-ios-3.1.1.a(JPUSHAliasOperation.o)
> -[JPUSHTagsRequest packData] in libjpush-ios-3.1.1.a(JPUSHTagsOperation.o)
> -[JPUSHBadgeNumberReportRequest packetData] in libjpush-ios-3.1.1.a(JPUSHBadgeNumberReport.o)
> -[JPUSHSetTagAlias requestJsonData] in libjpush-ios-3.1.1.a(JPUSHSetTagAlias.o)
> "_OBJC_CLASS_$_JCOREInterface", referenced from:
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHService.o)
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHClientController.o)
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHSetTagAliasArg.o)
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHBadgeNumberController.o)
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHDeviceTokenController.o)
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHTagAlias.o)
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHTagAliasManagerController.o)
> ...
> "_kJPFNetworkDidRegisterNotification", referenced from:
> -[RCTJPushModule init] in RCTJPushModule.o
> "_JCORECheckFormatOfMobileNumber", referenced from:
> -[JPUSHService setMobileNumber:completion:] in libjpush-ios-3.1.1.a(JPUSHService.o)
> "_kJPFNetworkDidSetupNotification", referenced from:
> -[RCTJPushModule init] in RCTJPushModule.o
> "_kJPFNetworkDidReceiveMessageNotification", referenced from:
> -[RCTJPushModule init] in RCTJPushModule.o
> "_OBJC_METACLASS_$_JPUSHRequest", referenced from:
> _OBJC_METACLASS_$_JPUSHAliasRequest in libjpush-ios-3.1.1.a(JPUSHAliasOperation.o)
> _OBJC_METACLASS_$_JPUSHTagsRequest in libjpush-ios-3.1.1.a(JPUSHTagsOperation.o)
> _OBJC_METACLASS_$_JPUSHUserPropertyRequest in libjpush-ios-3.1.1.a(JPUSHUserProperty.o)
> _OBJC_METACLASS_$_JPUSHSetTagAlias in libjpush-ios-3.1.1.a(JPUSHSetTagAlias.o)
> "_OBJC_CLASS_$_JPUSHResponse", referenced from:
> _OBJC_CLASS_$_JPUSHUserPropertyResponse in libjpush-ios-3.1.1.a(JPUSHUserProperty.o)
> "_kJPFNetworkIsConnectingNotification", referenced from:
> -[RCTJPushModule init] in RCTJPushModule.o
> "_OBJC_METACLASS_$_JPUSHReceivedPacketController", referenced from:
> _OBJC_METACLASS_$_JPUSHAliasResponse in libjpush-ios-3.1.1.a(JPUSHAliasOperation.o)
> _OBJC_METACLASS_$_JPUSHTagsResponse in libjpush-ios-3.1.1.a(JPUSHTagsOperation.o)
> "_OBJC_CLASS_$_JPUSHLog", referenced from:
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHService.o)
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHClientController.o)
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHLocalNotificationController.o)
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHBadgeNumberController.o)
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHDeviceTokenController.o)
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHTagAlias.o)
> objc-class-ref in libjpush-ios-3.1.1.a(JPUSHUserPropertyController.o)
> ...
> "_OBJC_METACLASS_$_JPUSHResponse", referenced from:
> _OBJC_METACLASS_$_JPUSHUserPropertyResponse in libjpush-ios-3.1.1.a(JPUSHUserProperty.o)
> "_JCOREDisplayVersion", referenced from:
> ___92+[JPUSHService commonSetupWithOption:appKey:channel:apsForProduction:advertisingIdentifier:]_block_invoke in libjpush-ios-3.1.1.a(JPUSHService.o)
> "_JPUSHBase64", referenced from:
> -[JPUSHBadgeNumberReportRequest p_generateRequestHead] in libjpush-ios-3.1.1.a(JPUSHBadgeNumberReport.o)
> "_JCOREGetBuildVersion", referenced from:
> ___92+[JPUSHService commonSetupWithOption:appKey:channel:apsForProduction:advertisingIdentifier:]_block_invoke in libjpush-ios-3.1.1.a(JPUSHService.o)
> "_kJPFNetworkDidCloseNotification", referenced from:
> -[RCTJPushModule init] in RCTJPushModule.o
> -[RCTJPushModule reactJSDidload] in RCTJPushModule.o
> "_kJPFNetworkDidLoginNotification", referenced from:
> -[RCTJPushModule init] in RCTJPushModule.o
> -[RCTJPushModule reactJSDidload] in RCTJPushModule.o
> -[JPUSHClientController observeNotifications] in libjpush-ios-3.1.1.a(JPUSHClientController.o)
> -[JPUSHClientController unobserveNotifications] in libjpush-ios-3.1.1.a(JPUSHClientController.o)
> ld: symbol(s) not found for architecture arm64

我也遇到这个问题
