### ISSUE TITLE
华为系统在发送多条通知时，消息会自动堆叠，直接点堆叠窗口会导致app总再打开一个app

### ISSUE THREAD

**Issue by 357280841** [jpush/jpush-react-native#585]
## 你的运行环境
jpush/jpush-react-native master
{
  "name": "Example",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "dev:start": "yarn dev && yarn start",
    "ios": "react-native run-ios",
    "android": "react-native run-android",
    "dev:ios": "yarn dev && yarn ios",
    "dev:android": "yarn dev && yarn android",
    "dev": "cp ../../src/* node_modules/react-native-router-flux/src/",
    "test": "jest"
  },
  "dependencies": {
    "jcore-react-native": "^1.3.0",
    "jpush-react-native": "^2.5.0",
    "prop-types": "^15.6.2",
    "react": "16.5.0",
    "react-native": "0.57.1",
    "react-native-button": "^2.3.0",
    "react-native-message-bar": "^2.0.10",
    "react-native-router-flux": "^4.0.4",
    "react-native-screens": "^1.0.0-alpha.12",
    "react-navigation": "2.x",
    "react-navigation-deprecated-tab-navigator": "^1.3.0",
    "react-navigation-stack": "^0.6.0"
  },
  "devDependencies": {
    "@babel/code-frame": "^7.0.0",
    "@babel/core": "^7.1.0",
    "@babel/plugin-proposal-decorators": "^7.1.0",
    "@babel/plugin-transform-runtime": "^7.1.0",
    "@babel/runtime": "^7.0.0",
    "autobind-decorator": "^2.1.0",
    "babel-core": "^7.0.0-0",
    "babel-jest": "^23.6.0",
    "jest": "^23.6.0",
    "metro-react-native-babel-preset": "^0.45.0",
    "react-test-renderer": "16.5.2",
    "schedule": "0.4.0"
  },
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-navigation|react-navigation-(tabs|drawer|deprecated-tab-navigator|stack))"
    ],
    "setupFiles": [
      "./test/setup.js"
    ]
  }
}

* 插件版本:
* react-native 版本：
"jcore-react-native": "^1.3.0",
"jpush-react-native": "^2.5.0",

## 期望效果

重现激活app

## 实际效果

在app内嵌启动一个新的app

## 重现步骤

1、【发送通知】发送多条消息时候，华为系统，荣耀v10系统，多条消息会自动堆叠；
2、如果app处于激活状态时，直接堆叠在一起的消息后，会导致程序异常；

## Debug logs

包括 Android 或 iOS 的日志：

华为系统在发送多条通知时，消息会自动堆叠，直接点堆叠窗口会导致app总再打开一个app；
使用jpush-react-native测试，有同样的问题；

我临时使用JPushModule.setLatestNotificationNumber(1)让消息不在通知栏中出现多条导致的堆叠问题；

该问题有没有更好的处理方法？

**Comment by JoshLipan** [comment]
再打开一个 APP？Android 系统应该不允许单应用同时开两个进程吧

**Comment by jamninetyfive** [comment]
> 再打开一个 APP？Android 系统应该不允许单应用同时开两个进程吧

same here！这个问题应该被打开。
因为确实在手机通知推送同时存在多条的时候
点击推送就会再次打开一个APP 覆盖在上面。
![image](https://user-images.githubusercontent.com/5283666/51449677-22d99580-1d68-11e9-8e94-ee91fe29fad7.png)
如上图

**Comment by EvanMaFYH** [comment]
一样的问题，怎么解决，不让消息堆叠也不太合适

**Comment by jamninetyfive** [comment]
@JoshLipan

**Comment by JoshLipan** [comment]
华为什么型号的，系统版本多少，我们这边测一下

**Comment by EvanMaFYH** [comment]
@JoshLipan 应该和手机没有太多关系，我用魅族手机也试了下一样的问题，复现方式是在app处于active的状态发送多条通知，使得通知在通知栏堆叠，然后不展开通知，直接点击，这个时候app会再次启动，按返回退出app会发现还有一个app处于active状态
如果在通知栏已经已经堆叠了好几条通知之后再启动app然后再点击堆叠的通知就不会出现这样的问题

**Comment by EvanMaFYH** [comment]
测试的两个手机型号：
华为荣耀8 Android8.0.0
魅族魅蓝Note6 Android 7.1.2

**Comment by HappyGB** [comment]
how to solve this issue? anyone help?

**Comment by Amos729** [comment]
> 再打开一个 APP？Android 系统应该不允许单应用同时开两个进程吧

我这边现在也有这个问题，测试直接提了bug，目前还没有解决，请问这是怎么回事？

**Comment by Amos729** [comment]
> > 再打开一个 APP？Android 系统应该不允许单应用同时开两个进程吧
> 
> same here！这个问题应该被打开。
> 因为确实在手机通知推送同时存在多条的时候
> 点击推送就会再次打开一个APP 覆盖在上面。
> ![image](https://user-images.githubusercontent.com/5283666/51449734-5a484200-1d68-11e9-9b2c-8b42d944dec0.png)
> 
> 如上图 4条推送消息 如果直接点击 就会打开一个app盖在上面。
> 如果点击展开具体的去点击某一条推送 就没有问题～


哥们这个问题解决了吗？

**Comment by JoshLipan** [comment]
找到[对应代码](https://github.com/jpush/jpush-react-native/blob/master/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java#L640)尝试更改启动模式，这里可以去掉 Intent.FLAG_ACTIVITY_NEW_TASK 试下
```
intent.setFlags( Intent.FLAG_ACTIVITY_SINGLE_TOP | Intent.FLAG_ACTIVITY_CLEAR_TOP);
```

**Comment by Amos729** [comment]
> 找到[对应代码](https://github.com/jpush/jpush-react-native/blob/master/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java#L640)尝试更改启动模式，这里可以去掉 Intent.FLAG_ACTIVITY_NEW_TASK 试下
> 
> ```
> intent.setFlags( Intent.FLAG_ACTIVITY_SINGLE_TOP | Intent.FLAG_ACTIVITY_CLEAR_TOP);
> ```

@JoshLipan 感谢回答，试过去掉你说的`Intent.FLAG_ACTIVITY_NEW_TASK `, 但是还是一样没效果
