### ISSUE TITLE
Build input file cannot be found: '.../RCTJPushModule/libjpush-ios-3.1.1.a'

### ISSUE THREAD

**Issue by pakyo-pan** [jpush/jpush-react-native#590]
## 你的运行环境

* 插件版本:    jcore-react-native: 1.3.1    jpush-react-native: 2.5.1
* react-native 版本：  react-native: 0.57.7

## 实际效果

`jpush-react-native: 2.5.1`版本，`Xcode` -> `Product` -> `Archive` 报错。
但是我重新安装`jpush-react-native: 2.5.0`版本，可以顺利打包，没有问题。

## 重现步骤

1. `npm install jpush-react-native jcore-react-native --save`
2. `react-native link`
3. 输入 `appKey`
4. (按照文档一步步配置)...
5. `Xcode` -> `Product` -> `Archive`

## Debug logs

iOS 的日志：
![image](https://user-images.githubusercontent.com/13342613/51112956-706f7300-183b-11e9-9d2e-170c99f657ab.png)

**Comment by huangminlinux** [comment]
这边测试没有问题，检查升级的时候时候有残留配置。

**Comment by pakyo-pan** [comment]
我刚才又尝试了一下`jpush-react-native: 2.5.1`版本，一切正常。不知道之前的问题是什么原因导致的，非常抱歉。另外，谢谢你的回复。
