### ISSUE TITLE
rn 0.56.0安卓编译报错

### ISSUE THREAD

**Issue by LCJ-MinYa** [jpush/jpush-react-native#593]
## 你的运行环境

* 插件版本:
* react-native 版本：0.56.0

## 期望效果

告诉我们你希望达到什么效果。

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

"jcore-react-native": "^1.3.1"
"jpush-react-native": "^2.5.1"

"react-native": "0.56.0" gradle 2.3.3
安卓编译报implementation()这个方法找不到，改为compile()这个方法，在node_module的jpush-react-native中有个地方又报api方法错误

尝试过升级com.android.tools.build:gradle:2.3.3 =》 3.1.0
distributionUrl=https\://services.gradle.org/distributions/gradle-3.5.1-all.zip =》 4.4

"jcore-react-native": "^1.3.1" => 降级2.2.10
"jpush-react-native": "^2.5.1"=>降级1.2.10
都有各种报错，求问官方有解决方法不？

**Comment by JoshLipan** [comment]
尝试过升级com.android.tools.build:gradle:2.3.3 =》 3.1.0，升级到3以上应该就可以用最新插件了
