### ISSUE TITLE
SetAlias 方法执行，但是回调没有走

### ISSUE THREAD

**Issue by SunRainMi** [jpush/jpush-react-native#596]
## 你的运行环境

* 插件版本:
* react-native 版本：0.55.4
*"jpush-react-native": "^2.2.9",
*"jcore-react-native": "^1.3.1",

## 期望效果
setAilas，以及addTags 回调方法执行
## 实际效果
setAilas，以及addTags 回调方法未执行

## 重现步骤

1.
![image](https://user-images.githubusercontent.com/18442533/53141749-4c3a4b00-35cc-11e9-94e2-f3f4d6f28614.png)

2. 
![image](https://user-images.githubusercontent.com/18442533/53141798-7f7cda00-35cc-11e9-984c-98dc84817b0a.png)
3.
![image](https://user-images.githubusercontent.com/18442533/53141840-a4714d00-35cc-11e9-8884-25c9ea7cfd8b.png)

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by SunRainMi** [comment]
iOS需要真机调试，才调用此方法

**Comment by whereiscode** [comment]
谁说的  模拟器也可以
