### ISSUE TITLE
请问有做对android 8.0 推送新增NotificationChannel的处理吗？

### ISSUE THREAD

**Issue by ljmkimqx** [jpush/jpush-react-native#597]
我在集成的jpush-react-native里搜索NotificationChannel并没有搜索到，如果还没做NotificationChannel的处理，有什么临时的解决办法可以让android 8.0收到推送呢

**Comment by JoshLipan** [comment]
Jpush 原生 SDK 默认通知对这一块已经适配过了，用插件接收通知没有问题
