### ISSUE TITLE
未在manifest中配置Appkey

### ISSUE THREAD

**Issue by xiaochao** [jpush/jpush-react-native#603]
所有的操作和官方给的文档一模一样，但是APP启动的时候，提示：未在manifest中配置Appkey

**Comment by xiaochao** [comment]
android Logcat 相关输出：

E/JIGUANG-JCore: [JCoreGlobal] errorcode:10001,metadata: JCore appKey - not defined in manifest

**Comment by wm20111003** [comment]
为什么关掉了？我也遇到了同样的问题；请问楼主解决了吗？

**Comment by matuanc** [comment]
https://github.com/jpush/jpush-react-native/issues/725
