### ISSUE TITLE
android收到通知不弹出显示

### ISSUE THREAD

**Issue by xiaochao** [jpush/jpush-react-native#604]
收到通知后，只在状态栏有提示，收到通知消息，但是却没有弹出个消息框，显示通知详情，请问这个如何实现。

**Comment by JoshLipan** [comment]
你说的弹出消息框具体指什么？

**Comment by JoshLipan** [comment]
这个不是SDK设置的，需要用户在通知栏设置允许悬浮通知

![image](https://user-images.githubusercontent.com/16323137/54183402-0abc0200-44df-11e9-9763-4f24b90dbf34.png)

**Comment by xiaochao** [comment]
这个悬浮通知，如何判断用户是否开启了 @JoshLipan

**Comment by JoshLipan** [comment]
没有提供这种接口判断

**Comment by benny-tw** [comment]
@JoshLipan 请问最新的库会如何处理这个问题呢？
2.5.11的版本没有hasPermission这个接口了。请指教,谢谢
