### ISSUE TITLE
Android 安卓下 无法获取到 rid ： JPushModule.getRegistrationID

### ISSUE THREAD

**Issue by orzhtml** [jpush/jpush-react-native#610]
## 你的运行环境
Android
* 插件版本:
"jcore-react-native": "^1.3.1",
"jpush-react-native": "^2.5.3",
* react-native 版本：
IDEs:
      Android Studio: EAP AI-171.4010489 AI-171.4010489
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.5 => 0.57.5 
    npmGlobalPackages:
      eslint-plugin-react-native: 3.5.0
      react-native-cli: 2.0.1
## 期望效果
希望是能获取到rid

## 实际效果
Android 配置好后，无法获取到rid，JPushModule.getRegistrationID 返回的是空数据
我用JPushModule.hasPermission检查已经获取到了通知授权，就是没有rid返回

## Debug logs
没有错误

包括 Android 或 iOS 的日志：

**Comment by JoshLipan** [comment]
初始化调用了吗

**Comment by liganghui** [comment]
我有同样的问题  , 请问你解决了么 ?

我的运行截图和代码
![Screenshot_20190521-155107](https://user-images.githubusercontent.com/15844198/58078076-76f26a80-7be0-11e9-92d2-37c924fbcb66.jpg)
![{FFB8713E-774D-4013-A0F7-B029F12E8031}_20190521155019](https://user-images.githubusercontent.com/15844198/58078098-85408680-7be0-11e9-880e-3e619cacf248.jpg)

## 版本信息
android 8.0 
react-native 0.59.3
jcore-react-native": "^1.3.2",
jpush-react-native": "^2.5.3",

**Comment by liganghui** [comment]
后续补充 :  我找到了问题原因  , 是 极光开发者服务-->应用设置--->推送设置---> 应用包名 设置有误。
Android正确的包名应参考  /android/app/build.gradle 中的 defaultConfig { applicationId "com.xxxxxxxx" }
我输入包名时 , 打错一个字母导致了该问题 :sob:

**Comment by orzhtml** [comment]
安卓需要初始化，否则就无法获取rid
