### ISSUE TITLE
Hide Notification when App on Foreground

### ISSUE THREAD

**Issue by putuyoga** [jpush/jpush-react-native#611]
**Platform: Android**

It may related to [this issue](https://github.com/jpush/jpush-react-native/issues/64), but i still can't figure it out how to hide the notification when the app on foreground. Is there any hint where i can set that behaviour?

My current implementation is calling `JPushModule.stopPush();` when app was on foreground, and call `JPushModule.resumePush();` when app went to background. But when app went to the background, the previous hidden notification (_which is sent when app on foreground_) will be showed again. It feels hacky. 

Any advice will be much appreciated 🙇

**Comment by JoshLipan** [comment]
You can send [Custom Message](https://docs.jiguang.cn/en/jpush/server/push/rest_api_v3_push/#messagecustom-message)，the notification will not show anyway,then control whether the notification is displayed by yourself.

**Comment by JoshLipan** [comment]
> But when app went to the background, the previous hidden notification (which is sent when app on foreground) will be showed again. It feels hacky.

This is normal logic, we will store the notification when you call`JPushModule.stopPush();`, and then resend it when you call `JPushModule.resumePush();`.

**Comment by putuyoga** [comment]
I just read the [Custom Message](https://docs.jiguang.cn/en/jpush/server/push/rest_api_v3_push/#messagecustom-message) doc, it seems can't be displayed when app on background. 

> This is normal logic, we will store the notification when you callJPushModule.stopPush();, and then resend it when you call JPushModule.resumePush();.
Is there any way to remove previous notification before i call `resumePush()`? mine is a chat app, so it does not make sense to have notification when app already on foreground, then the old message popped up when app closed. 😁

**Comment by putuyoga** [comment]
I've found the solution. Little bit tricky, but still doable.The idea is add a `receiveNotification` listener, when it fired, clear notification immediately.

```javascript
import JPushModule from 'jpush-react-native';
import { AppState } from 'react-native';

// Init the notification and add listener when notification is received
const initNotification = async (): Promise<void> => {
  JPushModule.initPush();
  JPushModule.notifyJSDidLoad(() => {
    JPushModule.addReceiveNotificationListener(JPushModule.clearAllNotifications);
  });
};

// Use this function to add or remove app state listener
export const handleAppStateChange = (nextAppState) => {
  const {
    addReceiveNotificationListener: startListen,
    removeReceiveNotificationListener: stopListen
  } = JPushModule;

  switch (nextAppState) {
    case 'active':
      startListen(JPushModule.clearAllNotifications);
      break;
    case 'background':
      stopListen(JPushModule.clearAllNotifications);
      break;
    default:
      break;
  }
};

// Somewhere on your componentDidMount
AppState.addEventListener('change', handleAppStateChange);
```

**Comment by beikeku** [comment]
Hello, met with the same requirements as you, just contact the react native, can you provide more about the sample usage, we should be grateful, thank you

**Comment by enigmablue** [comment]
Had the same problem. But my alternative code is:
```

  const _handleAppStateChange =  (nextAppState) =>{
    if (
         appState.current.match(/inactive|background/) && nextAppState === "active"
       ){
           ...
          !isAvailable &&  JPush.clearAllNotifications() //If pushnotification is using Jpush
    }
    appState.current = nextAppState;
    setAppStateVisible(appState.current);
  }
```

In my notification listener:

```
  const notificationListener = result => {
         console.log("JPushset notificationListener:" + JSON.stringify(result))
         try {
         if (appState.current=="active"){
           JPush.clearAllNotifications()
         } 
         if (result.notificationEventType == "notificationOpened"){
             setPushMessage(result)
         }
       }catch (error){console.error(error)}
     };
```

Originally i was just using the standard appState.current to clearAllNotifications. 
But I needed the the extra clear at the appstate event listener because the user may just open the app when existing notifications at on the screen. The clearAllNotifications from background to active state would solve that problem
