### ISSUE TITLE
[Android]按照文档配置后无法运行

### ISSUE THREAD

**Issue by JiangRubin** [jpush/jpush-react-native#620]
## 你的运行环境

* 插件版本: "jcore-react-native": "^1.3.2", "jpush-react-native": "^2.5.3",
* react-native 版本：0.57.8

## 期望效果

BUILD SUCCESSFUL

## 实际效果

BUILD FAILED

## 重现步骤

1. yarn add jcore-react-native
2. yarn add jpush-react-native
3. react-native link jcore-react-native
4. react-native link jpush-react-native  输入AppKey
5. react-native run-android

## Debug logs

包括 Android 或 iOS 的日志：

![WechatIMG3](https://user-images.githubusercontent.com/30112163/58144353-b1134900-7c80-11e9-8a8b-78f79ad68ac9.jpeg)

**Comment by puti94** [comment]
方法数超出了，android的app的build.gradle 的defaultConfig里面加上multiDexEnabled true这一行

**Comment by JiangRubin** [comment]
thanks
