### ISSUE TITLE
已经集成厂商SDK，但是存在问题

### ISSUE THREAD

**Issue by bashen1** [jpush/jpush-react-native#624]
## 你的运行环境

* 插件版本:
* react-native 版本：0.59.8

## 期望效果

1、魅族可正常收到推送（m1 note | android 5.1  |  flyme 6.3.0.2A）
2、oppo可以正常点击推送，并获取相关推送信息

## 实际效果

1、测试了两台魅族，一台老机型，原先应用在前台的时候能收到推送，对接厂商SDK后，无论在前台后台都无法收到推送。另外一台较新机型测试通过
2、OPPO不管有没有对接厂商SDK，收到推送，点击都无法触发事件。看文档需要用到自定义的activity，不知是否提供相应的文档与代码

## 重现步骤

无

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by bashen1** [comment]
已经自己解决，关闭

**Comment by Domingowen** [comment]
hi bashen1 请问你是怎么解决的呢？？我目前遇到了前台才能可以接到推送

**Comment by yy1300326388** [comment]
怎么解决的，oppo 点击消息无法获取透传数据
