### ISSUE TITLE
[AndroidUtil] AndroidManifest.xml missing required service: cn.jpush.android.service.PushService

### ISSUE THREAD

**Issue by HelloJack0** [jpush/jpush-react-native#626]
## 你的运行环境

* 插件版本:
    "janalytics-react-native": "^1.4.1",
    "jcore-react-native": "^1.3.2",
    "jpush-react-native": "^2.5.3",

* react-native 版本："^0.59.8",

## 期望效果

告诉我们你希望达到什么效果。
推送和统计
## 实际效果
推送不了，统计无数据，获取不到Registration ID

## 重现步骤
![image](https://user-images.githubusercontent.com/47816656/60097400-e92d1080-9785-11e9-8209-d59a05218059.png)
![image](https://user-images.githubusercontent.com/47816656/60097439-fcd87700-9785-11e9-9b79-8dd980738eca.png)
![image](https://user-images.githubusercontent.com/47816656/60097537-2e514280-9786-11e9-86f3-3da7e014cefe.png)
![image](https://user-images.githubusercontent.com/47816656/60097563-3a3d0480-9786-11e9-9f7c-50c83116f265.png)
![image](https://user-images.githubusercontent.com/47816656/60098368-f64aff00-9787-11e9-96c7-88fb728b1a22.png)

## Debug logs

包括 Android 的日志：过滤JIGUANG
![image](https://user-images.githubusercontent.com/47816656/60097335-c569ca80-9785-11e9-93fd-dfce89560cf8.png)

**Comment by WTFSSD** [comment]
cn.jpush.android.service.DownloadProvider does not exist
