### ISSUE TITLE
安卓怎么不要显示设置别名成功之后回调，action-onAliasOperatorResult

### ISSUE THREAD

**Issue by zouzhengtao** [jpush/jpush-react-native#628]
## 你的运行环境

* 插件版本:
* react-native 版本：

## 期望效果

告诉我们你希望达到什么效果。

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by zouzhengtao** [comment]
求高人解答

**Comment by xiaoduan7658** [comment]
您好 您的问题解决了吗?

**Comment by wicked-tc130** [comment]
不好意思，新版本已经可以了。
