### ISSUE TITLE
-[JPUSHSRVResolver processRecord:length:] in libRCTJPushModule.a(JPUSHSRVResolver.o)

### ISSUE THREAD

**Issue by xwartz** [jpush/jpush-react-native#63]
![image](https://cloud.githubusercontent.com/assets/4149827/20030459/559f408a-a3a0-11e6-9fc0-ef3948a6f2d2.png)

xcode 8.1

打包到真机的时候

**Comment by xwartz** [comment]
已经解决，少了个 libresolv  lib

**Comment by pampang** [comment]
碰到同样的问题，感谢。

**Comment by huangminlinux** [comment]
@pampang 
手动安装
在 iOS 工程 target 的 Build Phases->Link Binary with Libraries 中加入如下库
libz.tbd
CoreTelephony.framework
Security.framework
CFNetwork.framework
CoreFoundation.framework
SystemConfiguration.framework
Foundation.framework
UIKit.framework
UserNotifications.framework
**libresolv.tbd**  //加入这个


自动安装
最新版本的 jpush-react-native 插件自动安装已经加入了这个库
