### ISSUE TITLE
Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_JPUSHService", referenced from:       objc-class-ref in AppDelegate.o

### ISSUE THREAD

**Issue by freyzou** [jpush/jpush-react-native#636]
## 你的运行环境

* 插件版本:
"jcore-react-native": "^1.3.0",
"jpush-react-native": "^2.3.0",

* react-native 版本：
 react: 16.8.3 => 16.8.3
 react-native: ^0.60.4 => 0.60.4

## 期望效果

告诉我们你希望达到什么效果。
能正常运行

## 实际效果
编译出错

告诉我们实际是什么效果。
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by 2445967009** [comment]
我也是这个问题，请问解决了吗

**Comment by mokai** [comment]
同样的问题，希望官方能尽快解决下这个错误。

**Comment by dltjiangfeipeng** [comment]
我也碰到这个问题  请问你们解决了么

**Comment by wenjianli92** [comment]
同样的问题

**Comment by freyzou** [comment]
> 我也是这个问题，请问解决了吗

已解决，确保需要的两个动态库 .a文件都要链接进去，出现在link libraries 列表下

**Comment by wenjianli92** [comment]
我是有加进去的，还是报错的，

![image](https://user-images.githubusercontent.com/29296692/67373809-d3541e80-f5b2-11e9-96dd-a827abcd734d.png)

**Comment by wenjianli92** [comment]
你好，我已添加还是不行，还是报那个错误，我是按照github上手动添加教程一步步做的，
jcord 1.5.0
jpush&nbsp; 2.6.0



---Original---

**Comment by wenjianli92** [comment]
解决方案如下，官网指导的手动添加步骤有些没说清楚，按如下解决：
https://community.jiguang.cn/t/topic/39256
