### ISSUE TITLE
library not found for -ljcore-ios-2.1.1 

### ISSUE THREAD

**Issue by hexiao-o** [jpush/jpush-react-native#638]
## 你的运行环境
Mac ios
* 插件版本:
* react-native 版本：0.60.4

## 期望效果

正常打包构建

## 实际效果
ios
library not found for -ljcore-ios-2.1.1 

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by xyunsh** [comment]
same issue

**Comment by seiue-developer** [comment]
same issue

**Comment by LiuCao** [comment]
我找到问题所在了。
1、找到项目下目录下 node_module/jcore-react-native/RCTJCoreModule/jcore-ios-2.1.1.a
2、对就是这个 jcore-ios-2.1.1.a 这个文件。将它重命名为 libjcore-ios-2.1.1.a。
也就是在前面加个lib就行了。
3、到ios目录下 pod install 就可以了。

**原因：**
vendored_libraries： 配置需要引用的非系统静态库（ 要注意，这里的.a静态库名字必须要带lib前缀，如果引用的静态库名字没lib前缀会导致编译报错，只需要重命名加上即可 ）

**Comment by pandaLv** [comment]
> 我找到问题所在了。
> 1、找到项目下目录下 node_module/jcore-react-native/RCTJCoreModule/jcore-ios-2.1.1.a
> 2、对就是这个 jcore-ios-2.1.1.a 这个文件。将它重命名为 libjcore-ios-2.1.1.a。
> 也就是在前面加个lib就行了。
> 3、到ios目录下 pod install 就可以了。
> 
> **原因：**
> vendored_libraries： 配置需要引用的非系统静态库（ 要注意，这里的.a静态库名字必须要带lib前缀，如果引用的静态库名字没lib前缀会导致编译报错，只需要重命名加上即可 ）

亲测有效。
但通过修改 node_module 的方式很显然不太合适，希望官方尽快修复。

**Comment by LiuCao** [comment]
> > 我找到问题所在了。
> > 1、找到项目下目录下 node_module/jcore-react-native/RCTJCoreModule/jcore-ios-2.1.1.a
> > 2、对就是这个 jcore-ios-2.1.1.a 这个文件。将它重命名为 libjcore-ios-2.1.1.a。
> > 也就是在前面加个lib就行了。
> > 3、到ios目录下 pod install 就可以了。
> > **原因：**
> > vendored_libraries： 配置需要引用的非系统静态库（ 要注意，这里的.a静态库名字必须要带lib前缀，如果引用的静态库名字没lib前缀会导致编译报错，只需要重命名加上即可 ）
> 
> 亲测有效。
> 但通过修改 node_module 的方式很显然不太适合团队协作，所以我们采用了降级的方式来处理。希望官方尽快修复。

已在 `https://github.com/jpush/jcore-react-native` 提交issue

**Comment by vapao** [comment]
最近更新的 `jcore-react-native` 1.3.3版本的问题，把 `jcore-react-native` 降级到 1.3.2 就可以了

**Comment by shadow-boy** [comment]
same issue

**Comment by KingAmo** [comment]
any update on this?

**Comment by EternalChildren** [comment]
国内库更新的真的好慢啊 接受issue的速度也太慢了
目前还是没有解决 希望官方能够快点更新下

**Comment by excitedcat** [comment]
国内库更新的真的好慢啊 接受issue的速度也太慢了
目前还是没有解决 希望官方能够快点更新下

**Comment by Lris12J** [comment]
可更新到JPush2.5.7&&JCore1.2.7，255 版本是去掉了 pod 的集成方式

**Comment by Joyreece** [comment]
我是自己写的一个重装 node_modules 的脚本，然后在这个脚本里面处理类似这种问题。
提供一下修复这个问题的脚本作为参考，希望官方效率高一些吧。

```shell
fix_jpush_error() {
  # Fix JCore's static library file naming error.
  if [ -e "./node_modules/jcore-react-native/ios/RCTJCoreModule/jcore-ios-2.1.1.a" ]; then
    mv node_modules/jcore-react-native/ios/RCTJCoreModule/jcore-ios-2.1.1.a \
      node_modules/jcore-react-native/ios/RCTJCoreModule/libjcore-ios-2.1.1.a
  fi
}
```

**Comment by excitedcat** [comment]
@Joyreece 新版本已经 fixed 掉了呀，不需要写脚本了

**Comment by Joyreece** [comment]
> @Joyreece 新版本已经 fixed 掉了呀，不需要写脚本了

最初留意到 GitHub 上很早就修复了，但是无奈 npm 那面安装的还是有问题的。
前一段时间升级了一下但是还有有这个问题，我一会儿再试试新版本。

**Comment by excitedcat** [comment]
@Joyreece 我用的 0.6.5 RN, 一次集成成功😄

**Comment by wicked-tc130** [comment]
各位，已经更新了，麻烦重新install下使用新版

**Comment by excitedcat** [comment]
@wicked-tc130 已更新，没问题
