### ISSUE TITLE
cn.jpush.android.service.DownloadProvider does not exist 

### ISSUE THREAD

**Issue by BennyTian** [jpush/jpush-react-native#639]
## 你的运行环境
android 5.1
"jcore-react-native": "^1.3.2",
"jpush-react-native": "^2.5.3",

react-native-cli: 2.0.1
react-native: 0.59.5

## 期望效果
不报错

## 实际效果

unexpted!java.lang.IllegalArgumentException: Component class cn.jpush.android.service.DownloadProvider does not exist in com.huabenapp

## Debug logs

包括 Android 或 iOS 的日志：

*

08-13 12:09:05.779 29423 29423 W Thread-98: type=1400 audit(0.0:5721): avc: denied { search } for name="net" dev="sysfs" ino=28830 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:sysfs_net:s0 tclass=dir permissive=0

2408-13 12:09:05.779 29423 29423 W Thread-98: type=1400 audit(0.0:5722): avc: denied { search } for name="net" dev="sysfs" ino=28830 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:sysfs_net:s0 tclass=dir permissive=0
2508-13 12:09:05.793 29423 31167 W Settings: Setting adb_enabled has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
2608-13 12:09:09.885 29423 29471 W System : Ignoring header Cookie because its value was null.
2708-13 12:09:10.415 29423 29423 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
2808-13 12:09:18.581 29423 29423 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
2908-13 12:09:33.870 29423 29423 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
3008-13 12:09:43.801 29423 29423 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
3108-13 12:09:51.495 29423 29423 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
3208-13 12:10:00.658 29423 29423 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
3308-13 12:10:09.537 29423 29423 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
3408-13 12:10:11.733 29423 29433 I com.huabenapp: Background concurrent copying GC freed 212558(8MB) AllocSpace objects, 154(7MB) LOS objects, 50% free, 16MB/32MB, paused 615us total 251.123ms
3508-13 12:10:13.869 29423 29423 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
3608-13 12:10:20.896 29423 29423 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
3708-13 12:10:35.863 29423 29423 I ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
3808-13 12:10:37.503 29423 31224 E JIGUANG-JCore: [WakeController] unexpted!java.lang.IllegalArgumentException: Component class cn.jpush.android.service.DownloadProvider does not exist in com.huabenapp

*

**Comment by daiyehao** [comment]
时好时坏  没有觉得很神奇
