### ISSUE TITLE
[Android] How to prevent push notification showing up while the app is active?

### ISSUE THREAD

**Issue by sunkibaek** [jpush/jpush-react-native#64]
In my app, it shows notification even when the app is active. How do I prevent this so that I show notification only when the app is inactive or background in Android?

Thanks!

**Comment by KenChoi1992** [comment]
Yeah, your question is a good advice, will try to resolve this problem in next release.

**Comment by cashely** [comment]
@KenChoi1992 希望下个版本尽快出来，很头疼这个问题，另外还麻烦看下 #69

**Comment by KenChoi1992** [comment]
@sunkibaek  @cashely Since you receive a notification, it was already showed in notification bar, unless you send custom message, and defined the behaviour when receiving custom message, either send notification or don't send when app is running in foreground.

**Comment by putuyoga** [comment]
sorry to bump such old issue, but i still struggle with this, any clue @KenChoi1992 ?
