### ISSUE TITLE
  Android Studio 构建时报错

### ISSUE THREAD

**Issue by sumyfly** [jpush/jpush-react-native#643]
## 你的运行环境

* 插件版本: 2.5.3
* react-native 版本：0.59.10

## 期望效果
Android构建成功

## 实际效果
Android Studio报错

## 重现步骤
1. 安装插件
2. 构建APK

## Debug logs

包括 Android 或 iOS 的日志：
    <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="22" /> 不支持

**Comment by wicked-tc130** [comment]
请提供日志，另外能否集成新版看有没有问题？
