### ISSUE TITLE
请求升级ios sdk

### ISSUE THREAD

**Issue by knightxv** [jpush/jpush-react-native#645]
## 你的运行环境

* 插件版本:
jcore-react-native: ^1.3.2
jpush-react-native: ^2.5.3
* react-native 版本：
0.59.8
## 期望效果
ios上架审核时会出现如下提示：
ITMS-90683: Missing Purpose String in Info.plist
类似问题链接：
https://community.jiguang.cn/t/topic/34932/3
希望升级一下ios sdk。已解决iOS上架提示。
告诉我们你希望达到什么效果。

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by wicked-tc130** [comment]
已升级到最新，欢迎体验
