### ISSUE TITLE
iOS 没有 `openNotification` 事件的吗

### ISSUE THREAD

**Issue by xwartz** [jpush/jpush-react-native#65]
在代码里没有看到这个事件，如何 handle 住点击消息事件

**Comment by huangminlinux** [comment]
为了在收到推送点击进入应用能够获取该条推送内容需要在 AppDelegate.m didReceiveRemoteNotification 方法里面添加 [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo] 方法，注意：这里需要在两个方法里面加一个是iOS7以前的一个是iOS7即以后的，如果AppDelegate.m 没有这个两个方法则直接复制这两个方法，在 iOS10 的设备则可以使用JPush 提供的两个方法；如下所示
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
  // 取得 APNs 标准信息内容

  [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo];
}
//iOS 7 Remote Notification
- (void)application:(UIApplication *)application didReceiveRemoteNotification:  (NSDictionary *)userInfo fetchCompletionHandler:(void (^)   (UIBackgroundFetchResult))completionHandler {

  [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo];
}

// iOS 10 Support
- (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger))completionHandler {
  // Required
  NSDictionary * userInfo = notification.request.content.userInfo;
  if([notification.request.trigger isKindOfClass:[UNPushNotificationTrigger class]]) {
    [JPUSHService handleRemoteNotification:userInfo];
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo];
  }
  completionHandler(UNNotificationPresentationOptionAlert); // 需要执行这个方法，选择是否提醒用户，有Badge、Sound、Alert三种类型可以选择设置
}

// iOS 10 Support
- (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler {
  // Required
  NSDictionary * userInfo = response.notification.request.content.userInfo;
  if([response.notification.request.trigger isKindOfClass:[UNPushNotificationTrigger class]]) {
    [JPUSHService handleRemoteNotification:userInfo];
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo];
  }
  completionHandler();  // 系统要求执行这个方法
}



在接收到推送  点击推送进入 ，，都会 发 kJPFDidReceiveRemoteNotification 事件

**Comment by kingctan** [comment]
大侠，是不是搞错了哦？
openNotification  和 ReceiveNotification  不一样啊。
我也碰到这个问题。在点击消息后，想监听 openNotification ，再进入我的自定义消息页面。
但openNotification一直得不到。
难道和android的方式不一样么？

**Comment by huangminlinux** [comment]
openNotification  这个事件讲道理是无法调试debug 的，因为必须是推送唤起应用

**Comment by kingctan** [comment]
现在就是推送也无法唤起应用。。。。。

**Comment by huangminlinux** [comment]
@kingctan android 的？

iOS 点击推送唤起应用，是系统的功能，和代码无关

**Comment by huangminlinux** [comment]
openNotification  应用没有启动 点击推送唤起应用，   openNotification 用户获取推送过来的字段。

应用启动了后就通过 ReceiveNotification  事件获取推送字段就行

**Comment by JoshYuJump** [comment]
@huangminlinux 
在 App 运行的时候，收到推送
立即会传递 ReceiveNotification 事件，

这时点击推送消息，又传递 ReceiveNotification 事件

是不是不妥。
点消息的时候，是不是应该传个新的事件。

**Comment by llitfkitfk** [comment]
请检查 IOS 代码 
```
- (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler {
  // Required
  NSDictionary * userInfo = response.notification.request.content.userInfo;
  if([response.notification.request.trigger isKindOfClass:[UNPushNotificationTrigger class]]) {
    [JPUSHService handleRemoteNotification:userInfo];
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPFOpenNotification object:userInfo];
  }
  completionHandler(); // 系统要求执行这个方法
}
```
注意 使用`kJPFOpenNotification` 参数

**Comment by huangminlinux** [comment]
@llitfkitfk  这个方法名让太多人误解了，所以现在直接改为点击推送，  都会触发 kJPFOpenNotification。

**Comment by llitfkitfk** [comment]
@huangminlinux 现在`OpenNotification`还是会触发两次

**Comment by huangminlinux** [comment]
@llitfkitfk 试试 1.4.6版本看看还有没有出现这个问题

**Comment by llitfkitfk** [comment]
试了1.4.6 正常的, 但是RN版本是 0.36.1的, 不知道有何影响

**Comment by huangminlinux** [comment]
@llitfkitfk  现在真对 0.40.0 一下的版本做了预处理，现在也可以正常使用

**Comment by llitfkitfk** [comment]
@huangminlinux thx
