### ISSUE TITLE
new JPushPackage(!BuildConfig.DEBUG, !BuildConfig.DEBUG)

### ISSUE THREAD

**Issue by kevin871223** [jpush/jpush-react-native#654]
## 你的运行环境
 react-native 版本：0.60.5
* 插件版本:
最新

## 重现步骤
安装插件后，添加配置，运行命令后出现错误：
android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:74: ����: �޷����� JPushPackage�еĹ ����� JPushPackageӦ�õ���������;
      new JPushPackage(!BuildConfig.DEBUG, !BuildConfig.DEBUG),
      ^
  ��Ҫ: û�в���
  �ҵ�: boolean,boolean
  ԭ��: ʵ�ʲ����б�����ʽ�����б����Ȳ�ͬ
1 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

查找路径：
android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java
发现添加了：
public ArrayList<ReactPackage> getPackages() {
    return new ArrayList<>(Arrays.<ReactPackage>asList(
      new MainReactPackage(),
      new JPushPackage(!BuildConfig.DEBUG, !BuildConfig.DEBUG), 
      XXXXX
    ));
  }

**Comment by dogom** [comment]
"jcore-react-native": "^1.3.5",
"jpush-react-native": "^2.5.5",
"react-native": "0.60.4",

刚遇到同样的问题

**Comment by 1512751361** [comment]
![image](https://user-images.githubusercontent.com/24776858/64502450-c2986380-d2f8-11e9-94db-e68066388929.png)
"jcore-react-native": "^1.3.5",
"jpush-react-native": "^2.5.5",
"react-native": "0.60.5",
同样的问题

**Comment by linchenhuicn** [comment]
![image](https://user-images.githubusercontent.com/21193805/64513271-b7eec600-d31a-11e9-9dd9-88f7e88a02c0.png)

**Comment by 1512751361** [comment]
> package.json文件改下
> ![image](https://user-images.githubusercontent.com/21193805/64513271-b7eec600-d31a-11e9-9dd9-88f7e88a02c0.png)

修改jpush-react-native下的package.json文件，完美解决。

**Comment by DYwangxue** [comment]
我的package.json文件配置怎么和你的不一样，这咋改

"dependencies": {
    "@babel/plugin-transform-runtime": "^7.5.5",
    "babel-preset-react-native": "^4.0.1",
    "jcore-react-native": "^1.3.5",
    "jpush-react-native": "^2.5.5",
}

**Comment by 1512751361** [comment]
> 我的package.json文件配置怎么和你的不一样，这咋改
> 
> "dependencies": {
> "@babel/plugin-transform-runtime": "^7.5.5",
> "babel-preset-react-native": "^4.0.1",
> "jcore-react-native": "^1.3.5",
> "jpush-react-native": "^2.5.5",
> }

修改./node_modules/jpush-react-native/package.json 文件内容

**Comment by DYwangxue** [comment]
哦哦，多谢多谢

**Comment by DYwangxue** [comment]
我改完确实不报错了，作者升级升的有点粗心

**Comment by zhijianzhang** [comment]
你好，新版本中你有遇到安卓运行的时候报错，程序包cn.jpush.reactnativejpush和cn.jpush.android.api不存在的问题嘛

**Comment by yuhang1995** [comment]
@1512751361 请问为什么我link成功后，原生模块依然没有注册成功，我是用的是就版本初始化方法未initPush
![image](https://user-images.githubusercontent.com/31569789/64592858-81c74a00-d3df-11e9-921b-39ee8ca47ce2.png)

**Comment by 1512751361** [comment]
> 原生模块依然没有注

1. 最新的插件，api接口基本都变了，初始化为 init 了

**Comment by DYwangxue** [comment]
> @1512751361 请问为什么我link成功后，原生模块依然没有注册成功，我是用的是就版本初始化方法未initPush
> ![image](https://user-images.githubusercontent.com/31569789/64592858-81c74a00-d3df-11e9-921b-39ee8ca47ce2.png)

我安卓，手动添加的配置，link失效了，initPush没有这个方法了，换成了init

**Comment by yuhang1995** [comment]
@1512751361 @DYwangxue 我是用的旧版本，2.5.5里面有个path文件有问题

**Comment by DYwangxue** [comment]
> > 原生模块依然没有注
> 
> 1. 最新的插件，api接口基本都变了，初始化为 init 了

改完后你编译有遇到这个问题么，java.lang.Double cannot be cast to com.facebook.bridge.ReadableNativeMap，有点莫名其妙的问题

**Comment by 1512751361** [comment]
> > > 原生模块依然没有注
> > 
> > 
> > 
> > 1. 最新的插件，api接口基本都变了，初始化为 init 了
> 
> 改完后你编译有遇到这个问题么，java.lang.Double cannot be cast to com.facebook.bridge.ReadableNativeMap，有点莫名其妙的问题

没有我的react-native@0.60.5 版本的 link自动连接的

**Comment by yuhang1995** [comment]
> > > > 原生模块依然没有注
> > > 
> > > 
> > > 
> > > 1. 最新的插件，api接口基本都变了，初始化为init了
> > 
> > 
> > 改完后你编译有遇到这个问题么，java.lang.Double无法强制转换为com.facebook.bridge.ReadableNativeMap，有点莫名其妙的问题
> 
> 没有我的react-native@0.60.5版本的链接自动连接的

我这边是插件灭有注册成功，编译是通过了的

**Comment by yuhang1995** [comment]
> > @ 1512751361请问为什么我的链接成功后，原生模块依然没有注册成功，我是用的是就版本初始化方法未initPush
> > ![图片](https://user-images.githubusercontent.com/31569789/64592858-81c74a00-d3df-11e9-921b-39ee8ca47ce2.png)
> 
> 我安卓，手动添加的配置，链接失效了，initPush没有这个方法了，换成了INIT
再MainActivity.java和MainApplication.java加了如下代码后，原生模块能够注册成功

MainActivity.java
![image](https://user-images.githubusercontent.com/31569789/64667237-c6102400-d48b-11e9-80ef-f4786d6a3631.png)

MainApplication.java
![image](https://user-images.githubusercontent.com/31569789/64667257-d45e4000-d48b-11e9-9c06-ca704baa822f.png)

**Comment by Geek-ch** [comment]
2.6.0 版本已经不这么写了

**Comment by wicked-tc130** [comment]
> 2.6.0 版本已经不这么写了

是的，因为重构影响较大，建议大家重新看下api文档
