### ISSUE TITLE
安卓运行报错，提示程序包cn.jpush.reactnativejpush和cn.jpush.android.api不存在

### ISSUE THREAD

**Issue by zhijianzhang** [jpush/jpush-react-native#656]
* 插件版本:
* react-native 版本：0.60.4
* jcore-react-native: 1.3.5
* jpush-react-native: 2.5.5

## 实际效果

根据文档配置安卓的环境，在Android studio上运行的时候报错

## Debug logs

包括 Android 或 iOS 的日志：
/Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainApplication.java:25: 错误: 程序包cn.jpush.reactnativejpush不存在
import cn.jpush.reactnativejpush.JPushPackage;
                                ^
/Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:7: 错误: 程序包cn.jpush.android.api不存在
import cn.jpush.android.api.JPushInterface;
                           ^
/Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainApplication.java:43: 错误: 找不到符号
      packages.add(new JPushPackage(true, true));
                       ^
  符号: 类 JPushPackage
/Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:23: 错误: 找不到符号
            JPushInterface.init(this); //新加
            ^
  符号:   变量 JPushInterface
  位置: 类 MainActivity
/Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:35: 错误: 找不到符号
               JPushInterface.onPause(this);
               ^
  符号:   变量 JPushInterface
  位置: 类 MainActivity
/Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:41: 错误: 找不到符号
               JPushInterface.onResume(this);
               ^
  符号:   变量 JPushInterface
  位置: 类 MainActivity
/Users/huangxianjun/Downloads/app_item_v1/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:66: 错误: 无法将类 JPushPackage中的构造器 J应用到给定类型;
      new JPushPackage(!BuildConfig.DEBUG, !BuildConfig.DEBUG),
      ^
  需要: 没有参数
  找到: boolean,boolean
  原因: 实际参数列表和形式参数列表长度不同
7 个错误

**Comment by DYwangxue** [comment]
/Users/huangxianjun/Downloads/app_item_v1/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:66: 错误: 无法将类 JPushPackage中的构造器 J应用到给定类型;
new JPushPackage(!BuildConfig.DEBUG, !BuildConfig.DEBUG),
^
需要: 没有参数
找到: boolean,boolean
原因: 实际参数列表和形式参数列表长度不同

升级后的版本会一直报这个错误，不知道为什么，我也报错，去掉debug也不行

**Comment by xzq8** [comment]
我也是

**Comment by jaysonjh** [comment]
> /Users/huangxianjun/Downloads/app_item_v1/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:66: 错误: 无法将类 JPushPackage中的构造器 J应用到给定类型;
> new JPushPackage(!BuildConfig.DEBUG, !BuildConfig.DEBUG),
> ^
> 需要: 没有参数
> 找到: boolean,boolean
> 原因: 实际参数列表和形式参数列表长度不同
> 
> 升级后的版本会一直报这个错误，不知道为什么，我也报错，去掉debug也不行

Gradle未找到Jar包吗？

**Comment by jaysonjh** [comment]
> * 插件版本:
> * react-native 版本：0.60.4
> * jcore-react-native: 1.3.5
> * jpush-react-native: 2.5.5
> 
> ## 实际效果
> 根据文档配置安卓的环境，在Android studio上运行的时候报错
> 
> ## Debug logs
> 包括 Android 或 iOS 的日志：
> /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainApplication.java:25: 错误: 程序包cn.jpush.reactnativejpush不存在
> import cn.jpush.reactnativejpush.JPushPackage;
> ^
> /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:7: 错误: 程序包cn.jpush.android.api不存在
> import cn.jpush.android.api.JPushInterface;
> ^
> /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainApplication.java:43: 错误: 找不到符号
> packages.add(new JPushPackage(true, true));
> ^
> 符号: 类 JPushPackage
> /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:23: 错误: 找不到符号
> JPushInterface.init(this); //新加
> ^
> 符号: 变量 JPushInterface
> 位置: 类 MainActivity
> /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:35: 错误: 找不到符号
> JPushInterface.onPause(this);
> ^
> 符号: 变量 JPushInterface
> 位置: 类 MainActivity
> /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:41: 错误: 找不到符号
> JPushInterface.onResume(this);
> ^
> 符号: 变量 JPushInterface
> 位置: 类 MainActivity
> /Users/huangxianjun/Downloads/app_item_v1/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:66: 错误: 无法将类 JPushPackage中的构造器 J应用到给定类型;
> new JPushPackage(!BuildConfig.DEBUG, !BuildConfig.DEBUG),
> ^
> 需要: 没有参数
> 找到: boolean,boolean
> 原因: 实际参数列表和形式参数列表长度不同
> 7 个错误

在jcore-react-native,jpush-react-native中修改build.gradle为：
 api fileTree(dir: 'libs', include: ['*.jar']) 就编译通过了

**Comment by zhijianzhang** [comment]
> > * 插件版本:
> > * react-native 版本：0.60.4
> > * jcore-react-native: 1.3.5
> > * jpush-react-native: 2.5.5
> > 
> > ## 实际效果
> > 根据文档配置安卓的环境，在Android studio上运行的时候报错
> > ## Debug logs
> > 包括 Android 或 iOS 的日志：
> > /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainApplication.java:25: 错误: 程序包cn.jpush.reactnativejpush不存在
> > import cn.jpush.reactnativejpush.JPushPackage;
> > ^
> > /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:7: 错误: 程序包cn.jpush.android.api不存在
> > import cn.jpush.android.api.JPushInterface;
> > ^
> > /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainApplication.java:43: 错误: 找不到符号
> > packages.add(new JPushPackage(true, true));
> > ^
> > 符号: 类 JPushPackage
> > /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:23: 错误: 找不到符号
> > JPushInterface.init(this); //新加
> > ^
> > 符号: 变量 JPushInterface
> > 位置: 类 MainActivity
> > /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:35: 错误: 找不到符号
> > JPushInterface.onPause(this);
> > ^
> > 符号: 变量 JPushInterface
> > 位置: 类 MainActivity
> > /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:41: 错误: 找不到符号
> > JPushInterface.onResume(this);
> > ^
> > 符号: 变量 JPushInterface
> > 位置: 类 MainActivity
> > /Users/huangxianjun/Downloads/app_item_v1/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:66: 错误: 无法将类 JPushPackage中的构造器 J应用到给定类型;
> > new JPushPackage(!BuildConfig.DEBUG, !BuildConfig.DEBUG),
> > ^
> > 需要: 没有参数
> > 找到: boolean,boolean
> > 原因: 实际参数列表和形式参数列表长度不同
> > 7 个错误
> 
> 在jcore-react-native,jpush-react-native中修改build.gradle为：
> api fileTree(dir: 'libs', include: ['*.jar']) 就编译通过了

可以了谢谢

**Comment by lchenfox** [comment]
> > * 插件版本:
> > * react-native 版本：0.60.4
> > * jcore-react-native: 1.3.5
> > * jpush-react-native: 2.5.5
> > 
> > ## 实际效果
> > 根据文档配置安卓的环境，在Android studio上运行的时候报错
> > ## Debug logs
> > 包括 Android 或 iOS 的日志：
> > /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainApplication.java:25: 错误: 程序包cn.jpush.reactnativejpush不存在
> > import cn.jpush.reactnativejpush.JPushPackage;
> > ^
> > /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:7: 错误: 程序包cn.jpush.android.api不存在
> > import cn.jpush.android.api.JPushInterface;
> > ^
> > /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainApplication.java:43: 错误: 找不到符号
> > packages.add(new JPushPackage(true, true));
> > ^
> > 符号: 类 JPushPackage
> > /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:23: 错误: 找不到符号
> > JPushInterface.init(this); //新加
> > ^
> > 符号: 变量 JPushInterface
> > 位置: 类 MainActivity
> > /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:35: 错误: 找不到符号
> > JPushInterface.onPause(this);
> > ^
> > 符号: 变量 JPushInterface
> > 位置: 类 MainActivity
> > /Users/huangxianjun/Downloads/app_item_v1/android/app/src/main/java/com/company/flowerbloombee/MainActivity.java:41: 错误: 找不到符号
> > JPushInterface.onResume(this);
> > ^
> > 符号: 变量 JPushInterface
> > 位置: 类 MainActivity
> > /Users/huangxianjun/Downloads/app_item_v1/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:66: 错误: 无法将类 JPushPackage中的构造器 J应用到给定类型;
> > new JPushPackage(!BuildConfig.DEBUG, !BuildConfig.DEBUG),
> > ^
> > 需要: 没有参数
> > 找到: boolean,boolean
> > 原因: 实际参数列表和形式参数列表长度不同
> > 7 个错误
> 
> 在jcore-react-native,jpush-react-native中修改build.gradle为：
> api fileTree(dir: 'libs', include: ['*.jar']) 就编译通过了

It works for me. Thanks.
