### ISSUE TITLE
link jpush-react-native报错

### ISSUE THREAD

**Issue by yuhang1995** [jpush/jpush-react-native#659]
## 你的运行环境
win10
node 8.10
* 插件版本:
![image](https://user-images.githubusercontent.com/31569789/64579113-3f3c4800-d3b4-11e9-8574-8dcd5df436db.png)

* react-native 版本：
![image](https://user-images.githubusercontent.com/31569789/64579148-64c95180-d3b4-11e9-9943-db033a20ccfd.png)

## 实际效果
![image](https://user-images.githubusercontent.com/31569789/64579216-a659fc80-d3b4-11e9-9c43-d3486c2bf934.png)

告诉我们实际是什么效果。

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by pausermake** [comment]
推荐你用 2.5.3的版本 2.5.5的版本我也发现有这个问题，RN库被去掉了几个东西

**Comment by jaysonjh** [comment]
发现2.5.5里面的patch.js 是空的

**Comment by yuhang1995** [comment]
@pausermake 换低版本能够成功，但是为深恶恶么原生模块没有注册成功
![image](https://user-images.githubusercontent.com/31569789/64592094-cf42b780-d3dd-11e9-9051-f34670e822da.png)

**Comment by lx1024** [comment]
> @pausermake 换低版本能够成功，但是为什么原生模块没有注册成功
> ![image](https://user-images.githubusercontent.com/31569789/64592094-cf42b780-d3dd-11e9-9051-f34670e822da.png)

你这个问题解决了吗？我今天也遇到这个问题

**Comment by yuhang1995** [comment]
> > @pausermake 换低版本能够成功，但是为什么原生模块没有注册成功
> > ![image](https://user-images.githubusercontent.com/31569789/64592094-cf42b780-d3dd-11e9-9051-f34670e822da.png)
> 
> 你这个问题解决了吗？我今天也遇到这个问题

项目的reademe 更新了，参考3.1可以解决

**Comment by lx1024** [comment]
> > > @pausermake 换低版本能够成功，但是为什么原生模块没有注册成功
> > > ![image](https://user-images.githubusercontent.com/31569789/64592094-cf42b780-d3dd-11e9-9051-f34670e822da.png)
> > 
> > 
> > 你这个问题解决了吗？我今天也遇到这个问题
> 
> 项目的reademe 更新了，参考3.1可以解决

极光推送的3.1版本手动接入？

**Comment by yuhang1995** [comment]
> > > > @pausermake 换低版本能够成功，但是为什么原生模块没有注册成功
> > > > ![image](https://user-images.githubusercontent.com/31569789/64592094-cf42b780-d3dd-11e9-9051-f34670e822da.png)
> > > 
> > > 
> > > 你这个问题解决了吗？我今天也遇到这个问题
> > 
> > 
> > 项目的reademe 更新了，参考3.1可以解决
> 
> 极光推送的3.1版本手动接入？

是README.md更新了,目录3.1

**Comment by wicked-tc130** [comment]
更新到最新版本即可

**Comment by wicked-tc130** [comment]
新版还不支持react-native-link，android配起来比较麻烦，ios有pod install比较省事。
上班有其他任务，维护RN插件是在闲暇时间，说来惭愧我还没去了解RN-0.60以后怎么自动配置，大概率会拖到下个月去了解，真正的做要12月份了。
如果有知道的同学可以留言告诉我，非常感谢

**Comment by hu-qi** [comment]
> 新版还不支持react-native-link。
> 目前仅支持手动集成，android配起来比较麻烦，ios有pod install比较省事。
> 上班有其他任务，维护RN插件是在闲暇时间，说来惭愧我还没去了解RN-0.60以后怎么自动配置，大概率会拖到下个月去了解，真正的做要12月份了。
> 如果有知道的同学可以留言告诉我，非常感谢

您好，请问最近有更新实现autolink吗

**Comment by wicked-tc130** [comment]
> > 新版还不支持react-native-link。
> > 目前仅支持手动集成，android配起来比较麻烦，ios有pod install比较省事。
> > 上班有其他任务，维护RN插件是在闲暇时间，说来惭愧我还没去了解RN-0.60以后怎么自动配置，大概率会拖到下个月去了解，真正的做要12月份了。
> > 如果有知道的同学可以留言告诉我，非常感谢
> 
> 您好，请问最近有更新实现autolink吗

没有，看了官方文档表示RN0.60以后autolink功能增强了很多，但我实际测试还是不能满足需求。目前是我放弃了搞自动link，Android集成体验是差了很多，在此表示抱歉。

**Comment by GreatAuk** [comment]
> > > 新版还不支持react-native-link。
> > > 目前仅支持手动集成，android配起来比较麻烦，ios有pod install比较省事。
> > > 上班有其他任务，维护RN插件是在闲暇时间，说来惭愧我还没去了解RN-0.60以后怎么自动配置，大概率会拖到下个月去了解，真正的做要12月份了。
> > > 如果有知道的同学可以留言告诉我，非常感谢
> > 
> > 
> > 您好，请问最近有更新实现autolink吗
> 
> 没有，看了官方文档表示RN0.60以后autolink功能增强了很多，但我实际测试还是不能满足需求。目前是我放弃了搞自动link，Android集成体验是差了很多，在此表示抱歉。

![image](https://user-images.githubusercontent.com/20253809/91288710-e67fde00-e7c3-11ea-9d9b-5acb88a834bf.png)
