### ISSUE TITLE
点击通知栏消息，重新打开app，不能跳到指定页面。

### ISSUE THREAD

**Issue by Jonauil** [jpush/jpush-react-native#66]
作者你好，点击通知栏消息，我想跳转到指定页面。现在每次点击通知栏消息重新打开app。目前我用的最新1.2.5版本。
//android 通知栏
        JPushModule.addReceiveOpenNotificationListener(async (msg) => {
            let extra = msg['cn.jpush.android.EXTRA'];
            //有值   Dialog.comfirm('通知栏',extra);
            let message = JSON.parse(extra);
            this.notice= message;
            if(message.type == 4 || message.type == 5){
                this.order = await request('biz/getOrderInfo', {
                    userid: global.user.user_id,
                    token: global.user.access_token,
                    orderId: message.key,
                });
                _navigator.push({
                    title: '详情页',
                    component:  BidDetail,
                    passProps: {
                        orderId: message.key
                    },
                });

**Comment by KenChoi1992** [comment]
@Jonauil 你好，你要跳到指定界面的话，要改一下 Android 的代码，在 [JPushModule](https://github.com/jpush/jpush-react-native/blob/master/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java) 中去掉 258行到271行的代码，也就是去掉点击通知时，默认跳转到启动 App 部分的代码。

**Comment by KenChoi1992** [comment]
@Jonauil 如果还是不能再 JS  控制界面跳转的话，可以再新建一个 Activity，然后用 JS 渲染这个界面，只是在收到通知的时候再调用一下原生的方法控制一下界面跳转。可以[参考一下这篇文章](https://segmentfault.com/a/1190000006082315)，把跳转的部分移到收到点击通知的事件里。

**Comment by yulianger** [comment]
具体怎么实现呢
