### ISSUE TITLE
README 缺少usage、 iOS端集成方法 等

### ISSUE THREAD

**Issue by KingAmo** [jpush/jpush-react-native#660]
## 你的运行环境

* 插件版本: 2.5.3
* react-native 版本：0.60.5

## 期望效果

希望README 能更详细一些

**Comment by KingAmo** [comment]
作为一个 1000+ star  的大项目，这个`readme` 属实有点简陋了....

**Comment by KingAmo** [comment]
我记得之前有个api文档的啊？咋不见了

**Comment by KingAmo** [comment]
https://github.com/jpush/jpush-react-native/commit/eecda23efcbf5943881df69be46504d7f5a94a20 为啥删除了文档了呢？@詹强

**Comment by DYwangxue** [comment]
文档呢，跪求，升级都报错了，搞什么啊

**Comment by inkCrazy** [comment]
大兄弟是不是git操作失误了？

**Comment by KingAmo** [comment]
```
    "jpush-react-native": "^2.5.5",
    "jcore-react-native": "^1.3.5",
```
`RN 0.60.5` 始终无法运行起来。。。

**Comment by KingAmo** [comment]
`example` 中的 `RN` 版本还是`0.52.0`，`RN 0.60`  是 `Auto link` ,而 `readme` 中的集成方法还是旧的需要手动 `link`的方式，希望能继续更新一下，谢谢大佬啦

**Comment by KingAmo** [comment]
[Readme](https://github.com/jpush/jpush-react-native#5--其他)  按照更新后的`readme`所说，还不支持 `RN 0.60`咯？请问啥时候能支持到 `RN 0.60呢`
