### ISSUE TITLE
安卓home划掉app 点击之前的通知报错

### ISSUE THREAD

**Issue by loveacat** [jpush/jpush-react-native#68]
两个问题
1. 关闭app的情况下能接收推送的消息么？ 目前测试来看是接收不到的。
2. 开启app情况下前台后台都没问题，点击也能弹出界面，但是划掉app之后，之前的通知没清除，点击之后报错。这种情况下貌似也收不到后续的推送消息了。

**Comment by KenChoi1992** [comment]
@lovecat 第一个要别的安装了 jpush 的应用拉起才能收到。 至于第二个问题，我在 Android 6.0 上的手机测试通知是会被清除的，可能这块要适配一下。

**Comment by KenChoi1992** [comment]
@loveacat JPushModule 有提供清除所有通知的 API：JPushModule.clearAllNotifications(),  如果在退出程序时没有清除所有的 Notification，你可以调这个接口手动清除。

**Comment by loveacat** [comment]
收到，谢谢
