### ISSUE TITLE
收到通知，但在点击通知栏时没响应到事件JPushModule.addNotificationListener

### ISSUE THREAD

**Issue by leslieli8899** [jpush/jpush-react-native#684]
## 你的运行环境

* 插件版本:
* react-native 版本：

## 期望效果
JPushModule.addNotificationListener
我在
告诉我们你希望达到什么效果。
希望点击通知栏能接收到方法，然后做一些事情
## 实际效果

告诉我们实际是什么效果。
点击通知栏没有进来方法
## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by wicked-tc130** [comment]
> ## 你的运行环境
> * 插件版本:
> * react-native 版本：
> 
> ## 期望效果
> JPushModule.addNotificationListener
> 我在
> 告诉我们你希望达到什么效果。
> 希望点击通知栏能接收到方法，然后做一些事情
> 
> ## 实际效果
> 告诉我们实际是什么效果。
> 点击通知栏没有进来方法
> 
> ## 重现步骤
> 1. ...
> 2. ...
> 3. ...
> 4. ...
> 
> ## Debug logs
> 包括 Android 或 iOS 的日志：

看下跑demo有没有问题

**Comment by xiaoduan7658** [comment]
你好 问题解决了吗  我也遇到了同样的问题

**Comment by wicked-tc130** [comment]
> 你好 问题解决了吗 我也遇到了同样的问题

首先确认跑demo有没有问题？然后还有问题能否打包debug模式，贴一下相关sdk日志
