### ISSUE TITLE
Could not invoke JPushModule.setDebugMode

### ISSUE THREAD

**Issue by KingAmo** [jpush/jpush-react-native#685]
## 你的运行环境
* 插件版本:
```
  "jcore-react-native": "^1.3.7",
  "jpush-react-native": "^2.5.10",
```
* react-native 版本：`0.61.2`

## 期望效果
`Android`端成功集成`jpush-react-native`
## 实际效果
`iOS`端集成成功了，但是`Android`端报错:
```
Could not invoke JPushModule.setDebugMode
null
cn.jpush.android.api.JPushInterface
Failed resolution of : Lcn/jiguang/api/JDispatchAction
Didn't find class "cn.jiguang.api.JDsipatchAction" on path: DexPathList....."
```
另外，`Android Studio` build 项目时，有如下警告：
```
AGPBI: {"kind":"warning","text":"Type `cn.jiguang.api.JCoreManager` was not found, it is required for default or static interface methods desugaring of `void cn.jpush.android.helper.g.a(android.content.Context, org.json.JSONObject)`","sources":[{"file":"/Users/qinshuai/Documents/ReactNativeProj/kjkDoctor/node_modules/jpush-react-native/android/libs/jpush-android-3.3.4.jar"}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Type `cn.jiguang.api.JDispatchAction` was not found, it is required for default or static interface methods desugaring of `java.lang.Object cn.jpush.android.helper.f.beforLogin(android.content.Context, java.lang.String, int, java.lang.String)`","sources":[{"file":"/Users/qinshuai/Documents/ReactNativeProj/kjkDoctor/node_modules/jpush-react-native/android/libs/jpush-android-3.3.4.jar"}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Type `cn.jiguang.api.JCoreManager` was not found, it is required for default or static interface methods desugaring of `java.lang.Object cn.jpush.android.helper.e.a(android.content.Context, java.lang.String, java.lang.Object)`","sources":[{"file":"/Users/qinshuai/Documents/ReactNativeProj/kjkDoctor/node_modules/jpush-react-native/android/libs/jpush-android-3.3.4.jar"}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Type `cn.jiguang.api.JCoreInterface` was not found, it is required for default or static interface methods desugaring of `java.lang.Object cn.jpush.android.helper.e.a(android.content.Context, java.lang.String, java.lang.Object)`","sources":[{"file":"/Users/qinshuai/Documents/ReactNativeProj/kjkDoctor/node_modules/jpush-react-native/android/libs/jpush-android-3.3.4.jar"}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Type `cn.jiguang.api.JCoreManager` was not found, it is required for default or static interface methods desugaring of `void cn.jpush.android.helper.Logger.a(int, boolean, java.lang.String, java.lang.String, java.lang.Throwable)`","sources":[{"file":"/Users/qinshuai/Documents/ReactNativeProj/kjkDoctor/node_modules/jpush-react-native/android/libs/jpush-android-3.3.4.jar"}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Type `org.apache.http.util.EntityUtils` was not found, it is required for default or static interface methods desugaring of `void com.tencent.wxop.stat.ak.a(java.util.List, com.tencent.wxop.stat.aj)`","sources":[{"file":"/Users/qinshuai/Documents/ReactNativeProj/kjkDoctor/node_modules/react-native-wechat/android/libs/libammsdk.jar"}],"tool":"D8"}
AGPBI: {"kind":"warning","text":"Interface `cn.jiguang.api.ReportCallBack` not found. It\u0027s needed to make sure desugaring of `cn.jpush.android.a.c$1` is correct. Desugaring will assume that this interface has no default method.","sources":[{"file":"/Users/qinshuai/Documents/ReactNativeProj/kjkDoctor/node_modules/jpush-react-native/android/libs/jpush-android-3.3.4.jar"}],"tool":"D8"}

```
## 重现步骤

1.  集成`jpush-react-native`、`jcore-react-native`
2. 按照`README` 在`build.gradle`和 `AndridManifest.xml` 配置好`APPKey `和`channel`
3. 在`App.js`的 `componentDidMount` 中添加以下代码：
``` 
      JPush.setLoggerEnable({ debug: true });
        JPush.init();
```
4. 运行，报上面提到的错

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by KingAmo** [comment]
我大概知道原因了，`Android Studio ` 报错：
```
> Project with path ':jcore-react-native' could not be found in project ':app'.
```

**Comment by KingAmo** [comment]
也就是说，`android`端的`jcore-react-native` 没有`autolink`成功，但是`jpush-react-native`成功了啊...

**Comment by KingAmo** [comment]
手动在`setting.gradle`中添加
```
include ':jcore-react-native'
project(':jcore-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/jcore-react-native/android')
```
解决了这个问题，希望`android` 端的 `autolink` 能尽快实现

**Comment by FaiChou** [comment]
我也遇到了相似问题:

**Could not invoke JPushModule.init**

查看 config:

```
$ react-native config
...
    "jcore-react-native": {
      "root": "/Users/FaiChou/Projects/XXX/node_modules/jcore-react-native",
      "name": "jcore-react-native",
      "platforms": {
        "ios": {
          "sourceDir": "/Users/FaiChou/Projects/XXX/node_modules/jcore-react-native/ios",
          "folder": "/Users/FaiChou/Projects/XXX/node_modules/jcore-react-native",
          "pbxprojPath": "/Users/FaiChou/Projects/XXX/node_modules/jcore-react-native/ios/RCTJCoreModule.xcodeproj/project.pbxproj",
          "podfile": null,
          "podspecPath": "/Users/FaiChou/Projects/XXX/node_modules/jcore-react-native/JCoreRN.podspec",
          "projectPath": "/Users/FaiChou/Projects/XXX/node_modules/jcore-react-native/ios/RCTJCoreModule.xcodeproj",
          "projectName": "RCTJCoreModule.xcodeproj",
          "libraryFolder": "Libraries",
          "sharedLibraries": [],
          "plist": [],
          "scriptPhases": []
        },
        "android": null
      },
      "assets": [],
      "hooks": {},
      "params": []
    },
  "jpush-react-native": {
      "root": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native",
      "name": "jpush-react-native",
      "platforms": {
        "ios": {
          "sourceDir": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native/ios",
          "folder": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native",
          "pbxprojPath": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native/ios/RCTJPushModule.xcodeproj/project.pbxproj",
          "podfile": null,
          "podspecPath": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native/JPushRN.podspec",
          "projectPath": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native/ios/RCTJPushModule.xcodeproj",
          "projectName": "RCTJPushModule.xcodeproj",
          "libraryFolder": "Libraries",
          "sharedLibraries": [],
          "plist": [],
          "scriptPhases": []
        },
        "android": {
          "sourceDir": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native/android",
          "folder": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native",
          "packageImportPath": "import cn.jiguang.plugins.push.JPushPackage;",
          "packageInstance": "new JPushPackage()"
        }
      },
      "assets": [],
      "hooks": {},
      "params": []
    },
...
```

可以发现安卓的 *jcore-react-native* 没有 `autolink`.

需要手动 link:

1. `app/build.gradle` 添加

```
dependencies {
      ...
      implementation project(':jcore-react-native')  // 添加 jcore 依赖
  }
```

2. `setting.gradle`  添加

```
include ':jcore-react-native'
project(':jcore-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/jcore-react-native/android')
```

**Comment by KingAmo** [comment]
嗯，楼上分析的很对。看了下源码，`jpush` 代码中有 `JPushModule.java`和`JPushPackage.java`，集成到项目中需要生成一个`package` 放到`PackageList`中，而`jcore` 貌似只是提供一个`service`，并不需要生成`package`，项目的文件结构与`jpush`不一样，所以`cli`的`config`命令无法识别，也就无法做到`AutoLink`

**Comment by qduck** [comment]
感谢，收益了！

**Comment by lhuazai** [comment]
> 我也遇到了相似问题:
> 
> **Could not invoke JPushModule.init**
> 
> 查看 config:
> 
> ```
> $ react-native config
> ...
>     "jcore-react-native": {
>       "root": "/Users/FaiChou/Projects/XXX/node_modules/jcore-react-native",
>       "name": "jcore-react-native",
>       "platforms": {
>         "ios": {
>           "sourceDir": "/Users/FaiChou/Projects/XXX/node_modules/jcore-react-native/ios",
>           "folder": "/Users/FaiChou/Projects/XXX/node_modules/jcore-react-native",
>           "pbxprojPath": "/Users/FaiChou/Projects/XXX/node_modules/jcore-react-native/ios/RCTJCoreModule.xcodeproj/project.pbxproj",
>           "podfile": null,
>           "podspecPath": "/Users/FaiChou/Projects/XXX/node_modules/jcore-react-native/JCoreRN.podspec",
>           "projectPath": "/Users/FaiChou/Projects/XXX/node_modules/jcore-react-native/ios/RCTJCoreModule.xcodeproj",
>           "projectName": "RCTJCoreModule.xcodeproj",
>           "libraryFolder": "Libraries",
>           "sharedLibraries": [],
>           "plist": [],
>           "scriptPhases": []
>         },
>         "android": null
>       },
>       "assets": [],
>       "hooks": {},
>       "params": []
>     },
>   "jpush-react-native": {
>       "root": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native",
>       "name": "jpush-react-native",
>       "platforms": {
>         "ios": {
>           "sourceDir": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native/ios",
>           "folder": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native",
>           "pbxprojPath": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native/ios/RCTJPushModule.xcodeproj/project.pbxproj",
>           "podfile": null,
>           "podspecPath": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native/JPushRN.podspec",
>           "projectPath": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native/ios/RCTJPushModule.xcodeproj",
>           "projectName": "RCTJPushModule.xcodeproj",
>           "libraryFolder": "Libraries",
>           "sharedLibraries": [],
>           "plist": [],
>           "scriptPhases": []
>         },
>         "android": {
>           "sourceDir": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native/android",
>           "folder": "/Users/FaiChou/Projects/XXX/node_modules/jpush-react-native",
>           "packageImportPath": "import cn.jiguang.plugins.push.JPushPackage;",
>           "packageInstance": "new JPushPackage()"
>         }
>       },
>       "assets": [],
>       "hooks": {},
>       "params": []
>     },
> ...
> ```
> 
> 可以发现安卓的 _jcore-react-native_ 没有 `autolink`.
> 
> 需要手动 link:
> 
> 1. `app/build.gradle` 添加
> 
> ```
> dependencies {
>       ...
>       implementation project(':jcore-react-native')  // 添加 jcore 依赖
>   }
> ```
> 
> 1. `setting.gradle`  添加
> 
> ```
> include ':jcore-react-native'
> project(':jcore-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/jcore-react-native/android')
> ```

rn 版本0.61.5 按照上面步骤添加了  还会报下面的错误

Could not invoke JPushModule.init
Failed resolution of: Lcn/jiguang/api/JDispatchAction;
Didn't find class "cn.jiguang.api.JDispatchAction" on path: DexPathList[[zip file "/data/app/xxxxx
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)

**Comment by 90Mark** [comment]
me too~~ ,android 的 jcore-react-native 需要手动link噢~

**Comment by hezhii** [comment]
@KingAmo `react-native@0.61.5` 版本中没有 setting.gradle 文件，手动添加后 jcore 配置之后仍然不行，请问要如何处理呢
