### ISSUE TITLE
2.5.11 安装报错

### ISSUE THREAD

**Issue by excitedcat** [jpush/jpush-react-native#688]
## 你的运行环境

* 插件版本: 2.5.11
* react-native 版本：0.6

## 重现步骤

pod install 报错

![image](https://user-images.githubusercontent.com/8253512/66814925-fc98fd00-ef69-11e9-89be-2b82b733086d.png)

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by excitedcat** [comment]
object: { key => value } ??????

**Comment by LiangQiangQiang** [comment]
建议手动安装

**Comment by bashen1** [comment]
pjson["author"]

**Comment by ceu** [comment]
s.author          = pjson["author"]

**Comment by wicked-tc130** [comment]
> s.author = pjson["author"]

这是正确的，下周会补个版本

**Comment by wicked-tc130** [comment]
已更新
