### ISSUE TITLE
应用在前台收到通知，点击以后app自动退出

### ISSUE THREAD

**Issue by cashely** [jpush/jpush-react-native#69]
应用在前台收到通知，点击以后app自动退出

**Comment by KenChoi1992** [comment]
@cashely 你这个问题跟 https://github.com/jpush/jpush-react-native/issues/64 这个明显不是同一个问题啊，有没有日志？

**Comment by cashely** [comment]
如果在回调里面执行方法，会报错
expected dynamic type `string', but had type `object'

**Comment by KenChoi1992** [comment]
@cashely 看下你的回调怎么写的

**Comment by cashely** [comment]
![image](https://cloud.githubusercontent.com/assets/10458640/20339373/e9a19958-ac16-11e6-8ed2-9464ad1b7593.png)

**Comment by KenChoi1992** [comment]
@cashely 这个 map 是字典，里面的键值对是你在 jpush 控制台定义的。

**Comment by cashely** [comment]
非常感谢您的讲解，应该是我这边用release去测试，所以内部报错会造成app推出问题

**Comment by huip** [comment]
@cashely 这个提交 https://github.com/jpush/jpush-react-native/pull/75 可能可以解决你的问题
