### ISSUE TITLE
在react-native 0.61.2版本中，集成极光推送，没有任何反应

### ISSUE THREAD

**Issue by quietautumn** [jpush/jpush-react-native#693]
## 你的运行环境

* 插件版本:
"jcore-react-native": "^1.3.7",
 "jpush-react-native": "^2.5.11",
* react-native 版本：
![C1BB840D-D1B5-4D9A-80EC-991FF6F1E274](https://user-images.githubusercontent.com/16301518/67182878-b1239a80-f412-11e9-8330-1be2cc274dda.png)

根据教程手动配置，调用极光api的时候，没有报错，也没有任何反应，登陆极光后台，提示没有用户！

**Comment by excitedcat** [comment]
同样的问题，register id 生产环境发送预览的时候预计人数为 0。但是同样的 id 测试环境人数竟然为 1

**Comment by wicked-tc130** [comment]
证书上传的没问题吧

**Comment by wicked-tc130** [comment]
> ## 你的运行环境
> * 插件版本:
>   "jcore-react-native": "^1.3.7",
>   "jpush-react-native": "^2.5.11",
> * react-native 版本：
>   ![C1BB840D-D1B5-4D9A-80EC-991FF6F1E274](https://user-images.githubusercontent.com/16301518/67182878-b1239a80-f412-11e9-8330-1be2cc274dda.png)
> 
> 根据教程手动配置，调用极光api的时候，没有报错，也没有任何反应，登陆极光后台，提示没有用户！

开debug模式没有

**Comment by quietautumn** [comment]
开了的，获取register id为空

**Comment by william-coding** [comment]
同样的问题, 而且没有错误提示
