### ISSUE TITLE
希望新版iOS端加回getLaunchAppNotification 方法，否则app结束的情况下点击推送无法获取相关信息

### ISSUE THREAD

**Issue by bashen1** [jpush/jpush-react-native#696]
## 你的运行环境

* 插件版本: 2.5.10
* react-native 版本：0.61.2

## 期望效果

告诉我们你希望达到什么效果。

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by wicked-tc130** [comment]
新版是支持ios应用被杀死状态下点击消息启动app后收到消息回调，你看下example，都有明确的注释说明

**Comment by bashen1** [comment]
@wicked-tc130 其余情况都可以，就杀死APP的情况点击无任何反应，文档也没指明这个特殊情况会怎么集成。已经自己改模块，增加getLaunchAppNotification方法了。如果方便，望告知此情况的注意点，还有iOS下setBadge也无法清除角标。已经改了这个方法，加入了
```
 [[UIApplication sharedApplication] setApplicationIconBadgeNumber:[number integerValue]];
```

**Comment by wicked-tc130** [comment]
> @wicked-tc130 其余情况都可以，就杀死APP的情况点击无任何反应，文档也没指明这个特殊情况会怎么集成。已经自己改模块，增加getLaunchAppNotification方法了。如果方便，望告知此情况的注意点，还有iOS下setBadge也无法清除角标。已经改了这个方法，加入了
> 
> ```
>  [[UIApplication sharedApplication] setApplicationIconBadgeNumber:[number integerValue]];
> ```

1.在新版里添加了RCTJPushEventQuene用来存储应用启动时的消息点击事件，你可以看下https://github.com/jpush/jpush-react-native/tree/master/example/ios/example/AppDelegate.m
和还需要在js  componentDidMount 调用JPush.init()

2.插件提供的设置角标方法是用来设置极光服务器上存储的角标数量，这个方法还不健全，所以注释上标识了todo，预计下月完善

2
