### ISSUE TITLE
RN 0.36.1 用jpush-react-native v1.2.5，rnpm 时没有安卓平台，是什么原因？

### ISSUE THREAD

**Issue by 420697228** [jpush/jpush-react-native#70]
呼叫技术支持，RN 0.36.1 , jpush-react-native 是 v1.2.5, rnpm link 时只有ios，没有安卓，是什么问题？
![image](https://cloud.githubusercontent.com/assets/11764582/20342486/8acbd7c2-ac25-11e6-8e8c-165f2612835b.png)

**Comment by KenChoi1992** [comment]
试试 react-native link jpush-react-native

**Comment by thecorsair** [comment]
还是没有安卓!必须手动配置？

**Comment by KenChoi1992** [comment]
@thecorsair 跑一下脚本，然后手动配置一下 build.gradle 部分就行了，ReadMe 有介绍。这个 rnpm 暂时用不了，下个版本尝试解决。

**Comment by KenChoi1992** [comment]
@420697228 @thecorsair  官方文档貌似也没有提及 Android 的 rnpm link，http://reactnative.cn/docs/0.39/linking-libraries-ios.html ，你们的别的项目有成功链接到 Android 模块吗？

**Comment by KenChoi1992** [comment]
其实 rnpm link 就是在 settings.gradle 添加了工程依赖，并且在 build.gradle 添加了依赖，跟我们的脚本做的事差不多。

**Comment by thecorsair** [comment]
嗯哈～手动配置一样的 我用jpush成功推送了的 android端
