### ISSUE TITLE
getRegistrationID 的callback返回参数结构不一致

### ISSUE THREAD

**Issue by bmxklYzj** [jpush/jpush-react-native#701]
## 你的运行环境

* 插件版本:
    "jcore-react-native": "^1.3.7",
    "jpush-react-native": "^2.6.0",
* react-native 版本： "react-native": "0.61.2",

## 期望效果

文档写的返回结果是：
@param {Fucntion} callback = (result) => {"registerID":String}
https://github.com/jpush/jpush-react-native/blob/master/index.js#L48
实际上ios是这样，
https://github.com/jpush/jpush-react-native/blob/master/ios/RCTJPushModule/RCTJPushModule.m#L130
android 直接返回的字符串，不是对象：
https://github.com/jpush/jpush-react-native/blob/master/android/src/main/java/cn/jiguang/plugins/push/JPushModule.java#L155

## 实际效果

返回结构不一致

## 重现步骤
none

## Debug logs

none

**Comment by Miluaaa** [comment]
`JPush.getRegistrationID((res) => {
                                console.log(res)
                                let push_regid
                                if (Platform.OS === 'ios') {
                                    push_regid = res.registerID
                                } else {
                                    push_regid = res
                                }
                            })`

**Comment by favrio** [comment]
安卓和iOS SDK返回值不一致，需要区分处理下。

**Comment by bmxklYzj** [comment]
> `JPush.getRegistrationID((res) => { console.log(res) let push_regid if (Platform.OS === 'ios') { push_regid = res.registerID } else { push_regid = res } })`

提issue只是给开发者建议双端返回参数对齐，简单兼容如下，不用判断OS：

```
// JPush bug: https://github.com/jpush/jpush-react-native/issues/701
// @ts-ignore
const JPushRegisterID: string = res.registerID ? res.registerID : res;
````

**Comment by Miluaaa** [comment]
谢谢 编程新手碰到这个问题 顺便发出来了

**Comment by bmxklYzj** [comment]
> 谢谢 编程新手碰到这个问题 顺便发出来了

嗯嗯，你那样也行的，不熟悉java，可以考虑提个pr...

**Comment by wicked-tc130** [comment]
已处理
