### ISSUE TITLE
ios编译冲突

### ISSUE THREAD

**Issue by Ekhui** [jpush/jpush-react-native#702]
当使用pod install的时候 由于其他第三方需要添加‘use_frameworks’
但是当我添加这个编译的时候 jcore就会报错
Undefined symbols for architecture arm64:
“OBJC_CLASS$_JCORETcpObject”, referenced from:
OBJC_CLASS$_JPUSHNewRequest in libjpush-ios-3.2.2.a(JPUSHNewRequest.o)
“OBJC_CLASS$_JCOREDecoder”, referenced from:
objc-class-ref in libjpush-ios-3.2.2.a(JPUSHAliasOperation.o)
objc-class-ref in libjpush-ios-3.2.2.a(JPUSHMessage.o)
objc-class-ref in libjpush-ios-3.2.2.a(JPUSHTagsOperation.o)
objc-class-ref in libjpush-ios-3.2.2.a(JPUSHUserProperty.o)
“_kJPFNetworkIsConnectingNotification”, referenced from:
。。。

**Comment by wicked-tc130** [comment]
pod install后，你应该能看到源码的，可以手动改下jcore pod文件
