### ISSUE TITLE
RN0.58.3版本可以用的最新的版本是哪个？

### ISSUE THREAD

**Issue by chj-damon** [jpush/jpush-react-native#706]
## 你的运行环境

* 插件版本: 2.5.3
* react-native 版本：0.58.3

## 期望效果

IOS能收到推送，但是打开推送无法跳转到相应的页面，所以想要升级到最新版本，请问0.58.3能用的最新版本是多少？

**Comment by wicked-tc130** [comment]
请直接用最新的，并没有所谓的RN版本限制

**Comment by chj-damon** [comment]
@wicked-tc130 最新的依赖androidX，配置起来很麻烦。。。

**Comment by wicked-tc130** [comment]
> @wicked-tc130 最新的依赖androidX，配置起来很麻烦。。。

JPush没有用到AndroidX，在0.60以下版本一直都能用
