### ISSUE TITLE
componentDidMount registrationID 是空的？

### ISSUE THREAD

**Issue by kahwooi** [jpush/jpush-react-native#708]
## 你的运行环境

* 插件版本: 

    "jcore-react-native": "^1.5.0",
    "jpush-react-native": "^2.6.1",
    
* react-native 版本：
    "react": "16.8.3",
    "react-native": "0.59.10"

## 期望效果

registrationID 是空的。

## 实际效果

registrationID 不空。

## 重现步骤

```
import JPush from 'jpush-react-native';

componentDidMount() {
    JPush.init();
    JPush.getRegistrationID(registrationID => {
      this.setState({ registrationID });
      console.log(this.state.registrationID); // 空
    });
}

```

**Comment by kahwooi** [comment]
这样写, 能够得到 registrationID:

```
JPush.init();
    this.connectListener = result => {
      if (result.connectEnable) {
        JPush.getRegistrationID(registrationID => {
          this.setState({ registrationID });
          console.log(this.state.registrationID);
        });
      }
    };
    JPush.addConnectEventListener(this.connectListener);
```

**Comment by wicked-tc130** [comment]
> 这样写, 能够得到 registrationID:
> 
> ```
> JPush.init();
>     this.connectListener = result => {
>       if (result.connectEnable) {
>         JPush.getRegistrationID(registrationID => {
>           this.setState({ registrationID });
>           console.log(this.state.registrationID);
>         });
>       }
>     };
>     JPush.addConnectEventListener(this.connectListener);
> ```
> 
> 我用对吗？

registerID只要注册成功一次后就会一直保存到app内，直至app卸载/数据清除。
你第一次进入app内直接拿是不一定拿的到的，在长连接建立成功后去拿registerID是没问题的

**Comment by favrio** [comment]
IOS下registrationID拿到是一个对象，你要取里面的值。安卓下registrationID拿到的直接是id string，你需要根据返回类型处理下。

```
JPush.getRegistrationID(async (registrationID: { registerID: string } | string) => {
      if (typeof registrationID === 'string') {
        resolve(registrationID)
      } else {
        resolve(registrationID.registerID)
      }
    })
```

**Comment by wicked-tc130** [comment]
已处理
