### ISSUE TITLE
怎么没有 JPushModule.addReceiveOpenNotificationListener方法了，现在需要做一个点击通知栏跳转对应的页面，是需要自己用原生实现吗？

### ISSUE THREAD

**Issue by qingkongyumian** [jpush/jpush-react-native#709]
## 你的运行环境

* 插件版本:
* react-native 版本：16.9.0
*jcore-react-native：1.5.0
*jpush-react-native：2.6.1

**Comment by epixel-development-team** [comment]
Is this resolved

**Comment by yangwei2011** [comment]
same issue .....

**Comment by qingkongyumian** [comment]
用原生的代码实现



















在 2020-09-25 15:42:41，"yangwei2011" <notifications@github.com> 写道：

same issue .....

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
package com.test.demo;

import android.os.Bundle;
import android.content.Intent;
import android.app.Activity;
import android.os.Bundle;
import android.text.TextUtils;
import android.util.Log;
import android.widget.TextView;
import android.os.Process;
import org.json.JSONException;
import org.json.JSONObject;
import android.content.Context;
import android.content.pm.PackageManager;
import com.facebook.react.bridge.Arguments;
import com.facebook.react.bridge.WritableMap;
import cn.jiguang.plugins.push.helper.JPushHelper;
import cn.jiguang.plugins.push.JPushModule;
import android.content.Intent;
import android.app.ActivityManager;
import java.util.List;
import cn.jiguang.plugins.push.receiver.JPushBroadcastReceiver;
import android.app.ActivityManager.RunningTaskInfo;

public class OpenClickActivity extends Activity {

    private static final String TAG = "OpenClickActivity";
    /** 消息Id **/
    private static final String KEY_MSGID = "msg_id";
    /** 该通知的下发通道 **/
    private static final String KEY_WHICH_PUSH_SDK = "rom_type";
    /** 通知标题 **/
    private static final String KEY_TITLE = "n_title";
    /** 通知内容 **/
    private static final String KEY_CONTENT = "n_content";
    /** 通知附加字段 **/
    private static final String KEY_EXTRAS = "n_extras";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        handleOpenClick();
    }

    /**
     * 处理点击事件，当前启动配置的Activity都是使用 Intent.FLAG_ACTIVITY_CLEAR_TOP |
     * Intent.FLAG_ACTIVITY_NEW_TASK 方式启动，只需要在onCreat中调用此方法进行处理
     */
    private void handleOpenClick() {

        Log.d(TAG, "用户点击打开了通知");
        String data = null;
        // 获取华为平台附带的jpush信息
        if (getIntent().getData() != null) {
            data = getIntent().getData().toString();
        }

        // 获取fcm、oppo、vivo、华硕、小米平台附带的jpush信息
        if (TextUtils.isEmpty(data) && getIntent().getExtras() != null) {
            data = getIntent().getExtras().getString("JMessageExtra");
        }

        Log.w(TAG, "msg content is " + String.valueOf(data));
        if (TextUtils.isEmpty(data))
            return;
        try {
            JSONObject jsonObject = new JSONObject(data);
            String msgId = jsonObject.optString(KEY_MSGID);
            byte whichPushSDK = (byte) jsonObject.optInt(KEY_WHICH_PUSH_SDK);
            String title = jsonObject.optString(KEY_TITLE);
            String content = jsonObject.optString(KEY_CONTENT);
            String extras = jsonObject.optString(KEY_EXTRAS);
            Log.w(TAG, "JPushInterface.reportNotificationOpened(this, msgId, whichPushSDK)");
            Log.w(TAG, data);
            Log.w(TAG, "finish(),关闭OpenClickActivity");
            finish();
            if (!this.isAppAlive(this, "com.test.demo")) {
                Log.w(TAG, "isAppAlive-----app没有启动");
                Bundle bundle = new Bundle();
                bundle.putString("cn.jpush.android.MSG_ID", msgId);
                bundle.putString("cn.jpush.android.NOTIFICATION_CONTENT_TITLE", title);
                bundle.putString("cn.jpush.android.ALERT", content);
                bundle.putString("cn.jpush.android.EXTRA", extras);
                // bundle.putString("notificationEventType", "notificationOpened");
                JPushBroadcastReceiver.NOTIFICATION_BUNDLE = bundle;
                JPushHelper.launchApp(this);
            } else {
                Log.w(TAG, "isAppAlive-----app已经启动");
                Log.w(TAG, "JPushHelper.sendEvent");
                WritableMap wm = Arguments.createMap();
                wm.putString("extras", extras);
                wm.putString("content", content);
                wm.putString("title", title);
                wm.putString("messageID", msgId);
                wm.putString("notificationEventType", "notificationOpened");
                JPushHelper.sendEvent("NotificationEvent", wm);
                JPushHelper.launchApp(this);
            }
        } catch (Throwable throwable) {
            Log.w(TAG, "JPushBroadcastReceiver ACTION_NOTIFICATION_OPENED error:" + throwable.getMessage());
        }
        // 上报点击事件
        // JPushInterface.reportNotificationOpened(this, msgId, whichPushSDK);
    }

    /**
     * 判断应用是否已经启动
     *
     * @param context     上下文对象
     * @param packageName 要判断应用的包名
     * @return boolean
     */
    public static boolean isAppAlive(Context context, String packageName) {
        boolean isAppRunning = false;
        ActivityManager am = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
        List<RunningTaskInfo> list = am.getRunningTasks(100);
        for (RunningTaskInfo info : list) {
          if (info.topActivity.getPackageName().equals(packageName) && info.baseActivity.getPackageName().equals(packageName)) {
            isAppRunning = true;
            break;
          }
        }
        return isAppRunning;
    }


    private String getPushSDKName(byte whichPushSDK) {
        String name;
        switch (whichPushSDK) {
            case 0:
                name = "jpush";
                break;
            case 1:
                name = "xiaomi";
                break;
            case 2:
                name = "huawei";
                break;
            case 3:
                name = "meizu";
                break;
            case 4:
                name = "oppo";
                break;
            case 5:
                name = "vivo";
                break;
            case 6:
                name = "asus";
                break;
            case 8:
                name = "fcm";
                break;
            default:
                name = "jpush";
        }
        return name;
    }

}

**Comment by k1195453766** [comment]
这个不错，有用

**Comment by Talaxy009** [comment]
代码非常有用，帮了大忙，感谢！随便说一下通过上面 Activity 获取的 extras 是字符串类型的，后面需要再转换一下。

**Comment by ybwdaisy** [comment]
使用 addNotificationListener 方法监听，判断 result 中 notificationEventType === notificationOpened 表示打开了推送。

notificationEventType：分为 notificationArrived 和 notificationOpened 两种
