### ISSUE TITLE
在xcode 11.2.1上编译会出现

### ISSUE THREAD

**Issue by 1057376155** [jpush/jpush-react-native#713]
## 你的运行环境
xcode 11.2.1
mojave 10.14.5
ios 13.2

* 插件版本:
* react-native 版本：0.61.2

## 重现步骤
引入#import <RCTJPushModule.h> 在xcode中 编译就会报错

Ignoring file /Users/abc/Documents/xxx/node_modules/jcore-react-native/ios/RCTJCoreModule/libjcore-ios-2.1.1.a, missing required architecture i386 in file /Users/abc/Documents/xxx/node_modules/jcore-react-native/ios/RCTJCoreModule/libjcore-ios-2.1.1.a (4 slices)

Ignoring file /Users/abc/Documents/xxx/node_modules/jpush-react-native/ios/RCTJPushModule/libjpush-ios-3.2.2.a, missing required architecture i386 in file /Users/abc/Documents/xxx/node_modules/jpush-react-native/ios/RCTJPushModule/libjpush-ios-3.2.2.a (4 slices)

Undefined symbol: _kJPFNetworkFailedRegisterNotification
Undefined symbol: _kJPFNetworkDidLoginNotification
Undefined symbol: _kJPFNetworkDidCloseNotification
Undefined symbol: _OBJC_CLASS_$_JPUSHService

![屏幕快照 2019-11-21 下午10 21 41](https://user-images.githubusercontent.com/18670671/69347012-bf353700-0cae-11ea-8e74-0270a890bc21.png)

**Comment by wicked-tc130** [comment]
先rm -rf node_modules，再npm install
执行下pod deintegrate，再pod install
