### ISSUE TITLE
demo跑不通

### ISSUE THREAD

**Issue by shuairobin** [jpush/jpush-react-native#717]
我用把DEMO里的appkey换成了我的，

也收不到通知。有详细的文档吗？

**Comment by quietautumn** [comment]
在"jcore-react-native": "^1.5.0",
    "jpush-react-native": "^2.6.1",
    "react": "16.9.0",
    "react-native": "0.61.2",
ios的debug能打包安装，但是无法解析，显示错误如下：
![B556D96C-2820-4F80-9027-EC463C836D0C](https://user-images.githubusercontent.com/16301518/69897564-b1f00a80-1388-11ea-900b-dbdd94dfc030.png)
，根据教程直接集成，使用pod和手动，都不能正常打包。
