### ISSUE TITLE
property 'notification' cannot be found in found in forward class object 'UNNottificationResponse'

### ISSUE THREAD

**Issue by cashely** [jpush/jpush-react-native#72]
![image](https://cloud.githubusercontent.com/assets/10458640/20469661/7d6641de-afdc-11e6-8c5b-0d5335843412.png)

**Comment by huangminlinux** [comment]
?

**Comment by cashely** [comment]
按照readme里面配置ios这一步报错
![image](https://cloud.githubusercontent.com/assets/10458640/20469880/58de3590-afde-11e6-818c-df56a026b034.png)

**Comment by huangminlinux** [comment]
应该是没有导入头文件在 appdelegate.h 加入如下代码
```
#import <RCTJPushModule.h>
#ifdef NSFoundationVersionNumber_iOS_9_x_Max
#import <UserNotifications/UserNotifications.h>
#endif
```

**Comment by cashely** [comment]
恩，是的
@huangminlinux  为什么在ios模拟器下面会报这个错误呢cannot read property 'init push' of undefined，安卓是没问题的

**Comment by cashely** [comment]
已经明白，还是没仔细看文档，initPush只有安卓才需要，谢谢
