### ISSUE TITLE
example android 杀死进程后无法收到推送通知，重新打开app后收到通知

### ISSUE THREAD

**Issue by jackgreentemp** [jpush/jpush-react-native#721]
## 你的运行环境

使用本项目中的example测试推送通知。

- "jcore-react-native": "1.5.0",
-  "jpush-react-native": "2.6.1",
-  "react": "16.8.6",
- "react-native": "0.60.5"

## 期望效果

android 杀死进程后无法收到推送通知。

## 实际效果

android 杀死进程后可以收到推送通知。

**Comment by whereiscode** [comment]
极光的bug

**Comment by whereiscode** [comment]
解决了吗？

**Comment by whereiscode** [comment]
请问这个bug 什么时候修复

**Comment by wicked-tc130** [comment]
应用非运行状态还能收到通知那是厂商才能做到的，请联系极光商务开通厂商通道
