### ISSUE TITLE
切换到桌面，app没杀掉 安卓收不到通知

### ISSUE THREAD

**Issue by whereiscode** [jpush/jpush-react-native#723]
## 你的运行环境
安卓
* 插件版本:
2.5.3
* react-native 版本：
0.57
## 期望效果

切换到桌面后 不杀死app的情况下也能收到消息 

## 实际效果

切换到桌面的前5秒可能还能收到消息，但是过一会就收不到了 只有当重新打开，才噼里啪啦全来了

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by whereiscode** [comment]
请问这个bug 什么时候修复

**Comment by wicked-tc130** [comment]
是某个机器还是测试的所有机器都这样？
如果是某个机器，例如锤子他会杀极光的推送进程，这种问题暂时没法处理。
如果是测试的所有机器，那么请试下我们主页的demo是否也这样？

**Comment by whereiscode** [comment]
@wicked-tc130 放弃吧  极光的严重bug 无法解决的

**Comment by lchenfox** [comment]
同样的问题啊，你解决了吗 @whereiscode 我这个也是上线后才发现，客户都收不到推送，我测试了一下，和你的情况一样😓
