### ISSUE TITLE
iOS集成报错

### ISSUE THREAD

**Issue by weiwr** [jpush/jpush-react-native#735]
## 你的运行环境

* 插件版本: jcore-react-native: 1.5.0, jpush-react-native: 2.6.6,
* react-native 版本：0.59.10

## 期望效果

集成不报错

## 实际效果

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_JCOREIntegrate", referenced from:
      objc-class-ref in libjpush-ios-3.2.2.a(JPUSHService.o)
  "_OBJC_CLASS_$_JCORELog", referenced from:
      objc-class-ref in libjpush-ios-3.2.2.a(JPUSHService.o)
      objc-class-ref in libjpush-ios-3.2.2.a(JPUSHHelper.o)
  "_kJPFNetworkFailedRegisterNotification", referenced from:
      -[RCTJPushModule init] in RCTJPushModule.o
  "_kJPFNetworkDidCloseNotification", referenced from:
      -[RCTJPushModule init] in RCTJPushModule.o
  "_kJPFNetworkDidLoginNotification", referenced from:
      -[RCTJPushModule init] in RCTJPushModule.o
      -[RCTJPushModule convertConnect:] in RCTJPushModule.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## 重现步骤

1. 
npm install jpush-react-native --save
npm install jcore-react-native --save 
react-native link jpush-react-native
react-native link jcore-react-native
2. 
pod管理
展示如下：
  pod 'JCore', :path => '../node_modules/jcore-react-native'
  pod 'JPush', :path => '../node_modules/jpush-react-native'
3. pod install

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by quietautumn** [comment]
ios不用link，直接pod install就可以了

**Comment by weiwr** [comment]
不link的话 pod里边不会增加任何东西。强行导入头文件会报错：'RCTJPushModule.h' file not found。

**Comment by quietautumn** [comment]
你可以重新建一个新项目试试，我之前也是觉得需要link一下，一直报错，后来看了看example，里面也是没有pod 'JCore', :path => '../node_modules/jcore-react-native'
pod 'JPush', :path => '../node_modules/jpush-react-native'的，后来自己建了一个新项目，就跟着教程走，走通了

**Comment by weiwr** [comment]
我新建一个项目是好的。可能是之前的老项目，但是不清楚有什么问题。已经迂回解决 自己pod jpsuh的远程库。

**Comment by neverlist** [comment]
怎么解决的，求帮助

**Comment by chj-damon** [comment]
请问是怎么解决的？

**Comment by weiwr** [comment]
> 请问是怎么解决的？
我直接在iOS podfile里边 pod jpush。自己集成的。只不过用了这里的桥接文件
