### ISSUE TITLE
build.gradle gradle:1.2.3

### ISSUE THREAD

**Issue by shiyunjie** [jpush/jpush-react-native#74]
Android项目里 build.gradle一定要1.3.＋？ 换成1.2.3就收不到推送。
dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

**Comment by KenChoi1992** [comment]
@shiyunjie 这个没测试过，可能是推送延迟了？

**Comment by KenChoi1992** [comment]
@shiyunjie 鉴于这个问题不是插件本身的问题，所以把 issue 关了。你的 Gradle 版本也比较旧了，建议升级。
