### ISSUE TITLE
调用setAlias方法，无任何返回。

### ISSUE THREAD

**Issue by zhuangchuming** [jpush/jpush-react-native#746]
## 你的运行环境

* 插件版本:2.6.6
* react-native 版本：0.60.6

## 期望效果

告诉我们你希望达到什么效果。

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

1. ...JPushModule.setAlias({"sequence":102,"alias":'sID_54916'});
2. ...无任何返回。
3. ...
4. ...

## Debug logs
D/JIGUANG-JCore: [JCoreHelper] runActionWithService action:tagalis
D/JIGUANG-JPush: [ActionHelper] doAction:tagalis
D/JIGUANG-JPush: [TagAliasHelper] tagalias:{"platform":"a","op":"set","alias":"sID_54916@"}
D/JIGUANG-JCore-IMPL: [NetworkingClient] Received bytes - len:36, pkg:com.gaomushelltea
D/JIGUANG-JCore-IMPL: [NetworkingClient] Network listening...
D/JIGUANG-JPush: [ActionHelper] doAction:msg
D/JIGUANG-JPush: [JPushActionImpl] action:handleMsg:JPushResponse{cmd=29, rid=1485, rquestId=3}
D/RN-JPush: onAliasOperatorResult:JPushMessage{alias='sID_54916@', tags=null, checkTag='null', errorCode=0, tagCheckStateResult=false, isTagCheckOperator=false, sequence=102, mobileNumber=null}
W/JIGUANG-JPush: [JMessageReceiverHelper] MessageReceiver run failed:Attempt to invoke interface method 'java.util.Iterator java.util.Set.iterator()' on a null object reference

包括 Android 或 iOS 的日志：

W/JIGUANG-JPush: [JMessageReceiverHelper] MessageReceiver run failed:Attempt to invoke interface method 'java.util.Iterator java.util.Set.iterator()' on a null object reference

**Comment by zhuangchuming** [comment]
@javenfang @sunnylqm @baurine @arniu eaxmple的工程都有这个问题。

**Comment by wicked-tc130** [comment]
已处理
