### ISSUE TITLE
你好，请问什么时候可以支持Androidx

### ISSUE THREAD

**Issue by HZCgetcode** [jpush/jpush-react-native#750]
## 你的运行环境

* 插件版本:3.5.3
* react-native 版本：3.5.3

## 期望效果
可以运行这个库
告诉我们你希望达到什么效果。

## 实际效果
报错，版本不支持
告诉我们实际是什么效果。

## 重现步骤

1. 对代码进行androidx迁移

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by wicked-tc130** [comment]
AndroidX你应用支持即可，与sdk无关
