### ISSUE TITLE
使用极光推送过程中如果当前的app没有关掉，点击通知会再次打开这个app。

### ISSUE THREAD

**Issue by Zhang-DaLei** [jpush/jpush-react-native#754]
## 你的运行环境

* 插件版本: 2.6.6
* react-native 版本：0.61.5

## 期望效果

点击通知栏，跳转app做出相应回调动作。

## 实际效果

点击通知的时候，若原app处于打开状态，jpush会重新拉起app，造成app重复，效果就是点击返回键会前往之前app的页面。如何解决已打开的app，点击通知不需要再次拉起？

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by meiqi1992** [comment]
+1

**Comment by bebedon** [comment]
+1

**Comment by zhyu9997** [comment]
+1

**Comment by wicked-tc130** [comment]
麻烦看下example-https://github.com/jpush/jpush-react-native/blob/master/example/android/app/src/main/java/com/example/MainApplication.java，添加如下代码
`  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    //调用此方法：点击通知让应用从后台切到前台
    JPushModule.registerActivityLifecycle(this);
  }`
