### ISSUE TITLE
google play  上架被拒

### ISSUE THREAD

**Issue by jilx951102** [jpush/jpush-react-native#755]
* 插件版本: 2.7.5
* react-native 版本：0.59

## 期望效果

希望可以出一个版本支持google play的版本库，或者希望能够告诉我怎么做才能够避免上架被拒。
希望能够尽快帮我解决，🙏。

## 实际效果
下面是我上架被拒的截图

![截屏2020-01-14下午1 02 10](https://user-images.githubusercontent.com/36940549/72315537-157e8f00-36ce-11ea-8e4d-4550df8e7ccf.png)

## 重现步骤

完成google play正常上架流程，然后就反馈极光推送导致上架被拒。

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by jilx951102** [comment]
问题已解决，需要到极光官方网站下载支持google play的包，然后替换掉rn库里面对应的jar包和so包
链接 https://docs.jiguang.cn//jpush/resources/

**Comment by 417394980** [comment]
请问具体是换哪个包下面的

**Comment by 424626154** [comment]
@jilx951102 直接替换时jar包名需要修改么

**Comment by jilx951102** [comment]
> @jilx951102 直接替换时jar包名需要修改么

不需要改，只要替换jpush和jcore下面对应的包就好了

**Comment by jilx951102** [comment]
> @jilx951102 直接替换时jar包名需要修改么
不需要改名字，只要替换jcore和jpush里面对应的包就好了

**Comment by lchenfox** [comment]
请问，为啥我替换了所有的 jar 包 和 so包 后，我的推送居然收不到了？

```
    "jcore-react-native": "^1.8.0",
    "jpush-react-native": "^2.8.1",
    "react": "16.13.1",
    "react-native": "0.63.2",
```

@jilx951102 你之前替换之后推送能够正常收到吗？

**Comment by 417394980** [comment]
可以，正常



---原始邮件---
发件人: "chenlong"<notifications@github.com&gt;
发送时间: 2020年9月9日(周三) 下午4:37
收件人: "jpush/jpush-react-native"<jpush-react-native@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"小木鱼"<417394980@qq.com&gt;;
主题: Re: [jpush/jpush-react-native] google play  上架被拒 (#755)




 
请问，为啥我替换了所有的 jar 包 和 so包 后，我的推送居然收不到了？
     "jcore-react-native": "^1.8.0",     "jpush-react-native": "^2.8.1",     "react": "16.13.1",     "react-native": "0.63.2",  
@jilx951102 你之前替换之后推送能够正常收到吗？

**Comment by lchenfox** [comment]
@417394980 额...尴尬，我换了之后收不到推送，现在一直在找原因，不知道是不是因为的RN版本比较新😅

**Comment by cctvmikeowen** [comment]
我更换了google play的所有的 jar 包 和 so包 后编译报错Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: cn.asus.push.BuildConfig
	at com.android.tools.r8.utils.Reporter.a(:21)
	at com.android.tools.r8.utils.Reporter.a(:7)
	at com.android.tools.r8.utils.t.a(:36)
	... 36 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     Program type already present: cn.asus.push.BuildConfig
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

**Comment by 452MJ** [comment]
卧槽，完美解决我的问题
