### ISSUE TITLE
请问为何一直有 [JPUSHService] 请检查"setupWithOption:appKey:channel:apsForProduction:..."方法调用 这个警告信息

### ISSUE THREAD

**Issue by chujian** [jpush/jpush-react-native#77]
是我写错了还是什么呢? 通过变量或者直接填写,都有这个警告!!!

  [JPUSHService setupWithOption:launchOptions appKey:@"c34cd*******"
                        channel:nil apsForProduction:false];

**Comment by huangminlinux** [comment]
书写没有问题， ⚠️应该不影响使用，

**Comment by chujian** [comment]
确实如此,测试接收推送,也没问题,不纠结了,先用着把
