### ISSUE TITLE
ios打release包的时候编译出错，debug运行正常

### ISSUE THREAD

**Issue by GuoMeng6** [jpush/jpush-react-native#780]
## 你的运行环境
xcode： 11.3
* 插件版本: 
    "jcore-react-native": "^1.8.0",
    "jpush-react-native": "^2.8.0",
* react-native 版本： 0.62.1

## 期望效果
      打release包编译正常通过

## 实际效果
      ios在debug模式下运行正常通过，通知也正常接收，在编译release包的时候，报错。截图如下

     
<img width="798" alt="截屏2020-04-24下午6 34 13" src="https://user-images.githubusercontent.com/22705471/80203750-3f930600-865a-11ea-8d32-e97f1fac7312.png">

## 重现步骤

1. 配置好极光证书
2. 安装库 `yarn add jpush-react-native && yarn add jcore-react-native && cd ios && pod install`
3. 参考demo中 `AppDelegate.m`文件，添加 `JPush` 相关代码到自己的项目中，并修改 `appkey`
4. 运行项目，`debug` 运行正常，可以正常接收通知，但是 `release` 时编译报错

**Comment by TrustTheBoy** [comment]
如何解决的?

**Comment by Zero-Zheng** [comment]
@GuoMeng6 如何解决的问题？
react native: 0.62
npm jpush: 2.8.1
![image](https://user-images.githubusercontent.com/18066536/83944134-c7f8ef00-a833-11ea-8c92-67ff9dae31d5.png)

**Comment by chj-damon** [comment]
@GuoMeng6 请问是怎么解决的？我也遇到一样的问题

**Comment by inkCrazy** [comment]
问题怎么关闭了，如何解决的？

**Comment by inkCrazy** [comment]
> ## 你的运行环境
> xcode： 11.3
> 
> * 插件版本:
>   "jcore-react-native": "^1.8.0",
>   "jpush-react-native": "^2.8.0",
> * react-native 版本： 0.62.1
> 
> ## 期望效果
> ```
>   打release包编译正常通过
> ```
> 
> ## 实际效果
> ```
>   ios在debug模式下运行正常通过，通知也正常接收，在编译release包的时候，报错。截图如下
> ```
> 
> <img alt="截屏2020-04-24下午6 34 13" width="798" src="https://user-images.githubusercontent.com/22705471/80203750-3f930600-865a-11ea-8d32-e97f1fac7312.png">
> 
> ## 重现步骤
> 1. 配置好极光证书
> 2. 安装库 `yarn add jpush-react-native && yarn add jcore-react-native && cd ios && pod install`
> 3. 参考demo中 `AppDelegate.m`文件，添加 `JPush` 相关代码到自己的项目中，并修改 `appkey`
> 4. 运行项目，`debug` 运行正常，可以正常接收通知，但是 `release` 时编译报错

请问你是如何解决的？

**Comment by GuoMeng6** [comment]
我的问题是没有在 `realease`时正常 `import <UserNotifications/UserNotifications.h>` 。
当时由于自己对 `ios` 原生代码不是很熟，直接将文档中

```
#ifdef NSFoundationVersionNumber_iOS_9_x_Max
#import <UserNotifications/UserNotifications.h>
#endif
```
这三行代码写在了

```
#if DEBUG
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
```
这几个 `import` 的后面，当时没有特别注意有个 `if DEBUG` 的判断条件，因此出现了在debug模式下运行正常， `release` 会报错，实则就是没有在 `release` 模式下正常导入 `<UserNotifications/UserNotifications.h>` 这个包。
因此我修改为正确的导入方式，如下：

```
#import "AppDelegate.h"

#import "TalkingData.h"
#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <RCTJPushModule.h>

#if DEBUG
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

#ifdef NSFoundationVersionNumber_iOS_9_x_Max
#import <UserNotifications/UserNotifications.h>
#endif

```
此时 `release` 模式编译正常
希望能帮助到各位开发者

**Comment by chj-damon** [comment]
@GuoMeng6 非常感谢！马上尝试！

**Comment by inkCrazy** [comment]
> 我的问题是没有在 `realease`时正常 `import <UserNotifications/UserNotifications.h>` 。
> 当时由于自己对 `ios` 原生代码不是很熟，直接将文档中
> 
> ```
> #ifdef NSFoundationVersionNumber_iOS_9_x_Max
> #import <UserNotifications/UserNotifications.h>
> #endif
> ```
> 
> 这三行代码写在了
> 
> ```
> #if DEBUG
> #import <FlipperKit/FlipperClient.h>
> #import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
> #import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
> #import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
> #import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
> #import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
> ```
> 
> 这几个 `import` 的后面，当时没有特别注意有个 `if DEBUG` 的判断条件，因此出现了在debug模式下运行正常， `release` 会报错，实则就是没有在 `release` 模式下正常导入 `<UserNotifications/UserNotifications.h>` 这个包。
> 因此我修改为正确的导入方式，如下：
> 
> ```
> #import "AppDelegate.h"
> 
> #import "TalkingData.h"
> #import <React/RCTBridge.h>
> #import <React/RCTBundleURLProvider.h>
> #import <React/RCTRootView.h>
> #import <RCTJPushModule.h>
> 
> #if DEBUG
> #import <FlipperKit/FlipperClient.h>
> #import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
> #import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
> #import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
> #import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
> #import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
> 
> static void InitializeFlipper(UIApplication *application) {
>   FlipperClient *client = [FlipperClient sharedClient];
>   SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
>   [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
>   [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
>   [client addPlugin:[FlipperKitReactPlugin new]];
>   [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
>   [client start];
> }
> #endif
> 
> #ifdef NSFoundationVersionNumber_iOS_9_x_Max
> #import <UserNotifications/UserNotifications.h>
> #endif
> ```
> 
> 此时 `release` 模式编译正常
> 希望能帮助到各位开发者

谢谢您的帮助，确实是这个问题导致的。

**Comment by chj-damon** [comment]
@Zero-Zheng 我跟你的报错一模一样。
@GuoMeng6 按照你这么修改，还是会报错。
