### ISSUE TITLE
iOS release

### ISSUE THREAD

**Issue by TrustTheBoy** [jpush/jpush-react-native#787]
## 你的运行环境

* 插件版本:
* react-native 版本：0.62.2

## 期望效果

打包正常
## 实际效果

告诉我们实际是什么效果。

![image](https://user-images.githubusercontent.com/20201085/82441050-e8a11500-9acf-11ea-8141-39fd7fe1712f.png)

## 重现步骤

按文档安装并导入lib,打包APP是报错

## Debug logs

Showing All Messages
AppDelegate.m:83:42: Definition of 'UNNotification' must be imported from module 'UserNotifications.UNNotification' before it is required

AppDelegate.m:83:50: Definition of 'UNNotificationRequest' must be imported from module 'UserNotifications.UNNotificationRequest' before it is required

AppDelegate.m:83:58: Definition of 'UNNotificationContent' must be imported from module 'UserNotifications.UNNotificationContent' before it is required
AppDelegate.m:84:51: Declaration of 'UNPushNotificationTrigger' must be imported from module 'UserNotifications.UNNotificationTrigger' before it is required

AppDelegate.m:96:21: Declaration of 'UNNotificationPresentationOptionAlert' must be imported from module 'UserNotifications.UNUserNotificationCenter' before it is required

**Comment by chj-damon** [comment]
一样的问题

**Comment by inkCrazy** [comment]
+1，

**Comment by chj-damon** [comment]
@TrustTheBoy 你解决了吗？

**Comment by DaiYz** [comment]
谁解决了？

**Comment by chj-damon** [comment]
解决了。https://github.com/jpush/jpush-react-native/issues/790#issuecomment-645105197

**Comment by Esain** [comment]
直接archive报同样的错误.

**Comment by smk524198002** [comment]
连真机archive还是报错，有大佬解决了吗？

**Comment by smk524198002** [comment]
这个问题解决了。[详见](https://community.jiguang.cn/question/420918)
