### ISSUE TITLE
[Android] Receiving none push messages scenario

### ISSUE THREAD

**Issue by devhyunjae** [jpush/jpush-react-native#79]
1. Clean my phone's memory(= kill the app's process?)

2. Shoot a bunch of push messages(i.e test01, test02, test03)

3. Not getting any messages

4. Run my app

5. Shoot another push message(i.e test04)

6. Now I am getting all the push messages(test01~04) in the stack all together.

Is there a way to receive message when my app process is off?

**Comment by KenChoi1992** [comment]
@devhyunjae You should at least install an app with jpush inside( means using jpush-android sdk).

**Comment by devhyunjae** [comment]
@KenChoi1992 Doesn't `jpush-react-native` have `jpush android sdk` inside? 

I'm saying about the app that have `jpush-react-native` installed.
Seems like the i'm getting the `push message with some delay(10min ~ 2hour)`
,and when I touch the push noti, it crashes with the same error as #78

**Comment by KenChoi1992** [comment]
@devhyunjae jpush-react-native has jpush android sdk inside. I mean, when you kill the process of app that has jpush-react-native, you must promise there is another process of app that has jpush android sdk inside running. Then this process will awake the app installed jpush-react-native. 17 p.m. may in peek time. Normally, push delay is rare case.

**Comment by KenChoi1992** [comment]
@devhyunjae  Reference this https://community.jiguang.cn/t/topic/11184, I hope it will helps you. And if you have any question about JPush, but not using problems about this plugin, I hope you guys question here https://community.jiguang.cn/ This is our community.
