### ISSUE TITLE
IOS release模式下build报错，debug模式下build正常

### ISSUE THREAD

**Issue by chj-damon** [jpush/jpush-react-native#790]
## 你的运行环境

* 插件版本: 2.8.1
* react-native 版本：0.62.2
* xcode版本：Version 11.4 (11E146)
* MacOS版本：Catalina 10.15.3 (19D76)

## 期望效果

期望不管是release模式下build还是debug模式下build都可以正常构建成功

## 实际效果

release模式下build报错，debug模式下build成功

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs
Undefined symbols for architecture i386:
  "_kJPFNetworkFailedRegisterNotification", referenced from:
      -[RCTJPushModule init] in libJPush.a(RCTJPushModule.o)
  "_kJPFNetworkDidCloseNotification", referenced from:
      -[RCTJPushModule init] in libJPush.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPushNotificationIdentifier", referenced from:
      objc-class-ref in libJPush.a(RCTJPushModule.o)
  "_kJPFNetworkDidLoginNotification", referenced from:
      -[RCTJPushModule init] in libJPush.a(RCTJPushModule.o)
      -[RCTJPushModule convertConnect:] in libJPush.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPushNotificationTrigger", referenced from:
      objc-class-ref in libJPush.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPUSHRegisterEntity", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_JPushNotificationRequest", referenced from:
      objc-class-ref in libJPush.a(RCTJPushModule.o)
  "_OBJC_CLASS_$_JPushNotificationContent", referenced from:
      objc-class-ref in libJPush.a(RCTJPushModule.o)
  "_kJPFNetworkDidReceiveMessageNotification", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
  "_OBJC_CLASS_$_JPUSHService", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in libJPush.a(RCTJPushModule.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chj-damon** [comment]
@wicked-tc130 请问你知道会是什么问题引起的吗？我是按照readme一步步走下来的。

**Comment by chj-damon** [comment]
@huangminlinux 大佬帮忙看看

**Comment by chj-damon** [comment]
跑官方提供的example，结果一样，都是在debug的时候OK，但是一旦edit schema为release就直接报错。报错信息一模一样。

**Comment by chj-damon** [comment]
@RokieGodFather 大佬帮忙看看

**Comment by chj-damon** [comment]
@JoshLipan 大佬帮忙看看

**Comment by chj-damon** [comment]
在issues里面翻到原因了：https://github.com/jpush/jpush-react-native/issues/328

在release的时候不能用模拟器，要用真机，或者可以直接试试Archive

**Comment by hiscc** [comment]
![screenshot-20211119-110620](https://user-images.githubusercontent.com/17979372/142558216-fe905db5-f4b6-47ea-b900-79d12c4862a4.png)

https://community.jiguang.cn/question/420918 
 
我按这个配置解决了报错问题
