### ISSUE TITLE
ipa 使用企业证书重新签名后收不到通知

### ISSUE THREAD

**Issue by LuHugo** [jpush/jpush-react-native#791]
## 你的运行环境

* 插件版本:
* react-native 版本：
``` 
"react-native": "~0.61.5",
"jcore-react-native": "^1.8.0",
"jpush-react-native": "^2.8.1",
```

## 期望效果

iOS能正常推送通知

## 实际效果

使用打包时的证书可以推送通知，ipa 使用企业证书签名后无法推送，在极光官网后台广播通知，列表里显示 目标：1， 成功：0。

## 重现步骤

1. 修改appkey为正式环境的应用，使用Xcode打正式环境的ipa包。
2. 使用企业证书重新签名ipa包，修改bundleID与极光平台正式环境的bundleID一致
3. 安装ipa应用，可以获取到设备的registerID，发送广播或指定registerID的通知可以匹配到，但是发送不成功

## Debug logs

包括 Android 或 iOS 的日志：
正式版没有日志

**Comment by gancan110** [comment]
你好,有没有解决这个问题,或者找到问题?

**Comment by LuHugo** [comment]
@gancan110 找到问题了，是因为企业证书没有设置 aps-environment 这个属性。
