### ISSUE TITLE
iOS 14 APP 启动时，提示 剪贴板粘贴

### ISSUE THREAD

**Issue by sapjax** [jpush/jpush-react-native#795]
具体可以看这个类似的 issue
https://github.com/facebook/react-native/issues/29254

只要剪贴板有内容，打开 APP 时，系统都会提示，APP 读取了剪贴板
经过排查分析，定位到是 jPush 相关的 SDK 执行了相关的操作

**Comment by pleasecmxx** [comment]
哦嚯😯

**Comment by ShaoGongBra** [comment]
哦豁

**Comment by cj768025549** [comment]
> 具体可以看这个类似的 issue
> [facebook/react-native#29254](https://github.com/facebook/react-native/issues/29254)
> 
> 只要剪贴板有内容，打开 APP 时，系统都会提示，APP 读取了剪贴板
> 经过排查分析，定位到是 jPush 相关的 SDK 执行了相关的操作

什么玩意，粘贴个链接就close了，问题解决了没有？根本不是同一个问题好吗，就这态度？
