### ISSUE TITLE
iOS别名收不到，群发所有人可以，安卓别名没问题

### ISSUE THREAD

**Issue by whereiscode** [jpush/jpush-react-native#799]
* 插件版本:
* react-native 版本：0.63.2
 "jcore-react-native": "1.8.0",
    "jpush-react-native": "2.8.1",

iOS setAlias 后，指定alias发送消息无效
Android setAlias，指定alias发送消息有效

IOS和Android群发所有人都有效

**Comment by aisriver** [comment]
我也遇到了这个问题

**Comment by aisriver** [comment]
> * 插件版本:
> * react-native 版本：0.63.2
>   "jcore-react-native": "1.8.0",
>   "jpush-react-native": "2.8.1",
> 
> iOS setAlias 后，指定alias发送消息无效
> Android setAlias，指定alias发送消息有效
> 
> IOS和Android群发所有人都有效

我这边排查了一下，ios下alias不能设置成数字，需要是字符串。不然会有6003的错误码

**Comment by smk524198002** [comment]
别名里面不能包含特殊字符，有规范要求

**Comment by whereiscode** [comment]
放弃

**Comment by 2944986867** [comment]
我也遇到了，但是我找到问题了https://www.cnblogs.com/ljcgood66/p/13819564.html
