### ISSUE TITLE
请问vivo等手机安装app后默认是关闭通知推送的，这个应该如何处理

### ISSUE THREAD

**Issue by ShaoGongBra** [jpush/jpush-react-native#806]
测试了好久发现他通知默认是关闭的

**Comment by ztMalone** [comment]
You can try to add notification permissions for your android app. Check permissions  and show some tips to users every time the app is started.

**Comment by gamestarlsj** [comment]
同问，为什么有的应用一安装就有通知权限

**Comment by lh1991** [comment]
请问解决了吗？如何一次获取权限？

**Comment by JoshLipan** [comment]
vivo 默认通知权限是需要联系 vivo 测开放的，建议到[vivo开放平台咨询](https://dev.vivo.com.cn/home?from=header)
