### ISSUE TITLE
请问sequence的作用是什么？

### ISSUE THREAD

**Issue by chj-damon** [jpush/jpush-react-native#819]
## 你的运行环境

* 插件版本:
* react-native 版本：0.62.2

## 期望效果

sequence的作用是什么？

## 实际效果

不知道sequence的作用是什么。它是用它指定方法执行的先后顺序的吗？实际上我看到方法顺序并没有按照sequence指定的来。看起来是无序的。

有什么办法可以做到让方法有序执行，或者Promise之类的操作

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by Riant** [comment]
addConnectEventListener，addTagAliasListener 这些事件回调的参数中会包含这个 sequence ，这样的话，你就知道是哪个请求的返回吧，我常用 JobId 之类的描述。

这个本来应该是组件内部自己实现掉的，然后对外提供 Promise 更好一些。

**Comment by JoshLipan** [comment]
连接业务的请求和响应
