### ISSUE TITLE
iphone7 IOS10 getRegistrationID为空 

### ISSUE THREAD

**Issue by forrest23** [jpush/jpush-react-native#82]
按照文档一步一步配置的。

iphone7 IOS10 getRegistrationID为空 ，PUSH Notificotion开关已经打开，但是还是获取不到。
在IOS9 下却可以正常获取。

IOS10 还要修改什么吗？

**Comment by huangminlinux** [comment]
支持iOS 10 需要导入头文件
#ifdef NSFoundationVersionNumber_iOS_9_x_Max
#import <UserNotifications/UserNotifications.h>
#endif

然后注册的地方需要改一下   在appdelegate.m 里面 使用如下的注册方法
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    if ([[UIDevice currentDevice].systemVersion floatValue] >= 10.0) {
 #ifdef NSFoundationVersionNumber_iOS_9_x_Max
    JPUSHRegisterEntity * entity = [[JPUSHRegisterEntity alloc] init];
     entity.types = UNAuthorizationOptionAlert|UNAuthorizationOptionBadge|UNAuthorizationOptionSound;
     [JPUSHService registerForRemoteNotificationConfig:entity delegate:self];
 
#endif
} else if ([[UIDevice currentDevice].systemVersion floatValue] >= 8.0) {
    [JPUSHService registerForRemoteNotificationTypes:(UIUserNotificationTypeBadge |
                                                      UIUserNotificationTypeSound |
                                                      UIUserNotificationTypeAlert)
                                          categories:nil];
  } else {
    [JPUSHService registerForRemoteNotificationTypes:(UIRemoteNotificationTypeBadge |
                                                      UIRemoteNotificationTypeSound |
                                                      UIRemoteNotificationTypeAlert)
                                          categories:nil];
  }
}
```

**Comment by forrest23** [comment]
现在发现 应用第一次安装完之后启动，getRegistrationID 获取不到。但是我退出应用再打开，就能获取到了。 这是什么情况？ 是不是跟权限有关系？

**Comment by huangminlinux** [comment]
getRegistrationID 这个方法需要在 JPush 登录后才能成功获取，可以通过下面代码监听是否登录
```
var subscription = NativeAppEventEmitter.addListener(
  'networkDidLogin',
  (notification) => console.log(notification)
);
```

**Comment by forrest23** [comment]
这样吗？ @huangminlinux 
NativeAppEventEmitter.addListener('networkDidLogin', (token) => {
                JPushModule.getRegistrationID((jpushId) => {
                    console.log("getRegistrationID: " + jpushId);
                    setJpushId(jpushId);
                });
            });

**Comment by forrest23** [comment]
@huangminlinux  1.2.6 版本里面安卓 networkDidLogin 这个事件好像没有回调啊 监听不到的感觉

**Comment by chujian** [comment]
异步的问题把,第一次是在询问用户是否同意开启通知, 其实我的处理是不管的,就让它第二次进入的时候获取到就是了,你的软件要是用户只愿意打开一次,那也是失败的拉,哈

**Comment by KenChoi1992** [comment]
@forrest23 Android 没有这个事件，只有一个接口 JPushInterface.getConnectionState() 返回一个 boolean， 不知道这个是不是你想要的。
