### ISSUE TITLE
cn.jpush.android.api不存在

### ISSUE THREAD

**Issue by wangxue-git** [jpush/jpush-react-native#832]
## 你的运行环境

* 插件版本:
* react-native 版本：

## 期望效果

告诉我们你希望达到什么效果。

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by QShengW** [comment]
解决了吗，以前都可以都 沃日 突然就不行了
错误: 程序包cn.jpush.reactnativejpush不存在
import cn.jpush.reactnativejpush.JPushPackage;
                                ^
android/app/src/main/java/com/lsyapp/MainActivity.java:6: 错误: 程序包cn.jpush.android.api不存在
import cn.jpush.android.api.JPushInterface;
                           ^
android/app/src/main/java/com/lsyapp/MainApplication.java:56: 错误: 找不到符号
          new JPushPackage(!BuildConfig.DEBUG, !BuildConfig.DEBUG),
              ^
  符号: 类 JPushPackage
android/app/src/main/java/com/lsyapp/MainApplication.java:76: 错误: 找不到符号
          new JPushPackage(SHUTDOWN_TOAST, SHUTDOWN_LOG)   //  <-- 添加 JPushPackage
              ^
  符号: 类 JPushPackage
android/app/src/main/java/com/lsyapp/MainActivity.java:10: 错误: 找不到符号
        JPushInterface.init(this);
        ^
  符号:   变量 JPushInterface
  位置: 类 MainActivity
5 个错误

FAILURE: Build failed with an exception.

**Comment by JoshLipan** [comment]
cn.jpush.android.api 是sdkjar包的类，正常接入插件的话是不会报错的

**Comment by JoshLipan** [comment]
cn.jpush.android.api 是sdkjar包的类，正常接入插件的话是不会报错的
