### ISSUE TITLE
0.64.1集成jpush-react-native 安卓有报错提示

### ISSUE THREAD

**Issue by chj-damon** [jpush/jpush-react-native#840]
## 你的运行环境

* 插件版本: 2.8.3
* react-native 版本：0.64.1

## 期望效果

安卓可以正常接收到推送信息

## 实际效果

安卓无法接收到推送消息，registerId是空的。

## 重现步骤

按照最新版的readme集成jpush-react-native，然后运行项目

## Debug logs
![image](https://user-images.githubusercontent.com/4902684/123549002-bd402d80-d799-11eb-9074-805a0aaabf54.png)

包括 Android 或 iOS 的日志：

**Comment by chj-damon** [comment]
很奇怪，我用AndroidStudio打开，确实可以看到提示说这个JNotifyActivity在jpush-android-4.1.2.jar包里面，但是为什么会报这个错呢？

**Comment by chj-damon** [comment]
![image](https://user-images.githubusercontent.com/4902684/123549725-ca125080-d79c-11eb-8f53-bc8ef11da2c2.png)

**Comment by zjxcv7** [comment]
同样的问题

**Comment by zjxcv7** [comment]
咨询了官方，给出的解决办法是： 在manifest中重写这个JNotifyActivity，覆盖极光的
`
<activity
            android:name="cn.jpush.android.service.JNotifyActivity"
            android:exported="true"
            tools:node="replace"
            android:taskAffinity="jpush.custom"
            android:theme="@android:style/Theme.Translucent.NoTitleBar">

            <intent-filter>
                <action android:name="cn.jpush.android.intent.JNotifyActivity" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </activity>
`

**Comment by zjxcv7** [comment]
咨询了官方，给出的解决办法是： 在manifest中重写这个JNotifyActivity，覆盖极光的：

`<activity
   android:name="cn.jpush.android.service.JNotifyActivity"
            android:exported="true"
            tools:node="replace"
            android:taskAffinity="jpush.custom"
            android:theme="@android:style/Theme.Translucent.NoTitleBar">

            <intent-filter>
                <action android:name="cn.jpush.android.intent.JNotifyActivity" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </activity>
`

**Comment by zjxcv7** [comment]
咨询了官方，给出的解决办法是： 在manifest中重写这个JNotifyActivity，覆盖极光的，测试了一下可行

```
<activity
            android:name="cn.jpush.android.service.JNotifyActivity"
            android:exported="true"
            tools:node="replace"
            android:taskAffinity="jpush.custom"
            android:theme="@android:style/Theme.Translucent.NoTitleBar">
            <intent-filter>
                <action android:name="cn.jpush.android.intent.JNotifyActivity" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </activity>
```

**Comment by chj-damon** [comment]
@zjxcv7 请问你现在可以正常接收到推送吗？

**Comment by zjxcv7** [comment]
> @zjxcv7 请问你现在可以正常接收到推送吗？

可以的！
