### ISSUE TITLE
TypeError: _jpushReactNative.default.addCustomMessagegListener is not a function

### ISSUE THREAD

**Issue by ZhiXiao-Lin** [jpush/jpush-react-native#842]
* 插件版本: 2.8.3
* react-native 版本：0.64.0

## 期望效果

index.d.ts 中有拼写错误

## 实际效果

addCustomMessageListener 写成了 addCustomMessagegListener

## Debug logs
![image](https://user-images.githubusercontent.com/19965768/124260381-3527a280-db62-11eb-9737-f94f5e8eef3f.png)
![image](https://user-images.githubusercontent.com/19965768/124260447-496b9f80-db62-11eb-862d-f5a5d60074c3.png)

包括 Android 或 iOS 的日志：

**Comment by ZhiXiao-Lin** [comment]
希望官方修复一下

**Comment by zjxcv7** [comment]
addCustomMessage  **g**  Listener **g**去除掉，官方做的东西粗糙得很像个新手。

**Comment by zjxcv7** [comment]
如果用的typescript,则添加一条忽略或者直接修改类型文件。

**Comment by inkCrazy** [comment]
大兄弟怎么解决的？
