### ISSUE TITLE
更新了版本一直在报错，有人遇到了么

### ISSUE THREAD

**Issue by lh9403** [jpush/jpush-react-native#845]
jpush-react-native/ios/RCTJPushModule/RCTJPushModule.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by zjxcv7** [comment]
<img width="281" alt="F49E907B-4EEE-4F35-9ADA-77A1B9480D4A" src="https://user-images.githubusercontent.com/24834874/128474594-91e57cff-a838-443e-b471-c77aba3a834b.png">

是报这个错吗？如果是这个错的话可以直接修改源码：

`setGeofenecMaxCount`
改为
`setGeofeneceMaxCount`

**Comment by lh9403** [comment]
> <img alt="F49E907B-4EEE-4F35-9ADA-77A1B9480D4A" width="281" src="https://user-images.githubusercontent.com/24834874/128474594-91e57cff-a838-443e-b471-c77aba3a834b.png">
> 
> 是报这个错吗？如果是这个错的话可以直接修改源码：
> 
> `setGeofenecMaxCount`
> 改为
> `setGeofeneceMaxCount`

不知道，没再试了，极光的推送和统计隔三差五就会出问题，耗费太多精力了

**Comment by JoshLipan** [comment]
新旧版本交替问题，已更新v286版本处理
