### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by zjxcv7** [jpush/jpush-react-native#847]
## 你的运行环境

* 插件版本:
* react-native 版本：0.64.2

## 期望效果

改正拼写，保证编译正常（这种错误已经好几次了）

## 实际效果

更新后编译报错，经检查是拼写错误，错误如下：
<img width="281" alt="F49E907B-4EEE-4F35-9ADA-77A1B9480D4A" src="https://user-images.githubusercontent.com/24834874/128475494-8e1e666e-ce83-491b-98d6-2a3eb22c2996.png">
<img width="955" alt="WeChatf4913c73a1f50464f0081aa50c9de553" src="https://user-images.githubusercontent.com/24834874/128475523-427d2185-fd61-42cb-8361-628e1d815b42.png">

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by JoshLipan** [comment]
已重新发布v286处理

**Comment by zjxcv7** [comment]
更新了还是错的！这错真的有点无法容忍。
<img width="946" alt="WeChat8aba6e9f96d3d127e9151d41297e9c48" src="https://user-images.githubusercontent.com/24834874/128819904-5205643d-759a-494a-8ad3-4eebec87c730.png">
