### ISSUE TITLE
请问怎么可以实现app关闭之后还可以收到通知呢？

### ISSUE THREAD

**Issue by Coder108** [jpush/jpush-react-native#848]
问题 1.   经过测试，iOS关闭app之后可以正常收到通知，但Android接受不到
问题 2.  当iOS关闭app后收到通知之后点击唤醒app，但不能重新触发addNotificationListener方法，要是要做到关闭app点击通知之后条到对应的页面要怎么做呢？

**Comment by goldprog** [comment]
同问，哪位大神能解答一下啊

**Comment by whoopsHzh** [comment]
我也遇到这个问题了

**Comment by Coder108** [comment]
查过相关资料Android需要一个进程来保持运行，找过一个灰色常驻，但好像也不能用，后来好像发现这个要开通厂商渠道什么的才可以，最终就没做了，老板说这可以不要求关闭了还收到推送（毕竟太野蛮了），iOS的话按照sdk的搭建操作是关闭了app都可以收到推送，但我处理点击推送后唤醒app但不能跳到对应的界面，所以也是放弃了关闭app可以接收推送的功能

要是你实现了比较全面的功能，例如关闭app还能收到推送，而且可以进入到对应的页面，麻烦你多指教一下，因为我也不懂，希望可以一起学习，谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jpush/jpush-react-native"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月18日(星期六) 上午9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jpush/jpush-react-native] 请问怎么可以实现app关闭之后还可以收到通知呢？ (#848)





 
我也遇到这个问题了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JoshLipan** [comment]
如需杀死后接收通知，请接入各厂商通道：https://docs.jiguang.cn/jpush/client/Android/android_sdk/
