### ISSUE TITLE
怎么打开指定页面

### ISSUE THREAD

**Issue by goldprog** [jpush/jpush-react-native#853]
## 你的运行环境

* 插件版本:
 "jcore-react-native": "1.9.0"
"jpush-react-native": "2.8.2"
* react-native 版本：
"react-native": "0.63.4"
## 期望效果
启动主界面后可以跳转对应页面。
告诉我们你希望达到什么效果。
## 实际效果
启动主界面后无法跳转对应页面。
告诉我们实际是什么效果。

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by JoshLipan** [comment]
两种方式，1.推送时指定跳到原生界面，在原生界面处理 2.推送时携带页面参数，在点击回调中处理跳转
