### ISSUE TITLE
安卓关闭后、接收不到推送

### ISSUE THREAD

**Issue by whoopsHzh** [jpush/jpush-react-native#854]
## 你的运行环境
安卓关闭后、接收不到推送
* 插件版本:
* react-native 版本：
* 0.64

## 期望效果

告诉我们你希望达到什么效果。

## 实际效果

告诉我们实际是什么效果。

## 重现步骤

1. ...
2. ...
3. ...
4. ...

## Debug logs

包括 Android 或 iOS 的日志：

**Comment by JoshLipan** [comment]
Android杀死应用后接收通知，需要接入厂商通道：https://docs.jiguang.cn/jpush/client/Android/android_sdk/
