### ISSUE TITLE
jpush.init()会阻塞主线程

### ISSUE THREAD

**Issue by L-x-C** [jpush/jpush-react-native#856]
版本最新

在rn中调用jpush.init()会把整个app的渲染主线程给阻塞住，导致界面卡主

尤其是安卓

jpush.init安卓原生是不是直接在主线程中操作的？

**Comment by JoshLipan** [comment]
安卓初始化会开启子进程处理，正常不会影响主进程的主线程。如果觉得影响了主进程，当然您可以在子线程中调用初始化
