### ISSUE TITLE
杀死应用之后怎么让应用还能接收到推送消息呢

### ISSUE THREAD

**Issue by cashely** [jpush/jpush-react-native#86]

**Comment by KenChoi1992** [comment]
@cashely  JPush 默认的 PushService 是常驻后台的，讲道理杀死应用前没有调用 stopPush 的话应该是可以继续收到推送的

**Comment by cashely** [comment]
现在我这边在安卓上测试确实是收不到的，重新打开应用以后是会收到之前所有的推送

**Comment by KenChoi1992** [comment]
@cashely  componentWillUnmount 的时候有没有调用 stopPush？

**Comment by cashely** [comment]
没有

**Comment by KenChoi1992** [comment]
@cashely 这是  JPush 的问题，建议你到我们的社区去提问 https://community.jiguang.cn/

**Comment by KenChoi1992** [comment]
@cashely 参考一下这个 https://community.jiguang.cn/t/topic/11184
