### ISSUE TITLE
Got JPUshModule.getInfo is not a function error

### ISSUE THREAD

**Issue by zhuzhuojiang** [jpush/jpush-react-native#87]
在整合完成后，得到JPushModule.getInfo is not a function. (In 'JPushModule.getInfo(function(map){cb(Map);})','JpushModule.getInfo' is undefined)

哪里出错了？

**Comment by scriptfans** [comment]
我这边的问题是“Cannot read property 'getInfo' of undefined”，不知道怎么解决。RN版本0.39

**Comment by KenChoi1992** [comment]
@zhuzhuojiang  @scriptfans  Android Only
