### ISSUE TITLE
iOS杀进程后，点击通知无法回调

### ISSUE THREAD

**Issue by aiDove** [jpush/jpush-react-native#88]
IOS 8设备测试发现，当在App进程被杀掉的情况下，推送的通知点击后，能唤醒App，但NativeAppEventEmitter.addListener('ReceiveNotification', (notification) => {

});
无法回调。

**Comment by huangminlinux** [comment]
应用没有起来是不会走这条回调的，，

你需要在  AppDelegate 的 didFinishLaunchingWithOptions 方法里面加入如下代码，来获取该条推送

···
  NSDictionary *apnsInfo = launchOptions[@"UIApplicationLaunchOptionsRemoteNotificationKey"];
  if (apnsInfo) {
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:apnsInfo];
  }
···

**Comment by waynehong** [comment]
结合使用 https://github.com/wix/react-native-notifications  
https://github.com/jpush/jpush-react-native/issues/93

**Comment by huangminlinux** [comment]
这个问题  明天会发布版本解决这个问题

**Comment by huangminlinux** [comment]
新版本发布  https://github.com/jpush/jpush-react-native/releases/tag/1.2.9

添加 OpenNotification 这个监听获取打开推送字段
