### ISSUE TITLE
Android 下调用 setTags，一直显示 Loading 

### ISSUE THREAD

**Issue by xwartz** [jpush/jpush-react-native#89]
看了[代码](https://github.com/jpush/jpush-react-native/blob/master/android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java#L123)，应该是 dismiss 没有调到。

对 Java 不熟悉，能帮忙看一下吗

**Comment by xwartz** [comment]
或者静默更新？不显示 loading

**Comment by KenChoi1992** [comment]
@xwartz 我看看
