### ISSUE TITLE
ReactNative 0.70.0 集成IOS运行出错

### ISSUE THREAD

**Issue by windsleaver** [jpush/jpush-react-native#903]
## 你的运行环境
IOS
* 插件版本:
    "jcore-react-native": "^2.0.7",
    "jpush-react-native": "^2.9.7",
* react-native 版本：
    "react": "18.1.0",
    "react-native": "0.70.0"
## 期望效果
IOS端使用Xcode可以运行
告诉我们你希望达到什么效果。

## 实际效果
无法运行，编译出错
告诉我们实际是什么效果。

## 重现步骤

1. ...参照文档安装包和接入相关内容
2. ...
3. ...
4. ...

## Debug logs
 Cannot initialize a parameter of type 'id<JPUSHRegisterDelegate>' with an lvalue of type 'AppDelegate *const __strong'

包括 Android 或 iOS 的日志：
<img width="796" alt="image" src="https://user-images.githubusercontent.com/54970708/218325158-a76a2575-c0b4-4474-8dd6-ac5722b4be56.png">

**Comment by tanyicheng** [comment]
你好，我遇到了和你一样的问题，请问最后是怎么处理的？非常感谢，期待你的回答
