### ISSUE TITLE
Android 无法进行注册

### ISSUE THREAD

**Issue by linytsysu** [jpush/jpush-react-native#92]
我按照README上面的配置，在iOS下能够成功收到推送，但是Android下使用`getRegistrationID`得到的结果却始终为空，官网控制台上也只能看到有iOS设备注册，看不到任何Android设备。
我使用的React Native版本是`0.37.1`，jpush-react-native版本是`1.2.6`，我的配置应该是没有问题的。请问有什么可能导致这种情况？或者有谁也是出现了这种情况的吗？

**Comment by KenChoi1992** [comment]
@linytsysu initPush() 方法调用了没有

**Comment by linytsysu** [comment]
@KenChoi1992 我已经调用了`initPush()`方法：
``` js
componentDidMount() {
  JPushModule.initPush();
  JPushModule.getRegistrationID((data) => {
    alert(data);
  });
  JPushModule.addReceiveCustomMsgListener((message) => {
    alert(message);
  });
  JPushModule.addReceiveNotificationListener((message) => {
    alert(message);
  });
}
componentWillUnmount() {
  JPushModule.removeReceiveCustomMsgListener();
  JPushModule.removeReceiveNotificationListener();
}
```
运行的时候也有看到了`initPush()`方法的`init success`的反馈，但是`getRegistrationID()`得到的结果还是空。请问我上面代码这样掉用initPush()是否正确？

**Comment by KenChoi1992** [comment]
@linytsysu 这种情况没遇见过，如果你配置是对的话，应该能看到注册设备的。

**Comment by KenChoi1992** [comment]
@linytsysu 这个问题解决了吗？

**Comment by linytsysu** [comment]
@KenChoi1992 没有解决啊，我想请问一下，Android下有什么方法可以知道连接状态或者注册状态吗？

**Comment by KenChoi1992** [comment]
@linytsysu 倒是有个 getConnectionState 的 API，但是插件这边没有暴露这个接口。

**Comment by KenChoi1992** [comment]
@linytsysu 这个问题解决了吗？

**Comment by linytsysu** [comment]
![screenshot_1481877054](https://cloud.githubusercontent.com/assets/8371161/21262983/38df2614-c3cf-11e6-974e-7fd4f627a4a7.png)
发现了这个问题，是因为这个导致的吗？应该怎么解决？

**Comment by xwartz** [comment]
@yituring   这个问题最后是怎么解决的，我最近碰到有些设备不可以。。。

**Comment by llitfkitfk** [comment]
android注册 需要添加 jcore-react-native

**Comment by hu8373551** [comment]
init push success  成功了。 但是在个getRegistrationID 返回的值还是空的。这个问题有谁处理了么？ 普通的消息是可以接收到的。
