### ISSUE TITLE
PushNotificationIOS 无法同时使用

### ISSUE THREAD

**Issue by waynehong** [jpush/jpush-react-native#93]
因为需要iso在没启动的应用的情况下，点击通知去到指定页面，jpush并未提供接口：https://github.com/jpush/jpush-react-native/issues/13
，想用另一个rn插件，
https://github.com/wix/react-native-notifications
，但是按照各自的配置后，
react-native-notifications接口通知的事件并没有调起。
使用RN 官网的PushNotificationIOS也是一样，PushNotificationIOS.addEventListener('localNotification', this._onLocalNotification);
这个事件并没有调用，remoteNotification也是一样。

**Comment by huangminlinux** [comment]
应用没有起来是不会走这条回调的，你需要在 AppDelegate 的 didFinishLaunchingWithOptions 方法里面加入如下代码，来获取该条推送参数

```
  NSDictionary *apnsInfo = launchOptions[@"UIApplicationLaunchOptionsRemoteNotificationKey"];
  if (apnsInfo) {
 // 加入你的代码
  }
```

主要问题是 应用启动的时候会，jsreact 还没有起起来，后面版本会加入,操作的缓存处理。

**Comment by waynehong** [comment]
自己胡乱拼凑了一下，可以和  wix/react-native-notifications 一起使用了
`- (void)jpushNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(NSInteger))completionHandler {
  // Required
  NSDictionary * userInfo = notification.request.content.userInfo;
  if([notification.request.trigger isKindOfClass:[UNPushNotificationTrigger class]]) {
   // [JPUSHService handleRemoteNotification:userInfo];
    [RCTPushNotificationManager didReceiveRemoteNotification:userInfo];
    [RNNotifications didReceiveRemoteNotification:userInfo];
    //[[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo];
  }
  completionHandler(UNNotificationPresentationOptionAlert); // 需要执行这个方法，选择是否提醒用户，有Badge、Sound、Alert三种类型可以选择设置
}`

这么设置后目前测试正常使用，还望作者能不能解释下这个函数的作用？
