### ISSUE TITLE
addReceiveOpenNotificationListener接收不到用户点开消息

### ISSUE THREAD

**Issue by Moluth** [jpush/jpush-react-native#94]
安卓平台下：
componentDidMount() {
        JPushModule.addReceiveOpenNotificationListener((map) => {
                console.log("######## Jpush OpenNotification");
         });
｝

但是控制台没有相应输出，顺便问一句这个map怎么用

**Comment by Moluth** [comment]
componentDidMount() {
JPushModule.addReceiveOpenNotificationListener((map) => {
console.log("######## Jpush OpenNotification");
});
｝

**Comment by KenChoi1992** [comment]
@Moluth  我这边测试是正常的

**Comment by KenChoi1992** [comment]
@Moluth 你找到原因了吗？

**Comment by xuanheScript** [comment]
@KenChoi1992 当app在前台情况下正常，当app在后台的情况下我也是打不开。

**Comment by KenChoi1992** [comment]
@Moluth @xuanheScript 我用 demo 测试，当 app 在后台运行时是可以执行回调的，
```
componentDidMount() {
JPushModule.addReceiveOpenNotificationListener((map) => {
console.log("######## Jpush OpenNotification");
});
｝
```
这个 map 其实和 receiveNotification 这个事件差不多，你可以在收到 receiveNotification 事件后把各种变量保存起来。

**Comment by KenChoi1992** [comment]
![image](https://cloud.githubusercontent.com/assets/8196928/21450438/069a5030-c932-11e6-8f35-3fca41bee899.png)
这是 JS 写法，然后点击通知也有打印输出：
![image](https://cloud.githubusercontent.com/assets/8196928/21450452/21b8a448-c932-11e6-841e-392b66691ecf.png)

说明执行了点击事件

**Comment by KenChoi1992** [comment]
@Moluth @xuanheScript 这个问题你们没有回复，我先把 issue 关了。你们之后有问题可以再打开。

**Comment by llitfkitfk** [comment]
请检查 IOS 代码 
`- (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler {
  
  // Required
  
  NSDictionary * userInfo = response.notification.request.content.userInfo;
  
  if([response.notification.request.trigger isKindOfClass:[UNPushNotificationTrigger class]]) {
    
    [JPUSHService handleRemoteNotification:userInfo];
    
    [[NSNotificationCenter defaultCenter] postNotificationName:kJPFOpenNotification object:userInfo];
    
  }
  
  completionHandler(); // 系统要求执行这个方法
  
}`
注意 使用 kJPFOpenNotification参数
