### ISSUE TITLE
Android下：当app在后台的时候点击通知栏监听不执行

### ISSUE THREAD

**Issue by xuanheScript** [jpush/jpush-react-native#98]
android中监听事件共有三个:
receivePushMsg
receiveNotification
openNotification
当我app在后台的情况下，点击通知栏的推送消息，app被唤醒到前台，但是监听中回调并没有被执行，如果app在前台的情况下，点击通知栏的推送消息，回调会被正常执行，执行的是openNotification监听，我想知道是我配置的问题？还是什么？
react-native version 0.34.0

**Comment by xuanheScript** [comment]
![image](https://cloud.githubusercontent.com/assets/19216775/21378659/bd5ab9f6-c782-11e6-927f-bf4f75257d04.png)

**Comment by KenChoi1992** [comment]
@xuanheScript  可能是 JS 没起来，这个你可以尝试一下在 JPushReceiver 的构造函数中加上
```
public JPushReceiver() {
            HeadlessJsTaskService.acquireWakeLockNow(mRAC);
        }
```

相关参考 https://facebook.github.io/react-native/docs/headless-js-android.html

**Comment by xuanheScript** [comment]
JPushReceiver 已经继承了 BroadcastReceiver，要使用HeadlessJsTaskService必须要继承HeadlessJsTaskService吧，该如何改这里的代码呢？
![image](https://cloud.githubusercontent.com/assets/19216775/21380111/c1fdbaca-c78d-11e6-8155-434fbafd86b9.png)
![image](https://cloud.githubusercontent.com/assets/19216775/21380149/fb2015e6-c78d-11e6-85f6-44a8926a7875.png)

**Comment by KenChoi1992** [comment]
@xuanheScript 看官网说，只要在 onReceive() 执行前都可以调用 
```
HeadlessJsTaskService.acquireWakeLockNow(mRAC);
```
上面那个错误你有没有在 JPushModule 中 import：
```
import com.facebook.react.HeadlessJsTaskService;
```

**Comment by KenChoi1992** [comment]
@xuanheScript  和这个 issue https://github.com/jpush/jpush-react-native/issues/94 应该是差不多的。如果还是没有执行，有人在我们的[社区](https://community.jiguang.cn/latest) 说新建一个项目就好了，你也可以尝试一下。现在我把 issue 关了。
