### ISSUE TITLE
安卓的为什么连接不上

### ISSUE THREAD

**Issue by 13601916554** [jpush/jpush-react-native#99]

**Comment by KenChoi1992** [comment]
@13601916554 什么连接不上？能否提供更详细一点的信息？

**Comment by 13601916554** [comment]
研究了2天发现 安卓设备绑定到极光后台,需要一定的时间.  请问这个时间是多久.
我单独创建了项目只连接安卓 发现1-2天才能绑定到用户.
我正式的在开发的项目 到目前还没有绑定到后台 ,无法 发送信息

**Comment by DesignerTime** [comment]
我也是绑定不上，刚导入的库，后台发推送安卓没有任何反应

**Comment by DesignerTime** [comment]
之前用react-native-jpush没这毛病，刚转到这个库直接就没法用了

**Comment by KenChoi1992** [comment]
@DesignerTime 看看打印日志，说不定你还没有成功注册设备，所以无法接收。

**Comment by KenChoi1992** [comment]
@13601916554 @DesignerTime 建议你们到我们的[社区](https://community.jiguang.cn/)提问一下，这些问题应该也是 JPush 的常见问题，而不是插件本身的问题。

**Comment by KenChoi1992** [comment]
关于 registrationId 为空的问题，可以参考这个帖子：https://community.jiguang.cn/t/registrationid/7780 你们也可以在社区搜索相关解决方案。现在我把 issue 关了。
